### ISSUE TITLE
Plugin forces headers that invalidate cache

### ISSUE THREAD

**Issue by Ipstenu** [yikesinc/yikes-inc-easy-mailchimp-extender#166]
You can look on http://plugins.elftest.net/ but here's an example.

Expires:	Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control:	no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma:	no-cache
Set-Cookie:	PHPSESSID=HzAG9j5HLU7KGU8FVh9oA2; path=/

The problem here is that a cache like Varnish will see "Oh hai! That's expired so I shouldn't cache it!" And that means no cache :( Happens on nginx as a proxy too.

**Comment by EvanHerman** [comment]
We should have a look back into this now that the new version has been rolled out to the WordPress repository.

**Comment by TheTracyL** [comment]
Moved to to-do list.
