### ISSUE TITLE
Failed nonce security check error when potential subscribers try to sign up

### ISSUE THREAD

**Issue by rmgconsult** [yikesinc/yikes-inc-easy-mailchimp-extender#176]
I have had several people try to subscribe and they get this error message:
“Failed nonce security check. Please reload the page and submit this form again.”
They have tried several times but have been unable to subscribe.

This seems exactly like the problem at:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/156

I'm totally baffled because the sign up works correctly for me so I can't replicate the problem.
I've tried about 4 or 5 Mailchimp plugins...your plugin is the best as far as I can tell for my needs.

Can you please help me?

Also how can I donate some money or "uprgrade" my free version to a paid version? I can't contribute much but I would like to express my appreciation for the help and the software.

Thanks!
Richard Golden
rmgconsult@aol.com
www.learningmachines101.com

**Comment by varunsanadhya** [comment]
I had the same issue which got resolved when I disabled caching in WP optimize plugin
