### ISSUE TITLE
Select List does not show my only list

### ISSUE THREAD

**Issue by brucenow** [yikesinc/yikes-inc-easy-mailchimp-extender#179]
Select List does not show my only list which is just below the "Select List" button.

**Comment by EvanHerman** [comment]
Hi Bruce,

If you create a second list, does that show in the drop down?

Thanks
Evan

**Comment by brucenow** [comment]
Problem solved.  Well, actually there was never a problem, I just missed a key part of the instructions.  But thanks for you quick response.
Bruce 

     On Thursday, January 1, 2015 5:45 PM, Evan Herman <notifications@github.com> wrote:
   

 Hi Bruce,If you create a second list, does that show in the drop down?Thanks
Evan—

**Comment by EvanHerman** [comment]
Great, glad you got that resolved.

No worries at all. If you have any questions moving forward, feel free to reach out!


Evan
