### ISSUE TITLE
Cannot enter data in forms in Firefox

### ISSUE THREAD

**Issue by JKSteele972** [yikesinc/yikes-inc-easy-mailchimp-extender#181]
As stated...the forms work fine in Chrome, but I cannot enter info or submit when viewing the same page in Firefox. One form found here (there are others but if this gets fixed the others should follow)
http://www.amlifehomes.com/contact-us/

**Comment by EvanHerman** [comment]
Hi JKSteele,

I don't see the opt-in form on the page. If you can provide a link to a page with the form I can take a look.


Thanks,
Evan

**Comment by JKSteele972** [comment]
Yeah, sorry about that…I finally had to give up and find the reason why wordpress forms weren’t working and I finally got that done, and decided to forego the mailchimp integration for the time-being. Thanks for the fast response – just not fast enough for impatient clients! :)

**Comment by EvanHerman** [comment]
No problem.


Evan
