### ISSUE TITLE
Duplicate forms in the "Entry" section

### ISSUE THREAD

**Issue by ALorena** [yikesinc/yikes-inc-easy-mailchimp-extender#182]
Hey guys, 
I am using the Yikes plug in on my primary side bar and also wanted to use it in the "after entry section" . However, I noticed there are duplicate forms at the bottom of each post. See screen shot. 
Trying to figure out why this is happening to no avail. 

Not sure this is allowed but here is a link to a sample blog post for you to see this in action. I will remove the widget in the AM though (doesn't look good ya know? ) hopefully you see this before that.  

Thoughts? 

![duplicate-mc forms-end of blog post](https://cloud.githubusercontent.com/assets/5297515/5610423/531ccc50-9485-11e4-8d53-b821d7911e24.jpg)

Thanks

**Comment by EvanHerman** [comment]
Hi ALorena,

How are you generating the form in the sidebar? Are you using a widget, or using the shortcode?

You shouldn't only have one form displaying at a time (as I'm sure you're aware). If you can re-setup the widget and post the link back here I'll take a look. I haven't come across the issue of duplicate forms at all, so I may need to take a closer look on the back end. 

I'll also close out the thread you opened over on WordPress.org, as I don't want duplicates existing on both sites.


Thanks,
Evan

**Comment by ALorena** [comment]
Hi Evan,
I am using the widget for both, the side bar and also a widget in the "entry area". 

I shouldn't have two forms you mean?  I'd like to show the form at the bottom of each post AND page. Should I use a shortcode instead? 

Here is the link to one of my posts. 
http://www.healyounaturally.com/microwave-popcorn-maybe-making-you-sick-plus-best-homemade-organic-popcorn/

Yes, please close the other one, or maybe I can delete it. My apologies just wanted to make sure you saw it :)

Thanks 

ALorena

**Comment by EvanHerman** [comment]
Hi ALorena,

No worries at all. I've added a link back to here incase any one stumbles across that issue on wordpress.org in future.

When I said you should only have one form display, I mean't when you use the short code or widget, two forms shouldn't be displayed, but only the one. The widget must be running twice, and generating two separate forms.

You can try using a custom filter to append the form to the bottom of each page or post, instead of using the widget area. I'm curious, if you use that widget area for another widget, does it display twice as well, or is it an issue with our plugin?

Either way, I'll get things squared away for you today :)


Evan

**Comment by ALorena** [comment]
Evan,

Ok cool thanks for putting a link back. 

Oh Ok got cha! I am going to remove the widget from the "entry" area.  I loved the display and the ease of use though.  When you say to use a filter do you mean another plug in? I don't want to go that route if I don't have to.  

Actually I have never used another widget in that area, but I am going to do that now to try and figure out if it is your plug in or just that area so we can figure it out :) Let's brake it ha! 

Awesome!  By the way, thanks for this great plug in. Truly appreciate your hard work. :+1:

**Comment by EvanHerman** [comment]
No, when I say a custom filter I just mean a small piece of code that I'll provide for you and you can just add to your function.php file. But if that one widget area is causing a problem and just duplicating any widget you place in there, it may be the theme that's acting strange.

Either way, whatever conclusion we come too, I'm sure we can get it resolved without too much work.

And thank you for the kind words regarding the plugin! I'm glad that you're finding it useful, we put the time into development and support because we know it will save users a lot of time, and we've built in a lot of features that users expect to see from  powerful MailChimp plugin.

Evan

**Comment by ALorena** [comment]
Hi Evan, 

Sorry I never made it back to this issue.  It isn't your plug in that was causing the issue. I added two different plug ins that are being used else where and the same issue happened. 

Ok not much work- works for me.  Thanks! 

I am in trying period but love, love the fact that I can see stats right from the dashboard, and all of the other features. So, is there a script I should look for? I'd rather use something from you if that isn't much trouble.  Thanks in advance for all of your help! 

A.

**Comment by EvanHerman** [comment]
Hi Alorena,

I'm not sure I understand what you mean in your last paragraph? Were you able to get the duplicate issue resolved on the front end of the site? If you'd like, I can take a look for you. It's probably a small issue with one of the file templates.

The only way you can track your MailChimp stats on the site, iss with the plugin installed. It wouldn't be an easy task to extract the stats tracking aspect of the plugin, while stripping the rest away.


Thanks,
Evan

**Comment by ALorena** [comment]
Evan, 

Didn't mean to confuse you. I was talking about the features your plugin offers. 

Yes, I was able to get that issue resolved because I removed the widget from the "After entry" area, so no more duplicates.  
 
However, I still would like to add a form at the end of all of my pages and post with that custom filter ;) 

Thanks

ALorena

**Comment by EvanHerman** [comment]
Ah, Ok no problem. Give me a few minutes and I'll whip up a custom function for you.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Alorena,

You'll need to know what the ID of the mailing list is. You can get the ID from the 'Manage List Forms' page.

Once you have the ID of the form you want to display at the bottom of posts and pages, simply add it to the following function:

```php
// Append Yikes Inc. MailChimp Optin List to bottom of posts and pages
function append_yikes_mailchimp_to_end_of_post_page_content( $content ) {
	if( is_single() || is_page() ) {
		$content = $content . do_shortcode( '[yks-mailchimp-list id="your-list-id-here" submit_text="Submit"]' );
		return $content;
	}
}
add_filter( 'the_content' , 'append_yikes_mailchimp_to_end_of_post_page_content' , 20 );
`


You'll want to replace "your-list-id-here" with the ID of your mailing list.

Once you drop your ID into the function, you can copy and paste the entire function to the bottom of your active theme ***function.php*** file. Save the file, and reload a single post or a page, and you should now have the mailing list optin form displayed below each post and page.

Please let us know if that works for you!


Thanks,
Evan

**Comment by ALorena** [comment]
Hi Evan, 
Thanks for the script and VIP support. 
Awesome. I am going to get on this and will get back to you with a link and end results.  

Can't wait to implement it. woo hoo! 

Grazie

**Comment by ALorena** [comment]
Evan, 

The script worked.  I was able to add a form at the bottom (have been trying to do this for ages) really didn't have the time to look into it.  

Here is a sample on one of my posts. 
http://www.healyounaturally.com/microwave-popcorn-maybe-making-you-sick-plus-best-homemade-organic-popcorn/

By the way, would I be able to style this here? ei: put a line of code or add my log etc.. ? 

Thank you so much for the excellent support. You guys rock!

**Comment by EvanHerman** [comment]
Hi Alorena,

I'm glad that worked for you!

Inside of that function I wrote above, you can include additional styles to style your form. You can also use the color picker and style options on the manage list form page to style the form.

Either way, the form on each post should take on the styles that you specify.


Thanks,
Evan

**Comment by ALorena** [comment]
Hi Evan,
Great! I am going to look into styling it.  

Thanks again for all of your help!

**Comment by EvanHerman** [comment]
No problem at all! 

We're glad you are enjoying the plugin. If you continue to find it useful, we really enjoy hearing about it in the review section of the repository. (https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender)

Your review will go along way in helping others feel confident in installing the plugin, and it also helps others take note of our work so we can get a few more downloads.


Take care and enjoy!


All the best,
Evan

**Comment by ALorena** [comment]
Hi Evan,

That's exactly where I was heading... to write a review ;)

I will definitely share the truth. How helpful you were and how awesome the
plug in is.

On Wed, Jan 7, 2015 at 3:02 PM, Evan Herman <notifications@github.com>
wrote:

> No problem at all!
>
> We're glad you are enjoying the plugin. If you continue to find it useful,
> we really enjoy hearing about it in the review section of the repository. (
> https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender
> )
>
> Your review will go along way in helping others feel confident in
> installing the plugin, and it also helps others take note of our work so we
> can get a few more downloads.
>
> Take care and enjoy!
>
> All the best,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/182#issuecomment-69082474>
> .
>



-- 

To your health
,

Astrid
Founder/Webmaster
healYOUnaturally.com
Visit www.healyounaturally.com <http://www.healyounaturally.com/index.html>
 and learn how to heal what ails you without medications or fear of side
effects.

Visit our social profiles:
<https://www.facebook.com/pages/healYOUnaturallycom/256369163020>
<https://twitter.com/healU_naturally>
<https://plus.google.com/u/0/113370169364657871557/posts>
<http://www.youtube.com/channel/UCOxmluvEx3ZfploTyjikqPg?feature=mhee>
Pinterest <http://pinterest.com/healyounaturaly/boards/>

**Comment by EvanHerman** [comment]
Thank you so much Grazie :)!

**Comment by ALorena** [comment]
Evan,

I am not sure if it was your plug in or one of the other three I was
looking into, but I was debating if I should go with it being that it
didn't specify that it was "mobile friendly.  If yours is-- I'd definitely
add that.

On Wed, Jan 7, 2015 at 3:02 PM, Evan Herman <notifications@github.com>
wrote:

> No problem at all!
>
> We're glad you are enjoying the plugin. If you continue to find it useful,
> we really enjoy hearing about it in the review section of the repository. (
> https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender
> )
>
> Your review will go along way in helping others feel confident in
> installing the plugin, and it also helps others take note of our work so we
> can get a few more downloads.
>
> Take care and enjoy!
>
> All the best,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/182#issuecomment-69082474>
> .
>



-- 

To your health
,

Astrid
Founder/Webmaster
healYOUnaturally.com
Visit www.healyounaturally.com <http://www.healyounaturally.com/index.html>
 and learn how to heal what ails you without medications or fear of side
effects.

Visit our social profiles:
<https://www.facebook.com/pages/healYOUnaturallycom/256369163020>
<https://twitter.com/healU_naturally>
<https://plus.google.com/u/0/113370169364657871557/posts>
<http://www.youtube.com/channel/UCOxmluvEx3ZfploTyjikqPg?feature=mhee>
Pinterest <http://pinterest.com/healyounaturaly/boards/>

**Comment by EvanHerman** [comment]
Thanks for the input. Our forms / plugin is definitively mobile friendly. Each of the forms generated via our plugin our responsive, and adapt in width to the size of the device the users is on.

I believe we have mentioned that things are responsive, but didn't specifically mention 'mobile friendly', but we may just do that to help clarify things :)


Thanks again,
Evan

**Comment by ALorena** [comment]
Evan,

You are welcome!
Actually I mean to say responsive. Gosh do I confuse you or what?  Just
multitasking as usual (sigh).

If you did that's great, probly why I went with you guys.
Love the name of your company too.   What else? Oh why didn't you guys use
the mailchimp image for the plug in? If you can I'd do that even if you add
Yikes in the corner-- you know, your log somewhere.



On Wed, Jan 7, 2015 at 3:11 PM, Evan Herman <notifications@github.com>
wrote:

> Thanks for the input. Our forms / plugin is definitively mobile friendly.
> Each of the forms generated via our plugin our responsive, and adapt in
> width to the size of the device the users is on.
>
> I believe we have mentioned that things are responsive, but didn't
> specifically mention 'mobile friendly', but we may just do that to help
> clarify things :)
>
> Thanks again,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/182#issuecomment-69083897>
> .
>



-- 

To your health
,

Astrid
Founder/Webmaster
healYOUnaturally.com
Visit www.healyounaturally.com <http://www.healyounaturally.com/index.html>
 and learn how to heal what ails you without medications or fear of side
effects.

Visit our social profiles:
<https://www.facebook.com/pages/healYOUnaturallycom/256369163020>
<https://twitter.com/healU_naturally>
<https://plus.google.com/u/0/113370169364657871557/posts>
<http://www.youtube.com/channel/UCOxmluvEx3ZfploTyjikqPg?feature=mhee>
Pinterest <http://pinterest.com/healyounaturaly/boards/>

**Comment by ALorena** [comment]
Hi Evan,

I am not sure if I should post this issue and create a ticket over in the
WP but this is faster right now. Do let me know if I should create one over
there.

Something happened today where my site went down and ended up with a 500
ISE.  After much searching my hosting and I figured out it was the the
filter you provided

I must mention that I appended comments to the script (not sure that did
it) but it looked like this:

//*Begin MC yikes filter
// Append Yikes Inc. MailChimp Optin List to bottom of posts and pages
Did you enjoy reading this post? Get more like this by subscribing below:
function append_yikes_mailchimp_to_end_of_post_page_content( $content ) {
    if( is_single() || is_page() ) {
        $content = $content . do_shortcode( '[yks-mailchimp-list id="MY
LIST ID GOES HERE" submit_text="Submit"]' );
        return $content;
    }
}
add_filter( 'the_content' ,
'append_yikes_mailchimp_to_end_of_post_page_content' , 20 );
//*End MC Yikes filter


I had to remove the filter.

Thoughts?

Thanks for any feedback.

Astrid

Ast



On Wed, Jan 7, 2015 at 3:26 PM, heal YOUnaturally <
healyounaturally@gmail.com> wrote:

> Evan,
>
> You are welcome!
> Actually I mean to say responsive. Gosh do I confuse you or what?  Just
> multitasking as usual (sigh).
>
> If you did that's great, probly why I went with you guys.
> Love the name of your company too.   What else? Oh why didn't you guys use
> the mailchimp image for the plug in? If you can I'd do that even if you add
> Yikes in the corner-- you know, your log somewhere.
>
>
>
> On Wed, Jan 7, 2015 at 3:11 PM, Evan Herman <notifications@github.com>
> wrote:
>
>> Thanks for the input. Our forms / plugin is definitively mobile friendly.
>> Each of the forms generated via our plugin our responsive, and adapt in
>> width to the size of the device the users is on.
>>
>> I believe we have mentioned that things are responsive, but didn't
>> specifically mention 'mobile friendly', but we may just do that to help
>> clarify things :)
>>
>> Thanks again,
>> Evan
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/182#issuecomment-69083897>
>> .
>>
>
>
>
> --
>
> To your health
> ,
>
> Astrid
> Founder/Webmaster
> healYOUnaturally.com
> Visit www.healyounaturally.com
> <http://www.healyounaturally.com/index.html>
>  and learn how to heal what ails you without medications or fear of side
> effects.
>
> Visit our social profiles:
> <https://www.facebook.com/pages/healYOUnaturallycom/256369163020>
> <https://twitter.com/healU_naturally>
> <https://plus.google.com/u/0/113370169364657871557/posts>
> <http://www.youtube.com/channel/UCOxmluvEx3ZfploTyjikqPg?feature=mhee>
> Pinterest <http://pinterest.com/healyounaturaly/boards/>
>
>
>


-- 

To your health
,

Astrid
Founder/Webmaster
healYOUnaturally.com
Visit www.healyounaturally.com <http://www.healyounaturally.com/index.html>
 and learn how to heal what ails you without medications or fear of side
effects.

Visit our social profiles:
<https://www.facebook.com/pages/healYOUnaturallycom/256369163020>
<https://twitter.com/healU_naturally>
<https://plus.google.com/u/0/113370169364657871557/posts>
<http://www.youtube.com/channel/UCOxmluvEx3ZfploTyjikqPg?feature=mhee>
Pinterest <http://pinterest.com/healyounaturaly/boards/>

**Comment by EvanHerman** [comment]
Hi Astrid,

If that is a direct copy out of your functions.php file, it may be the line directly below the comments : 

"Did you enjoy reading this post? Get more like this by subscribing below:"

It looks like that line isn't commented out properly.

You can try copying the following back into your functions file, I have tested it and it doesn't appear to be throwing any errors on my end.

```php
// Begin MC yikes filter
// Append Yikes Inc. MailChimp Optin List to bottom of posts and pages
// Did you enjoy reading this post? Get more like this by subscribing below:
function append_yikes_mailchimp_to_end_of_post_page_content( $content ) {
    if( is_single() || is_page() ) {
        $content = $content . do_shortcode( '[yks-mailchimp-list id="MY LIST ID GOES HERE" submit_text="Submit"]' );
        return $content;
    }
}
add_filter( 'the_content' , 'append_yikes_mailchimp_to_end_of_post_page_content' , 20 );
// End MC Yikes filter
```


Let me know if you need help adding the function in the appropriate location. I can personally go in and add the function for you, if need be.


Thanks,
Evan

**Comment by ALorena** [comment]
Hi Evan,

Yes, that is the issue. I think I was testing it and never added the
appropiate code. Actually, I don't know much PHP anyway, but I thought I
could find something.
What I am trying to accomplish, is to be able to put some time of title and
some content to customize it as you can see.

I think I can add it in the right location in the functions.php file. What
I think I am having issues is with the syntax  or structure of the code to
make it do what I am looking for.
Maybe you can help me with that? I'd appreciate it :)

Thanks

Astrid



On Thu, Jan 8, 2015 at 6:24 PM, Evan Herman <notifications@github.com>
wrote:

> Hi Astrid,
>
> If that is a direct copy out of your functions.php file, it may be the
> line directly below the comments :
>
> "Did you enjoy reading this post? Get more like this by subscribing below:"
>
> It looks like that line isn't commented out properly.
>
> You can try copying the following back into your functions file, I have
> tested it and it doesn't appear to be throwing any errors on my end.
>
> // Begin MC yikes filter// Append Yikes Inc. MailChimp Optin List to bottom of posts and pages// Did you enjoy reading this post? Get more like this by subscribing below:function append_yikes_mailchimp_to_end_of_post_page_content( $content ) {    if( is_single() || is_page() ) {        $content = $content . do_shortcode( '[yks-mailchimp-list id="MY LIST ID GOES HERE" submit_text="Submit"]' );        return $content;    }}add_filter( 'the_content' , 'append_yikes_mailchimp_to_end_of_post_page_content' , 20 );// End MC Yikes filter
>
> Let me know if you need help adding the function in the appropriate
> location. I can personally go in and add the function for you, if need be.
>
> Thanks,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/182#issuecomment-69268924>
> .
>



-- 

To your health
,

Astrid
Founder/Webmaster
healYOUnaturally.com
Visit www.healyounaturally.com <http://www.healyounaturally.com/index.html>
 and learn how to heal what ails you without medications or fear of side
effects.

Visit our social profiles:
<https://www.facebook.com/pages/healYOUnaturallycom/256369163020>
<https://twitter.com/healU_naturally>
<https://plus.google.com/u/0/113370169364657871557/posts>
<http://www.youtube.com/channel/UCOxmluvEx3ZfploTyjikqPg?feature=mhee>
Pinterest <http://pinterest.com/healyounaturaly/boards/>
