### ISSUE TITLE
api problems for mail chimp

### ISSUE THREAD

**Issue by sbotsford** [yikesinc/yikes-inc-easy-mailchimp-extender#184]
trying to connect Mailchimp to wordpress site. error message says "Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information." help!

**Comment by EvanHerman** [comment]
Hi,

As the error states, what does the error log say the issue is?


Thanks,
Evan

**Comment by sbotsford** [comment]
It says no errors logged.

**Comment by EvanHerman** [comment]
if you can email me at Evan@Yikesinc.com, with your API key and temporary credentials, I will take a look for you.


Thanks,
Evan

**Comment by sbotsford** [comment]
I can set up a goto.

Meet now
Wed, Jan 7, 5:00 PM EST

Please join my meeting from your computer, tablet or smartphone.
https://global.gotomeeting.com/join/300420109

You can also dial in using your phone.
United States (Long distance): +1 (646) 749-3122
Access Code: 300-420-109 
More phone numbers: https://global.gotomeeting.com/300420109/numbersdisplay.html

**Comment by EvanHerman** [comment]
Ok, I'm not sure what were actually going to be able to resolve over go to meeting, I'm also at my full time job with no access to a webcam/mic.

But we can try.


Evan

**Comment by sbotsford** [comment]
thanks - can you see my screen?

**Comment by EvanHerman** [comment]
If you feel like you need additional help, please reach out to me at the email mentioned above. 


Thanks,
Evan
