### ISSUE TITLE
How do I edit the form templates

### ISSUE THREAD

**Issue by michaelofei** [yikesinc/yikes-inc-easy-mailchimp-extender#185]
Hi I'm currently using your MailChimp plugin to create optin forms for my landing page. I'm just wondering if there is anyway I can edit or remove some of the text from your templates?

Thanks

**Comment by EvanHerman** [comment]
Hey Michael.

You can remove any of the sections of the template in a few ways. You can hide parts of it using CSS selectors, setting things to display:none; , you can use a filter to remove the text in the template files, or you can copy the template to your theme for full access to do as you please.

 If you provide a link to your landing page I'll gladly provide you with some css to hide anything you'd like.


Thanks,
Evan

**Comment by michaelofei** [comment]
Wow thank you for your prompt response Evan! Our site is currently under
maintenance but I'll have a go and let you know :)
