### ISSUE TITLE
Can't get past signup 

### ISSUE THREAD

**Issue by pelmel** [yikesinc/yikes-inc-easy-mailchimp-extender#186]
I'm trying to get a mail chimp subscribe form on my website here - http://www.whatcomgop.com/?page_id=716 .  But in testing, once I enter my information and presses enter, it just refreshes the page.  What can I do to fix this?

**Comment by EvanHerman** [comment]
Hi Pelmel,

It looks like you have a few JavaScript errors being thrown on the page. If you have any js errors on your site, the ajax portion of the forms (the data being actually sent to MailChimp) wont work properly and your page will just refresh.

From what I can tell it looks like your running into a JS error with the following function:

```javascript
<script>(function() {with (this[2]) {with (this[1]) {with (this[0]) {return function(event) {return;
};}}}})</script>
```

If you can find and repair that error things should work properly , as intended.



Evan

**Comment by jmjimene** [comment]
My Form was working perfectly fine a few days ago and now it isn't. When someone puts in their information it just refreshes the page doesn't subscribe them, show the thank you, or direct them to another page.

**Comment by EvanHerman** [comment]
If it was working a few days ago, then you must have installed a plugin or switched to a theme that has JavaScript errors on the page. 

I would recommend uninstalling anything you have recently uploaded to the site. 


Thanks,
Evan

**Comment by jmjimene** [comment]
I removed everything that was installed, and it still doesn't work. In
addition I used the embedded code directly from mail chimp and it works
just fine.

**Comment by EvanHerman** [comment]
Please share a link where you are having issues and I'll take a look at the page.

Thanks,
Evan
