### ISSUE TITLE
Two forms - one not receiving confirmation emails

### ISSUE THREAD

**Issue by dogandponydesign** [yikesinc/yikes-inc-easy-mailchimp-extender#188]
I have two forms set up on my website, this one:
http://280.cce.myftpupload.com/event-space-contact-form/

and this one: http://280.cce.myftpupload.com/contactus/

When I send a test subscription to the first one, it works fine.  The second one is not sending a confirmation email.  The user is subscribed, but I am not being notified.  I double checked the spelling of the email address, etc and I can't find what is causing this.  Please advise.  Thanks!

**Comment by EvanHerman** [comment]
Hi ,

On your second form, it looks like the same form is being displayed twice on the page. If you display the same form twice on a page you're going to run into issues. Try removing one of the two forms and checking if it then works.


Thanks,
Evan
