### ISSUE TITLE
Gantry and Easy MailChimp Forms not compatible

### ISSUE THREAD

**Issue by apertureproject** [yikesinc/yikes-inc-easy-mailchimp-extender#189]
I am using WP 4.1 and Gantry 4.1.2. When I create a form and add it to a widget position, I received the following error message:

Fatal error: Unsupported operand types in .../wp-content/plugins/gantry/functions.php on line 337

I figured you all might be interested in this error. Thanks!

**Comment by EvanHerman** [comment]
Hi Apertureproject,

I will have a look into the issue. Are you referring to the Gantry Framework Plugin? (https://wordpress.org/plugins/gantry/)


Thanks,
Evan

**Comment by apertureproject** [comment]
Yes, I should have clarified that. Thank you for the quick response.

**Comment by EvanHerman** [comment]
No problem. I just installed them both and have the form displaying in the sidebar without any warnings being thrown.

Is there any specific steps to reproduce?

**Comment by apertureproject** [comment]
I created a quick form then went to Appearance >> Widgets. I have an override called Front Page in which I have it set up that only certain widgets show up on the home page. I selected that over ride and then added the Easy MailChimp widget to the sidebar, associated it to the form I created (no other modifications in regards to style etc) and clicked on save.

I reloaded the page and experienced that error. 

http://www.apertureproject.org/newsite/

**Comment by EvanHerman** [comment]
hmmm...it sounds like that plugin is causing some issues. I will have to see if I can replicate the issue, and see whats happening under the hood.


Thanks,
Evan

**Comment by apertureproject** [comment]
I will deactivate all my widgets except the required ones and then test it again.

**Comment by apertureproject** [comment]
It seems to also affect the admin side. (see photos) 

So I deactivate all plugins except those created by the theme developer, RocketTheme. Those plugins are:

Gantry Template Framework
Version 4.1.2 | By RocketTheme

RokAjaxSearch
Version 1.21 | By RocketTheme, LLC

RokBox
Version 2.50.5 | By RocketTheme, LLC

RokCommon Library
Version 3.1.12 | By RocketTheme, LLC

RokSprocket
Version 2.1.2 | By RocketTheme, LLC

When just these plugins are activated, everything works ok, but when I activate the Easy MailChimp plugin, it definitely appears to be conflicting with something. 

If you want my database and files, I am more than happy to share them. There is nothing on this site that is private.  

![all-plugins-deactivated-except-required-and-easymailchimp](https://cloud.githubusercontent.com/assets/10548894/5760871/5b9765c0-9c8c-11e4-87bc-30cdc4f8bf88.png)
![all-plugins-deactivated-except-required](https://cloud.githubusercontent.com/assets/10548894/5760872/5b97784e-9c8c-11e4-9661-527688545f72.png)

**Comment by EvanHerman** [comment]
Wow,

The framework requires that many plugins to function properly? I would almost guarantee that there is a conflict between one of those plugins and ours. Especially since it appears that a few of those function via AJAX, just like ours.

From the error you mentioned earlier, I looked into the core Gantry framework function file and it looks like it's doing something weird with the widgets by overriding them.

If you can email me at Evan@Yikesinc.com, I can take a look. But if it is infact a conflict with those other plugins, there's not really much that can be done on my end. I would gladly take a look for you tho.


Evan

**Comment by apertureproject** [comment]
I think I may have represented the plugins. I tested it and the only required plugin is the Gantry plugin. I closed my browser, flushed the cached, logged back in and deactivated everything except gantry, added the widget to the override sidebar and got the error again. I will email you. Thanks!

**Comment by apertureproject** [comment]
Evan, do you have any idea how I can disable the Easy MailChimp plugin and widget through MySQL? I can no longer get into my Admin area.

**Comment by apertureproject** [comment]
Please disregard. I figured it out. Thanks!
