### ISSUE TITLE
Mail chimp Forms in Wordpress

### ISSUE THREAD

**Issue by typieguy** [yikesinc/yikes-inc-easy-mailchimp-extender#190]
My Mail Chimp form looks different on my home page than on my blog posts. The version on the blog posts is correct. Not sure why is it showing up as an old version of the form on the home page.
![screen shot of home page](https://cloud.githubusercontent.com/assets/10555568/5770594/a8983ebc-9ce1-11e4-9613-28780bd1dc83.png)
![screen shot of blog post](https://cloud.githubusercontent.com/assets/10555568/5770596/abe56fcc-9ce1-11e4-93cf-92440ecd0e51.png)

**Comment by EvanHerman** [comment]
Hi Typieguy,

Do you have the URL to your site so I can check? It. It could potentially be a browser cache issue. Have you tried viewing it in other browsers?


Evan

**Comment by typieguy** [comment]
That was the issue. Thanks

**Comment by TheTracyL** [comment]
Glad it was an easy problem to resolve :-)
