### ISSUE TITLE
Subscribers subscribe to wrong list

### ISSUE THREAD

**Issue by vinnie2k** [yikesinc/yikes-inc-easy-mailchimp-extender#191]
Hi,

List subscription works fine except that the subscribers end up in the wrong list :-)
Where can I tell Mailchimp to add people to the correct list? Is it a setting in Easy mailchimp forms or is it on Mailchimp itself?

Thanks!
V.

**Comment by EvanHerman** [comment]
Hi Vinnie,

Whichever form you display on the page is the list that users will be subscribed too. It's not possible to sign up on one form and be added to another list because the list ID is passed along to MailChimp via the API.

Are you sure you are displaying the correct form?


Thanks,
Evan

**Comment by vinnie2k** [comment]
Awesome, that's what I was looking for :-) I was displaying my test form for when I had my test list. Thanks for putting me on the right track.

**Comment by EvanHerman** [comment]
No problem at all :)

Glad you were able to get things resolved!


Best,
Evan
