### ISSUE TITLE
Having Problem With Comment Form Opt-In Check Box

### ISSUE THREAD

**Issue by MichaelScheffel** [yikesinc/yikes-inc-easy-mailchimp-extender#193]
I confess to being a computer idiot.  That said, I shall explain my issue.  I have successfully installed the easy mail chimp plug-in and used it to add a newsletter sign up widget to my site.  Now, I am trying to figure out why the opt-in box is not appearing on a separate contact form (the newsletter sign up widget is not used on the Contact page).  I am using WP 4.1 with Studio Press Genesis framework 2.1.2.  I have verified that Mailchimp Forms>Mailchimp Settings>Display opt-in box on comment forms? is set to "show".  I am using the free Contact Form 7 plug-in.  I read in the FAQs it is necessary to set only the email field to required.  I did so, but the check box still does not show up.
Any ideas?  If not, can you point me to a contact form plug-in that you know will work with your plug-in?  Any assistance will be greatly appreciated.

**Comment by EvanHerman** [comment]
I Michael,

The Optin in checkbox is for comment forms not for contact forms. On your single post pages, when a user leaves a comment, they will then be added to your mailing list. This doesn't work for contact forms, as you mentioned.


Thanks,
Evan
