### ISSUE TITLE
Mail Chimp form has stopped working

### ISSUE THREAD

**Issue by wildkatuah** [yikesinc/yikes-inc-easy-mailchimp-extender#196]
It seems to have stopped working a couple weeks ago and yet there was no notification of a problem which is really bad. Weeks of people thinking they were subscribing when they were not. I have check the API key and that is valid.

**Comment by EvanHerman** [comment]
Hi,

You have not provided any pertinent information to help us diagnose your issue. If you can provide some information, we would be glad to help. Otherwise we will need to close out the support ticket.


Thanks,
Evan

**Comment by wildkatuah** [comment]
Let me know what to provide and I will do it.

**Comment by EvanHerman** [comment]
We can start with what you mean by "stopped working". Do the forms not submit any more, does data not get sent to MailChimp? What have you done recently to make things stop working?

Any debug information provided from the debug tab would be helpful. We've asked you to provide very specific information when opening a support ticket here. 


Thanks.

**Comment by wildkatuah** [comment]
The only think in the debug tab is the following:
This list does not have interest groups enabled	Jan. 22nd, 2015 - 12:24:32pm

I did not change anything so that is why i am baffled. When someone enters their info it appears to go through and even gives them the "thank you for subscribing message" above the widget. However the their info does not show up in mail chimp.

**Comment by EvanHerman** [comment]
If you're seeing that error in the debug tab, it most likely means at one point you had interest groups enabled, or you recently added new groups to the field and never updated the form in your dashboard.

You can try clicking 'Re-Import Form' (the yellow button at the bottom right of your list) on the manage list forms page.

**Comment by wildkatuah** [comment]
When you say dashboard do you mean in mail chimp? I will try the re-import form. Thanks.

**Comment by EvanHerman** [comment]
No from the dashboard I mean the dashboard on your WordPress site. If you go to the 'Manage List Forms' page, click the list you want to update and at the bottom right select "Re-Import" it may fix the issue.

Check this screenshot as an example : https://ps.w.org/yikes-inc-easy-mailchimp-extender/assets/screenshot-14.png?rev=1057507

**Comment by wildkatuah** [comment]
Thank you. Waiting on the re-import. Seems to be taking a while.

**Comment by EvanHerman** [comment]
It should take less than 3 seconds. It sounds like your having larger issues. Possibly some sort of issue with javascript or your ajax urls.

If you can grant me temporary access I can take a look.

**Comment by wildkatuah** [comment]
I'd be very grateful. Do you need username and password?

**Comment by EvanHerman** [comment]
Yes I'll need username and pass to access the backend.

You can email me at Evan@yikesinc.com



Evan

**Comment by wildkatuah** [comment]
Well, I hit the re-import button again, and now it says all is up-to-date. I tried entering my own name/info in the mailchimp form and now it seems to bee going through ok. Whew! Thank you very much. I am a yoga teacher, not a tech person so this sort of stuff is very challenging and frustrating for me. Thanks again for your help and patience.

**Comment by EvanHerman** [comment]
Not a problem at all! I'm glad you were able to get things resolved without much poking around.

Generally, when you update your forms over on Mail Chimps site, whether that be adding or removing interest groups from a a list, you'll always need to 're-import' the data into your Mail Chimp site.

If you make the changes from directly within our plugin, the data is re-imported automagically to help with the form updates.

If you continue using our plugin and find it at all useful, we love hearing about it in the [reviews section of the repository](https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender). Not only does the help justify the initial time we put into developing this free plugin for the community, but it also helps other users take note of the work in the repository among the hundreds of other MailChimp plugins.


Thanks and have a great afternoon!
Evan

**Comment by wildkatuah** [comment]
Ah, that will help me in the future so much, thanks. I will definitely leave a review. The plugin has worked well! Looks like just a bit of user error on my part somewhere along the way.
