### ISSUE TITLE
One list / more than one form

### ISSUE THREAD

**Issue by millerj** [yikesinc/yikes-inc-easy-mailchimp-extender#200]
On "Manage list forms" admin page, there is a "Your lists" dropdown that is populated by my Mailchimp lists. However, it appears to be only populated by lists that do not yet have a form created. This is a problem if I want to create two separate forms to feed the same list. For example, I have one form on my actual "Contact" page which has more fields and which I do want to redirect to another page on submission, and I also have a separate form that I am displaying in-line on other pages with less fields and no redirect, but I want both forms to feed the same list. Am I missing how to do this or can the "Your lists" dropdown be changed to still offer lists that already have one form? Thanks!

**Comment by EvanHerman** [comment]
Hi Millerj,

I have not come across this issue before. I'm wondering if you've resolved things on your end.

The latest release of the plugin should resolve the issue. Until then, you can run the latest stable beta of the plugin found [here](https://cldup.com/FHg0uPXZA4.zip). We should be rolling things out shortly.

Thanks,
Evan
