### ISSUE TITLE
Quotation marks in group name not escaped

### ISSUE THREAD

**Issue by millerj** [yikesinc/yikes-inc-easy-mailchimp-extender#202]
1. Create an interest group called:
test

2. Create a group name called:
one "two" three

Then when going back to edit the group name, I got this message:
Error : "one" is not a valid Interest Group for this list and grouping

It looks like the group name is getting cut off by the unescaped quotation mark.

**Comment by EvanHerman** [comment]
Hm interesting. I will have a look into this issue, and fix it in an upcoming release. Thanks for pointing this bug out!

Evan

**Comment by EvanHerman** [comment]
This will be resolved in v5.4, which I will be releasing a little later today. Thanks again for bringing up the issue here!


Thanks,
Evan

**Comment by millerj** [comment]
Great, thanks for the update!
