### ISSUE TITLE
Option for "add to mailing list" checkbox on standard contact form (not just comment)

### ISSUE THREAD

**Issue by millerj** [yikesinc/yikes-inc-easy-mailchimp-extender#203]
Thanks for the great plugin by the way. I promise this is my last post today! The plugin offers an option to add a checkbox for "add to mailing list" to a comment, but there is no such option for the standard signup form. I'm looking at using that form as both a "contact us" and a "mailing list signup", but would like to offer the "add to mailing list" checkbox, so only people who want the mailing list can be added, but otherwise can still use the form as a "contact".

I found a workaround by using the interest groups option and creating a checkbox group with only one option ("sign up for mailing list"). But it would be nice if this was a real feature without having to use the interest group workaround. Is that possible? Thanks!

**Comment by EvanHerman** [comment]
Thanks for this idea. We're looking into integrating this plugin with BuddyPress, WooCommerce and a few other great plugins out there. This way, when a user purchases a product or signs up on your site they have the option of being added to a mailing list.

This is one we have considered, and are working to include it in an upcoming release.



Thanks again,
Evan
