### ISSUE TITLE
How to recover form fields?

### ISSUE THREAD

**Issue by OVGJ** [yikesinc/yikes-inc-easy-mailchimp-extender#205]
Hello everyone. 

I have a mailing list in mailchimp, and recently used the Wordpress Plugin "Easy Mailchimp Forms by YIKES, Inc." to create a newsletter signup for my page. 

I connected it to mail chimp with an API.

I only wanted to collect email, name and organisation, so by accident I deleted the forms instead of unchecking the boxes. 
I think that I by accident ended up deleting some of my form fields in Mailchimp. 

Is there a way for me to restore the form fields? Could Mailchimp have a backup?
Or would it be possible - if I can find the old merge tags - to write them again?

Or are they lost? 

Please help me.

Oscar

**Comment by EvanHerman** [comment]
Hi Oscar,

I don't believe it's possible to recover deleted merge variables. I don't know if deleting merge variable also deletes the data associated with it for each user. You may be able to go back and check your existing subscribers and see which data is associated with their submission, but I'm not sure you can get the exact merge variable name.


Thanks
Evan

**Comment by OVGJ** [comment]
Hi Evan.
Thank you for your prompt response.
I think I will make a new list with all the fields I had before. I will start uploading all my backup'd data. I have a backup on most of it.
After that, I will import the rest from the list with lost data. 
So for the part that not backup'ed - I still have the mail and name and organisation. For some of them, I can find the rest of the data manually.
It is annoying, and time consuming, but luckily I had backup on most of it.
Thank you.
Oscar

**Comment by EvanHerman** [comment]
Hi Oscar,

I'm glad you were able to get this resolved. I know how annoying that can be! Good thinking importing all of your old data back into the list. I'm sure that saved you a bunch of time.



Evan
