### ISSUE TITLE
Radio Buttons fail...

### ISSUE THREAD

**Issue by DesignWise** [yikesinc/yikes-inc-easy-mailchimp-extender#207]
Not sure if this is just a theme issue, but I am using the generic WP 2015 theme and the radio buttons fail to load and display correctly. 
![screenshot-2015-02-09-13](https://cloud.githubusercontent.com/assets/5914290/6113532/aa3756c4-b05d-11e4-8dce-cad59de692cf.jpg)

**Comment by EvanHerman** [comment]
Hi DesignWise,

It does indeed look like a theme issue. Do you have a link to the page where you are trying to display these radio buttons? I would be more than happy to take a look and provide some CSS that should resolve the issue for you.



Thanks,
Evan

**Comment by DesignWise** [comment]
Thanks Evan,
WOW! That's FAST!
http://smartgrowthvote.com/join-gotsgv/
passwd: *github*


Stephen...
Phone: *920.256.9449*

DESIGNWISE NEW MEDIA MARKETING
DesignWise.net
<http://WebSchoolhouse.com>YouTube.com/designwise
<http://youtube.com/designwise>

<http://facebook.com/designwise>
<https://plus.google.com/u/0/b/116257459123818405959/116257459123818405959/posts>
  <http://www.linkedin.com/in/stephenkastner>
<http://twitter.com/by_designwise>
<http://www.pinterest.com/doorcountystyle/>

**Comment by EvanHerman** [comment]
Hi DesignWise,

It appears that the clean_blue.css file, that comes bundled with our template has a style defined that is causing the checkboxes to not appear. It looks like the path to one of the image files is incorrect.

What I would personally recommend, is copying over the clean_blue template into your active theme. That way any changes you make moving forward won't be lost on an update.

Once you have the template copied over to your active theme, you can make all the changes you need.

The first thing that I notice is that the images used for the checkboxes are actually missing. I would recommend first open up clean_blue.css and change the images path to pull in the correct image file.

Change the following line: 

`
.clean-blue input[type="radio"] + span {
  background: url("../images/check_radio_sheet_blue.png") -39px top no-repeat
}
`

to: 

`
.clean-blue input[type="radio"] + span {
  background: url("images/check_radio_sheet_blue.png") -39px top no-repeat
}
`

I'm going to install things locally and see if I can get things functioning. when I do I will post my CSS file, so you can just copy that onto your site.


Thanks,
Evan

**Comment by DesignWise** [comment]
Great! Thanks very much!

Stephen...
Phone: *920.256.9449*

DESIGNWISE NEW MEDIA MARKETING
DesignWise.net
<http://WebSchoolhouse.com>YouTube.com/designwise
<http://youtube.com/designwise>

<http://facebook.com/designwise>
<https://plus.google.com/u/0/b/116257459123818405959/116257459123818405959/posts>
  <http://www.linkedin.com/in/stephenkastner>
<http://twitter.com/by_designwise>
<http://www.pinterest.com/doorcountystyle/>

**Comment by EvanHerman** [comment]
Hi Stephen,

After much work we've complete re-worked the plugin. The latest stable beta release can be found [here](https://cldup.com/FHg0uPXZA4.zip).

We should be rolling things out to the repo shortly.

Thanks,
Evan
