### ISSUE TITLE
form submit reloads pages and nothing else

### ISSUE THREAD

**Issue by bigjimmy546** [yikesinc/yikes-inc-easy-mailchimp-extender#208]
hi
I downloaded your plug-in, and everything works fine with the forms,
but when I tried to submit information in the form, after I clicked on submit button, 
the page reloads itself and back to the form again.
no information were created or passed to my mailchimp account.
please kindly assist

plugin version	5.3.1
wordpress version	4.1
browser	Google Chrome 40.0.2214.111 on Mac
server	nginx/1.6.2

**Comment by EvanHerman** [comment]
Hi Jimmy,

That issue generally occurs when you have some sort of js error on the page. This prevents the ajax functionality from working, and refreshes the page without any further action being taken. Do you have a link to your site, maybe I can take a look and help pin point what the issue may be?

Thanks,
Evan
