### ISSUE TITLE
Mailchimp API Key Issue

### ISSUE THREAD

**Issue by L00ny2nz** [yikesinc/yikes-inc-easy-mailchimp-extender#209]
Plugin Version	5.3.1
Wordpress Version	4.1
Browser Information	Google Chrome 40.0.2214.111 on Windows
Server Information	Apache mod_fcgid/2.3.7 mod_auth_pgsql/2.0.3

Error Log

clear log	
Error Message	Date/Time
API call to helper/ping failed: Failed to connect to 172.224.175.7: Permission denied	Feb. 12th, 2015 - 6:15:17pm
API call to helper/ping failed: Failed to connect to 172.224.175.7: Permission denied	Feb. 12th, 2015 - 6:15:17pm
API call to helper/ping failed: Failed to connect to 172.224.175.7: Permission denied	Feb. 12th, 2015 - 5:42:02pm
API call to helper/ping failed: Failed to connect to 172.224.175.7: Permission denied	Feb. 12th, 2015 - 5:42:00pm
API call to helper/ping failed: Failed to connect to 172.224.175.7: Permission denied	Feb. 12th, 2015 - 5:41:17pm
API call to helper/ping failed: Failed to connect to 172.224.175.7: Permission denied	Feb. 12th, 2015 - 5:40:40pm

**Comment by EvanHerman** [comment]
Hi L00ny2nz,

From a quick google search it appears that your hosting provider is blocking ports which allow your site to connect to the MailChimp API.

you may want to contact your host provider and ask them to unblock those specific ports that return as *"Permission Denied"*.

Here is one resource I came across which should help : http://itaryan.com/2013/01/error-message-adding-mailchimp-api-key-in-wordpress/


Let us know if you need additional help!


Evan
