### ISSUE TITLE
Error message on bottom of form

### ISSUE THREAD

**Issue by ebtx** [yikesinc/yikes-inc-easy-mailchimp-extender#210]
I am using the plugin for the first time, and this message is displayed under the form:

Notice: Use of undefined constant display_yikes_mc_form_messages - assumed 'display_yikes_mc_form_messages' in /hermes/bosnaweb07a/b1755/d5.erniejr/public_html/littlelandplaygym.com/wp-content/plugins/yikes-inc-easy-mailchimp-extender/templates/shortcode_form.php on line 386

website is: http://www.littlelandplaygym.com/parents-day-out/

**Comment by EvanHerman** [comment]
Hi,

I noticed that this morning as well. If you turn off WP_Debug, the error message should disappear.

We're working on pushing out an update to resolve the issue.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Ebtx,

The patch has been released under v5.3.2, which should resolve the issue mentioned here. 

You can download the update now from the [repository](https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/), or you can wait for the update notification on your sites dashboard.

Thanks for creating an ticket here to alert us of the issue. If you're still having issues after updating, you can comment back here and we'll take another look.

Have a great day!


Evan
