### ISSUE TITLE
Checkbox data not transmitting

### ISSUE THREAD

**Issue by pccla** [yikesinc/yikes-inc-easy-mailchimp-extender#211]
One list form has a checkbox. When checked and form submitted, Mailchimp does not read that the box was checked.

Plugin Version	5.3.1
Wordpress Version	4.1
Browser Information	Apple Safari 8.0.3 on Mac
Server Information	Apache

**Comment by TheTracyL** [comment]
Hello, pccla.

Thank you for bringing this out our attention. 

Evan, the programmer in charge of the plugin, is out on vacation this week. He will be back next week and will be able to answer your ticket then.

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Hi Pccla,

The latest release of our plugin has completely addressed this issue. You can download the latest stable beta release [here](https://cldup.com/FHg0uPXZA4.zip), or you can wait for the plugin to hit the repository in the coming weeks.

Thanks,
Evan
