### ISSUE TITLE
3 columns, 3 rows table

### ISSUE THREAD

**Issue by dalibr** [yikesinc/yikes-inc-easy-mailchimp-extender#212]
Hello,

Is it possible to create a table like this:
Name | Hobby | Date
..........|.............|........
..........|.............|........
--------|----------|-------
Email .......

Sign Up Button

If yes, how?

Cheers,
Dal

**Comment by TheTracyL** [comment]
Do you mean there would be multiple fields for input below the header of each column?

**Comment by dalibr** [comment]
Yes exactly. Is it possible?

**Comment by TheTracyL** [comment]
Do you want all of those fields in data in Mailchimp? Did you create all of those fields and import them to your site via our plugin? It'll be a little hack-y, but I imagine you could accomplish this with CSS. A better tool for the job may be a form plugin with a MailChimp opt-in added. Something like Contact Form 7 where you can completely control the layout of the form
