### ISSUE TITLE
Forms submits successfully, but no new members added to list

### ISSUE THREAD

**Issue by wunderbarnook** [yikesinc/yikes-inc-easy-mailchimp-extender#213]
Hi,
I have successfully added the plugin and have activated API key integrated with mailchimp.
I entered test member into form and submit successfully, but member does not show up in list neither in wordpress or mailchimp!

Please advise.

Thannks, Mike

**Comment by TheTracyL** [comment]
Hi Mike.

Our programmer, Evan, is currently on vacation, but he will be back tomorrow and will be able to look into your issue then.

Thanks!

**Comment by EvanHerman** [comment]
Hi Mike,

Sometimes it takes up to 15 minutes for a user to be successfully added to a mailing list. Were you able to add a user to one of your lists, or are you still having an issue doing so?


Thanks,
Evan

**Comment by wunderbarnook** [comment]
THX, ALL GOOD





-------------------------------------------

Michael Gerike

Owner

Cypress Nook Restaurant

201 E. McNab Road

Pompano Beach, Fl 33060

www.CypressNook.com

954-933-7311



Dinner Hours:

Wednesday through Saturday 5-10pm



Breakfast and Lunch Hours:

7 Days a week from 7am til 2pm and 7am til 1pm on the weekends.

**Comment by EvanHerman** [comment]
Ah,

Ok. We're glad you were able to get things resolved. Sorry for the delay in responses. I was outside of the country with very limited access to internet.

If you run into any other issues, feel free to open up a new support ticket and we'll to helping you immediately.

Have a great day!

Evan
