### ISSUE TITLE
Yikes- mailchimp ----- I have a problem ----

### ISSUE THREAD

**Issue by rodown** [yikesinc/yikes-inc-easy-mailchimp-extender#214]
Fatal error: Uncaught exception 'Mailchimp_HttpError' with message 'API call to lists/list failed: SSL certificate problem: unable to get local issuer certificate' in /home/climixan/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.php:320 Stack trace: #0 /home/climixan/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(676): wpyksMCAPI->call('lists/list', Array) #1 /home/climixan/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(626): yksemeBase->getListsData() #2 /home/climixan/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/pages/lists.php(2084): yksemeBase->getLists() #3 /home/climixan/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(1332): require_once('/home/climixan/...') #4 [internal function]: yksemeBase->generatePageLists('') #5 /home/climixan/public_html/wp-includes/plugin.php(496): call_user_func_array(Array, Array) #6 /home/ in /home/climixan/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.php on line 320

**Comment by TheTracyL** [comment]
Hi rodown.

Our programmer, Evan, is currently on vacation, but he will be back tomorrow and will be able to look into your issue then.

Thanks!

**Comment by EvanHerman** [comment]
Hi Rowdown,

That error occurs when you're host has provided an incorrect path to your SSL certificates. Generally if you're site is using the HTTPs protocol.

One fix is to head over to the 'Debug Options' tab on the settings page and toggle 'SSL Verify Peer' to False. After you toggle this setting to false, you shouldn't have an issue validating your API key.


Thanks,
Evan
