### ISSUE TITLE
Valid Key -> InValid Key when clicking save Settings

### ISSUE THREAD

**Issue by AmmyKami83** [yikesinc/yikes-inc-easy-mailchimp-extender#215]
Hi,

I did intially have the SLL certificate problem when trying to add an API key, but I resolved that by disabling SSL Verify Peer.

Once I did that, when i copy and paste the key into the "Your Mailchimp API Key" box, I get a green tick to say this is a valid key.

Go to click "Save Settings", page reloads, the box is empty, with the message that my API key is invalid. 

I am running IIS 8.0, Wordpress 4.1.

tried in Chrome and Firefox (thinking it might be a browser issue). Same thing in both.

Regards.
Mat

**Comment by TheTracyL** [comment]
Hi Mat.

Our programmer, Evan, is currently on vacation, but he will be back tomorrow and will be able to look into your issue then.

Thanks!

**Comment by EvanHerman** [comment]
Hi Mat,

Sorry for the delay in responses, I was out of the office travelling abroad and had very limited access to a solid internet connection.

If you re-enable SSL verify peer, are you able to save the key? I don't believe that this setting should effect the JavaScript functionality of the page. It sounds like some other plugin or theme is causing a JavaScript error on the page, which is preventing the key from actually saving. The page shouldn't refresh when you click on 'save', but instead you should see a confirmation email at the top of the page.

I would try bringing up your browsers developer console, and checking to see if you are receiving any js errors on the page:
http://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Step_3:_Diagnosis

If we can pin point where the error is coming from I can help get things resolved for you so everything's working again.


Thanks,
Evan

**Comment by AmmyKami83** [comment]
Hi Evan,

Thanks, I will try this out today or tomorrow and feed back.

Cheers,
Mat

**Comment by AmmyKami83** [comment]
Hi Evan,

Hope this helps:

With SSL Verify Peer set to true, and the Advanced Logging turned on, when I put the API key in I get this in the console:

MailChimp API Response :  SSL certificate problem: unable to get local issuer certificate

And this in the Error Log:

API call to helper/ping failed: SSL certificate problem: unable to get local issuer certificate

So I set it SSL Verify Peer to False, I get "Valid API Key", but then when I click Save Settings, the page definately reloads and i get this in the console:

Mixed Content: The page at 'https://www.mywebsite.com/wp-admin/admin.php?page=yks-mailchimp-form&tab=form_options' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/mapdata/custom/world.js?ver=4.1'. This request has been blocked; the content must be served over HTTPS.

In the Error Log I get this:

API Key can not be blank

Regards
Mat

**Comment by EvanHerman** [comment]
Hi Mat,

The issue appears to be that http://code.highcharts.com/mapdata/custom/world.js?ver=4.1' is being loaded over http, but your site requires the dependencies to be loaded via HTTPS.

Are you at all able to grant me temporary access to take a look? You may just simply need to setup world.js  to load from https://code.highcharts.com/mapdata/custom/world.js?ver=4.1 .

Thanks,
Evan

**Comment by AmmyKami83** [comment]
Hi Evan,

Sorry for late reply, couple of days off :)

Let me ask the client first and then I'll get back to you.

Mat

**Comment by AmmyKami83** [comment]
Hi Evan,

Yes that is fine. How would you like me to get admin details / URL to you?

Regards,
Mat

**Comment by EvanHerman** [comment]
Hi Mat,

You can shoot me an email at Evan@Yikesinc.com and I'll take a look. I'm going to try and iron a few bugs out today.


Thanks,
Evan

**Comment by AmmyKami83** [comment]
Hi Evan,

Emailed you :) thanks very much.

Mat

**Comment by AmmyKami83** [comment]
Hi Evan,

Did you take a look at my issue?

Regards,
Mat

**Comment by AmmyKami83** [comment]
Hi Evan,

While I waited for your reply I just thought I would update to the latest version via the Plugin installer and that appears to have resolved the issue. So ignore me :)

**Comment by EvanHerman** [comment]
Hi Mat,

Sorry for he delay in responses. I'm glad that you were able to get things resolved using the latest version. 

My guess is that it was directly related to the tinyMCE editor that was initially on the settings page. Removing that seems to have resolved the issue for many of our users.


Thanks again for keeping us updated, and enjoy the plugin!


Evan
