### ISSUE TITLE
Can't change the name of form field 'Email Address'

### ISSUE THREAD

**Issue by Gelderse** [yikesinc/yikes-inc-easy-mailchimp-extender#216]
Hi, I'm trying to translate the form field 'Email Address' into 'E-mailadres' in Dutch. But when I do that, I get an error message that says 'Error : "EMAIL" does not appear to be a valid merge field for this list'. I don't get it, because the merge tag 'EMAIL' is standard. Now I'm not able to translate the field 'Email Address', though the other fields can be translated. Can you help me out? Thanks!

![mailchimp field](https://cloud.githubusercontent.com/assets/11173321/6346049/89a68f1e-bc0c-11e4-8e7d-3c24e8779d59.jpg)

**Comment by TheTracyL** [comment]
Hi there.

I have a feeling it has to do with the email field being the only field required by the Mailchimp API, but our programmer, Evan, can answer your question more fully. He is currently on vacation,but he will be back tomorrow and will be able to look into your issue then.

Thanks!

**Comment by Gelderse** [comment]
Ok thank you, I'm looking forward to his response.

**Comment by EvanHerman** [comment]
Hi Gelderse,

Tracy was correct. The "EMAIL" field is the only truly required field by MailChimp, thus limiting what can actually be changed within that merge variable.

I am going to push out a release (v5.3.3) in the next hour or so that will add a new filter, which will allow you to change the field label by adding a small snippet of code to your theme's function.php file.

I will comment back here when I get around to pushing out that release.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Gelderse,

I have just release version 5.3.3 of YIKES Inc. Easy MailChimp Extender. With that release comes a new filter for you to utilize which will allow you to alter the field label of the email address field.

Here is an example (which we've included in the readme.txt file of the plugin, and which can also be found on the 'Other Notes' section of the plugin in the WordPress repository) which will alter 'Email Address' to be 'Email'. You can change the text to whatever you'd like.

You'll want to enter this into little code snippet into your active themes functions.php file. Once added to that file, simply save the file and reload the page with the form to see things take effect.

`php
<?php
    /**
    * This example will alter the 'Email Address' field label, and return a 
    * new custom label name ('Email!')
    * anything else falls under 'default' and returns the un-altered label
    */
    function alter_mailchimp_field_labels( $label ) {

        switch ( $label ) {
            default :
                echo $label;
            break;
            
            case 'Email Address': // text of the existing label
                echo 'Email!'; // new email label text
            break;
        }
    }
    add_filter( 'yikes_mc_field_label' , 'alter_mailchimp_field_labels' );
?>
`


Please let us know if it works for you.


Thanks,
Evan
