### ISSUE TITLE
Easy MailChimp Forms Plugin for Wordpress  Settings Page not taking API Key

### ISSUE THREAD

**Issue by UsingMyJoints** [yikesinc/yikes-inc-easy-mailchimp-extender#217]
When I go into settings screen, API key space is blank but has error message " Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.	"

I copy Mailchimp API key into blank.  (I have had MailChimp check, the API key is valid).  The error message doesn't go away, and the SAVE button is not enabled.

No errors logged.

How am I supposed to add API key to the plugin?

Plugin Version 5.3.2 
Wordpress Version 4.1.1 
Browser Information  Unknown ? on Windows  
Server Information  Apache/2  
I'm on Internet exporer 11

**Comment by TheTracyL** [comment]
Hi there.

Our programmer, Evan, is currently on vacation,but he will be back tomorrow and will be able to look into your issue then.

Thanks!

**Comment by EvanHerman** [comment]
Hi Usingmyjoints,

From what you are explaining it sounds like your running into some sort of javascript error. When you paste the key into the API key field, an ajax function should fire, validating your API key with what what is stored on the MailChimp servers.

The save button should be enabled once a valid API key is returned.

Are you pasting the key in using control+v, or are you simply right clicking and selecting paste? The javascript function will fire once a key is pressed, so after you paste the key you may want to just hit the up arrow key or something to trigger it.


Thanks,
Evan

**Comment by UsingMyJoints** [comment]
Hi Evan, hope you had a great vacation.  In answer to your question, I am hitting control V to paste and then hitting enter.  Nothing -- error msg doesn't change and Save is not enabled.
Along these same lines, I also tried ctrl V to paste then TAB because I've seen forms where that works.  No joy -- error msg doesn't change and Save is not enabled.

**Comment by EvanHerman** [comment]
Hi UsingMyJoints,

If you can shoot me an email at Evan@Yikesinc.com, I'll take a closer look for you.

There may be a larger issue at hand here.


Thanks,
Evan

**Comment by UsingMyJoints** [comment]
Evan,
The API key is working since you added the first one.  I went in and changed the API key to a new one I generated and it still says valid.  Maybe the form just needed to be "seeded"???     THANK YOU VERY MUCH.
 Mary Tynes
