### ISSUE TITLE
Google Analytics Event on SignUp

### ISSUE THREAD

**Issue by NikolaiL** [yikesinc/yikes-inc-easy-mailchimp-extender#218]
Hello! Thank you for great extension!

Can you help me please. How can I setup code to trigger google analytics event on successful signup?

**Comment by EvanHerman** [comment]
Hi NikolaiL,

Sorry for the delay in responses. I'm not sure this is easy to do if you're not familiar with coding. you can implement a custom javascript script to send the request to google each time the form is successfully submit, but without much knowledge of JavaScript of Google analytics you may have a hard time and it is not something that can easily be explained.

Thanks,
Evan
