### ISSUE TITLE
Fatal error when activating Easy MailChimp Forms 5.4

### ISSUE THREAD

**Issue by Ericardh** [yikesinc/yikes-inc-easy-mailchimp-extender#219]
After upgrading Easy MailChimp Forms to 5.4 I get the following message when trying to activate: 

Warning: require_once(/home/mijnbuurt/domains/mijnbuurtje.nl/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender//Mailchimp/Folders.php): failed to open stream: No such file or directory in /home/mijnbuurt/domains/mijnbuurtje.nl/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php on line 2 Fatal error: require_once(): Failed opening required '/home/mijnbuurt/domains/mijnbuurtje.nl/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender//Mailchimp/Folders.php' (include_path='.:/usr/local/lib/php') in /home/mijnbuurt/domains/mijnbuurtje.nl/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php on line 2

How to solve this?

**Comment by EvanHerman** [comment]
Hi Eric,

In the latest release, we removed the old MCAPI_2.0.class.verify_false.php file, and replaced it with a standard untouched verison of the MailChimp php class wrapper.

Can you try toggling the SSL Verify option on the  'debug options' tab to 'True'.

You most likely have it set to false, which may be trying to reference an old file. We didn't change the name, so I'm not sure why it's saying the file was not found.

I will check it out and report back.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Eric,

I took a look at the two new MailChimp API files and it appears that the MCAPI_2.0.class.verify_false.php file had different paths set than the MCAPI_2.0.class.php file.

I would go ahead and try re-downloading the 5.4 version of the plugin. The path issue should be fixed for you.

Sorry about that,
Evan

**Comment by Ericardh** [comment]
Thanks Evan,

it is now solved!

Vriendelijke groet,

Eric.
[image: www.mijnbuurtje.nl] <http://www.mijnbuurtje.nl>
download gratis ons starterspakket voor een meer verbonden buurt
<http://www.mijnbuurtje.nl/wp-content/uploads/2014/07/mijnbuurtje-starterspakker2014.pdf>

Eric Hendriks

M: 06 535 434 66
W: www.mijnbuurtje.nl
E: Eric@mijnbuurtje.nl
T: @mijnbuurtje
A: Professor Cornelissenstraat 2
    6524 PJ Nijmegen

2015-03-02 22:53 GMT+01:00 Evan Herman <notifications@github.com>:

**Comment by EvanHerman** [comment]
Great, I'm glad to hear! 

Sorry about that :)


Have a great night!
