### ISSUE TITLE
YIKES mailchimp plugin not working after 2nd march update

### ISSUE THREAD

**Issue by AAACAA** [yikesinc/yikes-inc-easy-mailchimp-extender#220]
It is affecting our site and not sure what to do.  
Error message: Fatal error: Cannot redeclare class MailChimp.....
Can we get assistance on this?  Have deactivated plugin for now.
Thanks

**Comment by EvanHerman** [comment]
Hi Ghost,

I'm glad you were able to get this resolved. In the last release we included an unaltered version of the MailChimp API, and added a check to ensure it wasn't being loaded twice, if you were using another MailChimp plugin by chance.

Another plugin you were using could very well have been loading the same PHP class file but not checking if it had previously been loaded by another plugin.

If you run into another issue, feel free to reach out here and we'll help you get it resolved.


Thanks,
Evan
