### ISSUE TITLE
Restyle Submit Button

### ISSUE THREAD

**Issue by dscoobydee** [yikesinc/yikes-inc-easy-mailchimp-extender#221]
Good afternoon. Your plugin works effortlessly. I've briefly searched on how to style my submit button. I'd like to change the text size and font. I'm using the lifestyle pro theme. Thank you! 
Karen
http://www.karendoniere.com

**Comment by EvanHerman** [comment]
Hi Karen,

To adjust the font size or the font altogether you can target the button using CSS selectors provided by the plugin.

It depends on the route you want to take. For example, if you'd like to target <strong>all</strong> of the mailing list subscribe buttons you can use the css class .ykfmc-submit . 

If you want to target individual submit buttons, let's say if you wanted to style different form buttons differently, you could use the ID assigned to the form, which is the same as the classname but with the form ID appended. So the form in your sidebar would be : #ykfmc-submit_0-97e003bfd4.

Here is a solid jumping off point for styling the button to your needs : 

(globally)
`CSS
.ykfmc-submit {
   font-size: 16px;
   font-weight: 800;
   font-family: "Arial";
}
`

Or , alternatively, target the form on your homepage : 
`CSS
.ykfmc-submit {
   font-size: 16px;
   font-weight: 800;
   font-family: "Arial";
}
`


Let us know if that helps out at all!


Thanks,
Evan

**Comment by dscoobydee** [comment]
Thanks for the speedy reply Evan. I forgot to mention I'm a nob and don't have a real clue. So, where should I place the CSS within my stylesheet?

**Comment by EvanHerman** [comment]
You can place the code anywhere in your Style sheet, but ideally towards the bottom.


Evan

**Comment by dscoobydee** [comment]
No it didn't work. It's possible it's user error though...I used the CSS to target the form. Thanks. 
Karen

**Comment by EvanHerman** [comment]
Hi,

Which file did you put it in? Style.css? 

Which line?


Thanks,
Evan

**Comment by dscoobydee** [comment]
Yes, style.css at the very bottom. 
Thanks again,
Karen

**Comment by EvanHerman** [comment]
Hi Karen,

From what I can see, it looks like you've placed it inside of a media query.

Try moving the CSS declaration below the curly bracket ( } ) , and add the bracket you are missing. You'll also want to make sure your font family is on the same line as the 'font-family:' text:

You should change it to the following:

```
} // this closes the @media query

.ykfmc-submit { 
   font-size: 16px; 
   font-weight: 700; 
   font-family: Lucida Bright; 
}	


```

**Comment by dscoobydee** [comment]
Yep that was it! Told you it was user error. Thanks so much and here's my modest donation toward the cause. 
Take care,
Karen

**Comment by EvanHerman** [comment]
No worrys at all, thanks a bunch Karen!

If you find the plugin useful, you can give a little back by writing an honest review here : https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender

Reviews help us out more than donations do, as it helps others to take note of our hard work.

Hopefully you enjoy the plugin! If you run into any other issues don't hesitate to reach out again. We're always here to help.


Evan
