### ISSUE TITLE
how to translate 'Thank You for subscribing!' text via wpml?

### ISSUE THREAD

**Issue by bebiaelpo** [yikesinc/yikes-inc-easy-mailchimp-extender#222]
Hi,
how do I translate 'Thank You for subscribing!' text in another languages via WPML? the text doesn't show up in WPML string translation.

as I see in class.yksemeBase.php, it should work, but wpml doesn't register a string.

'single-optin-message' => __('Thank You for subscribing!', 'yikes-inc-easy-mailchimp-extender'),

Any suggestions?
Thanks

**Comment by EvanHerman** [comment]
Hi Bebiaelpo,

I don't actually have access to WPML and have used it in the past but haven't used it extensively. Are you able to grant me temporary access so I can take a look at how WPML is used to translate things? I think I may have a solution, but don't want to provide you with some code that may not work properly.

You can email me at Evan@Yikesinc.com if you'd like.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi,

You can now customize the error messages returned from the MailChimp API in our latest release.

Beta: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan

**Comment by bebiaelpo** [comment]
Thanks, Great!

**Comment by michaelschwaiger** [comment]
Hi,
thanks for this great plugin! I'm looking forward, using the beta version, unfortunately I can't activate it.
As an error message I get the following line:
Fatal error: Can't use function return value in write context in /usr/local/zend/apache2/htdocs/currycom/www/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php on line 557

There seems to be a problem creating the submenu pages.

Any suggestions?
Thanks

**Comment by EvanHerman** [comment]
Hi Michael,

Please create a new issue. Your issue and the one listed above are unrelated and do not belong in the same thread.


Thanks,
Evan
