### ISSUE TITLE
Failed nonce security check on localhost

### ISSUE THREAD

**Issue by kwaimind** [yikesinc/yikes-inc-easy-mailchimp-extender#223]
Hey

I know this issue has been raised before but when testing this plugin on localhost, I get the following error:

Failed nonce security check. Please reload the page and submit this form again.

However, when I run the firefox web developer tool and disable all cookies, the form works fine. I have no caching engine running, and have tried setting SSL Verify Peer to true and false - same issue. Advanced Error Logging is giving me no clues.

Can you help?

Currently running

* Plugin Version	5.4.1
* Wordpress Version	4.0.1
* Browser Information	Google Chrome 41.0.2272.76 on Mac
* Server Information	Apache/2.2.29 (Unix) mod_fastcgi/2.4.6 mod_wsgi/3.4 Python/2.7.8 * PHP/5.6.2 mod_ssl/2.2.29 OpenSSL/0.9.8za DAV/2 mod_perl/2.0.8 Perl/v5.20.0

**Comment by EvanHerman** [comment]
Hi Kwaimind,

I know the only other times this issue has occurred is when the site was also running some sort of back end caching or advanced caching plugin. 

The nonce security number is generated on each page load and is unique. If you have a caching plugin, the nonce number gets stored and a new one isn't generated so when the form is submitted the nonce doesn't return a unique number as expected and throws an error. This check is in place to prevent cross site scripting attacks on the form.

What other plugins are you running?


Thanks,
Evan

**Comment by kwaimind** [comment]
Hey

Ah I see. Strange as I am not running a cache though. This is my localhost site, running via MAMP with a standard Wordpress setup and the following plugins:

![screen shot 2015-03-09 at 14 42 37](https://cloud.githubusercontent.com/assets/4730761/6556008/b56d56ec-c66a-11e4-89d9-14362daddeaa.png)

Any of these look like they might cache a session?

Thanks, Daniel

**Comment by EvanHerman** [comment]
Can you try deactivating all other plugins and checking if things work? I'm wondering if it may be related to another plugin that you have installed.


Evan

**Comment by EvanHerman** [comment]
If you are still having issues please feel free to reach out to me.

Thanks,
Evan
