### ISSUE TITLE
Errors on wordpress multisite

### ISSUE THREAD

**Issue by andrewintheforest** [yikesinc/yikes-inc-easy-mailchimp-extender#224]
Hi...

When activating the plugin on wordpress multisite, the plugin works fine for the primary site.

However, on subsites, the settings page has some error that prevents the full HTML page markup being output. As a result, there is no option to hit 'save' on your configuration and cannot save any API key or other settings.

If it's of help, the last HTML that is output on the page is as follows:

get all lists from MailChimp -->

I have tested this on a completely clean install with the twentyfourteen theme activated and get this error.

Many thanks.

**Comment by EvanHerman** [comment]
Hi Andrewintheforest,

Thanks for bringing this error to our attention. This could be due to the fact that the settings page sends an API request to MailChimp to get your lists. I imagine that the API key isn't being carried down into your subsites, and thus throwing some sort of error when sending that API request.

We will have a look into the issue.

Thanks,
Evan

**Comment by marveisen** [comment]
Same problem with MU installation. Except on the main site, there is no option to save the Mailchimp options on the sub-sites, so the API key cannot be saved on any but the main site.

Looking forward to a fix for this bug.

Marv

**Comment by andrewintheforest** [comment]
Thanks Evan. Is this something that will be looked into in the next plugin update?

**Comment by EvanHerman** [comment]
Hi Andrewintheforest,

Yea this is something I want to get squared away in the next release. I was having some issues getting multi-site up and running on a localhost install, so I will have to try on a live server. I will keep you updated when I can a resuolution

Thanks,
Evan

**Comment by EvanHerman** [comment]
The latest beta release is fully multi-site compatable. You can also wait for the official release to the repo, but this issue has been addressed.

You can find the latest release [here](https://cldup.com/FHg0uPXZA4.zip).

Thanks again for reporting this here.


Evan
