### ISSUE TITLE
Plugin incompatible with some others I use.

### ISSUE THREAD

**Issue by Webdesign4pros** [yikesinc/yikes-inc-easy-mailchimp-extender#226]
Hello

I use your plugin and like it a lot but I found out that once activated some of my other plugins go crazy.

I use
-All In One WP Security
-LearnDash LMS
-Theme My Login
-Easy MailChimp Forms

1. When "All In One WP Security" , "Easy MailChimp Forms" and "LearnDash LMS" are activated at the same time, the "Installed plugins" page goes blank (no way to deactivate plugins or the other than FTP).

2. When "Easy MailChimp Forms" and "LearnDash LMS" are active ("All In One WP Security"is not!) the plugin admin page slows dowe to nearly 0and  loads for ages, and plugin "Theme My Login" admin pages go blank.

To make it short:
The administration of my WP only runs smooth when "Easy MailChimp Forms" is not active. To have it active I must first deactivate "All In One WP Security" first but even than the WP administration loads much slower than usual.

What can this be?

**Comment by EvanHerman** [comment]
HI,

Some WordPress security plugins block direct access to admin-ajax.php, which is used throughout our plugin for a lot of the back end functionality, as well as a lot of the API requests that gets triggered from the front end.

I will install 'All in One WP Security' and see if I can replicate the issue. If I can, I will take a look at what can be done to resolve it.


Thanks,
Evan

**Comment by EvanHerman** [comment]
If you are still having issues feel free to comment here. I will be closing this thread due to inactivity.

Thanks,
Evan
