### ISSUE TITLE
css sign up form

### ISSUE THREAD

**Issue by darthpadilla** [yikesinc/yikes-inc-easy-mailchimp-extender#227]
Hi!! Im a newbie and dont have much knowledge of css and would like to format my sign up form. I want to eliminate field names and place a header for the form, all in "raleway" font.

Thanks!!

My site is fitmates.mx

**Comment by EvanHerman** [comment]
Hi,

In future please provide some sort of starting base for us to work off. It's somewhat time consuming to go through and write code specific to your site...
`
#yks-mailchimp-form_1-6c53565ae4 label {
   display: none !important;
}
`
You cannot place a header above the form using CSS. If you've added the form as a widget, you can add a widget title. If you've placed it there via a php file you can use the provided hook, to hook in just before the form and place whatever content you would like.

`
 /**
    * Function to add text before the form with ID '6c53565ae4'
    * You can get form ID's from the 'MailChimp List' page
    */
    function custom_before_form_action() {
        echo '<h1>Sign up for our form below.</h1>';
    }
    add_action( 'yks_mc_before_form_6c53565ae4' , 'custom_before_form_action' );
`

Thanks,
Evan

**Comment by darthpadilla** [comment]
WOW!! Fast reply...thanks for the tip!!

I have other doubts, i'll open another ticket
