### ISSUE TITLE
how to receive an e-mail with filled out fields

### ISSUE THREAD

**Issue by acappelle** [yikesinc/yikes-inc-easy-mailchimp-extender#228]
Hi,

When I've created a form, everything works like a charm. However, I don't seem to receive an e-mail with the e-mail subscribe notification, though I filled out my e-mailaddress in the Mailchimp environment. The user filling out the form receives the final welcome message just fine. How can I receive the same content myself?

form: http://www.art-lab.be/mailchimp-offerte/

Thanks for your reply!

Anja

**Comment by EvanHerman** [comment]
Hi Acappelle,

The emails that are sent to the user upon signing up are generated by MailChimp. As far as I know MailChimp doesn't send out an email with the filled out fields.

However it would certainly be possible to make use of the hooks we've provided within the plugin to generate and send an email to yourself after each time the form has been filled out. The hook that you'll want to make use of is the `yikes_mc_get_form_data()` hook which captures user data before anything gets sent over to MailChimp.

What you would want to do is catch the user data and then generate an email using the `wp_mail()` function. It would take a little bit of custom coding, but it is certainly possible.

We will look into adding said functionality into future releases.


Thanks,
Evan

**Comment by acappelle** [comment]
Hello,

Since I'm not a developer this won't work for me :(. I'm looking forward to have this included in future releases.
But, notwithstanding things you say, I should at least receive a new user subscription notification?

THanks,

Anja

**Comment by EvanHerman** [comment]
Hi again Anja,

After looking into the issue a little bit, I've come to the conclusion that MailChimp actually offers this functionality on the site. If you head into the list you would like to receive notifications from, and at the top of the page click on 'Settings' and then 'List Name and Defaults'. 

At the bottom of this page you can enter an email address where each time a user subscribes you'll receive an email with the fields they have filled out.

![MailChimp Notifications](https://cldup.com/G3rhdnHO0K.png)

That should help out with out having to build in any new features or extending the plugin.


Thanks,
Evan
