### ISSUE TITLE
Sign up form

### ISSUE THREAD

**Issue by darthpadilla** [yikesinc/yikes-inc-easy-mailchimp-extender#229]
Hi!!

My site is fitmates.mx and I want to format my sign up form with the following characteristics:

1-All fields on the same horizontal line.
2-Asign "Raleway" font to the placeholders and submit button.
3-Have the same type of button as in the initial part of the page.

If you need more info please let me know. Thanks!!

**Comment by EvanHerman** [comment]
Hi,

This sounds like a custom CSS solution which would require some coding on your end. Our forms take on the styles of your theme by default but may require you to add some custom classes and define a few styles in your theme.

You may want to take a look at the [WordPress Codex](https://codex.wordpress.org/CSS) on custom styling.

Thanks,
Evan
