### ISSUE TITLE
Email address in confirmation email

### ISSUE THREAD

**Issue by saeah** [yikesinc/yikes-inc-easy-mailchimp-extender#230]
How do I change the email address in the confirmation email that someone receives after they register for my mailing list? My mail chimp email campaign and list reference a separate email, but it keeps directing to my personal email:

"If you received this email by mistake, simply delete it. You won't be subscribed if you don't click the confirmation link above.

For questions about this list, please contact: 
****email address@emailaddress.com*****"

**Comment by EvanHerman** [comment]
Hi Seah,

You can change the contact email address in the footer of the emails by logging into your MailChimp account and click 'Lists' at the top of the page. Select the list you want to alter, and at the top of the page select 'Settings > Required email footer content' : 

Screenshots:
![mailchimp required email footer content](https://cldup.com/Q_Zpytx7_D.png)

Next, scroll down and alter the email address under "How can recipients contact you?". This is the email address that's found in the footer of your emails. This can be altered per email.

![mailchimp alter email](https://cldup.com/Sj3G8jHnBh.png)

That should help out. Let us know if it does, or if you have any other questions!


Thanks,
Evan

**Comment by saeah** [comment]
thank you!
