### ISSUE TITLE
Compatibility with WPBakery Visual Composer Version 4.4

### ISSUE THREAD

**Issue by apperentmg** [yikesinc/yikes-inc-easy-mailchimp-extender#231]
It seems that there is a compatibility issue with the plugin when used with WPBakery Visual Composer Version 4.4.

if I wrap the short code in a visual composer row/column, the form submissions do not go through. No errors or confirmations. Plugin debugging seems to show no useful information.

When I use a short code on a page that does not use visual composer the plugin works fine. 

I can provide an account for troubleshooting.

**Comment by EvanHerman** [comment]
Hi Apparentmg,


If you can email me at Evan@Yikesinc.com with the temporary login credentials, I will take a look. I've had some issues in the past with visual composer working with a number of plugins. I believe it has something to do with the way the content is rendered on the page.


Thanks,
Evan

**Comment by EvanHerman** [comment]
In a future release we will be building out a visual composer extension. For now you can use the shortcode without issue, but there is not a dedicated extension for our plugin in the visual composer window.

Thanks,
Evan
