### ISSUE TITLE
Field title label and translations

### ISSUE THREAD

**Issue by teodorim** [yikesinc/yikes-inc-easy-mailchimp-extender#239]
Hello,
I have some problem understandig how to change the fields title and how to translate the error messages.
you can find my website at app.florim.it.
At the bottom of the page I set a form to collect emails from users and I would like to hide the field title (email address*) and I would like to have the messages language set in italian.
Can you help me?

Thanks and best regards.

Manuel

**Comment by EvanHerman** [comment]
Hi,

You cannot currently set the error messages to italian. We're working on re-writing the plugin to allow for this.

In regards to hiding the label, you can hide the field label using the css selector generated by the plugin.

```CSS
.yks-mc-label-email-address {
   display: none !important;
}
```


Thanks,
Evan

**Comment by teodorim** [comment]
Wich is the css selector? Where I can find it?
I've tried to put the custom css in the field custom class but it didn't work...
Let me know.
Regards.

Manuel

**Comment by EvanHerman** [comment]
Hi,

You can right click select inspect element and check which classes are assigned. The custom field classes should work fine.

Thanks,
Evan
