### ISSUE TITLE
yikesinc links obstructing create form list button

### ISSUE THREAD

**Issue by leanielouw** [yikesinc/yikes-inc-easy-mailchimp-extender#240]
Hi, Trying to add a mailchimp list to my wordpress site, but the links to Yikesinc help and review forms hover over the button that I need to press to add the list. 

![capture](https://cloud.githubusercontent.com/assets/11796072/6992377/50393cb8-daca-11e4-96b2-f9f22c97b504.PNG)

**Comment by EvanHerman** [comment]
Hi,

What is the resolution of your monitor? This issue will certainly be avoided in the [upcoming release of the plugin](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging). We're currently in an alpha stage, but when it does get released a ton of issues are going to be patched and a slew of new features will be included.


Thanks,
Evan
