### ISSUE TITLE
How do you center the form?

### ISSUE THREAD

**Issue by logoglo** [yikesinc/yikes-inc-easy-mailchimp-extender#242]
Hi there, in the custom style menu of your form, it says form align, I have set it to center, but its still aligned left, how do I center it?

http://makermentors.org/free-stuff/

You can see the form there.

**Comment by EvanHerman** [comment]
Hi,

It looks like you got it centered on the page successfully. We are in the midst of re-writing the plugin to address and iron out a few bugs.

If you run into any other issues feel free to post here.

Thanks,
Evan
