### ISSUE TITLE
Can't get "Opt-in checkbox for Comment forms" to display in localhost environment

### ISSUE THREAD

**Issue by iTBcom** [yikesinc/yikes-inc-easy-mailchimp-extender#243]
What a GREAT plugin!  
I'm new to Wordpress - a painter/artist building my own site.  After spending way too much time trying to implement MailChimp's "General" Opt-in form on its own page, your plugin is a Godsend(!).

"Display opt-in checkbox on Comment forms?" option is set to "SHOW" (MailChimp Forms > Mailchimp Settings screen).  But so far I don't see any opt-in checkboxes appearing above the Submit button on my test posts... 

I've encountered two plugins that exhibit limited functionality in my localhost environment (Xampp on a Windows PC).  Is this failure to display an opt-in checkbox on post COMMENTS due to my present/temporary localhost circumstances? 
Thanks

**Comment by EvanHerman** [comment]
Hi iTBcom,

It should make no difference on localhost or not. I developed the plugin on localhost, so it should work without issue. It could be the theme you are running doesn't have the proper hooks written into the plugin for our plugin to make use of. What theme are you using?

We're currently int he midst of re-writing the plugin, so the next release will be a huge update from the current plugin. You can find that in the [staging branch](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging) of this repository.

Thanks,
Evan

**Comment by iTBcom** [comment]
Hi, Evan ==
Thanks for the quick reply.  I'm using the Themify 'Basic' theme, which is a framework with lots of opportunity to modify without much (or any) coding knowledge.  The 'Basic' theme has a neat Hook Content feature.  See this link >  http://themify.me/docs/hook-content

I will GLADLY implement your newly re-written plugin upon completion, but in the meantime, if you can advise me on how to add necessary hook content to the Themify 'Basic' theme, I would undertake it immediately.
Thanks a lot, 
Tom

**Comment by iTBcom** [comment]
Evan!  
Thanks a TON for the very clear instructions.  It worked beautifully, but there is a snag.  I don't mean to burden you with this, but mention it as FEEDBACK that may or may not be useful to you.  And FWIW, I think adding the signup option to the Comment form is a FANTASTIC idea!

Having altered my comments.php file per your instructions (actually the comments.php in my Child theme folder) the checkbox and signup text DOES appear just above the Comment Submit button.  Very cool!  But here's the rub:

They only appear when I'm LOGGED IN to my WP Admin.  If I LOG OUT and view my test posts, the checkbox and text do NOT appear.  Reminder: I'm in an Xampp localhost environment.  If I *ever* get this site online, I'll maybe this will cease to be an issue...

QUESTION FOR YOU:  
When the checkbox and text DO appear, the checkbox is PRE-CHECKED.  I admire that level of Assertive Marketing <grin> but I worry that some Commenters may disapprove.  Is there a way to set the checkbox to UNchecked

**Comment by EvanHerman** [comment]
Hi iTBcom,

As mentioned in my previous comment the checkbox does only appear to logged in users. Mainly due to the fact that for the form data to be scucessfuly submitted over to MailChimp, an Email must be provided. Moving forward, with the new release we are working on this feature will be fully ironed out. I don't believe we will be pushing out any updates to the existing version as we would like to get the new one squared away sooner rather than later.

If you would like the checkbox to be unchecked on initial page load, you'll need to use some custom javascript to do so as we haven't built in an option to allow for that.

The following should help out : 
```php
function uncheck_comment_box() {
	?>
		<script>
			jQuery( '#yikes_mailchimp_comment_subscribe' ).attr( 'checked' , false );
		</script>
	<?php
}
add_action( 'wp_footer' , 'uncheck_comment_box' );
```

Keep an eye out for the new release in the coming week or two.


Thanks,
Evan

**Comment by iTBcom** [comment]
Thanks very much, Evan, and I hope I didn't clog up your thread with too many specific details.  I much appreciate the help and will post a 5-STAR review of your current plugin.  I missed your point about the checkbox only appearing to logged-in users (and not sure what that means in terms of the average visitor posting a comment on my site).  In any event, once I get this site online I'm sure it'll all make sense.

Food for Thought: MailChimp seems extremely stiff/uptight with regard to "acceptable practices".  Considering how your plugin is specific to MailChimp lists, it might be a good idea to include a means of chosing the initial Checkbox status.

Your plugin is EXCELLENT and far more intuitive than MailChimp's own.  And your Tech Support is TOO GOOD <ha!>.  I'm really looking forward to the new version of this plugin.

Thanks very much, and when finances are less strained I'll contribute or buy the Pro version, etc.
Tom 


----- Original Message -----
