### ISSUE TITLE
Nothing(very little) happens after submitting the form.

### ISSUE THREAD

**Issue by martijn99** [yikesinc/yikes-inc-easy-mailchimp-extender#245]
Hello,

A client asked us to take a look at their mailchimp form because it is not working.

If you press the button on the homepage for the sign-up, a form pops up and you can fill in a couple of details. But once you press 'send' it just goes back to the homepage, no message.

It was set to single opt-in, but also tried on double opt-in. Multiple email adresses (company, gmail, hotmail)No result. There is no adress added to the list and no confirmation mail send.

I've looked at it and to me all seems filled in correctly in the plugin settings, it has confirmed a valid mailchimp api key.

Enabled the advanced error logging. the only message showing up here is: 
This list does not have interest groups enabled

First of all I take it this is not a mandatory option to enable, but for the sake of testing I made a intresgroup and tested again. But nothing, except that the error log doesn't show the message.

The only remotely simular issue I could find via a google search was unresolved, 2 years old and suggesting a conflict with the theme. So i'm kind of stuck here.

Any suggestions or solutions?

Kind regards,

Martijn

**Comment by EvanHerman** [comment]
Hi,

Other users have reported this issue as well. We are currently working on re-writing the plugin to address some of the issues brought up by our users. We're almost ready to move into a beta stage, we are just finalizing a few of the features.

If you can email me at Evan@Yikesinc.com I can re-write part of the plugin to get things working for the time being. Moving forward there won't be any updates to the current version until the new version is released.


Thanks,
Evan
