### ISSUE TITLE
How to translate error message

### ISSUE THREAD

**Issue by cvakator** [yikesinc/yikes-inc-easy-mailchimp-extender#249]
Hi there, I don't know where to translate this message if don't put anything into the email field: 

Error - The following fields are required, and may not be left blank : E-mail

Thank you.

**Comment by EvanHerman** [comment]
Hi,

This message is not currently translatable. It is returned by the MailChimp API, and always returned in English. We are in the midst of re-writing the plugin to allow users to customize the error messages returned from MailChimp.

We are currently working hard on getting the re-write out to all of our users.

Thanks,
Evan

**Comment by cvakator** [comment]
Thanks for superfast reply. I try to push mailchimp.
