### ISSUE TITLE
Failed nonce security check. Please reload the page and submit this form again.

### ISSUE THREAD

**Issue by Lobelio** [yikesinc/yikes-inc-easy-mailchimp-extender#250]
Hi, I get this error on the 2 forms I'm using on this website: 

http://www.gowildfilms.com/joinus/
http://www.gowildfilms.com/yourstory/

Plugin Version	5.4.3
Wordpress Version	4.1.2
Browser Information	Google Chrome 42.0.2311.90 on Windows
Server Information	Apache

Thanks in advance

**Comment by EvanHerman** [comment]
Hi,

This generally happens when you are using some sort of caching plugin or your host is using aggressive caching. The nonce security check is in place to prevent XSS attacks. You may want to double check that caching isn't effecting our plugin.

Thanks,
Evan

**Comment by Lobelio** [comment]
Thanks, Evan,

There's no caching plugin and the I'm not aware of any other caching from my hosting provider (1&1). The plugin was actually working fine until a couple of weeks ago.

Best,
Teo

**Comment by Lobelio** [comment]
Sorry, Evan, I found the problem (my fault):
I'm using a custom bolierplate template without this function "getFrontendFormDisplay($list, $submit_text)"; Instead I basically copied the source code from the original form and pasted it in my own custom_header_template_boilerplate.php

I'm using this function for the nonce field but it's not working:
 <?php wp_nonce_field(); ?>	
I think that the form is not receiving the right  _wpnonce value

Any chance you could tell me how to solve this issue?
I'm really happy with this plugin but my php knowledge is not that good to solve this issue.

Best,
Teo

**Comment by Lobelio** [comment]
Hi Evan,

Finally, I found what I needed. This is the code and the correct string that the plugin is using:
<?php wp_nonce_field( 'yks_mc_front_end_form_'.$form_id[1] ); ?>

Thanks,
Teo
