### ISSUE TITLE
How to shorten the input box on my subscribe form

### ISSUE THREAD

**Issue by bonjour92** [yikesinc/yikes-inc-easy-mailchimp-extender#251]
Hi,
Thanks for the plug in. I have created a new page in my sugar and spice theme and added the form, but the email input box goes the full width of the page and I cannot see where I can shorten that. You can view it here: http://helenajohnsonauthor.com/subscribe/ 
How do I shorten the fields and also how do I centre it, once shortened, as styling it within the page didn't work.

many thanks

Helen

**Comment by EvanHerman** [comment]
Hi,

You have to use CSS to control the width of your forms.  You can also add additional custom styles to specify a width on the 'Manage forms' page.


Thanks,
Evan

**Comment by bonjour92** [comment]
Thanks for your quick response Evan. I tried everything in the Manage Forms and couldn't find anywhere to adjust this. It wouldn't let me when I clicked on edit in the fields.
Could you please be more specific about the css. Where exactly do I put it in, which file and which bit of code am I looking for. Sorry not an expert.
Thanks

Helen

**Comment by EvanHerman** [comment]
Hi Helen,

There is a checkbox on the manage lists page that lets you apply custom styles. Within that section there is a field to specifically alter the width of your form.

Also, there are many open/closed issues here on Github that provide specific examples on how and where to alter the CSS styles. You may want to take a look here and on the <a href="https://wordpress.org/support/plugin/yikes-inc-easy-mailchimp-extender">WordPress plugins repository</a>.

Thanks,
Evan

**Comment by bonjour92** [comment]
Hi Evan,
I've sussed the problem. I couldn't apply custom styles because I'd checked the template box. Once I'd unchecked it, it allowed me in and I'm sorted apart from some fiddling.  Thanks for your help and it's always the little things eh!

Helen

**Comment by EvanHerman** [comment]
Ah, that certainly would explain things. I'm glad you got things resolved. I'm actually just in the midst of wrapping up the latest version of our plugin. We've re-written the entire plugin, and moved some of the larger features over to a premium version of the plugin. Our customize will be in the premium version moving forward, so if you need access to the customizer I would hold off on updating :)

Thanks and keep an eye out for v6.0 which is a major re-write where we've squashed <em>all</em> reported bugs!


Thanks,
Evan
