### ISSUE TITLE
Similar to the below caching issue... 

### ISSUE THREAD

**Issue by mlmannozzi** [yikesinc/yikes-inc-easy-mailchimp-extender#252]
W3 total cache conflicts with my forms (they just stop working).  Are there specific files I can request W3 exclude when caching?

**Comment by EvanHerman** [comment]
Hi @mlmannozzi,

You may want to give our latest release a shot. We've re-written the plugin from the ground up and have ironed out many of the issues you see reported here in the GitHub repository.

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

In regards to your inquiry, if you install the new version you may want to exclude process-form-shortcode.php, which contains all of the functions to generate and cross check the security nonces.

Thanks,
Evan

**Comment by mlmannozzi** [comment]
oh oh. I think I downloaded the wrong thing *(sorry, not used to using Github). Which version is the latest please?
I see 5.1.1 but when I loaded it, wp is trying to update and all it’s doing is spinning.


On Apr 24, 2015, at 1:01 PM, Evan Herman <notifications@github.com> wrote:

Hi @mlmannozzi <https://github.com/mlmannozzi>,

You may want to give our latest release a shot. We've re-written the plugin from the ground up and have ironed out many of the issues you see reported here in the GitHub repository.

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging>
In regards to your inquiry, if you install the new version you may want to exclude process-form-shortcode.php, which contains all of the functions to generate and cross check the security nonces.

Thanks,
Evan

**Comment by mlmannozzi** [comment]
Evan thanks for responding earlier. I clicked on the link you sent and I see this: 
![screen shot 2015-04-24 at 5 06 56 pm](https://cloud.githubusercontent.com/assets/12091008/7328565/816ffb8e-eaa4-11e4-85ad-9d4b596a04b6.png)

If I click on "releases," version 5.1.1 from November is labeled as "latest release."   Should I instead click the "download zip" button in the lower right of the main screen?

**Comment by EvanHerman** [comment]
Hi Mlmannozzi,

Sorry for the delay in responses. I was away from my computer for a bit. The latest release that we have up on staging is our 6.0.0. version. The 5.1.1 version is older than the one you currently have installed and are having issues with.

If you follow this link : 
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

You'll be directed to the staging repo. In the right hand sidebar towards the bottom you'll see 'Download Zip'. Click that and when it's completed downloading you'll want to make sure that you rename the folder so it doesn't have -master at the end of it.

After you rename the folder you should have no problems going to 'Plugins > Installed Plugins > Add New' and uploading the zip you just downloaded and altered the folder name.

That should help out with getting the latest release installed. Let me know if you are still having issues.

Thanks,
Evan

**Comment by mlmannozzi** [comment]
Thank you so much!

**Comment by EvanHerman** [comment]
No problem :)
