### ISSUE TITLE
Invalis Mailchimp API

### ISSUE THREAD

**Issue by CrimsonFenixMarketing** [yikesinc/yikes-inc-easy-mailchimp-extender#254]
Cannot get my Mailchimp API to vaildate.

Plugin Version	5.4.3
Wordpress Version	4.2
Browser Information	Google Chrome 42.0.2311.90 on Windows
Server Information	Apache

**Comment by EvanHerman** [comment]
Hi,

Please give our latest release a shot. This issue has been addressed in this release :
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

We are looking for a few users to test it out to confirm the issue is gone before rolling things out to the WordPress repository.

Thanks,
Evan

**Comment by CrimsonFenixMarketing** [comment]
Same result.

**Comment by EvanHerman** [comment]
If you'd like you can email me at Evan@yikesin.com and we can discuss further. I would like to confirm that the issue is persistent in the new release.

Thanks,
Evan

**Comment by CrimsonFenixMarketing** [comment]
email sent.

**Comment by EvanHerman** [comment]
I haven't received an email.

**Comment by CrimsonFenixMarketing** [comment]
Realized I deactivated original plugin, but didn't delete before installing beta. Tried to delete plugin and install beta, but the install failed:

Installing Plugin from uploaded file: yikes-inc-easy-mailchimp-extender-staging.zip
Unpacking the package…

Installing the plugin…

Destination folder already exists. /home/content/88/8334488/html/cf/dev/wp-content/plugins/yikes-inc-easy-mailchimp-extender-staging/

Plugin install failed.

**Comment by EvanHerman** [comment]
We'll for whatever reason it looks like when you tried to install the beta without uninstalling the old plugin it still created the folder. You should see it listed on the plugins page if the folder already exists.

**Comment by CrimsonFenixMarketing** [comment]
It is not listed on the plugins page.

**Comment by EvanHerman** [comment]
Ok then you need to connect via FTP and manually delete the directory.

**Comment by CrimsonFenixMarketing** [comment]
I deleted and installed beta. When I tried to activate it:

Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected '[' in /home/content/88/8334488/html/cf/dev/wp-content/plugins/yikes-inc-easy-mailchimp-extender-staging/admin/class-yikes-inc-easy-mailchimp-extender-admin.php on line 1093

**Comment by CrimsonFenixMarketing** [comment]
I manually deleted the directory.

**Comment by EvanHerman** [comment]
Looking into it now. Going to activate it on a live site on my end.

**Comment by EvanHerman** [comment]
I didn't seem to have any issues on my end. I was able to upload and activate without hitting that fatal error. I just downloaded the copy from the staging repo as well.

Try and remove -staging from the end of the directory name insize of the .zip. That gets generated and appended by Github depending on the branch you download the zip from.

**Comment by CrimsonFenixMarketing** [comment]
Deleted "-staging" from directory name and zip file name. Deleted the directory. Installed beta. Upon activating, I got the same error.

**Comment by EvanHerman** [comment]
I just pushed an update to the staging repo. Try and install the plugin again. I made a few adjustments to some of our files.

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Evan

**Comment by CrimsonFenixMarketing** [comment]
Deleted plugin and directory. dl new "master" file, deleting "-master" from directory and file name. installed and successfully activated. 

When I paste my API key in the box and hit tab, nothing changes - "Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.", which is there prior to entering the key. 

It seems like it isn't trying to call the api or something. I assume it would attempt either as soon as a key is entered or after you tab off the box, correct?

**Comment by EvanHerman** [comment]
You don't want to download the master branch. You want to download the staging branch. The master branch is the current version that isn't working for you.

**Comment by CrimsonFenixMarketing** [comment]
The download button on this page is linked to the master file...
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

"https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/archive/master.zip"

**Comment by EvanHerman** [comment]
On my end when I click download from the staging branch I get the staging .zip.

I'm not sure why your getting the .master zip. You may want to try switching to the master then back to the staging.

Either way, here is file:
https://app.box.com/s/dowe1bae7phhjabit9ikv78avjzoas94

**Comment by CrimsonFenixMarketing** [comment]
I've tried both files. neither will activate. same parse error as before. sorry...

**Comment by EvanHerman** [comment]
Well if you want to email me at Evan@yikesinc.com and provide me with some temporary login so I can try and activate it that would certainly help. I can't reproduce the issue on my end so I'm not sure where the error is. I tried to follow the fatal error you mentioned before but after clearing that up you said the error still exists. If I can see what errors are happening and where I can try and mitigate the errors for you and push out a new release to GitHub.

Thanks,
Evan

**Comment by CrimsonFenixMarketing** [comment]
Login sent. I've deleted plugin and directory.

**Comment by EvanHerman** [comment]
Thank you, I am looking into it now.

**Comment by EvanHerman** [comment]
I believe the issue is related to the version of PHP running on your server. It seems that you're running 5.2, and we've formatted a few functions and arrays to be compatible with PHP >= 5.4.

I will have to re-work a few of these functions to get them to be compatible with older versions of PHP. I will keep you posted as I make progress.

Evan

**Comment by CrimsonFenixMarketing** [comment]
Thanks for the update!

**Comment by CrimsonFenixMarketing** [comment]
I think I can activate 4.4, if you'd like.

**Comment by EvanHerman** [comment]
If you can upgrade to 5.4 or later the issue should fix itself. That was a big help in identifying the problem tho, and I'm sure it will need to be addressed as the majority of users are running 5.3 I believe.

**Comment by CrimsonFenixMarketing** [comment]
I'll update. "NOTE: Programming language changes usually take 20 minutes, but they may take up to 45 minutes. "

**Comment by EvanHerman** [comment]
Ok, try and activate the plugin again in 15 or so minutes. I would imagine things would be up and running by then.

**Comment by EvanHerman** [comment]
It looks like it was updated

**Comment by CrimsonFenixMarketing** [comment]
I see that on the server side, but the php version plugin you added still showed 5.2.17

**Comment by CrimsonFenixMarketing** [comment]
can you activate it? i couldn't.

**Comment by EvanHerman** [comment]
Let me try. Did you get an error?

**Comment by CrimsonFenixMarketing** [comment]
same error

**Comment by EvanHerman** [comment]
It seemed to activate ok for me. Try emptying your browser cache and trying it again.

**Comment by CrimsonFenixMarketing** [comment]
no go. please activate. thanks.

**Comment by EvanHerman** [comment]
Plugin is active.

**Comment by CrimsonFenixMarketing** [comment]
Now I get the error when i try to log into admin.

**Comment by CrimsonFenixMarketing** [comment]
I'm in in firefox, but can't view plugins
give me same error.

**Comment by CrimsonFenixMarketing** [comment]
had to delete plugin to get back into wp.

**Comment by CrimsonFenixMarketing** [comment]
i install the php version plugin. the veresion that shows on the dashboard is changes back and forth from 5.2 and 5.4 if I navigate to a page and come back. Any ideas?

**Comment by EvanHerman** [comment]
It's definitely a caching issue. I would try browsing in private mode.

In the meantime I've disabled the plugin for you. You can try re-activating it after you've emptied your cache so you don't get locked out of the site.


Evan

**Comment by CrimsonFenixMarketing** [comment]
Private mode did the trick! Thank you! I appreciate you helping me out with the issue.

**Comment by EvanHerman** [comment]
Great I'm glad you got things resolved. No problem at all, glad I could help out. 

Have a great day.

Evan
