### ISSUE TITLE
My mailing list not available under Manage List Forms

### ISSUE THREAD

**Issue by tdierkes** [yikesinc/yikes-inc-easy-mailchimp-extender#256]
Hello,

Initially when I went to Manage List Forms (after entering my API key) I saw my mailing list in the dropdown.  Selecting Create a Form for this List did not work, however, and now when I go back to this section my mailing list is not in the dropdown.  The only option given is called "Array."

Thanks

**Comment by EvanHerman** [comment]
Hi,

Once you create a list (aka import the list to your site) it will no longer appear in the drop down.

**Comment by EvanHerman** [comment]
You can also download the most stable release [here](https://cldup.com/FHg0uPXZA4.zip).

Thanks,
Evan
