### ISSUE TITLE
Width Adjust

### ISSUE THREAD

**Issue by brettmogavero** [yikesinc/yikes-inc-easy-mailchimp-extender#257]
I have the newest version installed on wordpress, but need more explanation on changing the width of the container and locating .yks-mailchimpFormContainer.

I understand this is still in beta, but im sure the code is somewhere in here to change.

Any idea on when the pro version will be available?

Thanks!

**Comment by EvanHerman** [comment]
Hi Brett,

Do you have a link to the form on one of your pages? It will be easier to provide code specific to your site with an example.

We're not entirely sure when the pro version is going to be ready for release or even when the free version will be rolled out the WordPress repo.I am working very diligently to get things finished up, but have some things pop up in my day to day that delay things.

Hopefully in the next week or so we will have the free version rolled out to the repository. 


Thanks!
Evan

**Comment by brettmogavero** [comment]
Pennyvacay.com it's nested at the bottom of the header

**Comment by brettmogavero** [comment]
All in all its miles ahead of the alternatives out there, you guys are
killin' it!

**Comment by EvanHerman** [comment]
Hi Brett,

You can adjust the width of the form using the following CSS declaration:

```CSS
form#pre-launch-sign-up {
   width: 50%;
}
`

You can adjust the % to whatever you'd like. If you wanted to center the form after adjusting the width you can do so by adding a `margin:0 auto;` to the form. Something like so:

```CSS
form#pre-launch-sign-up {
   width: 50%;
  margin: 0 auto;
}
`

Thanks for the kind words! I'm very glad to hear that you're enjoying the re-write. I had a blast writing it! I can't wait till we can roll things out to the repo.

If you run into any other issues feel free to reach out and I'll help you as soon as possible!

Thanks again,
Evan

**Comment by brettmogavero** [comment]
I place the declaration into the style.css for the theme correct?

Sorry not a CSS master here :)

**Comment by EvanHerman** [comment]
Hi Brett,

That is correct. You will most likely want to place it at the bottom of your child theme style.css file so you know where it is in future. 

Evan

**Comment by brettmogavero** [comment]
placed it in my child theme style.css, still no change, not sure what im
missing

/*
Theme Name: Namo Child
Description: Namo Child Theme
Author: Brand Exponents
Template: namo
Version: 1.0
*/

@import url("../namo/style.css");

```CSS
form#pre-launch-sign-up {
   width: 50%;
  margin: 0 auto;
}
`

On Wed, Apr 29, 2015 at 1:59 PM, Evan Herman <notifications@github.com>
wrote:

> Hi Brett,
>
> That is correct. You will most likely want to place it at the bottom of
> your child theme style.css file so you know where it is in future.
>
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/257#issuecomment-97521551>
> .
>

**Comment by EvanHerman** [comment]
Remove the ```CSS and `. They shouldn't be there.

**Comment by brettmogavero** [comment]
Yeah i've tried it every which way, the theme must be overriding something.
This is the shortcode i'm using, not sure if that helps.

[yikes-mailchimp form="1" submit="Sign Me Up!"]

**Comment by EvanHerman** [comment]
As far as I can see you still have a back tick  at the end of the code.

You may also want to add an !important tag after the 50% and before the ;

ie:
```CSS
form#pre-launch-sign-up {
   width: 50% !important;
}
`

**Comment by brettmogavero** [comment]
figured it out, the code couldn't be at the bottom for some reason so i
moved it to the top. Thanks for helping out!

**Comment by EvanHerman** [comment]
No problem at all!


Evan
