### ISSUE TITLE
own class to submit button

### ISSUE THREAD

**Issue by adambako** [yikesinc/yikes-inc-easy-mailchimp-extender#261]
hi.

i have form classes in my theme css..
i used this class to the form in the layout file as i see where the form is rendered..

but i cant find how to add class name used on submit button..
i dont want to copy my button styles again to the class "ykfmc-submit"

where is the submit button rendered?? so i can put my class name there 
thx

**Comment by EvanHerman** [comment]
You'll find the submit button inside of [https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/lib/inc/yks-mc-frontend-form-display.php#L174](yks-mc-frontend-form-display.php) around line 174.

If you plan on using the plugin for a while I would recommend migrating over to our latest beta release. It is a complete re-write of the entire plugin and is far stable than the current one. We've included filters and hooks to alter the submit button so you won't need to edit core files.

You'll find the latest release on the staging branch of this repo.

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

We should be rolling it out to the repository in the coming weeks.

If you do migrate to the new beta, we have documented the hooks and filters we currently have in the readme.md file of the plugin.

Thanks,
Evan

**Comment by adambako** [comment]
hi,

thanks for your fast answer.. i already found the file and use my own class. also i needed to change submit button type from input to button.. i stay with this solution for now and after you realease the update i check what modifiacation i will need to make.. also i need to use css for hide field title and asterisk.. i thing it should do easy too.. 
i attach my finally layout just to show that i need simple form as possible :)

thx again
![snimka obrazovky 2015-05-01 o 1 03 25](https://cloud.githubusercontent.com/assets/8457004/7424119/e742a4a4-ef9d-11e4-85f2-3e12998c559d.png)

**Comment by EvanHerman** [comment]
No problem at all!


Evan
