### ISSUE TITLE
MailChimp API key

### ISSUE THREAD

**Issue by cclh** [yikesinc/yikes-inc-easy-mailchimp-extender#263]
I keep getting this error when I try to add a Mailchimp API key:

Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.

I have generated a couple of keys to try but the same message for each one

I also tried to upload the beta version of the plugin as you recommended to someone else but this made the plugin crash al together

**Comment by EvanHerman** [comment]
Hi,

I still would recommend running the beta as we're getting very close to release. I'm sure you downloaded the beta version just a few mins ago, which would explain the error. 

I've split things into two directories, one for our assets in the wordpress repo and the other for our core plugin files. 

You'll probably want to delete the repo_assets folder and move all of the core plugin files to it's own zip, and then trying to re-upload things. That would fix things for you.

Evan

**Comment by EvanHerman** [comment]
If you're still interested the latest release of the plugin can be found [here](https://cldup.com/FHg0uPXZA4.zip).

We should be releasing things shortly.


Thanks,
Evan
