### ISSUE TITLE
Edit email form field

### ISSUE THREAD

**Issue by andersoncasey** [yikesinc/yikes-inc-easy-mailchimp-extender#264]
I am trying to edit the email form field to delete the default label of "email*" and I am unable to. When I try to edit this field I receive the following error message, "You cannot update the EMAIL merge variable. If you'd like to change the field name/label, please use the yikes_mc_field_label filter. ( see readme.txt for example )"

I am unclear as to where to go to change this and cannot find the readme.txt anywhere. Any help would be much appreciated. 

Thanks, 
Casey

**Comment by EvanHerman** [comment]
Hi Andersoncasey,

Can you please provide a link to your site so we can take a look. Without access to your site, it would be hard to guess what is going on. Do you just want to hide the label field for the email field?

Thanks,
Evan

**Comment by andersoncasey** [comment]
samaschool.org 

the bottom of every page now has a subscribe form embedded so you can see it on every page. Yes I just want to hide the label field with the asterisk. 

Thanks!

**Comment by EvanHerman** [comment]
You can hide the label by simply adding the following css declaration to your child theme style.css file:

```CSS
..yks-mc-label-email-address {
   display: none !important;
}
`

I would also consider downloading the latest release from this repository. It is a complete re-write of the plugin and much easier to hide the labels of fields without actually writing code.

We should be rolling over to the new version in the next week or so.

Let us know if that helps.


Thanks,
Evan

**Comment by andersoncasey** [comment]
Hi Evan, 

That worked perfectly! Thanks! 

One other question -- is there a way to add text to the text input box so that it says 'email' until you click on it and thus remove the need for an external label?

**Comment by EvanHerman** [comment]
Hi Andersoncasey,

You can add the text into the field to give the user some indication of what's expected by filling in the 'placeholder' field on the manage forms page.

You can add 'Email' into the field to let the user know that is the email field.


Evan
