### ISSUE TITLE
Edit Template Text

### ISSUE THREAD

**Issue by xtcm8** [yikesinc/yikes-inc-easy-mailchimp-extender#265]
How do I change the standard text in the supplied templates?

E.G. I would like to use this one but it talks about fitness, how do I change it?
I'll Teach You FREE, How You Can...
Achieve your fitness level in no time!
Etc., etc.
Also, the picture doesn't display.

I read on one of the previous posts that you can copy the template to Wordpress to make the changes.  How do I do this?

**Comment by EvanHerman** [comment]
Hi,

There is a button where you select your templates to import the template files into your theme. You can use that, or read the 'How To' on how to manually copy over the files. Once copied over its simply a matter of deleting the unwanted text, or altering it to your needs.

Thanks,
Evan
