### ISSUE TITLE
Error : Zend_Exception: No object named "request" is registered.

### ISSUE THREAD

**Issue by toniup** [yikesinc/yikes-inc-easy-mailchimp-extender#266]
I've installed the plugin...and then vaious attempts...there is this error : 

Zend_Exception: No object named "request" is registered.

screenshot:
https://drive.google.com/file/d/0Bwhfq7PWR5ZqZjZMNVQ5YllZX0U/view?pli=1

**Comment by EvanHerman** [comment]
Are you using the new version or the old version? That error does not sound like it is coming from our plugin. We have not included the Zend framework in our plugin.

Can you try deactivating all of your other plugins and trying again? That error may be coming from another plugin you have installed.

Thanks,
Evan

**Comment by EvanHerman** [comment]
It sounds like you're using another MailChimp plugin, found here:
https://wordpress.org/support/topic/zend_exception-no-object-named-request-is-registered

Thanks,
Evan

**Comment by reneel** [comment]
No, I have a client that's using your plugin with the same issue. However it appears to be a Mailchimp issue.

**Comment by EvanHerman** [comment]
I will take a look into the issue shortly and report back here if I can locate some issue.

**Comment by reneel** [comment]
Okay, thanks.
