### ISSUE TITLE
Extra privacy checkbox

### ISSUE THREAD

**Issue by alexholzreiter** [yikesinc/yikes-inc-easy-mailchimp-extender#267]
Hi there, is it possible to add a extra privacy checkbox for EU laws compliance?

**Comment by EvanHerman** [comment]
Hi,

Are you using our new beta, or are you using the version found in the WordPress repository?

You can achieve what you are after using either version, but it will be much easier to achieve what you are after using the new beta. The version currently in the WordPress repository does not have some of the hooks and filters built into the new version.

If you can get the new beta version installed I will be glad to provide you with a little bit of code to get you headed in the right direction.



Thanks,
Evan

**Comment by alexholzreiter** [comment]
What`s the fastest way to get the beta can't find it ;)

**Comment by EvanHerman** [comment]
Hey, 

At the moment the fastest way to get the beta is by downloading it from [here](https://app.box.com/s/pkstootfcx8nl98giftu29gthkn69vsp). The .zip we have up here in the repo has a few files that are un-necessary to get the plugin up and running on your site.

The version you can download above, has the un-necessary files stripped out.

Let me know when you have the new version installed and you've created your form and have placed it onto it's own page. You may want to share the link here so I can take a look for the necessary ID/classes of the form.

Thanks,
Evan

**Comment by alexholzreiter** [comment]
Okay beta is installed, API Key is setup, now we`re talking ;) So show me the magic how to insert a checkbox ;)

**Comment by EvanHerman** [comment]
Awesome, I'm glad that went smoothly for you.

Give me a few minutes to write up an example. We're going to make use of the provided [hooks and filters](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/wiki/developer-docs) to get this done. I will post back here when I get a minute to write up the example and test it out.

Thanks,
Evan

**Comment by alexholzreiter** [comment]
sounds perfect ;)

**Comment by alexholzreiter** [comment]
Actually i`ve implemented the Address-fields like shown in Mailchimp, Street Adress, City, State, Postal and a dropdownlist for the Country, but in the Plugin it shows me only one field for address did i do something wrong?

**Comment by EvanHerman** [comment]
Hi Alex,

No, I don't believe that you did something wrong. We are still finalizing all of the form fields. I believe one of the last ones to get to is the address field.

I will get this example to you and then I'll work on finishing up the address field.

Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Alex,

I've added one additional hook to take advantage of, so I've re-released the latest release candidate.

You can download that version from here:
https://app.box.com/s/ph862eiw81qtfpktw3k78bqt7dbh0lo7

In regards to what is required to get the checkbox to appar below the form, you can use the following two hooks.

```php
/* Add additional checkbox field to form with id 4 */
function add_checkbox_after_form() {
	echo '<label><input type="checkbox" name="eu-laws" value="1"> I agree to comply with EU laws.</label>';
}
add_action( 'yikes-mailchimp-additional-form-fields-4' , 'add_checkbox_after_form' );

/* check if the checkbox was checked, if so continue, else return a custom error message */
function populate_user_firstname( $user_data ) {
    if( isset( $user_data['eu-laws'] ) ) {
		return $user_data;
	} else {
		$user_data = array(
			'error' => 1,
			'message' => 'Please check the checkbox to ensure that you comply with the EU Laws.'
		);
	}
    return $user_data;
}
add_filter( 'yikes-mailchimp-before-submission-4' , 'populate_user_firstname' );
```


Let me know if you have additional questions. I have tested this out and all seems to work as expected. If the user submits a form withotu checking off the checkbox, you're custom error is returned and no data is sent to MailChimp. Only once the checkbox is checked off will the data be submitted to MailChimp.

You'll want to place the above to functions into your active theme function.php file. You may also notice that -4 is appended to both the filter names. This allows you to target a specific form by ID. You can get the form ID either on the manage forms page, or on the page to edit a specific form.

Let me know if you're having difficulties getting things up and running. In the next day or two I will get this included into our developer documentation as I'm sure this will be a fairly popular tweak.


Thanks,
Evan

**Comment by alexholzreiter** [comment]
Hi Evan, thanks for your quick reply, i`ve added the two function at the end of the functions.php......How do i place this checkbox into the form?

**Comment by EvanHerman** [comment]
What is the ID of your form? You simply need to change the -4 to the ID of your specific form. The first action hook above renders the checkbox into the appropriate form.

**Comment by alexholzreiter** [comment]
ID 1, do i need the Form Customizer do insert the checkbox?

**Comment by EvanHerman** [comment]
No, you simply need to add the two functions above to insert the shortcode. As mentioned, once you add the functions above, and append -1 to the hooks, things will just start working. No further interaction needs to be taken.

Did you re-install the latest release with the new action hook? Also the two functions below have been adjusted for form 1.

```php
/* Add additional checkbox field to form with id 1 */
function add_checkbox_after_form() {
    echo '<label><input type="checkbox" name="eu-laws" value="1"> I agree to comply with EU laws.</label>';
}
add_action( 'yikes-mailchimp-additional-form-fields-1' , 'add_checkbox_after_form' );
```

```php
/* check if the checkbox was checked, if so continue, else return a custom error message */
function populate_user_firstname( $user_data ) {
    if( isset( $user_data['eu-laws'] ) ) {
        return $user_data;
    } else {
        $user_data = array(
            'error' => 1,
            'message' => 'Please check the checkbox to ensure that you comply with the EU Laws.'
        );
    }
    return $user_data;
}
add_filter( 'yikes-mailchimp-before-submission-1' , 'populate_user_firstname' );
```

**Comment by EvanHerman** [comment]
Note: You can also customize the returned error message inside of the returned $user_data array
eg:
```php
$user_data = array(
            'error' => 1,
            'message' => 'Please check the checkbox to ensure that you comply with the EU Laws.' // change error response here
        );
```

**Comment by alexholzreiter** [comment]
Works like a charm, just take a look http://goo.gl/2nvTCz
One question, the Email background "grey" is gone, i don't know why? Maybe you can help?
And for sure, you have to insert this "addon" it`s actually know plugin for the EU Law available!

**Comment by EvanHerman** [comment]
Great! I'm glad that we got that working! It looks great.


In regards to the email background changing, I'm not sure why that would have happened between the last release and this one. I will certainly take a look into that though.

In the meantime you can override the styles by adding the following to your style.css file:

```CSS
input#EMAIL {
  background: #F1F1F1;
}
```

That should set the background of the email field to the same color light grey as the other fields. Let me know if that works on your end.


Evan

**Comment by alexholzreiter** [comment]
awesome!! Great!! Next step should be the Street Adress, City, State, Postal and a dropdownlist for the Country ;)

**Comment by EvanHerman** [comment]
Great, the form is looking good on your end.

I will be working on that as well as the Easy digital downloads, bbpress and woocommerce checkbox integration tonight.

When they are complete I will release the final release candidate for final beta testing before pushing things out the repository.

Thanks again and I'm glad you got things working!


Evan

**Comment by alexholzreiter** [comment]
sounds perfect, I´ll wait ;) keep on going, if you want me to test, don`t hesitate to contact me...

**Comment by EvanHerman** [comment]
Hi Alex,

I've now pushed out a new beta release with all of the possible MailChimp fields finalized, including the address field.  

The easiest way to download it is via the following URL:
[Latest Beta Release](https://app.box.com/s/i2awje83sd8g450bbe2zt0ksx9nmk0kb)


Evan

**Comment by alexholzreiter** [comment]
Hi Evan,

everything works like a breeze, but it seems to me something with the css isn’t correct.
Sometimes its switching between these two layout versions. see attached Screenshots.

**Comment by EvanHerman** [comment]
Hi Alex,

I can't see any screenshots attached to your response.

Evan

**Comment by alexholzreiter** [comment]
https://www.dropbox.com/s/eh8e63fcm52nqpk/Bildschirmfoto%202015-05-17%20um%2022.51.05.png?dl=0 <https://www.dropbox.com/s/eh8e63fcm52nqpk/Bildschirmfoto%202015-05-17%20um%2022.51.05.png?dl=0>
https://www.dropbox.com/s/u6f13sq2l7cu0st/Bildschirmfoto%202015-05-17%20um%2023.10.23.png?dl=0 <https://www.dropbox.com/s/u6f13sq2l7cu0st/Bildschirmfoto%202015-05-17%20um%2023.10.23.png?dl=0>

Alex

**Comment by alexholzreiter** [comment]
you can check it yourself by visiting the page:
http://akademie-u5.com/infomappe/ <http://akademie-u5.com/infomappe/>

**Comment by EvanHerman** [comment]
Hi Alex,

The page is password protected, but I can see the issue in the screenshots. Is the issue still persistent today? It could be a temporary cache issue.

Evan

**Comment by alexholzreiter** [comment]
The password is: akademieu5alex

It always appears in the first load :( 

Sent from a mobile device. Please excuse brevity and typos.

**Comment by EvanHerman** [comment]
Hey Alex,

Thanks for the password. Things appear ok on my end. This is how things look in my browser: 
https://www.diigo.com/item/image/4s1ed/t7cj

Are you still having that issue of things appearing in the way they were in that screenshot?


Evan

**Comment by alexholzreiter** [comment]
Still The Same issue, After refreshing its ok..



Sent from a mobile device. Please excuse brevity and typos.

**Comment by EvanHerman** [comment]
What browser are you viewing it in? I am viewing in chrome and don't see any issues, even after clearing my browser cache or viewing it in private browsing mode.


Evan

**Comment by alexholzreiter** [comment]
The latest version of safari and Firefox, on both the same experience, initial load of page looks corrupt after refreshing it looks as it should.

Greets,
Alex

Sent from a mobile device. Please excuse brevity and typos.

**Comment by EvanHerman** [comment]
Hi Alex,

I have loaded it in all of the browsers that I can access, which is FireFox, Chrome, Safari Mobile and Internet Explorer. All of them seem to be loading the page just fine. Are you still having issues?

Thanks,
Evan

**Comment by TheTracyL** [comment]
Hello Alex.

We are getting ready to release the EU compliance plugin as an add-on. I was wondering if you could send me a link to more information on the law so I can write the description for the add-on.

Thank you!
-Tracy
