### ISSUE TITLE
I created two sign up forms - they were working - now they are not

### ISSUE THREAD

**Issue by HeatherJadus** [yikesinc/yikes-inc-easy-mailchimp-extender#268]
I don't understand why when I hit submit, it acts as if everything has been submitted with no errors but the page does not redirect as I indictaed in the form settings nor do any names get added?
Ahhhhhhhhhhhhhh.
Extremely frustrated!  And need this to work NOW!!!!!!!!!!!!!!!!!!

**Comment by EvanHerman** [comment]
It sounds to me like you have a JavaScript error on the page. If you need it to work now , you'll need to resolve the js error on the page or download the beta we have released. You may want to look through some of the recent issues to find the download link. 


Evan

**Comment by EvanHerman** [comment]
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/267

**Comment by HeatherJadus** [comment]
does that mean it might only be a problem on just my computer?  Others might not have the same issue?
And thank you!

**Comment by HeatherJadus** [comment]
Not sure what to do... hmmmm...

**Comment by EvanHerman** [comment]
No. That means you hVe a JavaScript error on the page. as suggested follow through the link above , download the beta and reinstall the plugin. 

Thanks
Wvan

**Comment by HeatherJadus** [comment]
WOrking on it.  If it says the folder already exists... how do I get rid of it?

**Comment by EvanHerman** [comment]
You have t uninstall the current version before you can install it again.

**Comment by HeatherJadus** [comment]
I don't see where to uninstall

**Comment by HeatherJadus** [comment]
Just delete or inactivate

**Comment by EvanHerman** [comment]
Delete. You'll have to recreate the forms upon reactivation.

**Comment by HeatherJadus** [comment]
It worked!  Woot Woot!  Thank you!

**Comment by EvanHerman** [comment]
Great! I'm glad the new version works for you. We should be rolling the final version out soon.

Thanks for keeping us posted! 
Evan
