### ISSUE TITLE
Change font on email confirmation message

### ISSUE THREAD

**Issue by remelfam** [yikesinc/yikes-inc-easy-mailchimp-extender#271]
The Easy Mail Chimp form on my website works very well, except for one thing. When an email is submitted, the email confirmation comes up in a dark font that is almost indiscernible against the dark background of my theme. Is there a way to alter the font of that message? Thanks so much for this fine plug-in.

**Comment by EvanHerman** [comment]
Hi,

You can alter the styles of the font and any things else related to the form writing some CSS code and placing it in your active theme style.css file.

I would recommend you read through some of the following articles for some information, tips and a starting point:
https://codex.wordpress.org/CSS
https://codex.wordpress.org/Finding_Your_CSS_Styles
https://wordpress.org/support/topic/complete-newbie-question-how-to-edit-stylecss-to-change-a-font?replies=6

Thanks,
Evan

**Comment by remelfam** [comment]
Okay. Thank you!

Regan
