### ISSUE TITLE
How to use the class rc-anchor-small ?

### ISSUE THREAD

**Issue by openmind2k5** [yikesinc/yikes-inc-easy-mailchimp-extender#273]
Hello.

I wanted to reduce the width of the  the RECAPTCHA I AM NOT A ROBOT box. No luck. I tried css 

.rc-anchor {
	width: 200px !important;
}

(initial width is 300)

No luck so I started to check the plugin and figured out that the plugin uses a remote css fila located on gstatic.com

I also found inside that particular file a class called .rc-anchor-small which draws a box of 156x156 px

How can I force the plugin to use that class (there is no option to chose anything in the plugin settings..so I guess I have to change some line of code somewhere.)

Could you please help me with this ? 

Best wishes
Adrian

**Comment by EvanHerman** [comment]
Hi,

I don't believe that you can currently re-style the reCaptcha form. I have tried in the past, but have had no success. It looks like the recaptcha library loads its own external CSS and JS files which cannot be overridden.

I will leave this issue open as I hunt for a reasonable solution.


Thanks,
Evan

**Comment by openmind2k5** [comment]
Thank you so much Evan. I noticed that the css is remote on Google's
server. I tried to override it locally with css ... No luck.

Thank you again. I'll check from time to time.

Best wishes
Adrian
În Mar, 2 iun. 2015 la 18:59 Evan Herman <notifications@github.com> a scris:

**Comment by gcodelabs** [comment]
Thanks for give the Solutions !!!

But we can overwrite the css.
if you need help, just reply.

Thanks 
Adrian
