### ISSUE TITLE
New account

### ISSUE THREAD

**Issue by TwinFox** [yikesinc/yikes-inc-easy-mailchimp-extender#274]
Hi,

I am using your MailChimp plugin on my WordPress site.  My company started using Booker, an online scheduling system, and they set up a new MailChimp account for us.  

It looks like in my MailChimp settings in the plugin that my new MailChimp account that Booker created is there and active. However, when I go on my website and fill in my email to sign up, it subscribes a new email to our old MailChimp account.  I'm not sure why this is happening.  Since my new MailChimp account is there in the plugin settings, why are new subscribers being added to the old MailChimp account.  Does this make sense? How do I change this? I would like to shut down our old MailChimp account but can't until I make sure that all new subscribers are added to the new MailChimp account.

**Comment by EvanHerman** [comment]
Hi TwinFox,

If your users are being added to the old list it could be because you haven't added your new API key into the settings page. If you have, I would recommend you uninstall and re-install the plugin and enter your new API key again. The API key could be stored in the cache causing new users to be added the old account.

You may also want to just clear your browser cache.


Thanks,
Evan

**Comment by TwinFox** [comment]
Cool!  Thanks for the quick reply.  I'll try that.

By the way, your plugin is great!  We are a small web company in Philly
too!  My husband and I are ColdFusion developers too.  Not many of us
around anymore.  :)

Thanks for your help!

**Comment by EvanHerman** [comment]
No problem at all! and that's awesome, small world! We have a Cold Fusion in house as well. Not too many left at all, but still very valued :)

Did you find the plugin up in the WordPress repository? We are going to be releasing a new version of the plugin in the coming weeks. We have the latest release up on our staging repo found (here)[https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging].

If you'd like to give that one a shot you can scroll down a bit and click on the 'Latest Stable Release' link. Things are far more stable in this release and we've shifted things into it's own table in the database for some higher level customization.

Either way, we're glad you're enjoying the plugin ! :+1: 

Evan

**Comment by TwinFox** [comment]
Hi, Evan,

I'm still working on this issue.  Can you tell me how to clean up my form?
We are using a list from MailChimp.  The list is also imported from Booker,
our online scheduling program.  It looks like the jumbled mess are email
campaigns that I've set up in Booker. I don't know why they are showing up
in the MailChimp form or widget.

[image: Inline image 2]

**Comment by EvanHerman** [comment]
Hi,

I'm not currently able to see the image you've attached to your question. I also don't believe I am understanding the issue properly.

If you've generated the forms through our plugin, you should have a standard html form. You won't get anything fancy. From your explanation it sounds like you've done something else to allow for something more advanced, or additional data to be displayed alongside the form.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi Elise,

If you still need assistance feel free to shoot me an email!

Evan
