### ISSUE TITLE
Looking for my API code for Mail Chimp

### ISSUE THREAD

**Issue by lilcelebrations** [yikesinc/yikes-inc-easy-mailchimp-extender#275]
Looking for my API code for Mail Chimp.  Thank you!

**Comment by EvanHerman** [comment]
Please follow along with our documentation.
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/wiki/Setup-Guide
http://kb.mailchimp.com/accounts/management/about-api-keys

Thank you,
Evan
