### ISSUE TITLE
Creating submenu pages causing error on Install

### ISSUE THREAD

**Issue by michaelschwaiger** [yikesinc/yikes-inc-easy-mailchimp-extender#276]
Hi,
thanks for this great plugin! I'm looking forward, using the beta version, unfortunately I can't activate it.
As an error message I get the following line:
Fatal error: Can't use function return value in write context in /usr/local/zend/apache2/htdocs/currycom/www/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php on line 557

There seems to be a problem creating the submenu pages.

Any suggestions?
Thanks

**Comment by EvanHerman** [comment]
Hi Michael,

Does this only happen on plugin activation, or does the plugin actually activate?

What version of PHP is your site running?


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hey Michael,

After taking a look, you are correct. There was a minor error on plugin activation trying to create the submenu.

The issue has been addressed and resolved. I've just rolled out a release candidate 3.0, which should now work without any issues.

Feel free to download the latest release from the following url:
https://cldup.com/jrUraHxhgN.zip

Sorry about that, but thank you for catching and reporting the issue!

Please let me know if there is any issues on your end.


Thanks,
Evan

**Comment by michaelschwaiger** [comment]
Hi Evan, 

thanks for your support, I'm looking forward to try it out.

Cheers,
Michael
