### ISSUE TITLE
signup form not working

### ISSUE THREAD

**Issue by jauyong** [yikesinc/yikes-inc-easy-mailchimp-extender#278]
Hi,

My signup form is not working when using the extension. I have confirmed that it works when using the mailchimp url. I have also tested to make sure the connection is up to date by editing the fields and seeing the updated text in my wordpress extension. When I fill out the fields and hit submit, the page just refreshes and the submit didn't do anything. I don't receive any email as I do when using the direct mailchimp url. 

thanks for your help.
- J

**Comment by EvanHerman** [comment]
Hi,

Do you have a link to a form where you are having issues? You may want to try switching things over to not use ajax form submissions. You most likely have a javascript error on the page which is why the page refreshes without the user ever being added to the list.


Thanks,
Evan

**Comment by jauyong** [comment]
Hi thanks for your reply...

Here are the two forms:
http://www.1000mice.com/?page_id=11036
http://www.1000mice.com/?page_id=11043

The issue is, is that I've just used templates and haven't written any code
myself. The theme is Avada, a very popular theme.

How can I switch over to not use ajax? Is that something on the mailchimp
extension or something on the wordpress page the form is embedded on?

Any help is greatly appreciated.

Thanks,
J

**Comment by EvanHerman** [comment]
Hi Jauyong,

Are you using our latest beta release or are you using the version that we have up in the WordPress repository?

If you're using the version up in the repository I would suggest that you download the latest stable release that we have rolled out.  You can find that version here: https://cldup.com/jrUraHxhgN.zip

The latest version is far more stable and has been re-written to help prevent any of these errors from happening. It looks like the javascript error is generated only on pages with the forms, and not on other pages. Once you install the latest version you should be able to migrate over your existing forms into the plugin, but you'll need to update your shortcodes with the new form ID.

After you install the latest release, and update your shortcodes you should no longer be seeing this error. On top of that you can toggle the AJAX functionality of the forms to test out if what you are facing is indeed a javascript error.


Thanks,
Evan

**Comment by jauyong** [comment]
Hi,

Thanks for the suggestions.

I've installed the version you linked above but it seems to be having problems recognizing the fields. 
I have verified the shortcode to be correct.

http://www.1000mice.com/?page_id=11036
http://screencast.com/t/NW695RdBE2Ap

**Comment by EvanHerman** [comment]
Hi,

That looks to be correct, althought those slashes shouldn't be there (obviously) and i'll get that cleared up before the release.

Have you tried re-adding the fields to the form and re-saving things?

It could be the way the fields saved during the migration.


Evan

**Comment by jauyong** [comment]
hmm, yes I've tried removing and adding back. As well as only adding a selection of fields as opposed to adding all 4. I should mention that on my initial adding of fields I saw an error message a about a JS/ajax (can't remember) error on line 88 etc. etc....but i removed and added back and haven't been able to reproduce that message.

**Comment by EvanHerman** [comment]
hmmm,

Have you tried creating a secondary form? That might trigger the js error again, but it looks like the fields are assigned to the form properly.

**Comment by jauyong** [comment]
yea, I tried creating a secondary form. didn't trigger the error but it produced the same message:

Whoops, it looks like you forgot to assign fields to this form.

**Comment by EvanHerman** [comment]
Let me take a look on a localhost install on my end and see if I can replicate the issue. Last I checked things seemed to be functioning properly on a fresh install running the 2015 theme.


Evan

**Comment by EvanHerman** [comment]
The latest release (release candidate 3.0) seems to be working without issue on my end, on a localhost and up on a live site.

I'm not entirely sure what's going wrong on your end.

**Comment by jauyong** [comment]
Do you think it has to do anything with the \ after the ' ? After every form update it adds more \

http://screencast.com/t/kYgFPLycf

**Comment by EvanHerman** [comment]
No, it shouldn't have anything to do with that. That's just the way the data is escaping when stored in the database.

**Comment by jauyong** [comment]
taking out the name and email fields I was able to get a new message:

An email field is required for all MailChimp forms. Please add an email field to this form.

When I add the email field it goes back to:

Whoops, it looks like you forgot to assign fields to this form.

**Comment by EvanHerman** [comment]
Can you create me a temporary login so I can see the errors first hand? Maybe I'll recognize something.

You can email me at Evan@yikesin.com and I'll take a look for you.

**Comment by jauyong** [comment]
it's failing to email Evan@yikesin.com is that spelled properly?

**Comment by EvanHerman** [comment]
ah, sorry about that. its Evan@Yikesinc.com , I missed the c.

**Comment by jauyong** [comment]
It looks like all systems go after installing the latest package. 

Thanks for all the help Evan. You sir, are a gentleman and a scholar. 

Cheers,
Jason

**Comment by Svennieco** [comment]
Hi all,
I have a valid mailchimp account with API that appears to be working (fields showing correctly in my website http://aebi-massane.com/en/year-book/) but no data is flowing into the list in Mailchimp. Any help?

**Comment by Svennieco** [comment]
I have replaced the embedded form now as not had time to resolve problem with a direct link to an external form :-(
Still interested in any solutions for the future.

**Comment by EvanHerman** [comment]
Hi,

In future please start up your own thread. Also related to this thread, we've stated a few times that the original poster must have some form of JavaScript error on the page. 

After looking at your page, you too have a  JavaScript error which you'll need to resolve before the form will start working.

I would suggest you try downloading and installing the most up to date beta version: https://cldup.com/URpzod5IWx.zip

Thanks,
Evan
