### ISSUE TITLE
Commented lines of code

### ISSUE THREAD

**Issue by emiluzelac** [yikesinc/yikes-inc-easy-mailchimp-extender#280]
- [/add_field_to_form.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/ajax/add_field_to_form.php#L1-12)
- [/add_interest_group_to_form.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/ajax/add_interest_group_to_form.php#L1-21)
- [/class.ajax.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/ajax/class.ajax.php#L15-107)
- [/process_ajax.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/ajax/process_ajax.php#L1-12)

There seems to be quite a few numbers of commented codes. To keep our project clean and bloat-free, I'd recommend removing them.

But also large ones like [/edit-form.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/edit-form.php#L2-86).

And:

- [/front-end-widget-form.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/front-end-widgets/front-end-widget-form.php)
- [/checkbox-settings.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/menu/options-sections/checkbox-settings.php)
- [/about-yikes.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/menu/about-yikes.php)

**Comment by emiluzelac** [comment]
Double check from your end please. @justintadlock just confirmed that GitHub syntax is messed up :(

**Comment by justintadlock** [comment]
Yep, just looks like GitHub's syntax highlighting is messed up.

**Comment by emiluzelac** [comment]
Cool, we will close this one too :)
