### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by emiluzelac** [yikesinc/yikes-inc-easy-mailchimp-extender#284]
It seems like all used images are broken:

![screen shot 2015-06-04 at 2 54 51 pm](https://cloud.githubusercontent.com/assets/1784526/7993168/f47268a2-0ac9-11e5-8487-6d0a05749b46.png)
![screen shot 2015-06-04 at 2 55 42 pm](https://cloud.githubusercontent.com/assets/1784526/7993169/f4757484-0ac9-11e5-897e-d35c7cf3d00c.png)
![screen shot 2015-06-04 at 2 55 52 pm](https://cloud.githubusercontent.com/assets/1784526/7993170/f4781cca-0ac9-11e5-8597-8d5d1fcb9d6e.png)

**Comment by EvanHerman** [comment]
Hi Emil,

I just want to confirm hat this is the latest version off of the staging server.  (https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging)

The top 2 images appears to be the welcome page in our old plugin, which has been removed in the re-write.


Thanks,
Evan

**Comment by emiluzelac** [comment]
Hi Evan,

I downloaded: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/archive/master.zip and used that, but it should of been: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/archive/staging.zip?

Thanks,
Emil

**Comment by TheTracyL** [comment]
You can use this: https://cldup.com/TXlbe0izFH.zip

**Comment by EvanHerman** [comment]
Hi Emil,

That's correct. The one up on our staging repo is actually a complete re-write of the master branch. We haven't rolled the staging branch out to the repo yet. We planned to merge things over once this code review was complete. 

The current version up on our master branch is the same plugin as the one currently up on GitHub. I think you'll find the newer version to be a little more organized and easier to follow.

The link Tracy has provided above should work well. That is the plugin packaged and ready for installation.

The version on our staging repo actually contains our travis config file, test files and our repo assets, so it may be easier to download from the zip in the comment above. Sorry about the confusion.

Evan

**Comment by emiluzelac** [comment]
You guys are the best! Thank you :)
