### ISSUE TITLE
Textdomains: General

### ISSUE THREAD

**Issue by emiluzelac** [yikesinc/yikes-inc-easy-mailchimp-extender#290]
[/class.bbpress_forms-checkbox.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/public/classes/checkbox-integrations/class.bbpress_forms-checkbox.php#L9)

Since plugin already defines and automates `$this->textdomain` you can add them to entire plugin where `yikes-inc-easy-mailchimp-extender` was used instead.

**Comment by justintadlock** [comment]
I'm not following this.  Are you saying to replace the textdomain used throughout with `$this->textdomain`?  Textdomains should be hardcoded strings.  We can't assume PHP is being used to parse the files for text strings.

**Comment by justintadlock** [comment]
Yep, now that I've dug deeper into the plugin, I see the use of `$this->text_domain`.  You can't use that.  See: https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/

**Comment by emiluzelac** [comment]
Yes, "Prevent direct access to the file" string was the only place where  `yikes-inc-easy-mailchimp-extender` was done that way :)
