### ISSUE TITLE
REQUEST Variable

### ISSUE THREAD

**Issue by justintadlock** [yikesinc/yikes-inc-easy-mailchimp-extender#298]
Make sure this is sanitized: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/partials/view-list.php#L3

In general, always sanitize or escape (depending on what you're doing) `REQUEST` variables.  Of course, if you're just checking against a whitelist, it's fine.  But, you're using `$_REQUEST['list-id']` directly and sending it to another function.

**Comment by EvanHerman** [comment]
I combed through the code one more time and ensured all variables being passed in $_POST/$_GET globals are sanitized properly before being used.
