### ISSUE TITLE
Admin UI colors

### ISSUE THREAD

**Issue by justintadlock** [yikesinc/yikes-inc-easy-mailchimp-extender#302]
I generally recommend against custom colors if possible in the admin.  You never know what admin color scheme a user has installed.  This is just to give you an idea of how out of place the blue color looks with an alternate admin scheme used.  See the screenshot.

Also, this WPSE thread is worth looking at if you want to match up with the admin color scheme: http://wordpress.stackexchange.com/questions/127401/get-current-active-wp-color-scheme

![admin-ui](https://cloud.githubusercontent.com/assets/1816309/8021286/2d102d5c-0c5f-11e5-9bac-d04cdc7608d8.png)

**Comment by TheTracyL** [comment]
Changed it to one of the official WP admin blues https://make.wordpress.org/design/2015/04/05/default-admin-color-scheme-update/
