### ISSUE TITLE
Encryption Module Not Installed

### ISSUE THREAD

**Issue by marksburgess** [yikesinc/yikes-inc-easy-mailchimp-extender#305]
Despite being installed, the plugin Easy Mailchimp forms is reporting that php mcrypt is not installed.

**Comment by EvanHerman** [comment]
Hi Mark,

In our latest re-write we've gone ahead and move away from the MCYPT module for protecting API keys as it caused a number of issues for our users. We've now simply used a password field when a valid API key is entered.

If you'd like to give that release a shot, you can download it off of our staging repository here on github:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

You can also download it directly via the following link: https://cldup.com/TXlbe0izFH.zip

You'll simply need to uninstall the previous version, and install this version to get things working.


Thanks,
Evan

**Comment by marksburgess** [comment]
Thanks, I’ll do that.  Will you be setting that plugin update in the Wordpress repository?

+----------------------------------------------------------------------------+
| Mark Burgess
| mark@pagemountain.com
| 619-405-7636
+----------------------------------------------------------------------------+

**Comment by EvanHerman** [comment]
Hi,

Yes. We are in the middle of finalizing the code base before releasing it to the repository.


Evan

**Comment by EvanHerman** [comment]
I am closing this thread due to inactivity. If you need additional help feel free to post here or open up a new issue.

Thanks,
Evan
