### ISSUE TITLE
form shown on logged in status is different

### ISSUE THREAD

**Issue by michaelschwaiger** [yikesinc/yikes-inc-easy-mailchimp-extender#307]
Hi Evan,

thanks for the new release of the plugin. it's working fine so far and the backend is really smooth!! 
but, I'm facing trouble getting the form work when I'm NOT logged in.

when I'm logged in all my settings done in the backend are shown correctly at the frontend, as soon as I log out the default order of the inputfields are shown. take a look at the attached screenshot.

any ideas?

thanks,
michael

![screenshot](https://cloud.githubusercontent.com/assets/8243579/8104133/9ff4e9f2-102e-11e5-912d-02b196d2d1c3.jpg)

**Comment by EvanHerman** [comment]
Hi Michael,

I have not come across this issue. I did just test things on my end, and I can't seem to replicate the issue both logged in and logged out.

It could possibly be a caching issue. Are you running any sort of caching on the site? Have you tried clearing your browsers cache?


Evan

**Comment by michaelschwaiger** [comment]
Hi Evan,

you're right it was a caching issue. Sorry for the circumstances.

Cheers,
Michael

**Comment by EvanHerman** [comment]
No worries at all, I'm glad that it was a minor issue and you got it squared away!


Evan
