### ISSUE TITLE
Submit-Button Translation

### ISSUE THREAD

**Issue by michaelschwaiger** [yikesinc/yikes-inc-easy-mailchimp-extender#308]
Hi Evan,

where can I translate the submit button? I can't find it in the settings, I also tried to add a Translation with "Loco - Translate" but no chance. I just found a source text "Submit Button Text:" so I guess you planed to add this to the "Custom Messages" - Section or so?

Should be my last question! :)

Thanks for your help!

Cheers,
Michael

**Comment by EvanHerman** [comment]
Hi Michael,

Inside of the shortcode you can specify the text of the submit button. you just need to pass in a submit="" parameter, and specify the text for the button. For example, the following would display your form with a submit button that has the text 'Submit this form':

```php
[yikes-mailchimp form="4" submit="Submit this form"]
```

If you have multiple forms on your site and want to globally set the submit text so you don't have to add the submit="" parameter to all of your shortcodes, you can use the provided filter `yikes-easy-mc-submit-button` to replace the default 'Submit' text. Something like the following should be all you need:

```php
/* Globally alter the default 'Submit' text to 'Einreichen' */
function alter_yikes_mailchimp_submit_text_globally( $submit_button ) {
	return str_replace( 'Submit' , 'Einreichen' , $submit_button );
}
add_filter( 'yikes-easy-mc-submit-button' , 'alter_yikes_mailchimp_submit_text_globally' );
```

Just drop the above function into your functions.php file to alter the text across the entire site. Before we release things to the repository we may change the filter from `yikes-easy-mc-submit-button` to `yikes-mailchimp-submit-button` just to keep the naming conventions unified among our actions hooks.

Let us know if that works for you!

Thanks,
Evan

**Comment by michaelschwaiger** [comment]
Hi Evan,

adding the string to the shortcode works just fine.

Thanks!!

Cheers,
Michael

**Comment by EvanHerman** [comment]
Great, thanks for letting us know! I'm glad that too was an easy fix.


Evan
