### ISSUE TITLE
Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.	

### ISSUE THREAD

**Issue by dmarso1** [yikesinc/yikes-inc-easy-mailchimp-extender#309]
im trying to set up my mail chimp form and it will not let me enter my key. Keep getting this error log:
Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.

**Comment by cblackthorn** [comment]
I have exactly the same problem - any suggestions?

**Comment by EvanHerman** [comment]
For anyone facing similar issues, please download the latest stable release from our staging repo:

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Or the direct link:
https://cldup.com/bQMjHMZLPG.zip

The issue has been resolved in the latest stable release.

Thanks,
Evan

**Comment by cblackthorn** [comment]
Dear Evan,


I have done so and now I get the following:


Warning: include_once(/home2/academicpillar/public_html/wp-content/plugins/mailchimp extender/includes/MailChimp/Mailchimp.php): failed to open stream: No such file or directory in /home2/academicpillar/public_html/wp-content/plugins/mailchimp extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.phpon line 53

Warning: include_once(): Failed opening '/home2/academicpillar/public_html/wp-content/plugins/mailchimp extender/includes/MailChimp/Mailchimp.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home2/academicpillar/public_html/wp-content/plugins/mailchimp extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php on line 53

Fatal error: Class 'MailChimp' not found in /home2/academicpillar/public_html/wp-content/plugins/mailchimp extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php on line 786

Nicola




> On 17 Jun 2015, at 18:11, Evan Herman <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> For anyone facing similar issues, please download the latest stable release from our staging repo:
> 
> https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging>
> Or the direct link:
> https://cldup.com/bQMjHMZLPG.zip <https://cldup.com/bQMjHMZLPG.zip>
> The issue has been resolved in the latest stable release.
> 
> Thanks,
> Evan
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/309#issuecomment-112880023>.
> 



Best Wishes,

Dr. Nicola Corkin

(BA (Oxon), MScEcon (Aber), PhD)

Academic Director
 
Academic Pillar Ltd. 
e: dr.corkin@academicpillar.org
t: +44 (0) 780 5849420
Fairhazel Lodge, 65 Canfield Gardens, London, NW6 3EA. <http://maps.google.com/maps?q=nw1+1hy&hl=en&sll=37.0625,-95.677068&sspn=59.727033,114.169922&hnear=London+NW1+1HY,+United+Kingdom&t=m&z=16&iwloc=A>
Confidentiality Notice: This e-mail is intended only for the person to whom it is addressed. If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to this e-mail. If you are not the intended recipient you must not use, disclose, print or rely on this e-mail. The information contained in this email including any attachments is solely for the attention of the addressee(s) and may be confidential. Any review, distribution or copying of this email or any attachment is prohibited. Any views or opinions are solely those of the author and do not necessarily represent those of Academic Pillar Ltd unless specifically stated.

**Comment by EvanHerman** [comment]
Hi,

From your file structure it looks like the plugin name is set incorrectly.

I strongly recommend downloading from here: https://cldup.com/bQMjHMZLPG.zip

The github repo is a bit advanced and would require you to alter the .zip name as well as a re-organizing the structure of the files inside. If you download from the link above you should have no issues just uploading the .zip to your site.


Evan
