### ISSUE TITLE
Required Field Legend

### ISSUE THREAD

**Issue by GEM-INI** [yikesinc/yikes-inc-easy-mailchimp-extender#310]
I have set the required field legend to hidden on my MailChimp account but when I import the form through Yikes widget it shows up on my form? How can I get rid of that? Also, how can I customize the fonts? Thanks...

**Comment by EvanHerman** [comment]
Hi,

Everything that you are asking can be achieved through the use of CSS selectors provided by our plugin. The font's you will either need to use the ones bundled with your theme or load them from an external site.

If you need additional help feel free to post a link to your site.


Thanks,
Evan
