### ISSUE TITLE
Getting "Failed security check. please reload page and submit these again" only on Safari

### ISSUE THREAD

**Issue by JGardiner03** [yikesinc/yikes-inc-easy-mailchimp-extender#311]
The newsletter signups go through beautifully on all browsers except Safari.  When signup is done in Safari, I get this error:  "Failed nonce security check. please reload page and submit these again"

http://myonatural.wpengine.com

I disabled the backend caching, checked for updates, and checked the settings for Preferred Form Layout to be set to div.

Nothing is helping...
Any help would be appreciated.

**Comment by EvanHerman** [comment]
Hi,

I have not come across this issue, nor has anyone reported it specifically in Safari. I will have to take a look and see if I can replicate things on my end in a Safari browser. I will report back here when I can find some info for you.

Thanks,
Evan

**Comment by JGardiner03** [comment]
I spoke with support over at wpengine and the plugin is conflicting with their internal caching.  They said that the only way for it to work on their system is for the nonce to be called via javascript.

**Comment by EvanHerman** [comment]
Ok, we do have access to wp engines servers so I'll give it a test through first thing tomorrow. We are working on re-writing the plugin, so I'm wondering if the new version has this issue as well. We've included the ability to swap between ajax and regular form submissions. If you want to give that a shot you can download it from the following url: https://cldup.com/t3iAASr95c.zip

I will report back when I can get more info on a wp engine server.



Evan

**Comment by EvanHerman** [comment]
After putting the latest release through some testing on a WP Engine install, things seem to be ok on my end. I'm not receiving any error related to the nonce security check in both AJAX and standard form submissions.

If you get the latest version installed and are still having issues, please post here.


Thanks,
Evan

**Comment by JGardiner03** [comment]
I have installed the update, it works.  Thank you so much :)

On Fri, Jun 19, 2015 at 12:05 PM, Evan Herman <notifications@github.com>
wrote:

> After putting the latest release through some testing on a WP Engine
> install, things seem to be ok on my end. I'm not receiving any error
> related to the nonce security check in both AJAX and standard form
> submissions.
>
> If you get the latest version installed and are still having issues,
> please post here.
>
> Thanks,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/311#issuecomment-113577019>
> .
>



-- 
Jennifer Gardiner
Web Developer
Seafoam Media, LLC
seafoammedia.com
c: (636) 577-5073

**Comment by EvanHerman** [comment]
Great, thanks so much for keeping us posted!

Evan
