### ISSUE TITLE
Form isn't adding email to list

### ISSUE THREAD

**Issue by conradbarrett** [yikesinc/yikes-inc-easy-mailchimp-extender#314]
When I enter an email into the form it refreshes the page but does not update with a confirmation message and it does not add email to the list. I've tried with multiple different themes. 

I've looked into the debug section and there are not any bugs. 

URL: http://kicks.deals

**Comment by EvanHerman** [comment]
Hi Conrad,

It looks like you forgot to assign a form to the widget.

Also on that page it looks like there is some sort of javascript error on the page. It looks like the main javascript file for oyur theme is throwing an error, possible because you haven't loaded jQuery yet.

```javascript
jQuery(document).ready(function () {
   jQuery(window).resize();
});
jQuery(window).resize(function(){
   height=jQuery(window).innerHeight()-40;
jQuery('body').css('min-height',height);
});
```

If you get that cleared up things should work. If you would like to give our new version a try you can download it from here: https://cldup.com/t3iAASr95c.zip

That version allows you to toggle between ajax and regular form submissions, so you should be able to avoid the issue altogether with that version.


Thanks,
Evan

**Comment by conradbarrett** [comment]
Hey Evan,

Thanks for the quick reply. I wouldn't know how to fix the jQuery so I've
installed the new plugin you sent.

I am running into this error:

​

Conrad

**Comment by EvanHerman** [comment]
Hi Conrad,

I cannot see any error message. I also do not see the form on your page.


Evan

**Comment by conradbarrett** [comment]
There should have been an image attached with error. But looking into it
again this morning it looks like I have it running and I received
confirmation email.

Is there away to assign a form design in the new version?

Best,

Conrad

**Comment by EvanHerman** [comment]
At the moment no, we are working on building out a templating/theme extensing that would allow you to customize the forms and build out your own templates. Once this version is finally released we should have that add-on released as well.

In the meantime you can alter the visual appearance of the form using CSS.

I am glad to hear that you got things up and running on your site using the new version, without much issue.

Evan

**Comment by conradbarrett** [comment]
Hey Evan,

I don't want to use up to much of your time. But if it's quick - do you
know how I could easily add the blue css template (from older version) to
the new version. Possibly duplicate clean_blue_form.css into updated css
folder and link to it in the updated css?


Really appreciate the time!

Best,

Conrad

**Comment by EvanHerman** [comment]
It is not possible to do that in the current version. We haven't built out a templating system in the new version as of yet. You can copy the styles out of the clean blue template and apply the appropriate classes to the form fields. IT isn't as easy as pasting some code here for you to copy though, it would require some leg work on your end.


Evan

**Comment by conradbarrett** [comment]
OK thanks.

Can you tell me the difference between public.css and public.min.css? Which
one should I edit or both?

Conrad

**Comment by EvanHerman** [comment]
Hi,

The difference between the two is one is a minified version of the other.

I would recommend that you don't make changes to either of them and add your changes directly to your active themes style.css file. Each time the plugin gets updated you will lose all of your changes if you edit core plugin files.


Evan
