### ISSUE TITLE
Cannot Remove Interest Groups

### ISSUE THREAD

**Issue by spyke01** [yikesinc/yikes-inc-easy-mailchimp-extender#315]
We have a user who added a few interest groups and now we cannot delete them. When we choose to delete them they slide out of the list and then the first bug occurs where the form says "no changes have been made" and won't allow you to save. To bypass this we changed the placeholder text on one of the fields to allow us to save but when you refresh the interest groups are all back again.

**Comment by EvanHerman** [comment]
Have you tried re-importing your field data? If the field no longer exists on the form, you'll run into an error.

**Comment by spyke01** [comment]
There was field data but it was the interest groups causing the issue. We actually deleted the entire form and reimported it and all the interest groups pulled back in.

We went through and deleted the interest groups again and saved and they come back all over again.

**Comment by EvanHerman** [comment]
Can you try deleting the interest groups over on MailChimp and then trying to re-import the form again? 

We've been working on our latest release, which is why there hasn't been an update to the plugin in a while. I haven't had a chance to test out any of the functionality in the old release.

**Comment by spyke01** [comment]
Can you tell where this is located in MailChimp, I looked through the groups, segments, and signup forms areas and don't see it.

Also we are on v5.4.2

**Comment by EvanHerman** [comment]
If you login to MailChimp you'll want to select 'Lists' at the top of the page. From there, select the list you want to edit.

Once on the edit page for that specific list click on 'Manage Subscriber' in the nav bar. Once the dropdown displays select on 'Groups'. You'll be presented with all of your interest groups for that form. You can add or delete any of the ones you had previously set up.

Once done, you'll want to try re-importing the list data to your site.

**Comment by spyke01** [comment]
The groups section was blank so I chose the re-import fields option in WP and when that didn't work deleted the form and re-imported it and the interests are still there.

**Comment by EvanHerman** [comment]
I'm confused. Were you editing things on MailChimp or within the plugin? What groups section was blank? If you had groups assigned within WordPress, but no groups assigned to the form on MailChimp they shouldn't be appearing on your WordPress site after importing the form.

**Comment by spyke01** [comment]
I was editing the form in WordPress and removing the interest groups from there as well.

I signed into MailChimp and checked the Groups section here and it was blank.

I then deleted the form, refreshed to make sure it was gone, and then reimported it to find that the groups were still listed.

**Comment by EvanHerman** [comment]
The only reason I can think that the interest groups are still present after you've cleared them from your MailChimp account is your site is caching some of the data returned by the MailChimp API. If that is whats happening then you'll see data from older forms before you made any changes.

I would recommend trying to clear your browser cache to see if that helps at all. Depending on the browser, the steps required to clear the cache are a bit different. The following URL should help out:
http://www.refreshyourcache.com/en/home/


Let us know!

Evan

**Comment by spyke01** [comment]
Thanks, just tried that and did the whole delete/re-import again and still the same issue.

Is there a db setting that I can wipe out to make sure all the data is getting deleted?

**Comment by EvanHerman** [comment]
No, unfortunately there isn't a setting inside of that version that you can just clean up to clear out the data. Resetting the plugin from the settings page will revert all of the settings back to its original state, including clearing out your forms and associated data.

If you want you can uninstall the plugin which should delete all of the options/data created by the plugin. Re-installing will re-create all of the options.

I still think something is going wrong if there are no interest groups on MailChimp but they still display on your WordPress site, especially after re-importing the form fields. The re-import just queries the MailChimp api and returns the associated data for that form.

**Comment by spyke01** [comment]
Thanks we'll give that a shot.

**Comment by EvanHerman** [comment]
Any luck with this issue?

**Comment by spyke01** [comment]
Unfortunately not, I’ll try and do some more digging on monday and let you know.

Paden Clayton
Owner
Fast Track Sites / Fast Track PCs
http://www.fasttracksites.com <http://www.fasttracksites.com/>

**Comment by BobIMG** [comment]
Team, please forgive me if I appear to be hijacking this conversation ... that is not my intent. But, I am wondering if what I am seeing relates to this issue.

I have this installed as a widget. After filling out the form and hitting submit, I see a refresh, but no "subscribe" confirmation on the widget. In the advanced Debug options I see "This list does not have interest groups enabled". The API is showing as correct/active. Could this be related to your issue? If not, let me know and I'll start my own thread.

**Comment by EvanHerman** [comment]
Bob, it sounds like you are running into some sort of javascript error. Can you check to see if you are running into one? If so, the page would refresh and none of the form data would be properly submitted to MailChimp.

https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors


Thanks,
Evan

**Comment by BobIMG** [comment]
-- Please reply above this line --

-----------------------------------------------------------
## Rex replied, on Jun 26 @ 2:46pm (PDT):

Thank you for the suggestion. Attached is a screenshot of the errors.
I'll have to have one of my engineers take a closer look. But, on a
pure logic basis, I'm confused as to why MailChimp's API is able to
register in the log ""This list does not have interest groups enabled"
if a javascript error is preventing the submission of the form.....
--------
*Please note that from Wednesday, July 1st through July 8th our
response time will be longer. Thank you for your understanding.

Rex Boyd
Intersect Support
415.895.2932
www.intersectmg.com [1]


Links:
------
[1] http://www.intersectmg.com


Attached:
Capture.JPG (77 KB)-
[file/21250288/c5f8dc3d5055ceb7d5259299210ccb40445aaf49/Capture.JPG]-----------------------------------------------------------
## Yikesinc/yikes-Inc-Easy-Mailchimp-Extend sent a message, on Jun 26 @ 1:35pm (PDT):



	Bob, it sounds like you are running into some sort of javascript
error. Can you check to see if you are running into one? If so, the
page would refresh and none of the form data would be properly
submitted to MailChimp. 

	https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors
[1] 

	Thanks,
 Evan 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1]
https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors
[2]
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/315#issuecomment-115873863


-----------------------------------------------------------
