### ISSUE TITLE
Sorry, that is an invalid MailChimp API key.

### ISSUE THREAD

**Issue by penjolife** [yikesinc/yikes-inc-easy-mailchimp-extender#316]
Hi

I've copied and pasted the correct API generated from MailChimp.

But the following is prompted.
"Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information."

Can someone help?

Thanks!

**Comment by EvanHerman** [comment]
Hi,

Have you seen similar issues here in the issue tracker? I would recommend you follow the suggestions made in issue #309 . 


Thanks,
Evan

**Comment by Eswebdesign** [comment]
I am getting the same error message:

" Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information."

It was there before I even placed an API key in the box, but continues after I do and I know it's a valid API,  I downloaded your plugin extender under issue #309, still not fixed... Help?  More of an explanaation -- remove your plugin and re-install?

**Comment by EvanHerman** [comment]
Did you install the version recommended in issue #309?

**Comment by penjolife** [comment]
Hi Evan

Yes, I tried to install it but there's an error message

Installing Plugin from uploaded file: bQMjHMZLPG.zip

Unpacking the package…

The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to
find End of Central Dir Record signature

**Comment by EvanHerman** [comment]
Hi,

The download link has changed. You can find the most recent download inside of the readme.md file in the staging branch of this repository. (https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging)

You can download it directly from here: https://cloudup.com/files/iviPuB5XU_U/download

When the next release is pushed out that download link will no longer work.


Evan
