### ISSUE TITLE
The form creation button is over the help button so I can't get to form creation

### ISSUE THREAD

**Issue by williamduncan** [yikesinc/yikes-inc-easy-mailchimp-extender#317]
There is no way to create a form because the semi transparent form creation button overlays the GitHub help button.

**Comment by EvanHerman** [comment]
Hi,

I would suggest you download the latest re-write of the plugin from the following URL: https://cloudup.com/files/iviPuB5XU_U/download

That version should be in the WordPress repository by the end of this month.


Thanks,
Evan

**Comment by williamduncan** [comment]
Thanks...looks great.

On Sun, Jul 5, 2015 at 11:34 AM, Evan Herman <notifications@github.com>
wrote:

> Hi,
>
> I would suggest you download the latest re-write of the plugin from the
> following URL: https://cloudup.com/files/iviPuB5XU_U/download
>
> That version should be in the WordPress repository by the end of this
> month.
>
> Thanks,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/317#issuecomment-118634076>
> .
>



-- 


Bill Duncan
Box 760
12 Cranfield St.
New Castle, NH 03854
NOTE: LAND LINE IS DROPPED
(c) 603-682-4748
waduncan@gmail.com


Advancing New Hampshire Public Education

**Comment by EvanHerman** [comment]
Thanks for keeping us updated on the issue William! If you run into any issues feel free to open up a new issue here and we'll get right on taking care of it.

Evan
