### ISSUE TITLE
Multiple wpspin_light.gif keep appearing whenever i click submit button.

### ISSUE THREAD

**Issue by paulfrankfriend** [yikesinc/yikes-inc-easy-mailchimp-extender#318]
Multiple instances of this image (wpspin_light.gif) appears for a few seconds when i click the submit button to sign up for my mailchimp form. By multiple i mean i see 7 of these appearing at the same time in different areas of the form, (hidden inputs also trigger this) whenever i hit the submit button.
Please lemme know of a quick fix if anyone has. Will appreciate it very much!

Janelle

**Comment by EvanHerman** [comment]
Hi Janelle,

Which verison of the plugin are you running? It sounds like you have a javascript error on the page. If you have a javascript error on the page, the wpspin_light.gif won't actually disappear from the page and the page will either refresh and not submit data, or just hang and never refresh.

I would strongly recommend you use the following, updated version of the plugin:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

That version is slated to take the place of the current version in the WordPress repository by the end of this month. We have a few extensions planned for release as well.


Thanks,
Evan

**Comment by paulfrankfriend** [comment]
Hi Evan, 
thank you so much. I needed a quick fix so i switched to use another plugin. But nonetheless thank you so much for your help!

Janelle
