### ISSUE TITLE
How Do I Pull Custom Form

### ISSUE THREAD

**Issue by stephaniebregman** [yikesinc/yikes-inc-easy-mailchimp-extender#320]
I am in my wordpress dashboard- In Mailchimp directly I created a custom popup form for my site.  It says to copy and paste code to site but not sure where this is? I have the extension in wordpress but don't see anything about copying code to make live on site? Please help.

**Comment by TheTracyL** [comment]
Hi Stephanie.

It looks like you created a custom form in MailChimp and they gave you some code to embed on your site. All you would need to do it copy the code from MailChimp and paste it into a page on your site making sure you're on the "Text" tab of the page editor.

You will not need our plugin if you're adding a form this way.

Thank you!
-Tracy
