### ISSUE TITLE
Issue with List ID coming up invalid

### ISSUE THREAD

**Issue by SeniorSavers** [yikesinc/yikes-inc-easy-mailchimp-extender#322]
This is for https://SeniorSaversNetwork.org
I am trying to create my first form, and I need to add a field.   I give the error that the List ID is invalid.    

I tried deleting the form and starting over, but got the same error.

**Comment by TheTracyL** [comment]
Hello.

I would recommend that you give our new, completely rebuilt version of the plug in a try.
https://cldup.com/KCt_IxOZ4d.zip

We have ironed out a few bugs that were popping up in the old version.

Thank you!
-Tracy
