### ISSUE TITLE
Optin checkbox on comment form does not work

### ISSUE THREAD

**Issue by jiteshshah** [yikesinc/yikes-inc-easy-mailchimp-extender#324]
Hi,
i have selected show in the opt-in check box on comment form.
But the checkbox did not appear in front end.

Can you please tell what shall be done?

**Comment by TheTracyL** [comment]
Hello Jiteshshah,

I would recommend that you give our new, completely rebuilt version of the plug in a try.
https://cldup.com/KCt_IxOZ4d.zip

You can add the opt-in under Easy Forms > Settings > Additional Settings box > Checkbox Settings.

Thank you!
-Tracy
