### ISSUE TITLE
Invalid Mailchimp API Key

### ISSUE THREAD

**Issue by hsagulo** [yikesinc/yikes-inc-easy-mailchimp-extender#325]
I am using valid api key, but when submitting forms I have this error 
Invalid MailChimp API Key: ef13d43d33c85240225de1ffdca52228 and I didn't use this key. 

Thanks..

**Comment by TheTracyL** [comment]
Hi Hsagulo.

I would recommend that you give our new, completely rebuilt version of the plug in a try.
https://cldup.com/KCt_IxOZ4d.zip

We have ironed out a lot of issues people were experiencing with API issues.

Thank you!
-Tracy
