### ISSUE TITLE
API Key Error

### ISSUE THREAD

**Issue by cgwmorris** [yikesinc/yikes-inc-easy-mailchimp-extender#326]
The error message won't leave after I have entered my new key, and I am unable to save settings.

**Comment by JWEremeeva** [comment]
I have the same problem.

**Comment by EvanHerman** [comment]
The issue has been addressed. Please see #316. 

In short, the resolution is to use the latest beta release that we have up on our staging. We are pushing hard to get things released to the WordPress repository. 

Thanks,
Evan
