### ISSUE TITLE
Use form to append to MailChimp info

### ISSUE THREAD

**Issue by ninjaraysv** [yikesinc/yikes-inc-easy-mailchimp-extender#328]
Sorry if I'm missing the obvious, but trying to figure out how to use a MailChimp Extender form to append to our existing MailChimp list data, not as the original sign up. Would like to create a form on the site where existing subscribers can visit (via a link they receive by email) that asks them to answer some questions about interests and preferences.  Only option we're getting is when filling out the form (including required email), user is told they are already subscribed and need to update profile on the MailChimp site.  Is that the only option?

Sample at http://www.venturaclassifieds.com/newsletter-customization/

Also, any guidance or links to best way to clean up formatting would be appreciated.

Really like the plugin, thanks for all the hard work!

**Comment by TheTracyL** [comment]
Hello Ninjaraysv,

Currently our plugin is only for new signups, it doesn't allow current uses to modify their existing info.
However, we will be rolling out add-ons to our core plugin and that is definitely something we may build an add-on for.

Thank you!
-Tracy
