### ISSUE TITLE
Thank you message

### ISSUE THREAD

**Issue by minhhang** [yikesinc/yikes-inc-easy-mailchimp-extender#329]
Hi

The form will be displayed none when the thank you message shows up after the submission 

Thanks

**Comment by TheTracyL** [comment]
Hello Minhang

I would recommend that you give our new, completely rebuilt version of the plugin a try.
https://cldup.com/KCt_IxOZ4d.zip

Let us know if that resolves your issue.

Thank you!
-Tracy
