### ISSUE TITLE
reCAPTCHA setting not taking

### ISSUE THREAD

**Issue by heatherlhg** [yikesinc/yikes-inc-easy-mailchimp-extender#330]
I have 2 wordpress sites on the same server (one will be our main company website and the other is a private site on a subdomain). Google states that only one set of keys is needed per domain (and all its subdomains). I have successfully implemented reCAPTCHA on the private site, but when I try to enable it using the same keys on the main site, it doesn't work... the changes don't take. I select enable, paste in the keys and click save settings. The page seems to process, but then returns to the same page with the dropdown showing "disabled" like nothing changed. I tried searching through the other posted issues for something similar and didn't find anything. Any ideas?

**Comment by TheTracyL** [comment]
Hello Heatherlhg.

First off, I would recommend that you give our new, completely rebuilt version of the plugin a try.
https://cldup.com/KCt_IxOZ4d.zip

We have completely rebuilt it and have ironed out some bugs from the old version.

If you are still experiencing issues, please let us know.

Thank you!
-Tracy
