### ISSUE TITLE
list problems

### ISSUE THREAD

**Issue by globalfamilyfarms** [yikesinc/yikes-inc-easy-mailchimp-extender#331]
Hi there, 

I'm using the plugin with the Divi wordpress theme and am having trouble. It shows that the API key is saved in the system, but when I go to format a signup form the list does not show up in the pull down option - even though both the API key and the list are present in the panel. 

Can you please help me figure out how to get the list to feed into the sign up form? 

Thanks,
Kristen

**Comment by EvanHerman** [comment]
Hi Kristen,

How many lists do you have on your site?

My best recommendation is to use our latest release which is far more stable then the previous releases. I plan to roll that out to the WordPress repository this coming mondy, August 17th. 

The new release will resolve many issues that our users are facing. I would recommend downloading it directly from here: https://cloudup.com/files/ikw-kH1S-iK/download

or from our staging repo:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging

Thanks,
Evan

**Comment by globalfamilyfarms** [comment]
Hi Evan, 

We currently only have 1 list associated with this site. 

I uploaded the newest release, but the list is still not popping up in the sign up module. Everything looks fine on the admin panel... I can't figure out where the disconnect is. 

Any other ideas? 

Thanks,
Kristen

**Comment by EvanHerman** [comment]
No unfortunately I don't have any idea. I don't have access to your MailChimp account, and I haven't come across this issue before.

**Comment by TheTracyL** [comment]
Hi Kristen.

Which step, exactly, are you experiencing the issue? We are also working on a new Knowledge Base for the new version of the plugin: https://yikesinc.freshdesk.com/support/solutions/6000083118

Thanks,
Tracy

**Comment by TheTracyL** [comment]
Hi Kristen.

We haven't heard back from you, so I am going to close out this ticket.
If you need any more help feel free to reopen it.

Thank you!
