### ISSUE TITLE
Default interest group

### ISSUE THREAD

**Issue by ccoakley2** [yikesinc/yikes-inc-easy-mailchimp-extender#332]
Hi

I want to be able to hide the areas of interest in my group on the form, but have one checked by default. There doesnt seem to be a way to do that from the form settings.

For example I have a group called "My Blog", I have set it to hidden in the form. It has 2 subgroups, called "Blog series 1" and "Blog series 2". I would like to have the form add the subscribers to the "Blog series 1" subgroup by default (without them having to tick a box).

Is that possible?

Thank you

Ciaran

**Comment by EvanHerman** [comment]
HI,

What you are describing can be easily achieved with the upcoming release You can go ahead and give it a shot by downloading the following version:

https://cloudup.com/files/ikw-kH1S-iK/download

We are looking to roll that version out to the repository on Monday August 17th.


Thanks,
Evan
