### ISSUE TITLE
Invalid MailChimp API key

### ISSUE THREAD

**Issue by macdaddysuperfly** [yikesinc/yikes-inc-easy-mailchimp-extender#333]
I created a new API key (610b6dbed585726c243fda6821554ddd-us7) from my account and added it to the entry point as instructed but I keep getting this error:
"Sorry, that is an invalid MailChimp API key"

**Comment by EvanHerman** [comment]
Hi ,

Please search the issues here on github (open & closed) for a resolution. There have been plenty of these issues resolved.


Thanks,
Evan
