### ISSUE TITLE
"Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information."

### ISSUE THREAD

**Issue by ammarjutt** [yikesinc/yikes-inc-easy-mailchimp-extender#334]
Hello,
I am using mailchimp plugin but there is an issue with Api key when i enter it. Following Error is there.
"Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information."
I have also check the consol option. there is an error
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

So please let me tell about the solution..

Thanks..!!!

**Comment by jeancarroll** [comment]
I have tried many times to get this to work. The error message "Invalid API key" just stays there and never goes away, I tried getting another key, putting us8 at the end. Nothing works. I'm working on a new theme and need to get this working ASAP! Please help.
Jean Carroll

**Comment by EvanHerman** [comment]
I would recommend downloading the version from our staging site. The issue has been ironed out and squashed in the latest release. That verison will be up in the WordPress.org repo at the end of the month. The download link is:
https://cloudup.com/files/ikw-kH1S-iK/download

Thanks,
Evan

**Comment by jeancarroll** [comment]
Ok,thanks.
