### ISSUE TITLE
recaptcha language

### ISSUE THREAD

**Issue by JosiahCarberry** [yikesinc/yikes-inc-easy-mailchimp-extender#335]
When recaptcha is enabled, it is displayed in a language chosen by Google, which is often NOT the language that the user might want, nor the language that the site owner might want. However, it seems that the Google recaptcha interface does allow sites to specify the language of recaptcha. 

Is there a way it can be done now, or does this require new functionality? If the latter, I highly recommend adding this capability ASAP.

**Comment by TheTracyL** [comment]
Hello Josiah,

Thank you for bringing this to our attention.

We will flag this to be looked into for future releases of the plugin.

-Tracy

**Comment by JosiahCarberry** [comment]
If you need help with testing, please let me know

Kind regards,
Josiah

**Comment by EvanHerman** [comment]
Hi Josiah,

Can you point me to some documentation explaining how to alter the language that reCaptcha is presented in? I can't seem to find anything in terms of altering languages in the new version of reCaptcha.


Thanks,
Evan

**Comment by JosiahCarberry** [comment]
You might look here: 
https://developers.google.com/recaptcha/docs/display#explicit_render

-J

**Comment by EvanHerman** [comment]
Hi Josiah,

Feel free to download the latest stable version and update the one you currently have installed:
https://cloudup.com/files/iS9n4nMMVde/download

I've just gone through and added a check for the site language, and based on that loaded the reCaptcha in that language.

The possible languages available for reCaptcha can be found here:
https://developers.google.com/recaptcha/docs/language

Based on my testing it seems to have worked quite well. Give it a shot and let us know if it works as you expected. Also, If you run into any issues please let us know.

Thanks,
Evan

**Comment by JosiahCarberry** [comment]
Hello Evan,

Thanks for incorporating the requested functionality.

Here are some remarks about the new version:

1. This new version is a rather big change and the user needs to be 
appropriately warned about the need to update the database and take all 
precautions regarding saving the database before the upgrade, as well as 
the deprecation of the form of the shortcode to use. Users expect 
upgrades to simply work, and if they require manual changes afterwards, 
they need to be told in advance.

2. The database upgrade failed at first, but succeeded after I 
deactivated and reactived the plugin.  You really should NOT have to do 
this. Can you not deactivate the plugin programmatically, avoiding the 
necessity to take this extra step manually?

3. The message "Users who sign up via this form will be added to the 
following list." is incorrect. It should read "Users who sign up via 
this form will be added to the /preceding/ list." (or, the message 
should be put /above/ the corresponding list)

4. The message "Update an existing subscribers info when they attempt to 
re-subscribe instead of displaying an "already subscribed" message." has 
a misspelling. Read "subscriber's" instead of "subscribers". To avoid 
the inelegant issue of the antecedent of the plural "they" being a 
singular noun phrase, the message might also read, "When a subscriber 
re-subscribes, update the existing subscriber's info, instead of 
displaying an "already subscribed" message."

5. The message "Thank you for subscribing message" is not very visible 
and the user may be concerned that the form may not have worked. You 
might do two different things to make it more visible:
a) Place it immediately after the subscribe button, so the user 
immediately sees the change in the.
b) Change the font (size, family, etc.) of the text or the background 
color of the message

6. In the migration to the new version, the two recaptcha keys were not 
brought over. I had to look them up and re-enter them

7. The configuration of the form I had previously created was not 
entirely conserved during the migration. All the fields that I had 
previously removed from the form re-appeared and had to be deleted again

8. I note that the bug causing truncation of the "hints" that one could 
add in the forms' fields has been fixed and I thank you for that.

Kind regards,
Josiah

**Comment by JosiahCarberry** [comment]
I forgot one point.

While the technique of setting the language of the recaptcha to the 
language of the site meets /my/ current needs, I can easily imagine how 
it would be preferable to allow the site owner to manually set the 
language to a different value for each form. A multi-lingual site, for 
example, might benefit from this approach.

To simplify things for everyone else, you could set the default value of 
the language to the language of the site.

Kind regards,
Josiah

**Comment by TheTracyL** [comment]
Hi Josiah,

Thank you for the feedback. 

This is a complete rebuild of our free plugin, so there are some major changes users will have to make (like the new short codes). However, the code for this version is much better and irons out some reoccurring bugs some of our users were experiencing. It will be a short moment of pain in order to have a much better product for everyone.

We will check out each one of the items you listed. We really appreciate the time you took to test it and the feedback you provided in order to improve the plugin.

-Tracy
