### ISSUE TITLE
Still don't have the new version of Easy MailChimp

### ISSUE THREAD

**Issue by jeancarroll** [yikesinc/yikes-inc-easy-mailchimp-extender#336]
Evan gave me a link for the new vewrsion of MC signin forms and I installed it . I got a form into my website but it's not working. I do the settings from my dashboard In "Easy MC" but the forms aren't completed and then I went to the Yikes details and I realized that all the choices in the screen shots were not in my plugin???
Please tell me how to get the very latest version?

Thanks, Carol Rubright

**Comment by TheTracyL** [comment]
Hi Jean.

We are working on a Knowledge Base for the new version of the plugin.
Please visit: https://yikesinc.freshdesk.com/support/solutions/6000083118

We are adding new articles daily, so if the info you need is not yet written, just let me know exactly what you are trying to do.

Thank you!
-Tracy
