### ISSUE TITLE
Two successive subscriptions with group

### ISSUE THREAD

**Issue by SybilBoquet** [yikesinc/yikes-inc-easy-mailchimp-extender#337]
If I do two successive subscriptions (without refresh the page containing form) the group is not send to mailchimps.

**Comment by EvanHerman** [comment]
Does the issue persist in the upcoming 6.0 release?


Thanks,
Evan

**Comment by SybilBoquet** [comment]
Yes. I try this version (6.0)

**Comment by SybilBoquet** [comment]
;-)

**Comment by TheTracyL** [comment]
Do you have a link to your form?

**Comment by SybilBoquet** [comment]
Yes. This one : 
http://wp400.editionsfortuna.net/

**Comment by TheTracyL** [comment]
Hi it looks like you're not using the newest version of the rebuilt plugin. Can you please try downloading and installing this one: https://cldup.com/KCt_IxOZ4d.zip

Thank you!
-Tracy

**Comment by SybilBoquet** [comment]
Hi.
Thank you for this new version (may be i made mistake with gihub).
But, i've got always the problem.

Note : when i send the first subscription, the selected elements in the group is not cleaned (the others fields are cleaned).

**Comment by EvanHerman** [comment]
I will look into the issue, see if I can replicate it and (if need be) push out an update before the end of the day for you.

Stand by for an update!

Thanks,
Evan

**Comment by SybilBoquet** [comment]
Hi, the problem happens only with "AJAX Submission".
I can diseable it.
