### ISSUE TITLE
'Update Profile' Email Not Using MailChimp's Template

### ISSUE THREAD

**Issue by heyzeekay** [yikesinc/yikes-inc-easy-mailchimp-extender#339]
Is there a way to use the MailChimp Profile Update email template for the update profile story? The plugin currently sense some other custom template, which we also don't have the ability to modify.

![screen shot 2015-08-25 at 4 15 33 pm](https://cloud.githubusercontent.com/assets/5667483/9479803/a8ee7a0e-4b44-11e5-999b-0a919e2042df.png)

**Comment by TheTracyL** [comment]
Hello Heyzeekay,

Unfortunately we are unable to use the MailChimp email templates.

Thank you!
-Tracy
