### ISSUE TITLE
Replace Label with in Field Text 

### ISSUE THREAD

**Issue by squidg** [yikesinc/yikes-inc-easy-mailchimp-extender#340]
First of all fantastic plugin! Absolutely love it!

I was wondering how I could remove the label text and only keep in-field text.

This is an screenshot of what I would like to do:
https://dl.dropboxusercontent.com/u/47731225/Capture.JPG

**Comment by TheTracyL** [comment]
Hi Squidg,

You can do this easily with the new version of our plugin we are going to release soon. 
You can download the beta version here: https://cldup.com/KCt_IxOZ4d.zip

All you need to do is set the placeholder text for each field and then check off "Hide Label"

You can get more detailed help in our Knowledge Base. Scroll towards the bottom where it says "Click on a field to expand it and view all of its options." 
https://yikesinc.freshdesk.com/support/solutions/articles/6000030971-editing-forms

Hope this helps!
-Tracy

**Comment by squidg** [comment]
Great! That did the trick!

By the way just so you know there is a bug when copying and pasting the code into an existing page and trying to save it. You cannot save it because the fields are required.
This means only the shortcode can be used.

Screenshot:
https://dl.dropboxusercontent.com/u/47731225/mailchimp-bug.jpg

**Comment by squidg** [comment]
Great!
Do you know when the official version will be released?

**Comment by TheTracyL** [comment]
We are aiming for early Sept.
