### ISSUE TITLE
How to style text 

### ISSUE THREAD

**Issue by Nucleus-Strategies** [yikesinc/yikes-inc-easy-mailchimp-extender#341]
Hello - I need to style the form label text so it matches my theme. I'm using a custom font plug-in that replaces the default theme font with one I designated. 

I set all the form labels to be the same custom class "newsletter_text" and added the following custom CSS to my Qode (theme) settings:

.newsletter_text { 
	color: #f7f3f0; 
	font-family: "default"; 
}

Nothing happens. Advice would be much appreciated.

Thanks!

**Comment by TheTracyL** [comment]
Hello, 

Can you please provide a link to the form?

Thank you!
-Tracy

**Comment by Nucleus-Strategies** [comment]
http://dev.nucleus-strategies.com/ - the form is in the footer

Regards,

*Sean Shepherd*



*Mobile: *250.862.7684
*Email: *sean@nucleus-strategies.com
*Web:* nucleus-strategies.com
*Twitter*: @NucStrategies

**Comment by TheTracyL** [comment]
I don't see your `.newsletter_text` class on the label field.

First let's see if your css will work if you switch it to
`
.yks-mailchimpFormDivRowLabel { 
color: #f7f3f0; 
font-family: "default"; 
}

**Comment by Nucleus-Strategies** [comment]
That worked, thanks! I deleted the class from the plug-in UI. Not sure why
it wasn't working.

Regards,

*Sean Shepherd*



*Mobile: *250.862.7684
*Email: *sean@nucleus-strategies.com
*Web:* nucleus-strategies.com
*Twitter*: @NucStrategies

**Comment by TheTracyL** [comment]
Yay! I'm glad that worked. 

I am curious why the custom class didn't work, but we are coming out with a major update to the plugin soon anyway.

Thanks!
-Tracy
