### ISSUE TITLE
Warning: file_put_contents(/www/htdocs/.........../yks_mc_error_log.php): failed to open stream: Permission denied in /www/htdocs/w0119974/reflect-yourself.com/2015/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php on line 3889

### ISSUE THREAD

**Issue by tini1203** [yikesinc/yikes-inc-easy-mailchimp-extender#342]
Hi there,

I get the message "Warning: file_put_contents(/www/htdocs/w0119974/reflect-yourself.com/2015/wp-content/plugins/yikes-inc-easy-mailchimp-extender/lib/error_log/yks_mc_error_log.php): failed to open stream: Permission denied in /www/htdocs/w0119974/reflect-yourself.com/2015/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php on line 3889" when I look at my Newsletter page in wordpress.

Do you know what's wrong? I didn't Change anything.

Greeting,
Martina

**Comment by EvanHerman** [comment]
Hi Martina,

I'm not sure what that error is. I haven't come across it before. I would recommend giving the latest version a shot. I believe that issue will be resolved as we've handled the error logging a bit differently this time around:
https://cloudup.com/files/iS9n4nMMVde/download

If you are still having issues feel free to post here and we'll be glad to take a look into it. We should be rolling out that version linked above in the coming days (early September).


Thanks,
Evan
