### ISSUE TITLE
API key not accepted

### ISSUE THREAD

**Issue by SteveIM** [yikesinc/yikes-inc-easy-mailchimp-extender#343]
getting the ' Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.' message but all attempts at changing the API or changing settings to enable advanced logging fail. Save settings on Form Options page is disabled. Where to go from here?

**Comment by renesansa** [comment]
I am having the same issue - cannot connect to the MailChimp API.

![safari](https://cloud.githubusercontent.com/assets/14093107/9632680/e43f309a-5188-11e5-8bb4-6b412f8f7860.png)
![safari_2](https://cloud.githubusercontent.com/assets/14093107/9632679/e43db094-5188-11e5-94a0-b558940f4276.png)

**Comment by EvanHerman** [comment]
Hi,

It is strongly recommended that you use the latest stable release found here:
https://cloudup.com/files/ild_CCVSapg/download

We are working on updating the plugin, and hope to release things at some point next week. For the time being we recommend you use the new version to iron out any issues you are facing.


Thanks,
Evan
