### ISSUE TITLE
MailChimp Sign-Up Form Not Working

### ISSUE THREAD

**Issue by peace5885** [yikesinc/yikes-inc-easy-mailchimp-extender#344]
Hello,

When trying to use the MailChimp Form for my WordPress page, I receive the following error: 
This list does not have interest groups enabled.  

My issue is, I don't have any groups for this specific email list.  Something I'm missing?

Thank you,
Paul

**Comment by EvanHerman** [comment]
Hi Paul,

No that is the default message returned from the MailChimp API. Interest groups disabled means they are either disabled or non-existent.

When you add one to your form, they will automatically be enabled.


Thanks,
Evan
