### ISSUE TITLE
Changing text in your Clean Blue Template?

### ISSUE THREAD

**Issue by Danielbrinch** [yikesinc/yikes-inc-easy-mailchimp-extender#346]
Hey,

How do I change text in the Clean Blue Template?
I am a beginner, so please explain it as easy for me as possible.

Thanks.

**Comment by EvanHerman** [comment]
Hi Daniel,

The templating system will be removed in the upcoming release and moved over to a premium add-on. The reason for this is mainly so we cold fully focus on it's features and provide a better experience for our users. The customization and templating add-on will utilize the WordPress customizer so you'll get more of a WYSIWYG experience. That will ideally include fully customizing the colors, adding images, and altering text on the fly.

We're working hard on getting that out. Hopefully by the end of next week.


Thanks,
Evan
