### ISSUE TITLE
Add custom default value tags causes an error when updating a form field

### ISSUE THREAD

**Issue by mad102190** [yikesinc/yikes-inc-easy-mailchimp-extender#347]
First off, forgive me if this is a rookie mistake, I'm not too well versed in wordpress plugins. 

Anyway, I want to add a custom default value tag that inserts a randomly generated code into a form field. I found the example functions in the developer docs and after spending a while trying to figure out where exactly I was supposed to put them, I finally put them in my theme's functions.php:  

````
<?php
    /**
    * This example will add two new user defined tags to the list of accepted default value tags array list
    * - note, this will only add your tags to the the list. use the next function to parse the tag and return some value
    **/
    function custom_yikes_mailchimp_default_value_tag( $custom_tag_array ) {
        $custom_tag_array = array( '{new_custom_tag}' , '{new_custom_tag_2}' );
        return $custom_tag_array;
    }
    add_filter( 'yikes_mailchimp_default_value_tag' , 'custom_yikes_mailchimp_default_value_tag' , 10 );
?>

<?php
    /**
    * You can use the following function to process the custom default value tag into some useful data
    * ( note : you must pass in your new default custom tags using the provided yikes_mailchimp_default_value_tag filter (see example above ) )
    * ---------------------------------------------------------------------------------------------------------
    * Example #1 : Converts {new_custom_tag} into the users display name
    * Example #2 : Converts {new_custom_tag_2} into the referral page ( used to track how users landed on this page )
    **/
    function process_custom_yikes_mailchimp_default_value_tag( $field ) {
        switch ( $field['default'] ) {
            // convert {new_custom_tag} into usable data
            case '{new_custom_tag}': 
                global $current_user;
                // get current user info.
                get_currentuserinfo();
                // set this custom default tag to the users display name
                $default_value = $current_user->display_name;
                break;
                
            // convert {new_custom_tag} into usable data
            case '{new_custom_tag_2}': 
                $default_value = $_SERVER["HTTP_REFERER"];
                break;
                
            default:
                $default_value = $field['default'];
                break;
        }
        // return the default field value
        return $default_value;
    }
    add_filter( 'yikes_mailchimp_process_default_value_tag' , 'process_custom_yikes_mailchimp_default_value_tag'  , 10 );
?>
````
Now, I also have the code for a random code generator, which I haven't included here, but even without putting that code in the functions.php file, I already encounter the following error: when I go to manage my forms and try to edit one of the fields in the form, I select (in this case) "{new_custom_tag}" which shows up next to the other default value tags as expected. When I hit "Update Field", I get an message at the top of the edit-field popup that just says "Error: " in red with no message. Even if I select one of the pre-defined value tags (like {post_title), etc) and don't even touch the new ones, it gives me the error.

If I take out the methods from my functions.php, this error doesn't occur anymore and I can select any of the default value tags (except for the new ones, which no longer show up obviously) and it updates just fine. 

Any idea why this might be happening? 

PS: I've tried having each method be in its own <?php ?> tag, and I've tried putting all of them in one giant tag and it didn't make any difference so I'm not sure which way is the correct way.

**Comment by EvanHerman** [comment]
Hi,

Which version of the plugin are you currently using? Am I correct it is the current one in the WordPress.org repository (v5.4?).


Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi mad102190,

Tomorrow we will be rolling out a new version of the plugin and the hooks and filters are going to change.

We recommend upgrading tomorrow then trying your function again with the new code.

Thank you!
-Tracy
