### ISSUE TITLE
Create a message before sign-up fields 

### ISSUE THREAD

**Issue by andreanyc** [yikesinc/yikes-inc-easy-mailchimp-extender#349]
I want to use your embed forms in posts on my website. But I would like to create a message. So, instead of just having:

Email address
Zip Code

I would like a box explaining with a message explaining what these fields mean.
So something like: 

Sign up to our Newsletter to get our handpicked news stories delivered to your inbox

Email address
Zip Code

Is it possible to have a message to go along with the fields and have it pasted into posts uing the shortcode?

**Comment by TheTracyL** [comment]
Hi Andreanyc,

First I recommend you download our newest version of the plugin: https://cloudup.com/files/ild_CCVSapg/download

It is in development, but we are launching it very soon.

You can easily use the form "description" to accomplish what you want. 

Directions for adding descriptions: https://yikesinc.freshdesk.com/support/solutions/articles/6000030964-creating-forms
Using descriptions in shortcodes: https://yikesinc.freshdesk.com/support/solutions/articles/6000030972-adding-forms-to-pages-and-posts

Thank you!
-Tracy

**Comment by andreanyc** [comment]
Thanks!

Can I use that plugin on WordPress?

On Sunday, September 6, 2015, Tracy Levesque <notifications@github.com>
wrote:

> Hi Andreanyc,
>
> First I recommend you download our newest version of the plugin:
> https://cloudup.com/files/ild_CCVSapg/download
>
> It is in development, but we are launching it very soon.
>
> You can easily use the form "description" to accomplish what you want.
>
> Directions for adding descriptions:
> https://yikesinc.freshdesk.com/support/solutions/articles/6000030964-creating-forms
> Using descriptions in shortcodes:
> https://yikesinc.freshdesk.com/support/solutions/articles/6000030972-adding-forms-to-pages-and-posts
>
> Thank you!
> -Tracy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/349#issuecomment-138102546>
> .
>


-- 
Andrea

www.thisdogslife.co

Follow us to keep up to date on This Dog's Life
Instagram <https://instagram.com/thisdogslifesite/>
Facebook  <https://www.facebook.com/thisdogslife>
Twitter <https://twitter.com/Thisdogslifeco>

**Comment by TheTracyL** [comment]
Yes, you can use it on a site using WordPress software, but not a wordpress.com site.

Use Method Two to install the plugin via that zip file I linked to above.
https://yikesinc.freshdesk.com/support/solutions/articles/6000026419-how-to-install-the-plugin
