### ISSUE TITLE
"Failed nonce security check. Please reload the page and submit this form again."

### ISSUE THREAD

**Issue by RafaePavon** [yikesinc/yikes-inc-easy-mailchimp-extender#350]
Hi  there.

Today I've been experimenting this mesage in my subscription form:

"Failed nonce security check. Please reload the page and submit this form again."

Any idea to fix it??

Recently I upgraded WordPress to 4.3.

**Comment by EvanHerman** [comment]
Hi,

What version of the plugin are you running? Are you currently running any caching plugins? Generally caching plugins can effect the way nonces are generated. If you have a caching plugin installed, and don't exclude our plugin specifically, the nonce key will be generated once and used for every form submission until the cache refreshes or is cleared.

Thanks,
Evan

**Comment by RafaePavon** [comment]
Hi Evan,

Thanks for the reply! Ok this is the info

-Easy MailChimp Forms Plugin Version 	5.4.3

-Running WP Super Caché Plugin Version Versión 1.4.4

Can you help me to exclude Easy MailChimp Forms from the caching plugin??

Thanks!!

**Comment by RafaePavon** [comment]
Hi Evan,

I just deactivated WP Super Cache plugin, refresh the site, but the mesage is still shown.

**Comment by EvanHerman** [comment]
The cache may still be prsent. I know WP Super cache is aggressive in it's caching even after de-activating the plugin.

You might want to try re-activating the plugin, excluding the form page from being cached and finally clearing the cache of the site.

https://wordpress.org/support/topic/plugin-wp-super-cache-exclude-specific-pages?replies=4

Evan

**Comment by RafaePavon** [comment]
Ok, thanks let me try,

I'll inform you.
