### ISSUE TITLE
Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.

### ISSUE THREAD

**Issue by malibuwoman2015** [yikesinc/yikes-inc-easy-mailchimp-extender#351]
This is the message I receive when I try to enter my very VALID Mailchimp API Key. I have tried to debug as well. Tried everything, even a new API key via MailChimp. 

Message: "Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information."

**Comment by TheTracyL** [comment]
Hello Mailbuwoman2015,

I would highly recommend using the soon to be released new and improved version of our plugin.
You can download it here: https://cloudup.com/files/iVYPwaobOjl/download

In it we've ironed out any API key bugs.

Please give it a try and let us know how it goes.

Thank you!
-Tracy
