### ISSUE TITLE
how to build a Single-line horizontal form with yikes-inc-easy-mailchimp?

### ISSUE THREAD

**Issue by queenstar** [yikesinc/yikes-inc-easy-mailchimp-extender#352]
I want to build a Single-line horizontal form with First name and Email address just like the attached image. 
pls help me how to set up ? thanks!
![example](https://cloud.githubusercontent.com/assets/14246570/9830766/0c664f68-596d-11e5-9823-029f214e58c8.png)

**Comment by TheTracyL** [comment]
Hi Queenstar,

Do you have a link to your form as it is now? I could write up some CSS code for you.

Thanks!
-Tracy

**Comment by queenstar** [comment]
Hi Tracy,

Thanks for your message and here is my link for mailchimp form.
http://www.queenstarhair.com/

I want to make it the Single-line horizontal form the same with attached
image or horizontal form with First Name and Email.

Please check if you could help.
Thanks a lot!
Jack

Queenstar Hair Co.,Ltd

2015-09-14 21:58 GMT+08:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Hi Jack,

Can you please switch to the newest version of our plugin? We will be releasing this soon and I wouldn't want you to have to change up the code I give you.

This is the link to download it: https://cloudup.com/files/iBIJ6q4knFF/download

Here are instructions on how to install and use it. 
https://yikesinc.freshdesk.com/support/solutions/6000083118

After you've installed the new version and added your form, I'll whip up some code for you.

Thanks!
-Tracy

**Comment by queenstar** [comment]
Hi Tracy,

I have installed and activated the newest version of your plugin.
It requires me to update my PHP version to at least 5.3 version, however i
did not update it now.

Please check my link and help me code for a Single-line horizontal form.

Thanks!
Jack



2015-09-15 22:33 GMT+08:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Hi Jack

Try dropping this css into your style sheet.  Your theme may have a place where you can add custom CSS. Either a css file that is safe to edit or a theme option where you can drop it in. Either way, don't edit the theme's main css file unless it's a custom theme you have built yourself.
```
.yikes-easy-mc-form-1 .yikes-easy-mc-form input[type=email] {
	float: left;
    width: 40%;
}

.yikes-easy-mc-form-1.yikes-easy-mc-form .yikes-easy-mc-submit-button {
    float: left;
    margin: 0 0 0 1em;
    width: 40%;
}
```

**Comment by queenstar** [comment]
Hi Tracy,

Many Thanks for your help!

Actually my host provider could not provide PHP update help so your plugin
did not show the horizontal form now.
Anyhow i would update it later and recommend your plugin to my colleagues.

Thanks!
Jack

2015-09-17 4:04 GMT+08:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Thank you!
