### ISSUE TITLE
Mailchimp form not working in layered slider

### ISSUE THREAD

**Issue by Hawkinsian** [yikesinc/yikes-inc-easy-mailchimp-extender#354]
Hello,
I've just been working with Easy Mailchimp Forms plugin for Wordpress. Everything is great - it's a very useful plugin.

I've set up a form and placed it in the main homepage slider (slide 1) and in the footer of a new website: http://www.skaluk.org/skalukwopr/

The form works nicely in the footer, but I can't get it to work in the layered slider. 

Can anyone help me out and fix this?

Many thanks
Ian

**Comment by EvanHerman** [comment]
Hi Hawkinsian,

What happens within the slider when the form is placed there? Does it just not display?

If you can, would you mind setting things up again how you had them before so I can take a look. It may be a simple fix.


Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi Hawkinsian,

We haven't heard back, so I am going to close this ticket.

Feel free to reopen if you have more info for us.

Thank you!
-Tracy
