### ISSUE TITLE
can't get version 6.1

### ISSUE THREAD

**Issue by jeancarroll** [yikesinc/yikes-inc-easy-mailchimp-extender#355]
I have tried and tried to get 5.4 to work and I can't. I was told in Aug that the new version would be out soon but I can't seem to get it?

Carol Rubright

**Comment by TheTracyL** [comment]
Hi Carol.

Here is the link to it: https://cloudup.com/files/idSnuvf7N1d/download

And here are instructions on how to install it (Use *Method Two*):
https://yikesinc.freshdesk.com/support/solutions/articles/6000026419-how-to-install-the-plugin

Please let me know if you are successful.

Thank you!
-Tracy
