### ISSUE TITLE
[SERIOUS ISSUE] invalid MailChimp API key

### ISSUE THREAD

**Issue by rebelholic** [yikesinc/yikes-inc-easy-mailchimp-extender#356]
When I entering my mailchimp api key such as xxxxxxxxxxxxxxxxxxxxxxxxxx-us11 got error log such as

     API call to helper/ping failed: Couldn't resolve host 'us11 .api.mailchimp.com'

Could you fix it now?

Best Regards

**Comment by TheTracyL** [comment]
Hello Rebelholic,

I recommend downloading the newest version of the plugin that we will soon be launching.
You can download it here: https://cloudup.com/files/idSnuvf7N1d/download

In it we've ironed out the API issues people were experiencing.

Here is the Knowledge Base for it in case you need any instructions:
https://yikesinc.freshdesk.com/support/solutions/6000083118

Please give it a try and let us know if it works.

Thank you!
-Tracy

**Comment by rebelholic** [comment]
Its very worst newest version because I've got some encountered errors like below:

1. It must delete old plugin before install latest version like above because it will cannot working when input the API

2. When I click "update form" on setting page it will add some forms with automatically like my screenshot below:
![error](https://cloud.githubusercontent.com/assets/6254876/9932351/59bc835a-5d6d-11e5-8f85-e49ca6b83203.jpg)

3. Its cannot compatible with my theme because cannot input the email and click "Subscribe" button like below:
![error2](https://cloud.githubusercontent.com/assets/6254876/9932428/f07980cc-5d6d-11e5-8bd1-10525ad68a20.jpg)
You can check out on [my website's home](http://galerigadget.com/)
How I can fix it?

**Comment by EvanHerman** [comment]
Can you try removing this form, and creating a new one and re-assigning the fields to your form. It looks like you only have an email address field, so I'm not sure where those additional fields are coming from.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Are you still facing the issue mentioned above? If not I would like to close out this issue.


Thanks,
Evan
