### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by Jkurbs** [yikesinc/yikes-inc-easy-mailchimp-extender#357]
I want to put this text "We respect your privacy......."  just before the "submit button". How do i do that?
Thanks!

**Comment by EvanHerman** [comment]
Hi,

It's recommended that you download the latest stable release from the following url:
https://cloudup.com/files/igb9MJNZhKd/download

Once that is installed you can use the hook `yikes-mailchimp-after-form` to print some custom content after the form. I believe it will be placed AFTER the submit button. I don't think there is a hook in place to enter content before the submit button.


Evan

**Comment by TheTracyL** [comment]
Hi Jkurbs,

I can add that to our future features list.

Thanks!
-Tracy

**Comment by EvanHerman** [comment]
After some testing, 

It looks like it is possible using the `yikes-mailchimp-form-submit-button` filter.

This filter allows you to customize the submit button, whether that be swapping the anchor tag out for an input button or adding additional classes.

If you want to add content before the submit button you can do so using the following function that I have written and tested:

`
function add_disclaimer_text_before_yikes_mailchimp_submit_button( $submit_button ) {
     $disclaimer = '<p class="yikes-mailchimp-custom-disclaimer"><em>We respect your privacy.......</em></p>';
     return $disclaimer . $submit_button;
}
add_filter( 'yikes-mailchimp-form-submit-button', 'add_disclaimer_text_before_yikes_mailchimp_submit_button' );
`

You could then style the disclaimer text using the class `.yikes-mailchimp-custom-disclaimer`.


Thanks,
Evan
