### ISSUE TITLE
Fatal Error Message

### ISSUE THREAD

**Issue by AgilityMike** [yikesinc/yikes-inc-easy-mailchimp-extender#358]
Received below error message.  Help!
Fatal error: Uncaught exception 'Mailchimp_Error' with message 'We received an unexpected error: null' in /home/c39779065/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php:248 Stack trace: #0 /home/c39779065/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php(227): Mailchimp->castError(NULL) #1 /home/c39779065/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(682): Mailchimp->call('lists/list', Array) #2 /home/c39779065/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(632): yksemeBase->getListsData() #3 /home/c39779065/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/pages/lists.php(2128): yksemeBase->getLists() #4 /home/c39779065/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(1342): require_once('/home/c39779065...') #5 [internal function]: yksemeBase->generatePag in /home/c39779065/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php on line 248

**Comment by EvanHerman** [comment]
Hi,

It is recommended that you download the latest stable release from either here in the Github repo (staging branch), or from the following URL:

https://cloudup.com/files/igb9MJNZhKd/download

You should no longer have the above issue.

Thanks,
Evan
