### ISSUE TITLE
Input bars

### ISSUE THREAD

**Issue by asaphtunes** [yikesinc/yikes-inc-easy-mailchimp-extender#359]
Please help - its very urgent.
The text input bars in the sign up form are in black. How do i change the colour of them? You can see it here - http://www.asaphtunes.com/sign-up/

Also the country list - the bars are in white and so the text is invisible. How do i fix it??
http://www.asaphtunes.com/sign-up/

**Comment by TheTracyL** [comment]
Hello Asaphtunes.

The stylesheets in your theme is controlling the colors of the form.

For example that drop down is set to inherit the font color of it's container which is white for that area:
![css](https://cloud.githubusercontent.com/assets/1252286/9990714/6a8f5df8-6031-11e5-89c0-49a3df850d50.png)

The input boxes are controlled by another style sheet in your theme.
![css2](https://cloud.githubusercontent.com/assets/1252286/9990756/b5294a0e-6031-11e5-94eb-54f9b791abb7.png)

Does your theme allow you to add custom CSS to it?

**Comment by asaphtunes** [comment]
Yes we can put custom CSS. What should we put?

----- Reply message -----

**Comment by TheTracyL** [comment]
This is the CSS code. You can use whatever colors you want.
```
.yks-mailchimpFormDivRowField input {
    background-color: white;
}

.yks-mailchimpFormDivRowField select {
    color: black;
}
```

**Comment by asaphtunes** [comment]
thank you so much 

Date: Mon, 21 Sep 2015 05:05:55 -0700

**Comment by TheTracyL** [comment]
No problem!
