### ISSUE TITLE
How to Export a list 

### ISSUE THREAD

**Issue by wunderbarnook** [yikesinc/yikes-inc-easy-mailchimp-extender#361]
I see my subscriber list within the Easy mailchimp forms but I don't know how to export the list of subscribers? And I also dont see any that were exported in the mailchimp.com site!

Please advise.
Thx
Mike

**Comment by TheTracyL** [comment]
Hi Mike,

You can't export a list of subscribers from within our plugin. You will need to do that on the MailChimp site. 

Here is MailChimp's article on how to view or export a list:
http://kb.mailchimp.com/lists/managing-subscribers/view-or-export-a-list

Thank you!
-Tracy

**Comment by wunderbarnook** [comment]
Thanks but I cant find what your instructions show. This is what I see:

Please advise further.''Thanks





-------------------------------------------

*Michael Gerike*
Owner
*Cypress Nook Bavaria Haus Restaurant*
201 E. McNab Road
Pompano Beach, Fl 33060
www.CypressNook.com

954-933-7311
Dinner Hours:
Wednesday through Saturday 5-10pm

 Breakfast and Lunch Hours:
7 Days a week from 7am til 2pm and 7am til 1pm on the weekends.

Celebrating 36 plus years in business!

**Comment by TheTracyL** [comment]
Hello, 

There's no screenshot or anything attached to your last message.

The instructions I linked to are from MailChimp. If you are having issues with your MailChimp account, you should contact them to see if they can help you.

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Hi,

From a quick search I was able to find the following directions on exporting your MailChimp list:

1. Log into MailChimp.
2. Click the Lists tab.
3. Click the name of the list you want to export.
4. Click Export List.
5. The file is prepared for download on your Subscriber Exports page. Once it is done, click Export.
6. Save the file to your computer's desktop

You can also find the associated MailChimp Knowledge Base article here (as mentioned by Tracy in a previous comment): http://kb.mailchimp.com/lists/managing-subscribers/view-or-export-a-list


Thanks,
Evan
