### ISSUE TITLE
API form issue

### ISSUE THREAD

**Issue by UnhinderedArts** [yikesinc/yikes-inc-easy-mailchimp-extender#364]
Before entering my API which I just generated I get this error "preloadermessage Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information.	" When I put in an API it does not go away. When I go down to try to save the save key is disabled, only the reset key is enabled. When I click that the error does not go away. I checked the debug tab it says no errors at this time. 
Easy Mailchimp Forms by YIKES, Inc.

**Comment by TheTracyL** [comment]
Hello

I would recommend downloading the new version of the plugin we have in development and will soon be releasing. It's a complete rebuild of the plugin and in it we have ironed out any API bugs people were experiencing.

You can download it here: https://cloudup.com/files/iU2qFFvl2li/download

If you need help installing/using the plugin, please refer to our Knowledge Base where we have created step-by-step guides for everything. https://yikesinc.freshdesk.com/support/solutions/6000083118

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
As [previously addressed](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+invalid) in a number of closed issues here on Github, it is strongly recommended that you install the latest stable of the plugin found here: https://cloudup.com/files/iU2qFFvl2li/download

The issue has been addressed and resolved in the latest release of the plugin.


Thanks,
Evan

**Comment by UnhinderedArts** [comment]
I already did. 20 minutes ago. I read the forums and had already downloaded it and installed.

**Comment by TheTracyL** [comment]
Great, is it working for you now?

**Comment by UnhinderedArts** [comment]
Nope.

**Comment by UnhinderedArts** [comment]
I'll just go with a different one. Thanks for being so quick to respond though.

**Comment by TheTracyL** [comment]
Can you please send a screen shot of the error? Also under Settings > Debug settings you need to have "Enable Debugging" checked to start logging errors.

**Comment by TheTracyL** [comment]
Oh, ok. Best of luck!

**Comment by UnhinderedArts** [comment]
Thanks Tracy. Tell Evan not to be so cranky and quick to close cases. It makes us want to go with other apps.

**Comment by EvanHerman** [comment]
Thank you for your feedback.


All the best,
Evan
