### ISSUE TITLE
Not saving Mailchimp API Key

### ISSUE THREAD

**Issue by Damindo** [yikesinc/yikes-inc-easy-mailchimp-extender#366]
Even when i input the correct Mailchimp API Key in the Your Mailchimp API Key field, the Save Settings button is grayed out and I am unable to save.

The api is correct and i even logged in to Mailchimp when I am setting this up but no dice.
I had also enabled advanced debugging and is not reporting anything

Please help

**Comment by EvanHerman** [comment]
Hi,

I would recommend that you download the latest stable release of our upcoming re-write of this plugin:
https://cloudup.com/files/iU2qFFvl2li/download

The new version has been completely re-written and has the most recurring bugs ironed out, including the one you mention above.

I would give the new version a shot, and let us know if the issue still persists.


Thanks,
Evan

**Comment by Damindo** [comment]
Thanks Evan,

I actually solved the problem, getting insight from the Faq page.When I read about Javascript issue, I immediately suspected a js conflict with a plugin known to cause such issues - CKEditor

**Comment by TheTracyL** [comment]
Great, I'm glad you got things resolved. :-)

-Tracy
