### ISSUE TITLE
Whoops, something went wrong! Please try again.

### ISSUE THREAD

**Issue by enxaqueca** [yikesinc/yikes-inc-easy-mailchimp-extender#368]
When submitting the form at the bottom of the page http://www.enxaqueca.com.br/blog/easy-forms/ (just a test page) , I get the error message "Whoops, something went wrong! Please try again.". AJAX is disabled. What is wrong?

**Comment by EvanHerman** [comment]
I'm not entirely sure what may be going on. I can't see anything that would be throwing that error.

If you head into the settings page, 'Easy Forms > Settings > Debug Settings' you can toggle on advanced debugging, which may actually display a better error in terms of figuring out what's going wrong under the hood. That and it may log the actual error being returned by MailChimp on that page.


Evan

**Comment by enxaqueca** [comment]
Inexplicable as it may seem, the form in www.enxaqueca.com.br/blog/easy-forms seems to be working now without my having done anything. I'll close this thread while I test other opt-in and submit settings.

I'd like to ask you, if I may - how do I "prettify" my form? Do you have one or two CSS examples to inspire CSS-challenged folks like myself?
