### ISSUE TITLE
Translation File Incomplete?

### ISSUE THREAD

**Issue by enxaqueca** [yikesinc/yikes-inc-easy-mailchimp-extender#370]
As I'm updating and improving my pt_BR translation, I've come across some lines of text that seem to be missing from the Source, such as "Whoops, something went wrong! Please try again." which appears when the form fails to submit, and "Thank you for subscribing!", which appears after a successful form submission.

**Comment by TheTracyL** [comment]
Dr Alexandre,

Those messages can be completely customized by the user:

![messages](https://cloud.githubusercontent.com/assets/1252286/10263951/ceb98a3e-69cc-11e5-9733-34dbed441cf2.png)

**Comment by EvanHerman** [comment]
Hello Dr Alexandre,

I had a look into the issue you had mentioned above and it seems that a lot of our plugin files were set with a certain line ending (windows) which was causing the xgettext functions to skip over a lot of our files and translation strings.

I've gone through and updated all of the necessary files to the proper line ending (unix), and updated all of our translation files. A lot more strings were discovered this time around, so after downloading the latest release, https://cloudup.com/files/iFNHWI2TTS8/download, you should be seeing the new strings including the ones you mentioned.

Let us know if you don't and are still missing strings.


Thanks,
Evan
