### ISSUE TITLE
Can't get first subscription through the form

### ISSUE THREAD

**Issue by helpfulmoneytips** [yikesinc/yikes-inc-easy-mailchimp-extender#371]
Hi,
I am a newbie to your plugin.  I followed instructions, got rid of all the bugs but still can't seem to get my test email to connect through the form unto my Mail chimp subsciption list named Helpful Money Tips.  Account is:  Helpful Money Tips.  Any ideas would be welcomed. 
Thanks!
RMF

**Comment by TheTracyL** [comment]
Hello RMF

First, I would recommend that you switch to the newest version of the plugin that we will be releasing very soon. It's completely rewritten and much improved.

You can download it here: https://cloudup.com/files/iFNHWI2TTS8/download

Installation instructions are here: https://yikesinc.freshdesk.com/support/solutions/articles/6000026419-how-to-install-the-plugin

Please try it again. If you are still experiencing problems, we can troubleshoot from there. 

Often issues where the form is not sending info the MailChimp have to do with Javascript conflicts. In the new version of the plugin we have an option to turn of Ajax which will usually resolve these.

You can read more about that here: https://yikesinc.freshdesk.com/support/solutions/articles/6000073014-i-hit-submit-on-my-form-but-nothing-happens-

Thank you!
-Tracy
