### ISSUE TITLE
Mobile Browser Calendar Date Picker Issue

### ISSUE THREAD

**Issue by enxaqueca** [yikesinc/yikes-inc-easy-mailchimp-extender#372]
When in the Google App on an iPhone (iOS 9.0.2), the date picker fails to show up for the Birthday Field. The form will send successfully if I write the date instead of using the date picker - but the date format input type must be MM/DD, which becomes an issue in countries using DD/MM as default.

When in Safari on an iPhone, the date picker does show up in the form of a calendar (see screenshot attached), but is quite hard to use: touching the screen anywhere outside the calendar will make it disappear. Inadvertently touching a date will result in its entry in the field and disappearance of the calendar. Touching the Birthday Field again will not make the calendar reappear. To further complicate matters, the calendar is partially "transparent" to fields beneath, as can be seen in the screenshot.

I would suggest enabling the default/standard iOS date picker, which would be much easier for subscribers to select. Language and input format would cease to be an issue when the Month is presented with their standard three letter English abbreviations, universally recognized, followed by the numbers corresponding to the days.
![photo oct 05 10 34 21 am](https://cloud.githubusercontent.com/assets/14874437/10282866/60f0185a-6b53-11e5-9ec0-012a3f33df03.png)

**Comment by EvanHerman** [comment]
Hi,

All of the date formatting is done via MailChimp. At the bottom of the birthday and date fields, you'll see a small note that states if you need to alter the format of the date it must be done over on MailChimp.com

I have cleared up the issue of the date_format not being sent this morning, which will be rolled out with the plugin.

In the meantime if you need to alter the date format you can do so on your MailChimp account under the merge variable fields.

We will have a look into implementing the standard IOS date picker on mobile devices and add it to our feature list for future releases.


Thanks,
Evan

**Comment by enxaqueca** [comment]
Hi,

Strangely, the date formatting in the MailChimp signup form's Birthday field is set to DD/MM. I only come across this issue when using the plugin (www.enxaqueca.com.br/blog/easy-forms/) and not MailChimp's embedded signup form (www.enxaqueca.com.br/blog/newsletter/)
