### ISSUE TITLE
Issues upgrading to version 6 - read this first

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#373]
Hello Everyone,

We are excited to finally release the new and improved version of our MailChimp plugin. But we know the migration will be a little bumpy for some users.

If you are experiencing any issues, please look through these articles we have written

* **[Upgrading to version 6 - Troubleshooting](https://yikesplugins.com/support/knowledge-base/upgrading-to-version-6-troubleshooting/)**
* **[Changes from Version 5.4.4](https://yikesplugins.com/support/knowledge-base/upgrading-to-version-6-changes-from-version-5-4-4/)** 
* **[Performing the Upgrade](https://yikesplugins.com/support/knowledge-base/upgrading-to-version-6-performing-the-upgrade/)**

If the problem you're experiencing is not covered here, please submit a new issue.

Thanks, everyone!
-Tracy

**Comment by baytonemus** [comment]
After upgrading, my required fields are no longer indicated with an asterisk(*). I checked the field settings under Easy Forms/Opt-in Forms/form name/edit and the checkbox is selected for all required fields.

**Comment by EvanHerman** [comment]
Hi Baytonemus,

That is correct. We've removed the asterisk from the front end of the site as the majority of our users in the previous version no longer wanted that, and were constantly requesting some custom code to remove it.

The required fields now follow the HTML5 structure, and will apply a required attribute to the input field, thus preventing the user from submitting the form until that field is filled in.

If you display a form on the front end with at least one required field assigned to the form, fill out the email field with a valid email address and hit submit, you'll see the required field displays a small tooltip back to the user letting them know that field is required.

Depending on the number of fields that you have displayed on the given form, you can use the filter `yikes-mailchimp-field-label` (where field is the <b>merge tag</b> of the given form).

Example:
![merge tag example](https://www.diigo.com/file/image/rabssqszcsaccqrdpzbsersrra/Edit+Form+%E2%80%B9+Yikes+MailChimp+%E2%80%94+WordPress.jpg)

So to add an asterisk to the label of the field used in the example above, you could drop the following code into the bottom of your functions.php file:

```php
/*
*	Apply an asterisk to indicate this field is required
*	@demonstration
*/
function yikes_mailchimp_add_asterisks_to_fields( $label_text ) {
	return $label_text . ' <span style="color:#F96969;">*</span>';
}

/* Build an array of fields to set as required */
$required_field_merge_tags = array(
	'EMAIL',
	'FNAME',
);

/*
*	Loop over the fields above
*	and append an asterisk to indicate the field is required
*/
foreach( $required_field_merge_tags as $merge_tag ) {
	add_action( 'yikes-mailchimp-' . $merge_tag . '-label', 'yikes_mailchimp_add_asterisks_to_fields' );
}
```

<b>Note:</b> You'll want to swap out the items in the $required_field_merge_tags array with the values of your field merge tags.

I just did a quick test and can confirm the above method is working. Feel free to give it the above code a shot to display the asterisks back on required fields.


Thanks!
Evan

**Comment by megamurmulis** [comment]
During update process **# '** symbol results in unterminated string breaking JS code (DB restore required due partial update)...
```
Error: SyntaxError: missing } after property list
Source File: http://www.*********.com/wp-admin/admin.php?page=yikes-inc-easy-mailchimp-update&migrate_options_nonce=add1673fcf
Line: 670, Column: 1504
Source Code:
4","merge":"MMERGE4","label":"Breif Description of what you'd like to learn.","require":false,.....
```
