### ISSUE TITLE
Opt-In Security Issue for EasyForms for MailChimp

### ISSUE THREAD

**Issue by aschaevitz** [yikesinc/yikes-inc-easy-mailchimp-extender#375]
One feature of the Opt-in settings for the new Easy Forms for MailChimp allows a user to update their information if they are already in the list rather than getting an "already registered" message (Update Existing Subscriber). However, there is no ability to force a "double opt-in" process in this case. Thus, anyone can update someone's information by knowing their email address if this feature is selected. This is a security hole that should be corrected ASAP.

Thanks,
Alan Schaevitz

**Comment by TheTracyL** [comment]
Hi Alan,

We are only allowing the plugin to perform functionality that MailChimp provides in the first place.
If MailChimp allows folks to update their info. via their API then they should really be providing some kind of two step authentication for that.

That being said, we will see if we can create a method for two step authentication of updating user information, and if so, get that implemented into our next update.

Thank you for your feedback!
-Tracy
