### ISSUE TITLE
Upgrading error message, bunch of code

### ISSUE THREAD

**Issue by jerryw1976** [yikesinc/yikes-inc-easy-mailchimp-extender#376]
I get this error message after upgrading. 
Warning: file_exists(): open_basedir restriction in effect. File(/etc/mailchimp.key) is not within the allowed path(s): (/home/understa:/usr/lib/php:/usr/local/lib/php:/tmp) in /home/understa/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php on line 212

Fatal error: Uncaught exception 'Mailchimp_Error' with message 'You must provide a MailChimp API key' in /home/understa/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php:126 Stack trace: #0 /home/understa/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/partials/menu/manage-forms.php(17): Mailchimp->__construct('') #1 /home/understa/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php(845): require_once('/home/understa/...') #2 [internal function]: Yikes_Inc_Easy_Mailchimp_Forms_Admin->generateManageFormsPage('') #3 /home/understa/public_html/wp-includes/plugin.php(503): call_user_func_array(Array, Array) #4 /home/understa/public_html/wp-admin/admin.php(236): do_action('toplevel_page_y...') #5 {main} thrown in /home/understa/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php on line 126

**Comment by EvanHerman** [comment]
Hi Jerry,

It sounds like your site has an open_basedir() set , which is something that is set at a server level. Some shared hosts have this option set for security purposes. I've found that if you email your hosting provider and ask them to disable the open_basedir option, they will do so. If they are unable to remove it, their may be other work arounds, but that is certainly the quickest and least amount of work on your end.


Thanks,
Evam

**Comment by TheTracyL** [comment]
Hi Jerry,

I'm going to close this ticket, but if you need any further help on this issue, feel free to add a comment.

Thank you!
-Tracy
