### ISSUE TITLE
his MailChimp shortcode is now deprecated. Please insert the new shortcode to display this form.

### ISSUE THREAD

**Issue by xtremist** [yikesinc/yikes-inc-easy-mailchimp-extender#377]
Logged into my site (xtremist.me) this morning to find the message on one of my pages. All of my settings were wiped out such as api code, etc... Followed suggestion to deactivate/reactivate - did not help. Tried delete and get fatal error.
 I can't delete it. I can't reactivate it - I'm stuck big time.

Fatal Error (hide details) (remove)
The site encountered a problem that it cannot recover from. Please use the following information to try to resolve the problem.

Error Message

Fatal Error: Cannot redeclare class Mailchimp in /home/xtremist/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php on line 17
Description

The Easy Forms for MailChimp by YIKES plugin code created an error that caused PHP execution to fail.

The code tried to create a function that already existed (class Mailchimp()). This error typically occurs when the PHP file that defines the function is loaded more than once, which could indicate a bug in the code or that some modification is incorrectly trying to load the file again. This type of error can sometimes indicate a plugin conflict which can occur if two plugins try to use the same function name.

Solutions

Invalid code modifications can cause this problem. If you have made any modifications to the plugin, remove them and try to load the site again.
It is possible that this plugin's code is out of date and that an upgrade is available. Check with the plugin's author to see if an upgrade is available.
There may be a conflict with another plugin running on the site. Try upgrading the other plugins on the site. A plugin conflict can be ruled out by deactivating all the other active plugins on the site and checking to see if the error still occurs.
The Easy Forms for MailChimp by YIKES plugin may not have been fully uploaded. Uploading the plugin again could fix the issue. Important: If you do this, you will lose any modifications made to the plugin.
Error Source Details

Type	Plugin
Name	Easy Forms for MailChimp by YIKES
Version	6.0.1
Author	YIKES
Path	/home/xtremist/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender
File	includes/MailChimp/Mailchimp.php
Other Software Details

WordPress Version	4.3.1
PHP Version	5.3.29
Full Error Details

Type	Zend Compile-Time Error (E_COMPILE_ERROR)
Message	Cannot redeclare class Mailchimp
File	/home/xtremist/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php
Line	17
Type Description	This type of error indicates that the PHP code is violating a restriction enforced by PHP. An example of such a violation is trying to use a reserved word for a class or function name.

Note that this message is generated by iThemes.com products when an error is encountered on the site. While an iThemes product is generating this message, it is not necessarily the cause of the problem.

**Comment by EvanHerman** [comment]
Hi xtremist, 

Are you using more than one MailChimp product alongside of ours? Generally the error Message `Cannot redeclare class Mailchimp
File /home/xtremist/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php` occurs when you're using multiple products attempting to include the MailChimp PHP wrapper class file.


Evan

**Comment by xtremist** [comment]
I am using ithemes exchange which has an integrated mail chimp add-on

**Comment by xtremist** [comment]
but they both worked fine for the last week until this morning

**Comment by xtremist** [comment]
disabling ithemes extender seems to have resolved the issue

**Comment by EvanHerman** [comment]
Ok, it looks like we'll need to wrap the our include in a check to ensure that the class hasn't been previously declaired.

What I can recommend (for a temporary fix) is to replace the following line:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/plugin_core/admin/class-yikes-inc-easy-mailchimp-extender-admin.php#L55

with

```php
// ensure the MailChimp class wasn't previously declared in another plugin
if( ! class_exists( 'Mailchimp' ) ) {
	// Include our MailChimp API Wrapper
	include_once( YIKES_MC_PATH . 'includes/MailChimp/Mailchimp.php' );
}
```

I've been working on a patch with a few minor tweaks over the past day that I'm hoping to push out in the next day or so.  I'll get this included into that patch.

Evan

**Comment by TheTracyL** [comment]
Hi xtremist,

Thank you so much for bringing this to our attention.

I noticed that the subject of your ticket mentioned the new shortcodes. If you need help regarding that, please see the first item on this list: https://yikesinc.freshdesk.com/support/solutions/articles/6000067427-upgrading-to-version-6-changes-from-version-5-4-4

Thank you!
-Tracy
