### ISSUE TITLE
Define text value of submit button not working.

### ISSUE THREAD

**Issue by erousr** [yikesinc/yikes-inc-easy-mailchimp-extender#380]
You can no longer define the text of the submit button in the shortcode. Is this feature depricated?

**Comment by TheTracyL** [comment]
Hi Erousr,

This is works in the newest version, but the syntax has changed.

If you want to change the text for the submit button, add your custom text to the shortcode using submit="Your Custom Text Here"

`[yikes-mailchimp form="1" submit="Sign Up!"]`

Thank you!
-Tracy

**Comment by erousr** [comment]
Perfect, Thanks!
