### ISSUE TITLE
Submissions not being added & submit_text Q

### ISSUE THREAD

**Issue by baytonemus** [yikesinc/yikes-inc-easy-mailchimp-extender#384]
Easy Forms/Settings/General Settings says that I am connected to the database. However, form submissions are not being added despite the congratulation msg.

I'm wondering if this is still supported code: [yikes-mailchimp form="2" submit_text="Sign Up"] The form on the page still displays "Submit" as the button text.

Updated to 6.0.2.4. Thanks.

**Comment by EvanHerman** [comment]
Hi Baytonemus,

Is the list set to single or double optin? If it's set to double opt-in the user won't be added until the user clicks the confirmation link in the email sent to them.

Through my testing - If this is a relatively new list, or if you've been testing a bunch of emails in a row, it may take a little bit for the user to appear on the list. I believe this has something do with the cache on MailChimps side.

In regards to the shortcode, I believe to alter the submit button text you just need to pass submit="Sign Up" to the shortcode. So using your example above, it would be:

`[yikes-mailchimp form="2" submit="Sign Up"]`



Thanks,
Evan

**Comment by baytonemus** [comment]
Thanks. It is set to double opt-in. Your short code adjustment worked. Can the text be styled in-line?

**Comment by EvanHerman** [comment]
Which text? The submit button text? 

You can alter the styles using the following bit of CSS:

`
.yikes-easy-mc-submit-button {
   font-size: 20px;
   color: green;
   /* Alter as needed */
}
`


Evan

**Comment by baytonemus** [comment]
Yes, thanks. Just wondered if the shortcode allowed inline styling.

**Comment by EvanHerman** [comment]
Oh,

No - the shortcode does not accept inline styles. Everything must be done via your active themes stylesheet or a custom css plugin.


Evan

**Comment by baytonemus** [comment]
Got it! Thanks again for your really prompt responses.

**Comment by EvanHerman** [comment]
No problem at all!

Evan
