### ISSUE TITLE
Using the_content() filter

### ISSUE THREAD

**Issue by bgantick** [yikesinc/yikes-inc-easy-mailchimp-extender#385]
It seems that passing the form description field through the `the_content()` filter has undesirable/unexpected conflicts with certain other plugins that make use of this filter to append elements to posts (Monarch Social Plugin and  Facebook Comments Plugin). I can look into this further at some point and maybe create a pull request if I find a good fix.

**Comment by EvanHerman** [comment]
Hi,

I can take a look, but as far as I know utilizing `the_content()` filter is a fairly common WordPress task. If other plugins are hooking into `the_content()` (aka certain social share plugins, share daddy by jetpack etc.) then you'll most likely need to unhook those actions in the necessary locations.

I will have to look into a work around for a future release.


Thanks,
Evan

**Comment by bgantick** [comment]
Modifying/utilizing `the_content()` is fairly common, but it seems it should be renamed in this case, as it's not the "main" `the_content()`. Looks like you were looking into this some time ago [here](http://wordpress.stackexchange.com/questions/152488/apply-the-content-filter-but-prevent-other-hooked-actions)

**Comment by EvanHerman** [comment]
Hi Bgantick,

Thanks for bringing that thread back up from a while ago. I had forgotten about that. I'll get that included in our next update coming this week.


Evan

**Comment by bgantick** [comment]
Cool, thanks. I've patched my install. Happy to create a pull request if you'd like.

**Comment by EvanHerman** [comment]
Hi Bgantick,

I have a fix in place slated for the next release using a new `yikes_mailchimp_frontend_content` filter. I have a few other things I'm patching in the next release so hopefully the update won't take too long.


Thanks again,
Evan

**Comment by bgantick** [comment]
Awesome. Keep up the good work :)

**Comment by EvanHerman** [comment]
I've just release v6.0.3, you can download here in our Github Repo or feel free to upgrade your copy of the plugin from the WordPress dashboard!


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi bgantick,

Feel free to update to the latest release of the plugin, the content issue should now be resolved.

Thank you for your patience while I got everything worked out on our end! If you're still having issues feel free to re-open this thread and we can investigate further.


Evan
