### ISSUE TITLE
Wrong message displayed for existing subscriber

### ISSUE THREAD

**Issue by tmoore615** [yikesinc/yikes-inc-easy-mailchimp-extender#387]
Hi,
I just installed the plugin the other day and am getting it set up.  So far it's great, except for one glitch I've found. In opt-in settings I have set 'Update Existing Subscriber' to 'no'. I am using your MailChimp Easy Forms widget and if I enter an already subscribed email address, I get the General Error Message instead of the Email Already Subscribed message. Any thoughts?

Thanks...

**Comment by EvanHerman** [comment]
Hi tmoore615,

Is the form set to AJAX or non-ajax? Can you give both a testing to see if it behaves the same way in both instances of the form.

I'll do some testing on my end and see what I can come up with.


Thanks,
Evan

**Comment by tmoore615** [comment]
Hi Evan,
Thanks for the quick response. It does the same thing with AJAX set to either yes or no. Hope you can help.
--Terry

**Comment by EvanHerman** [comment]
Hi Terry,

I just had a look into this issue and I can't seem to replicate it. The error message that is displayed back to me when I input an email already subscribed to the mailing list is "". I can also alter the email message inside of the 'Custom Messages' tab on the edit form page. Both ajax and non-ajax worked as intended.

Does this only happen when an existing email is subscribed? I have seen that error occur when you have additional required fields that you haven't assigned to the form in the form builder. You may want to try toggling on 'Advanced Debugging' on the settings page and trying again. Ideally after toggling that setting on and trying to submit the form, you can head back into the 'Debug' settings page and check the error log for any errors returned from MailChimp.



Evan

**Comment by tmoore615** [comment]
Hi Evan,
If a new subscriber tries to sign up, everything works fine. If they are already subscribed and put the same email address in again, I get a Whoops message--
![debug off whoops error msg](https://cloud.githubusercontent.com/assets/15382285/10892733/c98ee72e-816a-11e5-91cc-54e776554211.JPG)
I turned Debug on as you suggested and got an "Unexpected" error message--
![debug on unexpected error msg](https://cloud.githubusercontent.com/assets/15382285/10892746/d3331a48-816a-11e5-87af-28094f45cb95.JPG)
When I check the error log there are no entries. 

I get the same results in the latest versions of Firefox, Explorer, and Chrome. I am using a PC with Win7 64 bit. My computer has all the latest Windows updates. Also WordPress and all plugins are the latest versions.

I am doing development on a temp domain. You can take a look at it at http://952.8d7.myftpupload.com . Try subscribing and subscribing again. I'd be interested to hear what you get. The actual deployed site is https://prayerguide.org. I got the same error messages on it, so I have temporarily disabled the subscriptions. 

All else failing, maybe we could set up a time to let you take a look using TeamViewer.

Terry

**Comment by tmoore615** [comment]
Accidentally closed this issue. Still having the problem.

**Comment by EvanHerman** [comment]
Hi,

On the settings page can you confirm that you are still connected to the API? On the debug settings page, do you have 'Enable Debugging' enabled? 

Can you create a test page on your live site so we can take a look at the issue first hand, and possible see what might be going on.

If you log into your MailChimp account, just below your API keys in the section titled 'Last 24 Hours of API Calls' do you see anything listed there with a more descriptive error?
https://admin.mailchimp.com/account/api


Thanks,
Evan

**Comment by tmoore615** [comment]
Hi,
API is still connected. 

Debug is enabled. No errors appear in the debug log.

On live site, https://prayerguide.org, on the home/welcome page at the top of the right widget area there is an enabled subscribe link. If you put in your email address it should succeed. If you put it in again you should get an error. I just tested it and got an error, but there is nothing in the debug error log.

After testing and getting an error, I checked MailChimp for last 24 hour API calls as you suggested. It shows my test failed with a "List_AlreadySubscribed" response, but that's not the message YIKES displays.

![api](https://cloud.githubusercontent.com/assets/15382285/10976637/7735b40e-83b2-11e5-9dca-842fcfdc9963.JPG)

Please take a look and hopefully you can figure it out. If not, my offer to set up a session in TeamViewer is still on the table. You can take a look at all my settings, etc.

Thanks,
Terry

**Comment by EvanHerman** [comment]
What do you have set in the edit form page under custom messages?

**Comment by tmoore615** [comment]
All messages are default, except for Email Already Subscribed. That is set to "The provided email is already subscribed. Please use the links at the bottom of update emails to change your preferences or to unsubscribe."

With debug off I get the General Error Message, "Whoops! It looks like something went wrong. Please try again."

I'm not seeing on MailChimp where you subscribed...

**Comment by tmoore615** [comment]
Yes, I see where you subscribed and unsubscribed now. This is strange.

**Comment by EvanHerman** [comment]
I had unsubscribed after waiting a bit - I didn't want to remain on the list and forget about it.

What theme are you currently using? Any chance it's free and that I can test with it on my end?


Evan

**Comment by tmoore615** [comment]
I just tested it on my iPad and got the Whoops message. I am using the free version of the Adventurous theme. I have made a child theme that is active because I've added some CSS code to change colors on menus and hyperlinks.

**Comment by EvanHerman** [comment]
The only thing that I can recommend is trying to latest patch that will be coming out either today or tomorrow. Another user reported an incorrect message displayed - but that was due to stripslashes() stripping the wrong stuff. I don't think the two are related - but you never know.

Without personal access I can't necessarily provide assistance.



Evan

**Comment by tmoore615** [comment]
Thanks Evan. I'll look for the new patch. In the mean time, I will customize the error message to alert people to the problem.
