### ISSUE TITLE
Not working and invalid licence key

### ISSUE THREAD

**Issue by N36** [yikesinc/yikes-inc-easy-mailchimp-extender#389]
Hi there, i just downloaded and installed your form customizer.

I cannot request support in the plugin itself as it says 'invalid license key' even though my site is validated on you site and within the license area of the plugin.

It works in the preview window, but none of the styling properties work in the front end. it just uses the default ones.

Please seen here: https://www.titanreality.com

Rather urgent as we are going live with PR next week!

Kind regards,

Mike

**Comment by TheTracyL** [comment]
Hello Mike,

Can you please email me directly at tracy@yikesinc.com?
I can give you the address to create a premium support ticket straight from email.

This will enable us to help you in the quickest way.

Thank you!
-Tracy
