### ISSUE TITLE
"Hide Field" and "Hide Label" sows the field

### ISSUE THREAD

**Issue by jafcobend** [yikesinc/yikes-inc-easy-mailchimp-extender#390]
If both the "Hide Field" and "Hide Label" boxes are checked for a given field then the input field is shown without a label. Seems like the field should be hidden.

This is in v6.0.3

**Comment by EvanHerman** [comment]
Thanks for the bug report. This is a known issue, and something that we have outlined in the documentation.

We are going to patch this in a future release, as you are correct - when both are checked the form should be hidden regardless.


Evan

**Comment by EvanHerman** [comment]
Hi Jafcobend,

This issue will be resolved in the upcoming 6.0.3.1 release. thank you again for reporting it here. Keep an eye out for an update in the next day or so.


Thanks,
Evan

**Comment by jafcobend** [comment]
Thank you. I will. Its not a big issue. Just thought it ought to be in
the tracker so it can get fixed sometime.

THX - Jon

Evan Herman wrote:
>
> Hi Jafcobend,
>
> This issue will be resolved in the upcoming 6.0.3.1 release. thank you
> again for reporting it here. Keep an eye out for an update in the next
> day or so.
>
> Thanks,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/390#issuecomment-152650112>.
>

-- 
Sent from my Debian Linux workstation -- http://www.debian.org/intro/about

Jon Foster
JF Possibilities, Inc.
jon@jfpossibilities.com
541-410-2760
Making computers work for you!

**Comment by TheTracyL** [comment]
The update will be coming out later today.

Thank you for your help!
-Tracy

**Comment by EvanHerman** [comment]
Hi Jafcobend,

I just pushed out the v6.0.3.1 release which should now include the patch to fix this issue outlined above.

Feel free to update from the dashboard and give the new version a shot. If you're still having issues feel free to drop us a line here and we'll re-examine.

Thanks,
Evan

**Comment by jafcobend** [comment]
I just installed the new version and the visibility issue is fixed.
Thanks guys!

THX - Jon

Evan Herman wrote:
>
> Hi Jafcobend,
>
> I just pushed out the v6.0.3.1 release which should now include the
> patch to fix this issue outlined above.
>
> Feel free to update from the dashboard and give the new version a
> shot. If you're still having issues feel free to drop us a line here
> and we'll re-examine.
>
> Thanks,
> Evan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/390#issuecomment-153104265>.
>

-- 
Sent from my Debian Linux workstation -- http://www.debian.org/intro/about

Jon Foster
JF Possibilities, Inc.
jon@jfpossibilities.com
541-410-2760
Making computers work for you!

**Comment by TheTracyL** [comment]
Fantastic! So glad we were able to clear that up for you.

If you are enjoying the plugin, please consider leaving a review.
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Thank you!
-Tracy
