### ISSUE TITLE
Feature Request: Ability to add hidden field values as a short code parameter

### ISSUE THREAD

**Issue by publicdisplay** [yikesinc/yikes-inc-easy-mailchimp-extender#391]
I think it might be easier to try to explain. I use hidden fields to show which page/blog post folks are coming from to sign up for our newsletter.  So every page will have a different value for my hidden field called "signup location".  Currently it looks like I would have to create a new form for every page and add the value in the form creator.  This doesn't scale well.  It would be nice if I could do something like:

[yikes-mailchimp form="2" title="0" description="0" submit="Button Wording Here" signup="blogpostname"]

Where "signup" is the mailchimp field tag I have defined in mailchimp as a hidden field. And "blogpostname" is what I can change on a per post basis.

Hope this makes sense.  This would be really helpful I think for folks using hidden tags.

**Comment by EvanHerman** [comment]
Hi Publicdisplay,

Actually, we have built in quite an efficient way to handle exactly what you mention.

You can use the same form for every page on your site, while properly populating the hiddne field with the current page, page ID, page URL, blog name etc. We've even included a method for defining your own custom tags for those times you need to do something a little more special.

What you'll want to do is create a simple 'text' field, and assign it to your form in the form builder.

Once you have the input field assigned to your form you can set the field to 'hidden'. Just below the 'default value' input field you'll see  (note im just using the first name field as an example - this can be called anything you want).

![image 1](https://www.diigo.com/file/image/rabssqszcscooproczbsqocsos/Edit+Form+%E2%80%B9+Yikes+MailChimp+Test+%E2%80%94+WordPress.jpg)

When you click the link for the default value you'll get a new modal pop up with some of the available tags to choose from. The first is 'page title'. This tag will get parsed and populate the input field with the current page title, depending on which page you are viewing.

This was a fairly common request in our previous versions and needed to previously be achieved through JS. With the new version we've enabled a much more efficient and scaleable way to handle this.

Give things a shot and if need be I can provide better instruction. On that note I'll need to setup a knowledge base article on how to achieve this.

Thanks!
Evan

**Comment by publicdisplay** [comment]
perfect! thanks.
