### ISSUE TITLE
When multiple forms on same page, only last one is submitted to

### ISSUE THREAD

**Issue by chrisbloom7** [yikesinc/yikes-inc-easy-mailchimp-extender#392]
We have a Yikes form in our sidebar for signup to our primary mailing list, and we're attempting to add another form to a post to signup for a secondary list. Anytime someone submits the secondary signup form they are added to the primary mailing list. We've tried disabling AJAX submission on the secondary form but that doesn't seem to have any affect. We've verified that placing the secondary form on a page without a sidebar form submits to the secondary list as expected. Each list requires an email address field to be filled in.

**Comment by TheTracyL** [comment]
Hi Chris Bloom.

This is a known issue we are actively creating a fix for to be released very soon.

Please [read this thread on the WordPress support forums[(https://wordpress.org/support/topic/multiple-forms-on-a-single-page?replies=16) for more info and a patch you can try.

Thank you!
-Tracy

**Comment by chrisbloom7** [comment]
Thanks for the link. Looks like you're making progress on it and should
have it wrapped up soon. Thanks!

**Comment by TheTracyL** [comment]
The update will be coming out today.

Thank you for your patience!
-Tracy

**Comment by EvanHerman** [comment]
Hi Chris,

I just pushed out the v6.0.3.1 release which should now include the patch to fix this issue outlined above.

Feel free to update from the dashboard and give the new version a shot. If you're still having issues feel free to drop us a line here and we'll re-examine.


Thanks,
Evan
