### ISSUE TITLE
I paid for the addon plug, but I can not submit a request for support

### ISSUE THREAD

**Issue by publicdisplay** [yikesinc/yikes-inc-easy-mailchimp-extender#393]
Hello,

I purchased the addon plug on Friday. I tried to submit a support request via the "support" link in wordpress I go an invalid license key error even though I purchased the add-on. As a matter of fact on the support page it says "It looks like you are one of our premium users! Fill out the form below to submit a priority support request.".  

thanks,
Shannon

**Comment by TheTracyL** [comment]
Do you see the form and are you able to fill it out?

**Comment by publicdisplay** [comment]
Yes, I see the form, I can fill it out.  When I click request support
that's when I get the error.  Here's an attachment with what I see.

thanks,
Shannon

On Mon, Nov 2, 2015 at 11:29 AM, Tracy Levesque <notifications@github.com>
wrote:

> Do you see the form and are you able to fill it out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/393#issuecomment-153074301>
> .
>



-- 
401-239-2192
shannon.lewis@panopticdev.com
www.panopticdev.com
www.twitter.com/panopticdev
www.facebook.com/Panopticdev

**Comment by TheTracyL** [comment]
Hi Shannon,

I don't see an attachment. 

But in the meantime, in your purchase receipt there is an email listed that you can use and it'll automatically create a support ticket if you are experiencing problems with the form.

If you deleted that email, email me your issue at tracy@yikesinc.com and I will create a ticket for you.

Thank you for your patience.
-Tracy
