### ISSUE TITLE
Submit button cannot be customized

### ISSUE THREAD

**Issue by kamargo** [yikesinc/yikes-inc-easy-mailchimp-extender#395]
I just added this plugin to my wordpress, and all the form is localized except the Submit Button. I reviewed all the configuration options and cannot find where can I change the "Submit" texto for something in spanish

**Comment by TheTracyL** [comment]
Hi Karmargo.

The submit button is set via the shortcode. You can set it to say anything you like.

Please refer to this Knowledgebase article for complete instructions:
https://yikesplugins.com/support/knowledge-base/adding-forms-to-pages-and-posts/

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello Again.

I created a new Knowledgebase article inspired by your ticket:
https://yikesplugins.com/support/knowledge-base/how-do-i-change-the-submit-button-text/

Thank you!
-Tracy

**Comment by kamargo** [comment]
Thanks!
