### ISSUE TITLE
Blank pages in WP admin since upgrate to Version 6.0.3.1

### ISSUE THREAD

**Issue by zeweb** [yikesinc/yikes-inc-easy-mailchimp-extender#396]
Hi support team,

I do every upgrade when it's available, for your plugin and also for the other ones.
Yesterday I saw that a new version of Easy Forms for MailChimp by YIKES was available, so I made the upgrade, but since that upgrade a lot of usefull pages linked from wordpress admin are not working any more. I just get a blank white page. On frontend, the forms seem still to be working.

Here are the not working pages :
wp-admin/admin.php?page=yikes-inc-easy-mailchimp
wp-admin/admin.php?page=yikes-inc-easy-mailchimp-lists
wp-admin/admin.php?page=yikes-inc-easy-mailchimp-account-overview

Curiously these 3 pages still work : 
wp-admin/admin.php?page=yikes-inc-easy-mailchimp-settings
wp-admin/admin.php?page=yikes-inc-easy-mailchimp-support
wp-admin/admin.php?page=yikes-inc-easy-mailchimp-addons

Thanks for your help

Regards

**Comment by TheTracyL** [comment]
Hi Zeweb,

Can you please try this from our troubleshooting docs? Let me know if this works, and if not, we'll move on to further troubleshooting. Thank you!

**After upgrading, some of the Plugin’s pages are blank, but others work fine.**

If you click on pages like Opt-in Forms, Mailing Lists or Account and they are blank, reset the API cache from the settings page. Head into Settings > API Cache and click the delete button to empty the data returned from MailChimp. Heading back into any of those blank pages should send a request to the API which should re cache in your database.

**Comment by zeweb** [comment]
Hi TheTracyL,
Thanks for your answer.
I cannot click on the button to delete cache, it looks like disabled, in grey.

**Comment by EvanHerman** [comment]
You may need to re-connect your site with the MailChimp API key. I recommend that you clear the settings on the general settings page - save - re-enter your API key and save again.


Evan

**Comment by zeweb** [comment]
Hi Evan,
Thanks for your answer.
I have removed the hidden api key and saved. After that I have pasted my api key taken from MailChimp but this does not seem to work. I have this error : We received an unexpected error: null
And your plugin is not connected to mailchimp anymore.

**Comment by EvanHerman** [comment]
Yep, that's what I assumed would happen and explains why things aren't working.

Unfortunately this is an issue with your hosting environment, and not necessarily with our plugin. It doesn't look like your host can connect to the MailChimp servers, and it doesn't look like any useful message is being returned from the API which leads me to believe that the API is never reached at all.

Who is your host? What is your version of PHP? If you want us to take a look feel free to create a temporary login for Evan@yikesinc.com and I'll take a look for you.


Thanks,
Evan

**Comment by zeweb** [comment]
But it worked just before last upgrade ... with same hosting (Hostwinds)
Here you have all information http://www.idalina-voyance.com/wp-content/plugins/host-php-info/info.php

Maybe I should downgrade ?

**Comment by EvanHerman** [comment]
Unfortunately that info doesn't help me debug the issue. 

Feel free to send us crendetials so we can take a look, otherwise you can downgrade - but the plugin will most likely stop working come the new year due to MailChimp API changes.


Thanks,
Evan

**Comment by zeweb** [comment]
Ok, I've created you an access and sent it by email.
Thanks for your help.
Regards

**Comment by zeweb** [comment]
Evan, did you get my email ?

**Comment by EvanHerman** [comment]
Hi zeweb,

I don't believe I did. I don't have an email in my spam or inbox, so I don't currently have access to the site.


Evan

**Comment by zeweb** [comment]
Hi Evan, I have just fw the same e-mail to Evan@yikesinc.com

**Comment by zeweb** [comment]
Evan,
Could you manage to take a look ?
I do not catch any lead since this update.
Thanks
Regards

**Comment by EvanHerman** [comment]
This issue was worked out via email and helped with some of the issues patched in v6.0.3.2. Anyone else facing similar issues should update to the v6.0.3.2 or greater and take a look at the following knowledge base article:

https://yikesplugins.com/support/knowledge-base/i-received-the-following-error-we-received-an-unexpected-error-null/

Evan
