### ISSUE TITLE
[solved] sign up form doesn't work since upgraded to 6.0.3.1

### ISSUE THREAD

**Issue by pydun** [yikesinc/yikes-inc-easy-mailchimp-extender#397]
Hi there,

Our sign up form doesn't work since upgraded to 6.0.3.1, and after I filled in the details and click submit, the form does nothing. Could you take a look for me? Thanks. The address is https://www.prohavit.com/newsletters/

Regards,
Gary Zhang

**Comment by pydun** [comment]
To avoid losing subscribers, we have used back default mailchimp form, sorry about that. But I still think there's some kind of bug in the new version, so you might want to look into it

**Comment by EvanHerman** [comment]
Hi Gary,

Is the form AJAX or a standard form? Have you tried toggling to the other option and testing again? It looks like you have some sort of JavaScript error on the page which is causing the form not to function properly, which may be coming from your theme or from another plugin you have installed on the site. 


Evan

**Comment by pydun** [comment]
I guess it is a standard form because I am don't know anything about AJAX, so I won't touch those options. I have created a test page with the same shortcode so you can see how the form looks like
https://www.prohavit.com/test-2/

**Comment by EvanHerman** [comment]
Hi,

On the edit form page, in the right hand sidebar, inside of the 'Submission Settings' drop down (click it to expand this section), The option for 'Enable AJAX Submission' - what is that set to? Yes or No?

I have just tested on a localhost install on my end and both ajax and non-ajax forms appear to be working as expected with Google reCaptcha enabled.

Can you set the form option for AJAX to 'No' and I can try the form again.


Thanks,
Evan

**Comment by pydun** [comment]
It was Yes, now it is No, please try again

**Comment by EvanHerman** [comment]
So the non-ajax forms seemed to work, which leads me to believe that something on your site is preventing the ajax event from firing, which means the form never gets submitted and no data is ever sent over to MailChimp. Without actually having the theme on my end, I can't say for sure and I can't really do any testing on my end to help figure out what's going on.

What theme are you using? Is it a free one I can download, or is it a theme purchased off of theme forest?

Thanks,
Evan

**Comment by pydun** [comment]
Thank you for figuring out the problem. Now that the problem is located, I will delete the test page.

The theme is Avada purchased from theme forest.

**Comment by EvanHerman** [comment]
Ok, I will have to see if I can get my hands on a copy of Avada for testing.

Thanks,
Evan
