### ISSUE TITLE
Updating Interest Groups on Opt-In Form

### ISSUE THREAD

**Issue by tmoore615** [yikesinc/yikes-inc-easy-mailchimp-extender#398]
If I add or delete a group on MailChimp, in order to have the changes show in my opt-in form, I have to remove the "Select email updates you wish to receive" field in Form Builder and then add it again. Is this normal? Is there a way to make Easy MailChimp Extender automatically update the list of interest groups it displays?

Thanks,
Terry Moore

**Comment by TheTracyL** [comment]
Hi Terry,

Did you try clearing the MailChimp API cache? We have instructions here: https://yikesplugins.com/support/knowledge-base/api-cache-settings/

Let me know if that works. If it doesn't update the field after it's been added, then yes, you'll have to remove and re-add to get the newest information. 

We can look further into having it force new data into live forms.

Thanks!
-Tracy

**Comment by tmoore615** [comment]
Thanks, Tracy
