### ISSUE TITLE
Do not fetch the list well

### ISSUE THREAD

**Issue by BabyOnMove** [yikesinc/yikes-inc-easy-mailchimp-extender#401]
Somehow i was not having any list present in my MailChimp account and as I could be redirected to the mailchimp website. I therefore connected directly to the website and created that list.
it is now present onto the account... 

But when I go back to the opt-in forms menu, then the dropdown list on the right hand side is not updated with the latest list created. 

Can you have a look at that issue? 
This is blocking me from integrating the form into my website

Cheers,
Julien

**Comment by BabyOnMove** [comment]
I just realize that the issue is resolved by himself
probably there is a refresh time somewhere that was blocking me from getting that shown in the list location

**Comment by TheTracyL** [comment]
Hi there.

Yes, the MailChimp API cache needs to be cleared after you make changes to your MailChimp account.

We have a knowledge base article explaining it in more detail: https://yikesplugins.com/support/knowledge-base/im-not-seeing-all-my-lists-on-the-drop-down-menu-when-i-go-to-make-a-new-form/

Thank you!
-Tracy
