### ISSUE TITLE
Improvement on the French translation

### ISSUE THREAD

**Issue by BabyOnMove** [yikesinc/yikes-inc-easy-mailchimp-extender#402]
Dear, 

if you are looking for some improvement on the french translation, I can help you a bit there. 

Therefore do not hesitate to contact me
Cheers, 
Julien

**Comment by TheTracyL** [comment]
Hi Julien.

We would love improvements to the French translations. Thank you very much for volunteering.

You can suggest changes in GlotPress: https://translate.wordpress.org/projects/wp-plugins/yikes-inc-easy-mailchimp-extender/stable/fr/default

You will need to have a WordPress.org account to make suggestions. Just find a string you want to suggest changes for and click on the "details" link next to it. There you can type in your translation.

Thank you so much!
-Tracy

**Comment by TheTracyL** [comment]
Hi Julien,

Alternatively, if you don't want to make suggestions via GlotPress, you can email Mia Levesque, our French translator, directly: mia@yikesinc.com

She would appreciate the help.

Thanks again!
-Tracy
