### ISSUE TITLE
New Subscription Notification not working

### ISSUE THREAD

**Issue by Adelphoi** [yikesinc/yikes-inc-easy-mailchimp-extender#403]
I've added my email address to both the subscribe notification and unsubscribe notification options.  I get the unsubscribe notifications, but not the new subscribers notification.  I've checked email addresses, spam folders, etc.  There is only one form on the page.  Please help!

**Comment by EvanHerman** [comment]
1) Can you provide a link to your site?

2) Can you be a little more specific in what you have tried to debug the issue? Is the form ajax or non-ajax? How long have you waited before subscribing?

3) Have you read through the following knowledge base article to confirm data is sent to MailChimp? 
https://yikesplugins.com/support/knowledge-base/confirm-data-is-being-sent-to-mailchimp/

If you're seeing data transmitted to MailChimp on that list when a user subscribes, then there shouldn't be any issues with receiving the confirmation emails. Once the data is received by MailChimp they send out the confirmation email. All our plugin does is make the necessary connections with your site and MailChimp.

Evan

**Comment by Adelphoi** [comment]
Site address is :  casaofcollincounty.org
page to view form:  http://casaofcollincounty.org/about/

the form will be on the right hand side towards the bottom.

<img width="1055" alt="screen shot 2015-11-11 at 12 45 25 pm" src="https://cloud.githubusercontent.com/assets/15804877/11099704/795e5f82-8872-11e5-97c8-d744adda2d03.png">

The new subscriber gets their email.  I do not get the notification that any one subscribed.  I do get the notification if they unsubscribe.  

<img width="1240" alt="screen shot 2015-11-11 at 12 49 55 pm" src="https://cloud.githubusercontent.com/assets/15804877/11099755/c341de9e-8872-11e5-8783-ab8cb0ff75a9.png">

**Comment by Adelphoi** [comment]
i've tried changing email addresses.  Single email address, multiple email addresses... I've spent about 2.5 hours on this trying to resolve it thus far.

**Comment by EvanHerman** [comment]
When you created the list did you check off 'One-by-one' for "Subscribe notifications as they happen"?

**Comment by Adelphoi** [comment]
i honestly do not recall.  is there a way to check/edit that?

**Comment by EvanHerman** [comment]
I'm trying to find an article that explains how to do it. If you temporarily create a new list you'll see the option that I'm referring too. I can't seem to locate that option once the list is actually created tho.

**Comment by EvanHerman** [comment]
This may be what you need to confirm:
http://kb.mailchimp.com/lists/managing-subscribers/change-subscribe-and-unsubscribe-notifications

**Comment by Adelphoi** [comment]
i've tried everything on that link

**Comment by Adelphoi** [comment]
oh geez...i think i found it.  It has to be set to double opt-in and I had it as single!  Geez!!!

**Comment by TheTracyL** [comment]
Ha ha no problem.

Glad you figured it out :-)

**Comment by EvanHerman** [comment]
Yep, that would be the problem:

### Troubleshooting Subscribe and Unsubscribe Notifications

If you don't receive notifications as expected, verify that your email address is entered in the New subscriber notifications fields correctly. If that isn't the problem, review this list of possible issues.

* Lists must be set to double opt-in to trigger a subscription notification. Imports, manual adds, and all of our current integrations and imports from other systems ( Paypal, Wufoo, E-junkie, etc.), will not send a subscription notification.
* If you've added more than one email address to receive notifications, be sure they are separated with commas and don't exceed the field limit of 100 characters total.
* Your notification emails may be getting stuck in a spam filter. To test this, enter an email address with a different domain and sign up to your list to trigger the notification. If you receive the notification at the new email address, then you'll know the notification process is working but you have a spam filter issue on your end. 
To fix this, add the email address from the reply-to field of the successful notification to your email client's address book. Update your notifications back to your regular address and sign up on your list again once more.


Thanks for posting the solution here.


Evan
