### ISSUE TITLE
Activation causes server to crash

### ISSUE THREAD

**Issue by RailfanDepot** [yikesinc/yikes-inc-easy-mailchimp-extender#404]
Hello,

I really would like to use your plugin - and will be buying one or both paid add ons - but... activating the plugin causes my server to crash.  It tried it three times.  Twice with an upload via WordPress and once with downloading the plugin and then uploading via FTP and then activating... in all three cases, the server crashed and I get a Server Error 500.  I then go with my backup and all is okay again.

I am using the latest stable WP (not Beta) with WooCommerce on Cloudways with Digital Ocean.  Any ideas?

Thank you,
Tim

**Comment by RailfanDepot** [comment]
Never mind, I went with MailChimp for WordPress Pro, plus the addon.  $100.00.

**Comment by EvanHerman** [comment]
No worries,

Thanks for keeping us updated. Best of luck!


Evan
