### ISSUE TITLE
Customization for Buttons

### ISSUE THREAD

**Issue by jlhoffman77** [yikesinc/yikes-inc-easy-mailchimp-extender#406]
Hello,

I would like to customize the look of my form by changing some things. I was able to edit the CSS to change the color of the input field and the button, however I can't figure out how to change the text color and type. Can anyone help with this?

Thank you!
Jennifer

**Comment by TheTracyL** [comment]
Hi Jennifer, 

Do you have a link to your form?

Thank you!
-Tracy

**Comment by jlhoffman77** [comment]
Hi Tracy,

Thanks for your help! Yes the link is below. The link looks strange because it's a temporary domain from my host while we are building the website.

http://02d.ca6.myftpupload.com/

Since I posted this I realized that the custom CSS I entered only shows if I'm logged in. I'm a newby at CSS and don't know it very well.

I appreciate your help!

Jennifer

**Comment by TheTracyL** [comment]
Hello, 
Is this your form? https://cldup.com/YnTeQEy-Po.png
How do you want it to look specifically?

Also, how are you editing the CSS?

Thank you!
-Tracy

**Comment by jlhoffman77** [comment]
Yes that's my form however, it's much narrower on my screen which is how I want it. The image you linked to has the custom CSS colors and font selections I entered which is great, but I wonder why it's not showing up on my end if I'm not logged into the website.

**Comment by TheTracyL** [comment]
You should try doing a hard refresh when not logged in and see if you see your styles.

How are you editing the CSS?

**Comment by jlhoffman77** [comment]
The hard refresh worked and my CSS stuck!  I am using a section in my theme called "custom CSS."

**Comment by TheTracyL** [comment]
Oh, that is perfect! 

Ok, what may I help you with specifically? What exactly do you want changed?

**Comment by jlhoffman77** [comment]
Well, now that it seems to be working, there's not much I want to change. Maybe just make the button a little smaller vertically.

**Comment by TheTracyL** [comment]
That is controlled by the padding on the button:

```.yikes-easy-mc-form .yikes-easy-mc-submit-button {
min-height: 40px;
    padding: 10px;
}```

You can change the padding to something like:

```.yikes-easy-mc-form .yikes-easy-mc-submit-button {
    padding: 10px;
}```

**Comment by jlhoffman77** [comment]
Great, thank you so much!  I will play with this until I get the size I'm hoping for.

Thank you!

**Comment by TheTracyL** [comment]
Awesome. 

Best of luck!
-Tracy
