### ISSUE TITLE
Edit Form Link present at bottom of Sign-Up Form

### ISSUE THREAD

**Issue by Sipreme** [yikesinc/yikes-inc-easy-mailchimp-extender#407]
Hi,

On our website (www.testsipreme.com) we used your signup form plugin. It works fine except that at the bottom of the form (under the submit button) there is a link that says "edit form".

This takes you to the form editor and we I not want that to be visible to website visitors. 

Can you please help?

Thanks!
![image](https://cloud.githubusercontent.com/assets/16099102/11498950/8fe40ffc-9887-11e5-86f4-8bc9eb659f5e.png)

**Comment by TheTracyL** [comment]
Hi there.

That edit link only appears for you if you are logged in as an admin. It does not show for regular visitors. Try logging out or opening an incognito browser window and try it again.

Thank you!
-Tracy
