### ISSUE TITLE
Fixes for "API call to helper/ping failed..." didn't work

### ISSUE THREAD

**Issue by ajn2199** [yikesinc/yikes-inc-easy-mailchimp-extender#408]
I tried both suggested fixes for the "API call to helper/ping failed: SSL certificate problem: unable to get local issuer certificate" error but neither one worked.  I am using a xampp on a windows development server.  

I downloaded the ccert.pem file and added the line 

     curl.cainfo="C:\xampp\php\cacert.pem"

to my php.ini file and restarted the apache server but no change.

I then added the function yikes_mailchimp_disable_ssl_verfiy_host_and_peer( $ch )...  to the functions.php file in my Wordpress theme but still no change.

What do I do now?

**Comment by EvanHerman** [comment]
Hi ajn2299,

At this point I would recommend you try the following: https://yikesplugins.com/support/knowledge-base/i-received-the-following-error-we-received-an-unexpected-error-null/

Unfortunately, this error can be due to a number of things and really needs to be handled by your host provider.


Evan

**Comment by ajn2199** [comment]
Hi Evan,
Thanks for the advice.  Interestingly, when I removed the key, added the code from the post you mentioned, and then put the key back in, it connected.  I'm glad it did since the server is the development machine in my office, not a server at a host provider.

Thanks!

**Comment by EvanHerman** [comment]
Hi ajn2199,

Thanks for keeping us updated on the issue. I didn't realize the server was a localhost install. After you installed the cacert.pm, you need to restart your virtual server (stop/start) for things to take effect. If you did, I'm not sure why that wouldn't have worked - but glad things are up and running now!


Evan
