### ISSUE TITLE
I have an error message after upgrading that says:

### ISSUE THREAD

**Issue by jeeEE27** [yikesinc/yikes-inc-easy-mailchimp-extender#409]
Fatal error: Uncaught exception 'Mailchimp_Error' with message 'We received an unexpected error: null' in /home/elizabet/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php:236 Stack trace: #0 /home/elizabet/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php(218): Mailchimp->castError(NULL) #1 /home/elizabet/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/partials/menu/options-sections/integration-settings.php(90): Mailchimp->call('lists/list', Array) #2 /home/elizabet/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/partials/menu/options.php(118): include('/home/elizabet/...') #3 /home/elizabet/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php(1080): require_once('/home/elizabet/...') #4 [internal function]: Yikes_Inc_Easy_Mailchimp_Forms_Admin->generatePageOptions('') #5 /home/elizabet/public_html/wp-includes/plugi in /home/elizabet/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/MailChimp/Mailchimp.php on line 236

**Comment by EvanHerman** [comment]
Hi JeeEE27,

Are you still encountering this issue? From the other ticket you have open it sounds like you got past this error. Do you have any other MailChimp plugins active? If so it's possible that the other plugin has loaded a set of MailChimp class files but is excluding a few used in our plugin.


Evan

**Comment by jeeEE27** [comment]
The problem is resolved. I'm still not sure why. I deleted and reinstalled the plugin a few times and then it worked. Not much help to you, but it's working now. Thanks.

**Comment by EvanHerman** [comment]
Hi JeeEE27,

No problem, If you are still having some issues with your other open issue, feel free to let us know! Otherwise we'll wait a day or so and close that issue out as well.


Thanks!
Evan
