### ISSUE TITLE
Receiving an unexpected error: null

### ISSUE THREAD

**Issue by aylim14** [yikesinc/yikes-inc-easy-mailchimp-extender#410]
Hi!

I'm getting unexpected errors when i try to save my MailChimp API key. 

I just installed your plugin. I have the latest one and the most updated version of Wordpress as well. 

I tried the steps here (https://yikesplugins.com/support/knowledge-base/i-received-the-following-error-we-received-an-unexpected-error-null/) and contacted my webhost (inmotionhosting.com). 

Support agent said they don't block connections.

So i'm now at a loss. Help?

**Comment by EvanHerman** [comment]
Hi Aylim14,

After you implemented the recommended steps in the knowledge base article, what was the response you received back? In that article on step 3 you'll see the response was 'Access Denied'. Did you have anything returned?

Also you may want to confirm that the data is being received properly by the MailChimp API servers:
https://yikesplugins.com/support/knowledge-base/confirm-data-is-being-sent-to-mailchimp/

Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi Aylim14,

Let us know the response you received in Evan's message above so we can further help you.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Aylim14,

We have not heard back from you in a long time so I can going to close out this ticket. Feel free to reopen if you need further help.

Thank you!
-Tracy
