### ISSUE TITLE
API won't connect

### ISSUE THREAD

**Issue by jeeEE27** [yikesinc/yikes-inc-easy-mailchimp-extender#412]
API key won't connect. Have tried most suggested fixes. i have two sites with this issue.

**Comment by EvanHerman** [comment]
Hi,

What is the issue that you are having? What is the response back when you save the API key?


Have you tried the fixes mentioned in this knowledge base article:
https://yikesplugins.com/support/knowledge-base/i-received-the-following-error-we-received-an-unexpected-error-null/

You may also want to confirm that your site is communicating with the MailChimp API servers:
https://yikesplugins.com/support/knowledge-base/confirm-data-is-being-sent-to-mailchimp/

**Comment by TheTracyL** [comment]
Hi jeeEE27,

Please let us know if you tried the things Evan suggested above and if you have and you are still experiencing the problem we can help you troubleshoot further.

Thank you!
-Tracy

**Comment by jeeEE27** [comment]
No, it’s working now, but I have no idea why.

Thanks, you can consider this closed.

 

Elizabeth Edgett

Visit my website at  <http://www.elizabethedgett.com> http://www.elizabethedgett.com

**Comment by TheTracyL** [comment]
Great, I'm so glad things got resolved.

Thank you for the update!
-Tracy
