### ISSUE TITLE
Easy Forms for MailChimp

### ISSUE THREAD

**Issue by DTade** [yikesinc/yikes-inc-easy-mailchimp-extender#413]
Hello I recently installed this plug-in into my Bridge wordpress theme. It works great and connects to my mailchimp account like a dream. I do have a request for some help with this issue because I don't know where to start. On initially loading the registration page where the form is - the form drops all the formatting. When I refresh the page it comes back and looks great. Is there a way to make sure the form looks right at the first view? The users won't know that the form could look so much better! This also occurs on mobile devices, PC and Mac. I have attached screen shots for you to see the before and after,  the URL is http://omidevweb.com/register/
Any help or suggestions for custom css that I could use to help keep the formatting intact would be amazing. 
Thank you, 
[GitHub-Ticket-MailChimpEasyForm.pdf](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/files/57371/GitHub-Ticket-MailChimpEasyForm.pdf)

**Comment by TheTracyL** [comment]
Hello DTrade,

I just took a peek at your site and I see the formatting correctly upon load.

Here is a screencast video so you can see how I am experiencing it. http://screencast-o-matic.com/watch/colQrshuRU

I'm not sure what may be going on for it to not render immediately for you, but maybe you could try viewing it from another Internet connection? 

Let me know if you need further help.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
I just checked again on my laptop at home and there is no delay here either.

**Comment by TheTracyL** [comment]
Hello DTrade,

Just checking in, are you still experiencing this problem?

Thank you!
-Tracy

**Comment by DTade** [comment]
Hello thank you so much for checking. It is good to see that you are viewing it correctly. But I am still experiencing this issue. Both on my Mac, and my PC at work, and my co-worker at work is getting the same thing. At home with my Mac and at work are different internet connections….

I am stumped...


Denise Tade, Graphic Designer
dftade@gmail.com

**Comment by TheTracyL** [comment]
Do you think you could try using a caching plugin? I did a little research and found these links: 

http://www.kriesi.at/support/topic/css-rendering-delay/
https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

This one gets really granular with how to construct your CSS to render efficiently:
https://css-tricks.com/efficiently-rendering-css/

**Comment by DTade** [comment]
That could be just the thing. I will give it a try. I really appreciate your help, I wouldn't know where to begin without it! 

Thank you.

**Comment by TheTracyL** [comment]
No problem, I'm happy to help.
