### ISSUE TITLE
Mailchimp button does not appear on visual editor

### ISSUE THREAD

**Issue by redrosesburning** [yikesinc/yikes-inc-easy-mailchimp-extender#414]
Hello,

I wanted to add my form on different pages using the mail chimp button on the Visual tab as I aw in the knowledge base article. The button is non existent though. I am using site origin's Vantage theme. Is the button only available on certain themes?

Thank you

**Comment by EvanHerman** [comment]
Hi,

The button should be visible across all themes. If it's not showing up, it's most likely a conflict with your theme or another plugin. You may want to try and disable plugins one at a time until the button appears. If by the time you disable ll of the plugins, other than ours, and the icons is still not present - you may want to try switching themes temporarily.

Once you can find the cause of the problem, we would be glad to help our and get a fix out for you.



Thanks,
Evan

**Comment by redrosesburning** [comment]
Thanks Evan,

Ive managed to fix the issue. I'd like to ask you a question about changing the color of the fonts that describe the field. I've put the opt in form on my header on my website, which is black, but because the fonts are a near grey, people are unable to see the text. Any way to change this?

Also is there a way to get rid of the edit form button that is below the input fields?

My website is www.spiritstarastrology.com 

so you can have a look at what I mean.

Thanks so much and much appreciated,

Melissa

**Comment by TheTracyL** [comment]
Hi Melissa.

We have a paid add-on called [Form Customizer for Easy Forms for MailChimp](https://yikesplugins.com/plugin/form-customizer-for-easy-forms-for-mailchimp/) that will allow you to change the styles of your form. 

Alternatively, you can write some custom CSS and drop that in your theme or child theme's style sheet.

This CSS code will turn your field labels white in the header:

```#header-sidebar .yikes-easy-mc-form label {
    color: #fff;
}```

You have a few options to add CSS code:
* If you created this theme yourself, you can just add it to your style.css file
* If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
* Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
* You can use a plugin like [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/) or Jetpack and enter the code in their Custom CSS area

Thank you!
-Tracy

**Comment by redrosesburning** [comment]
Thank you Tracy!
The field labels are now white. Could you please give me a CSS code to make the form description on top of the input fields white as well?

One more thing, I will have to get the paid add on if I want to change the color and size of the sign up button?

Am grateful for your help. Thanks again!

**Comment by TheTracyL** [comment]
Hi Melissa,

You can write your own custom CSS for any element of the form, you don't need to buy the add-on, but the add-on will allow you to do it without needing to know how to code CSS.

The form description is actually the widget title which is controlled by your theme, here is the CSS code to make that part white:

```#masthead .hgroup #header-sidebar .widget-title {
    color: #fff;
}```

Thank you!
-Tracy

**Comment by redrosesburning** [comment]
Thank very much!

**Comment by TheTracyL** [comment]
No problem, glad to help!

If you're enjoying the plugin and support, please consider leaving a nice review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make a plugin developer's day :-)

Thank you!
-Tracy
