### ISSUE TITLE
Single Optin Selected but Double Optin email being sent

### ISSUE THREAD

**Issue by lmacpherson78** [yikesinc/yikes-inc-easy-mailchimp-extender#415]
The first form I created worked great, but the second form is sending a double optin email even though I have selected "single optin" as I did with my first form. Can you advise? Thanks.

**Comment by TheTracyL** [comment]
Hi Laura.

I am going to close this ticket, because it's a duplicate of one in progress on WordPress.org

Thank you!
-Tracy
