### ISSUE TITLE
Hello i have a proble to make a suscriber form for my website with easy forms?

### ISSUE THREAD

**Issue by angeliquedesserts** [yikesinc/yikes-inc-easy-mailchimp-extender#416]
Hello i have a proble to make a suscriber form for my website with easy forms, when i star create but dont appear the list i have in mail chimp, i already did why i fount to do in the website, can help me?

**Comment by EvanHerman** [comment]
Hi,

If you've recently created the list you'll need to clear out the MailChimp API cache temporarily stored on your site.

Take a look at the following knowledge base article for some help:
https://yikesplugins.com/support/knowledge-base/api-cache-settings/

That should help clear things up. Once you clear the cache data, simply refresh the page and your list should appear in the drop down.

Thanks,
Evan

**Comment by angeliquedesserts** [comment]
Hello, I already do that 7 time's in different days, also clear the cache of my Explorer to see if that work and still the problem.

**Comment by EvanHerman** [comment]
Is the list set to private or something? Are you able to see other MailChimp activity? The list should appear after clearing the MailChimp API cache on your site.


Evan

**Comment by TheTracyL** [comment]
Hi angeliquedesserts,

We have not heard back from you in a couple weeks, so I am going to close out this ticket.

If you need further help, feel free to reopen it.

Thank you!
-Tracy
