### ISSUE TITLE
Warning: end() expects parameter 1 to be array, null given when no user logged in

### ISSUE THREAD

**Issue by wolfems** [yikesinc/yikes-inc-easy-mailchimp-extender#417]
The following two warning errors are generated when viewing the form from an unauthenticated user (which is the norm) however, it is good to note when you are logged in to the site as admin or any other user, these errors are not present.

![image](https://cloud.githubusercontent.com/assets/8948033/12025674/3740d076-ad7f-11e5-8d08-c40e97056f01.png)

**Comment by EvanHerman** [comment]
Hi Wolfems,

Is this form an Ajax or Non-Ajax form? I'll take a look into this and report back with some findings.


Thanks,
Evan

**Comment by wolfems** [comment]
It is currently set to Ajax.   Thank you

**Comment by EvanHerman** [comment]
What theme are you currently using on your site?

On [that line](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/plugin_core/public/partials/shortcodes/process_form_shortcode.php#L129-L131) we're checking what styles are enqueued on your site, and enqueing our styles **after** all others.

The error that you're seeing leads me to believe that styles are not properly enqueued on your site and the global styles array is returning empty.


Evan

**Comment by wolfems** [comment]
Ah, that could be it.
I'm using Thesis version: 2.1.9

**Comment by EvanHerman** [comment]
Can you try temporarily changing themes and seeing if the error is still present on your end? I can't test against thesis as it appears to be a premium framework.


Thanks,
Evan

**Comment by wolfems** [comment]
It works properly in the delivered Twenty Fourteen theme.

![image](https://cloud.githubusercontent.com/assets/8948033/12026647/0bcacf7c-ad8a-11e5-9bfa-43e2133a7670.png)

**Comment by EvanHerman** [comment]
We're you at all able to get this resolved?


Evan

**Comment by wolfems** [comment]
Not resolved, but I think we reached the conclusion that it is an implementation problem on the Thesis end, not on the Yikes end.

**Comment by TheTracyL** [comment]
Sorry about that, we are going to close this ticket on our end.
