### ISSUE TITLE
home address showing

### ISSUE THREAD

**Issue by diningwithdebbie** [yikesinc/yikes-inc-easy-mailchimp-extender#419]
Confirmation emails to subscribers are showing my home address. How do I omit that?

**Comment by TheTracyL** [comment]
Hi Debbie,

The confirmation email is generated by MailChimp itself. They probably provide you a place to set the from: email address. 

Here is their article on double opt-ins http://kb.mailchimp.com/lists/signup-forms/the-double-opt-in-process 

It doesn't have that info. specifically, but it seems like a good place to start.

Thank you!
-Tracy
