### ISSUE TITLE
Fields in Form jump from standard fields to big text areas

### ISSUE THREAD

**Issue by csbonesteel** [yikesinc/yikes-inc-easy-mailchimp-extender#420]
I added an opt-in form using Easy Forms to my sidebar. I then added the code to my index file for a pop-up form created in MailChimp. When I did that, the field boxes in my sidebar changed to huge text areas. I deleted the pop-up code, deleted the Easy Forms opt-in, then recreated the Easy Forms opt-in for my sidebar. They are still big text areas.

**Comment by TheTracyL** [comment]
Hi Csbonesteel,

Can you please provide a link to the form so we can take a look?

Thank you!
-Tracy

**Comment by csbonesteel** [comment]
http://www.trainedbytoddlers.com/

**Comment by EvanHerman** [comment]
It looks like the form in the popup is not the code from our plugin but instead the code generated by MailChimp. If that is what caused the issue, then the two are not compatible and there is some sort of theme conflict.


Evan

**Comment by csbonesteel** [comment]
That's fine- but when I tried to take the pop up down, I deleted and re created the Easy Forms and it still did the same thing. Even without the MailChimp pop up.

**Comment by TheTracyL** [comment]
It's actually the widget in the sidebar - that is our plugin and the input fields are huge. I'm looking into it now :-)

**Comment by EvanHerman** [comment]
@csbonesteel see fix above ^

**Comment by TheTracyL** [comment]
Yes, Evan's code above will totally fix it.

You have a few options to add CSS code:

 - If you created this theme yourself, you can just add it to your style.css file
 - If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
 - Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
 - You can use a plugin like Simple Custom CSS https://wordpress.org/plugins/simple-custom-css/ or Jetpack and enter the code in their Custom CSS area

Thank you!
-Tracy

**Comment by csbonesteel** [comment]
The problem is that I took out the pop-up code. I deleted the Easy Forms opt-in and started all over with JUST the Easy Forms opt-in. They don't return to the small form fields.

**Comment by TheTracyL** [comment]
Do you mean in the sidebar? 

Did you try adding that CSS code Evan posted? 

```.yikes-easy-mc-form input[type=text], 
.yikes-easy-mc-form input[type=url], 
.yikes-easy-mc-form input[type=email], 
.yikes-easy-mc-form input[type=number], 
.yikes-easy-mc-form select {
   height: auto;
}```

That will solve the problem with the fields.

**Comment by csbonesteel** [comment]
Sorry! Didn't see the code. I put the code into Custom CSS in Jetpack and it doesn't look like it worked.

**Comment by TheTracyL** [comment]
Ok, try adding !important to the style.

Like this:

```.yikes-easy-mc-form input[type=text], .yikes-easy-mc-form input[type=url], .yikes-easy-mc-form input[type=email], .yikes-easy-mc-form input[type=number], .yikes-easy-mc-form select { height: auto; }```

Thank you!

**Comment by TheTracyL** [comment]
Ok, try adding !important to the style.

Like this:

```.yikes-easy-mc-form input[type=text], .yikes-easy-mc-form input[type=url], .yikes-easy-mc-form input[type=email], .yikes-easy-mc-form input[type=number], .yikes-easy-mc-form select { height: auto !important; }```

Thank you!

**Comment by csbonesteel** [comment]
Oh thank you thank you!! So does that mean I can not have the pop up and the widget exist together?

**Comment by TheTracyL** [comment]
Try the popup now and see if it works for you.

**Comment by csbonesteel** [comment]
In the same Custom CSS?

**Comment by csbonesteel** [comment]
*In the same Custom CSS area or somewhere else?

**Comment by TheTracyL** [comment]
The CSS should work for all of our forms no matter where they are.

Try adding the a form to the pop up the way you did before.

**Comment by TheTracyL** [comment]
Just to clarify, you wont need to add any more custom CSS, the CSS you added will work for all of our forms.

**Comment by csbonesteel** [comment]
Oh great. Thank you so much for your incredibly fast and efficient help!

**Comment by TheTracyL** [comment]
No problem at all, we are happy to help.

If you're enjoying the plugin and support, please consider leaving a nice review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make a plugin developer's day :-)

Thank you!
-Tracy
