### ISSUE TITLE
Cyrillic letters bug

### ISSUE THREAD

**Issue by kab91** [yikesinc/yikes-inc-easy-mailchimp-extender#421]
Hi, I noticed a bug. I typed Russian letters into "Form Description" field and clicked "Update form" button. After that all text was replaced with "?" characters.

![edit form wordpress](https://cloud.githubusercontent.com/assets/4497916/12108460/5f7ac88e-b3a2-11e5-9cfb-a324b10b02ca.png)

**Comment by TheTracyL** [comment]
Hello Kab91,

Thank you for bringing this to our attention. 

This is a known bug and it is on our [fix list for a future update](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/353). In the meantime, we're really sorry for the inconvenience.

Thank you,
Tracy
