### ISSUE TITLE
First and Last Name not showing up for subscribers

### ISSUE THREAD

**Issue by rockintech** [yikesinc/yikes-inc-easy-mailchimp-extender#424]
On this page when I try to view a subscriber: /wp-admin/admin.php?page=yikes-mailchimp-view-user

-- only Email shows up.
-- First and Last Name for the subscriber are missing.

** the First and Last Name are saved into MailChimp just fine.

Varun

**Comment by EvanHerman** [comment]
Hi Rocintech,

That page pulls in data from MailChimp. Are you sure that those users have first and last names set? It's possible that they did not at one point and got stored in your sites cache, but that should be cleared every hour.

If you view the users info card, are you still not seeing any first or last names?


Evan

**Comment by TheTracyL** [comment]
Hi Rocintech,

We have not heard back from you in a couple weeks, so I am going to close out this ticket.

If you need further help, feel free to reopen it.

Thank you!
-Tracy
