### ISSUE TITLE
Javascript error: Uncaught Error: no such method 'instance' for droppable widget instance when running with Avada theme

### ISSUE THREAD

**Issue by davidmcgregor** [yikesinc/yikes-inc-easy-mailchimp-extender#426]
When the easy forms plugin is installed with the latest version of the Avada theme (3.9.2) it causes the following javascript error to be thrown when using Avada's page builder: Uncaught Error: no such method 'instance' for droppable widget instance. If I uninstall the plugin the page builder works correctly.

**Comment by EvanHerman** [comment]
Hi David,

Since Avada is a premium theme, we don't have immediate access to test against. If we can get our hands on a copy, we'll give things a testing and see what might be going on.

Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi David,

Would you be willing to give us a copy of Avada so we can test with our plugin?

Thank you!
-Tracy
