### ISSUE TITLE
SOURCE merge code not being transmitted to MailChimp

### ISSUE THREAD

**Issue by MaryGMB** [yikesinc/yikes-inc-easy-mailchimp-extender#427]
I have the plugin installed on two different websites. In my forms, I have a hidden field "SOURCE", that I use to track which form they used to subscribe. The other two fields are for them to enter their name and email. On one site, everything works beautifully, all information from the forms are transmitted to MailChimp. On the other site, only the name and email are being sent to MailChimp, even though the hidden SOURCE field is present in the generated html code. On both sites, the subscription process works as expected, except for this one issue.

The form that is not transmitting all the data can be seen in the sidebar here: http://karenbentley.com

The ones that ARE transmitting all the data are on this site: http://thebigheartcenter.com , one in the sidebar and another on the email list page linked in the menu.

On the off chance that it would make a difference, I generated a new API code for the plugin on the  karenbentley.com website. It made no difference at all.

Any help would be appreciated! Thanks!

**Comment by TheTracyL** [comment]
Hi Mary.

Are both sites on the same host? Are there any other differences in hosting environment? Do both sites use the same theme?

Please let us know :-)

Also, I am going to close the duplicate ticket on the WordPress.org support forum.

I apologize in advance if there is a delay in responses, because it is a 3-day weekend for us.

Thank you!
-Tracy

**Comment by MaryGMB** [comment]
Yes, both sites are on a server we (my husband and I) manage, both sites use the same theme. Both are using the most up-to-date version of Wordpress. Sorry about the duplicates, I wasn't sure where to get the quickest response. Also, I'm sorry to interrupt your 3-day weekend.

Thanks!
Mary

**Comment by TheTracyL** [comment]
No worries! 

We are back in the office on Tuesday and Evan will be able to answer then at the latest. He will have a better knowledge of what may be going on.

Thank you for your patience.
-Tracy

**Comment by MaryGMB** [comment]
Thanks, Tracy! Meanwhile, I'll keep trying things to see if I can figure this out. Karen (the site owner) wants this up and running by tomorrow, and I told her I'd get it done. Didn't expect this kind of a glitch!

**Comment by MaryGMB** [comment]
Ok, I found the trouble, I think. After reading one of the other issues: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/142, I went and cleared the cache in the plugin cache settings. Then I tried the subscription form again, and it worked like a charm. Now, my question is, is there a way to disable the cache so I don't have to go clear it manually? Once I get this all set up, I'll be using the plugin on 6 different websites, all connected to the same MailChimp list. I really don't want to have to clear the cache several times a day on all 6 sites!

**Comment by MaryGMB** [comment]
Well, no joy in Mudville. Clearing the cache only fixed it for a little while. I tried subscribing again a few minutes ago, after first clearing the cache in the plugin and looking at the list on the MailChimp site to make sure I wasn't already in the list. I double-checked the SOURCE setting as well, for good measure. Still no joy - the SOURCE field value isn't being sent to MailChimp.

**Comment by EvanHerman** [comment]
Hi Mary,

From what I can see both of the forms are set up the exact same way, and have all of the same fields. On the one site, I can see the 'SOURCE' field as `Big_Heart_Center_Sidebar`. On the other, `KarenBentley_Sidebar`.

Both have the same field names 'SOURCE', so they should be mapping to the appropriate merge fields on your MailChimp list.

What happens in your MailChimp list with that field when you submit the data? Is it just blank? What happenes with the name and email fields? Do those get sent over?

Are these two sites setup in a multi-site environment, or are they two separate entities? Are both forms linked to the same MailChimp mailing list?

In regards to the cache, that should have no effect on whether the field is being submitted along with the other field data. The fields are hidden fields pre-populated with data from your site. The cache stores things such as what fields you have associated with what fields, field labels, pre-checked/pre-filled options etc.

Ideally, things should be working as it sits now. From what I can see on the front end of both sites, the fields and forms are setup properly. I can try and setup an environment that may replicate this setup, but from what I can see it looks correct.

Maybe it's a browser caching issue? Can you try re-submitting the forms via a 'private'/'incognito' browsing window?



Thanks!
Evan

**Comment by MaryGMB** [comment]
Hi Evan,

What happens in her (Karen's) MailChimp list is if the SOURCE info is sent, it shows up with the subscriber's infor in the list. If it's not sent, the SOURCE is blank for that entry in the list. The two sites are completely seperate entities, and both forms are linked to the same MC list. In fact, I have the plugin installed on six different websites, all on the same server, with seven different forms, and the one on karenbentley.com is the only one that doesn't always work. It's maddening! 

I was grasping at straws when I cleared the API cache, I didn't really think it made a difference. Just now, while I'm typing this, I signed myself up again through the form on karenbentley.com, and it's working perfectly. I honestly don't know what a private/incognito browsing window is, though I can pretty well guess what it's supposed to do. I use Firefox.

Maybe it IS a browser or connection issue. Our network here at home WAS pretty slow last night. Odd though, that the name and email field input would transmit, but not the source field info.

Thanks for taking time out from your long weekend, I appreciate that!

**Comment by EvanHerman** [comment]
Hey Mary,

When the form is submitted, you've just setup a redirect to that confirmation page? Or did you actually write some additional code ontop of the redirects built into the plugin?

The way things work, as I'm sure you've noticed, is that the name and email address fields are visible whereas the SOURCE field is a hidden field. All of those fields should be sent over to MailChimp, regardless of their visibility state.

When I check the SOURCE field, I can see that it is there and has some content entered into it. I can't think of any reason that the field would be negated and excluded from transmitting over to MailChimp.

Since they are linked to the same MailChimp mailing list, if you signed up on one site and then went and signed up on a second site, the second sites SOURCE would be the one in place for that user. I wonder if it is somehow getting overwritten or something strange.

If you would like to [email me](http://www.yikesinc.com/company/people/), we can discuss in private and I can personally take a look at what might be going wrong under the hood. From my testing, the hidden fields do get sent over to MailChimp consistently.


Thanks,
Evan

**Comment by MaryGMB** [comment]
On the MailChimp site, in the advanced mode confirmation thank-you page interface, I put this line into the body:

<script>location.href='http://karenbentley.com/success/?source=*|SOURCE|*'</script>

On the karenbentley.com/success page, which is a php page, I included a function that I wrote that will take the GET source variable and send them to one of several pages, depending on the value of "source". 

I don't know what happened, but the trouble seems to have fixed itself. Since yesterday, I've been signing up for her newsletter through the form on karenbentley.com, and the source is being consistently transmitted with the rest of the form data.  I am about to implement a workaround to include in my function a different action to perform if the source variable is blank, just in case.

The whole point of the exercise is so Karen could send subscribers back from whence they came, and give them a different freebie depending on which site they were on when they signed up.

I appreciate your offer to email you for more private assistance, but I think we can call this issue closed. Thank you very much for your help, Evan!

**Comment by EvanHerman** [comment]
Great! I'm glad that things are at least working in the meantime. It could have been a browser cache issue, or something similar - but I'm glad things are up and running and functioning properly for the time being.

If you notice anything weird going on, feel free to comment back here and we can work things out :)

Finally, if you are enjoying the plugin - we would greatly appreciate it if you could leave us a review in the WordPress repository for others to make note of.

https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender


Thanks again Mary, have a great afternoon!


Evan

**Comment by MaryGMB** [comment]
Hi Evan,

Your plugin saved me many hours of "reinventing the wheel", and I will be happy to leave a review in the WP repository. Thank you again for all your help, I appreciate it!

Mary

**Comment by TheTracyL** [comment]
That is great to hear! We love it when our plugins save people time.

Have a good day!
-Tracy

**Comment by MaryGMB** [comment]
I just left a detailed review for you guys and your plugin at Wordpress. I got lucky when I chose yours first from among the mailchimp plugins in the repository. Many thanks to both of you!
Mary
