### ISSUE TITLE
Upgrade to version 6 generates 406 errors

### ISSUE THREAD

**Issue by TitoZ** [yikesinc/yikes-inc-easy-mailchimp-extender#428]
Greetings,

While trying to upgrade to version 6, the migration screen just hangs. The Safari console shows several 406 errors on admin-ajax.php. This causes the migration to fail.

How could I get around this issue? Please advise and thanks in advance!

**Comment by TheTracyL** [comment]
Hello TioZ,

We have an upgrade troubleshooting guide in our Knowledge Base: https://yikesplugins.com/support/knowledge-base/upgrading-to-version-6-troubleshooting/

Here is the item regarding the migration hanging:

**When trying to perform the migration it just hangs and does nothing.**
If you run into the problems during the migration, try deactivating and reactivating the plugin. This will make sure the new database tables are created and the migration can do its thing.

Please give this a try and let us know if it doesn't work.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello TioZ,

Just checking in on this. Were you able to get things up and running?

Please let us know if you need further help.

Thank you!
-Tracy

**Comment by TitoZ** [comment]
Hi Tracy,

Thanks for following up. It seems we need to use a new API key from MailChimp but our client has not provided us with it so I have not tested that theory yet.

I will update you as soon as we find out if the new API key resolves the issue.

Best,
Tito

**Comment by TheTracyL** [comment]
Ok, cool. Thank you for the update.

I'm going to close this ticket, but if you need more help, feel free to reopen it.

Best wishes,
-Tracy
