### ISSUE TITLE
Failed to send your message.

### ISSUE THREAD

**Issue by netizenkane** [yikesinc/yikes-inc-easy-mailchimp-extender#429]
Suddenly getting this error message:

Failed to send your message. Please try later or contact the administrator by another method.

site: barkleymovie.com

**Comment by EvanHerman** [comment]
Hi,

Where are you getting that message? It doesn't sound like its coming from our plugin.


Thanks,
Evan

**Comment by netizenkane** [comment]
Getting it on the website below the form.  Screen shot attached
![yikes](https://cloud.githubusercontent.com/assets/16901926/12587449/3fdc6934-c409-11e5-9ce8-767f79a38093.JPG)

**Comment by EvanHerman** [comment]
That does not appear to be a form generated by our plugin.

**Comment by netizenkane** [comment]
ah. ok. thanks
