### ISSUE TITLE
forms text is white

### ISSUE THREAD

**Issue by crucializer** [yikesinc/yikes-inc-easy-mailchimp-extender#430]
www.thecoffeemademedoit.com

the mail chimp signup form on the left column. when u enter text it's white. what do i need to do to make it readable?

**Comment by EvanHerman** [comment]
Hi,

It looks like your theme has inputs set to #fff color.

You can try adding the following to your theme (or child themes) style.css file:

.widget .yikes-mailchimp-container input {
   color: #333;
}

That should get things in working order. That will set only our input fields to be black text. If yo have other fields such as dropdowns, you can add the following:

.widget .yikes-mailchimp-container input,
.widget .yikes-mailchimp-container select {
   color: #333;
}

Which will also target dropdown fields.


Let us know if that helps out!
Evan

**Comment by crucializer** [comment]
You nailed it.

Thank You

**Comment by TheTracyL** [comment]
Awesome! Glad we could help :-)

If you're enjoying the plugin and support, please consider leaving a nice review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make plugin developers' day :-)

Thank you!
-Tracy
