### ISSUE TITLE
International Dates and Phone Numbers

### ISSUE THREAD

**Issue by jvoz** [yikesinc/yikes-inc-easy-mailchimp-extender#431]
Hello,

Before I sign up for support and dive headlong into Yikes, I want to confirm that I can easily configure the use of Australian dates ("dd-mm-yy") and phone numbers (typically 99-9999-9999).

Can someone please confirm this and advise where I set it up?

Thanks

John

**Comment by TheTracyL** [comment]
Hi John,

Here is our knowledgebase article on date formats: https://yikesplugins.com/support/knowledge-base/how-do-i-change-the-frontend-date-picker-format/

Our plugin displays international phone number formats as well.

Thank you!
-Tracy

**Comment by jvoz** [comment]
Thanks Tracy, I have both formats now coming through into the form builder. 

On dates, the odd thing is though that although I have defined my field as DD/MM/YYYY, if I enter, say 01/15/2010, the date is accepted by the form and then converted to 01/01/1970 by MC.  

Then on the phone number, I am not seeing any formatting at all on the front end, even though it is defined as International at both MC and on your form.

Any ideas?  Cheers!

**Comment by TheTracyL** [comment]
Hi Jvoz,

We very recently did I lot of work on international dates. Can you please double check you are using the newest version of the plugin -- version 6.0.4 and try again?

Evan can answer your second question. Also, may we please have a link to the form?

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Hi Jvoz,

As Tracy suggested, you'll want to make sure that you're using our most recent version (v4.0).

I did some thorough testing with international and US formatted dates, and both seemed to work without any issues. The previous versions used an outdated method for passing along the date info.

Another user is currently running the date fields using DD/MM/YYYY formats without any issues.


In terms of the phone number - that's correct. There is no formatting on the front end of the site for international phone numbers. The API states:

> If your account has the US Phone numbers option set, this must be in the form of NPA-NXX-LINE (404-555-1212). If not, we assume an International number and will simply set the field with what ever number is passed in.

We built in formatting for the US phone number to ensure that it follows the expected format. The International phone numbers can be formatted in any number of ways, and would be hard for us to predict, however we've gone ahead and built in filters to allow for you to alter the phone formats as needed.

The filter you'd want to use is `yikes-mailchimp-international-phone-pattern`.

The filter allows you to alter the regex pattern on the input field. The default regex pattern is `[0-9]{1,}`.

You'll find that on the `input` field of the phone field type, where we process the shortcode on the frontend of your site:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/65240c3dc01dfb14a8051b570a0f0d430956ad18/plugin_core/public/partials/shortcodes/process_form_shortcode.php#L566

Additionally, we've added an `onblur` attribute to the US phone formats, so that when you click away from the fields they are formatted as such. You should be able to do the same for international phone numbers, much in the same way that we've done for the US fields.



Thanks,
Evan

**Comment by jvoz** [comment]
Hello Tracy,

Thanks for your reply.

You will find the form at http://www.infocube.com.au/corporate-planning-lp-form/.

I can confirm that I am using the latest version of the plugin.

While on the form, you’ll also see that the Submit button is almost invisible.  Any ideas how I can make it visible?

Thanks heaps

John

John Vaughan
Managing Director



133 Alexander Street, Crows Nest NSW 2065
t: 1300 136 755 | m: 0418 634 652 | f: 02 9439 2738
john.vaughan@infocube.com.au<mailto:john.vaughan@infocube.com.au> | www.infocube.com.au<http://www.infocube.com.au/>

Accountants that specialise in business analytics.




On 3 Feb 16, at 01:49, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jvoz,

We very recently did I lot of work on international dates. Can you please double check you are using the newest version of the plugin -- version 6.0.4 and try again?

Evan can answer your second question. Also, may we please have a link to the form?

Thank you!
-Tracy

—
Reply to this email directly or view it on GitHub<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/431#issuecomment-178610353>.

******************************************************************************** This communication is intended only for use of the addressee and may contain legally privileged and confidential information. If you are not the addressee or intended recipient, you are notified that any dissemination, copying or use of any of the information is unauthorised. The legal privilege and confidentiality attached to this e-mail is not waived, lost or destroyed by reason of a mistaken delivery to you. If you have received this message in error, we would appreciate an immediate notification via e-mail to info@infocube.com.au or by phoning 1300 136 755, and ask that the e-mail be permanently deleted from your system. InfoCube Consulting (Australia) Limited ACN 159 148 660 ********************************************************************************

**Comment by jvoz** [comment]
Thanks Evan. I will do some testing on the international phone numbers hopefully later today.  Kind regards, John

John Vaughan
Managing Director



133 Alexander Street, Crows Nest NSW 2065
t: 1300 136 755 | m: 0418 634 652 | f: 02 9439 2738
john.vaughan@infocube.com.au<mailto:john.vaughan@infocube.com.au> | www.infocube.com.au<http://www.infocube.com.au/>

Accountants that specialise in business analytics.




On 3 Feb 16, at 02:02, Evan Herman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jvoz,

As Tracy suggested, you'll want to make sure that you're using our most recent version (v4.0).

I did some thorough testing with international and US formatted dates, and both seemed to work without any issues. The previous versions used an outdated method for passing along the date info.

Another user is currently running the date fields using DD/MM/YYYY formats without any issues.

In terms of the phone number - that's correct. There is no formatting on the front end of the site for international phone numbers. The API states:

If your account has the US Phone numbers option set, this must be in the form of NPA-NXX-LINE (404-555-1212). If not, we assume an International number and will simply set the field with what ever number is passed in.

We built in formatting for the US phone number to ensure that it follows the expected format. The International phone numbers can be formatted in any number of ways, and would be hard for us to predict, however we've gone ahead and built in filters to allow for you to alter the phone formats as needed.

The filter you'd want to use is yikes-mailchimp-international-phone-pattern.

The filter allows you to alter the regex pattern on the input field. The default regex pattern is [0-9]{1,}.

You'll find that on the input field of the phone field type, where we process the shortcode on the frontend of your site:
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/65240c3dc01dfb14a8051b570a0f0d430956ad18/plugin_core/public/partials/shortcodes/process_form_shortcode.php#L566

Additionally, we've added an onblur attribute to the US phone formats, so that when you click away from the fields they are formatted as such. You should be able to do the same for international phone numbers, much in the same way that we've done for the US fields.

Thanks,
Evan

—
Reply to this email directly or view it on GitHub<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/431#issuecomment-178619317>.

******************************************************************************** This communication is intended only for use of the addressee and may contain legally privileged and confidential information. If you are not the addressee or intended recipient, you are notified that any dissemination, copying or use of any of the information is unauthorised. The legal privilege and confidentiality attached to this e-mail is not waived, lost or destroyed by reason of a mistaken delivery to you. If you have received this message in error, we would appreciate an immediate notification via e-mail to info@infocube.com.au or by phoning 1300 136 755, and ask that the e-mail be permanently deleted from your system. InfoCube Consulting (Australia) Limited ACN 159 148 660 ********************************************************************************

**Comment by EvanHerman** [comment]
Hi,

From an initial glance at your site, I can tell that you have at least 2 java script errors on the page. I would recommend that you clear those up before you continue with our plugin. 

When you select the 'Date to Meet' field, a jQuery calendar should appear allowing your users to enter the date in the format that is expecting. My guess is that you are entering a different format than expected, and things are not formatted properly when submitted over to MailChimp.


It looks like you have some JS on the page, that is causing issues:

```js
$(function(){

      SyntaxHighlighter.all();

    });

    $(window).load(function(){

      $('.flexslider').flexslider({

        animation: "slide",

        start: function(slider){

          $('body').removeClass('loading');

        }

      });
```



Thanks,
Evan

**Comment by jvoz** [comment]
Yikes Evan.  You’ve gone way over my head on that one!  Do you know of anyone who can help me decipher and correct the problem?  Thanks heaps, John

John Vaughan
Managing Director



133 Alexander Street, Crows Nest NSW 2065
t: 1300 136 755 | m: 0418 634 652 | f: 02 9439 2738
john.vaughan@infocube.com.au<mailto:john.vaughan@infocube.com.au> | www.infocube.com.au<http://www.infocube.com.au/>

Accountants that specialise in business analytics.




On 3 Feb 16, at 08:03, Evan Herman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

From an initial glance at your site, I can tell that you have at least 2 java script errors on the page. I would recommend that you clear those up before you continue with our plugin.

When you select the 'Date to Meet' field, a jQuery calendar should appear allowing your users to enter the date in the format that is expecting. My guess is that you are entering a different format than expected, and things are not formatted properly when submitted over to MailChimp.

It looks like you have some JS on the page, that is causing issues:

$(function(){

      SyntaxHighlighter.all();

    });

    $(window).load(function(){

      $('.flexslider').flexslider({

        animation: "slide",

        start: function(slider){

          $('body').removeClass('loading');

        }

      });

Thanks,
Evan

—
Reply to this email directly or view it on GitHub<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/431#issuecomment-178817188>.

******************************************************************************** This communication is intended only for use of the addressee and may contain legally privileged and confidential information. If you are not the addressee or intended recipient, you are notified that any dissemination, copying or use of any of the information is unauthorised. The legal privilege and confidentiality attached to this e-mail is not waived, lost or destroyed by reason of a mistaken delivery to you. If you have received this message in error, we would appreciate an immediate notification via e-mail to info@infocube.com.au or by phoning 1300 136 755, and ask that the e-mail be permanently deleted from your system. InfoCube Consulting (Australia) Limited ACN 159 148 660 ********************************************************************************

**Comment by TheTracyL** [comment]
Hi John,

To fix the button you can use this code, it will make it the same blue color as your menu bar.

`.yikes-easy-mc-form .yikes-easy-mc-submit-button {
    background-color: #047aa8 !important;
}`

You have a few options to add CSS code:

<ul>
	<li>If you created this theme yourself, you can just add it to your style.css file</li>
	<li>If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file</li>
	<li>Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.</li>
	<li>You can use a plugin like <a href="https://wordpress.org/plugins/simple-custom-css/">Simple Custom CSS</a> or Jetpack and enter the code in their Custom CSS area</li>
</ul>

**Comment by EvanHerman** [comment]
Hi,

Unfortunately I don't know any one off the top of my head. There could be tons of reasons that your site has a javascript error on it. It could be the theme, it could be another plugin that you have running on the site or it could be some script someone wrote for you somewhere along the way.

The WordPress support forums are fairly helpful when it comes to this stuff, but I'm not sure they'll be able to tell you where or what file that error is in. Generally speaking, this is more of a theme developer question - unless of course it is another plugin causing the issue.

To test I would recommend that you disable your other plugins, and re-test.our plugin. If that still doesn't work, I would recommend leaving your plugins deactivated and then switching themes to something like TwentySixteen.

If the plugin begins to work, you can then re-enable plugins one at a time until you help pin point the issue.

If you are able to figure out what is causing the issue - you can post back here and we can take a closer look. If it is a theme issue, and the theme is a premium theme - I won't necessarily have a way to test as I don't have the premium theme on hand.


Evan

**Comment by jvoz** [comment]
Hi Tracy, I tried to add this into the style.css, just pasting at the end.  I then refreshed the browser and re-loaded, but it did not make any difference. Any thoughts would be muchly appreciated!  Thanks heaps, John



On 3 Feb 16, at 08:18, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi John,

To fix the button you can use this code, it will make it the same blue color as your menu bar.

.yikes-easy-mc-form .yikes-easy-mc-submit-button {
background-color: #047aa8 !important;
}

You have a few options to add CSS code:

  *   If you created this theme yourself, you can just add it to your style.css file
  *   If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
  *   Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
  *   You can use a plugin like Simple Custom CSS<https://wordpress.org/plugins/simple-custom-css/> or Jetpack and enter the code in their Custom CSS area

—
Reply to this email directly or view it on GitHub<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/431#issuecomment-178825903>.

******************************************************************************** This communication is intended only for use of the addressee and may contain legally privileged and confidential information. If you are not the addressee or intended recipient, you are notified that any dissemination, copying or use of any of the information is unauthorised. The legal privilege and confidentiality attached to this e-mail is not waived, lost or destroyed by reason of a mistaken delivery to you. If you have received this message in error, we would appreciate an immediate notification via e-mail to info@infocube.com.au or by phoning 1300 136 755, and ask that the e-mail be permanently deleted from your system. InfoCube Consulting (Australia) Limited ACN 159 148 660 ********************************************************************************

**Comment by TheTracyL** [comment]
Hi John,

I can't access the page with your form anymore. I'm getting a Not Found error.

Thanks,
Tracy

**Comment by jvoz** [comment]
Sorry. Changed the link. It's now at http://www.infocube.com.au/corporate-planning-information-form/

Sorry about that!

----------------------------
John Vaughan
Managing Director
InfoCube Consulting
t: 1300 136 755
m: 0418 634 652
e: john.vaughan@infocube.com.au<mailto:john.vaughan@infocube.com.au>
w: www.infocube.com.au<http://infocube.com.au>
----------------------------

On 5 Feb 2016, at 00:40, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi John,

I can't access the page with your form anymore. I'm getting a Not Found error.

Thanks,
Tracy

—
Reply to this email directly or view it on GitHub<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/431#issuecomment-179844990>.

******************************************************************************** This communication is intended only for use of the addressee and may contain legally privileged and confidential information. If you are not the addressee or intended recipient, you are notified that any dissemination, copying or use of any of the information is unauthorised. The legal privilege and confidentiality attached to this e-mail is not waived, lost or destroyed by reason of a mistaken delivery to you. If you have received this message in error, we would appreciate an immediate notification via e-mail to info@infocube.com.au or by phoning 1300 136 755, and ask that the e-mail be permanently deleted from your system. InfoCube Consulting (Australia) Limited ACN 159 148 660 ********************************************************************************

**Comment by TheTracyL** [comment]
Hi John,

Do you have a caching plugin on the site or does your host do caching?

There is a version number appended to your style sheet link and that version does not have the code in it. If I remove it, the button shows as it should:

![image](https://cloud.githubusercontent.com/assets/1252286/12828220/8597318a-cb51-11e5-894d-9791c04b40b0.png)

**Comment by jvoz** [comment]
Yeah. Sucuri. Might be time to ditch that!  Thank you Tracy.

----------------------------
John Vaughan
Managing Director
InfoCube Consulting
t: 1300 136 755
m: 0418 634 652
e: john.vaughan@infocube.com.au<mailto:john.vaughan@infocube.com.au>
w: www.infocube.com.au<http://infocube.com.au>
----------------------------

On 5 Feb 2016, at 07:14, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi John,

Do you have a caching plugin on the site or does your host do caching?

There is a version number appended to your style sheet link and that version does not have the code in it. If I remove it, the button shows as it should:

[image]<https://cloud.githubusercontent.com/assets/1252286/12828220/8597318a-cb51-11e5-894d-9791c04b40b0.png>

—
Reply to this email directly or view it on GitHub<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/431#issuecomment-180027878>.

******************************************************************************** This communication is intended only for use of the addressee and may contain legally privileged and confidential information. If you are not the addressee or intended recipient, you are notified that any dissemination, copying or use of any of the information is unauthorised. The legal privilege and confidentiality attached to this e-mail is not waived, lost or destroyed by reason of a mistaken delivery to you. If you have received this message in error, we would appreciate an immediate notification via e-mail to info@infocube.com.au or by phoning 1300 136 755, and ask that the e-mail be permanently deleted from your system. InfoCube Consulting (Australia) Limited ACN 159 148 660 ********************************************************************************

**Comment by TheTracyL** [comment]
Sucuri is pretty great, I wouldn't ditch them, but see if you can flush the cache and get the latest version of the style sheet.

**Comment by jvoz** [comment]
Woohoo!  Flushed and now the button works!  Yay, thanks heaps Tracy.  Now onto the JS errors…

John Vaughan
Managing Director



133 Alexander Street, Crows Nest NSW 2065
t: 1300 136 755 | m: 0418 634 652 | f: 02 9439 2738
john.vaughan@infocube.com.au<mailto:john.vaughan@infocube.com.au> | www.infocube.com.au<http://www.infocube.com.au/>

Accountants that specialise in business analytics.




On 5 Feb 16, at 07:28, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Sucuri is pretty great, I wouldn't ditch them, but see if you can flush the cache and get the latest version of the style sheet.

—
Reply to this email directly or view it on GitHub<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/431#issuecomment-180032557>.

******************************************************************************** This communication is intended only for use of the addressee and may contain legally privileged and confidential information. If you are not the addressee or intended recipient, you are notified that any dissemination, copying or use of any of the information is unauthorised. The legal privilege and confidentiality attached to this e-mail is not waived, lost or destroyed by reason of a mistaken delivery to you. If you have received this message in error, we would appreciate an immediate notification via e-mail to info@infocube.com.au or by phoning 1300 136 755, and ask that the e-mail be permanently deleted from your system. InfoCube Consulting (Australia) Limited ACN 159 148 660 ********************************************************************************

**Comment by TheTracyL** [comment]
WOOT!
