### ISSUE TITLE
Fields disappear when press 'update form' after adding them to form builder

### ISSUE THREAD

**Issue by WhitegateSC** [yikesinc/yikes-inc-easy-mailchimp-extender#432]
Hi there,
I have set up a sign up form and it is linking to my mailchimp list. When I go to add the fields to the form builder, the forms add OK to the form builder window but when I press 'update form' they disappear!
I have deleted the sign up form and added another one to see if that made a difference but unfortunately not.
Any help with this would be greatly appreciated.
Many thanks
Jo

**Comment by WhitegateSC** [comment]
Just thought I would try deactivating the plugin and reactivating - it worked! Panic over...

**Comment by EvanHerman** [comment]
Hey,

Thanks for keeping us updated on the issue, and very glad things are resolved and it wasn't anything larger at hand. 

It's possible the tables weren't created properly the first time the plugin was activated. 

If you run into any issues, feel free to reach back out. 

Thanks,
Evan
