### ISSUE TITLE
Pre Form text (and disclaimer text) does not work in the form customizer.

### ISSUE THREAD

**Issue by mcfarlandclan** [yikesinc/yikes-inc-easy-mailchimp-extender#434]
I've attempted to customize my subscription form by adding Pre Form text, but it never appears in my form. After saving and reloading the customize menu, the Pre Form text box is empty. Running WP 4.4.2

**Comment by TheTracyL** [comment]
Hi mcfarlandclan,

Can you please submit a premium ticket? Purchasing an add-on gives you access to our premium ticketing system.

Here are instructions on how to do that: https://yikesplugins.com/support/knowledge-base/how-do-i-get-premium-support/

Thank you!
-Tracy

**Comment by mcfarlandclan** [comment]
I would love to, but your premium ticketing system is not working. My license page shows a valid key, but when I submit a ticket I get an “Invalid License Key” response.

– Jeff

On February 2, 2016 at 1:37:33 PM, Tracy Levesque (notifications@github.com) wrote:

Hi mcfarlandclan,

Can you please submit a premium ticket? Purchasing an add-on gives you access to our premium ticketing system.

Here are instructions on how to do that: https://yikesplugins.com/support/knowledge-base/how-do-i-get-premium-support/

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Jeff,

If you have any problems with the form, send an email to the support address listed at the top of the page. This addresses is also listed in your purchase receipt email.

Thank you!
-Tracy
