### ISSUE TITLE
Invalid License Key

### ISSUE THREAD

**Issue by mcfarlandclan** [yikesinc/yikes-inc-easy-mailchimp-extender#435]
When trying to submit a support request through the Easy Form support form, I get an "Invalid License Key" response, even though my add-on settings page shows a "Valid Support License".

**Comment by EvanHerman** [comment]
Hi mcfarlandclan,

Feel free to shoot me an email at Evan@Yikesinc.com and I can take a look as to what the issue may be.


Thanks,
Evan

**Comment by TheTracyL** [comment]
You can send us an email using the support email listed in your email receipt and the top of the Support page. That will generate a premium support ticket.

Thank you!
-Tracy
