### ISSUE TITLE
Error : Dropbdown menu - Form

### ISSUE THREAD

**Issue by rpeladeau** [yikesinc/yikes-inc-easy-mailchimp-extender#436]
Hi, we have a form with dropdown selection in page : http://www.piecesdautostfrancois.com/club-carquest/, and the list of value doesn't show in the form. 
When we save the form in Wordpress, the field "Default selection become empty".

Thanks for your help,

![image](https://cloud.githubusercontent.com/assets/17047188/12784709/b4256a04-ca56-11e5-9d9c-e03df49a5c95.png)

**Comment by EvanHerman** [comment]
Hi rpeladeau,

Can you provide me with a list of possible options in that dropdown? It's possible that because it's in another language, some of the characters are being stripped - but I would like to do some testing on my end to be sure.


Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi rpeladeau,

Just checking in on this issue. Are you able to provide the info. Evan requested?

Let us know.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi rpeladeau,

We haven't heard from you on this issue, so I am going to close out the ticket.
If you need further help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
