### ISSUE TITLE
Error Creating Form

### ISSUE THREAD

**Issue by ascott7007** [yikesinc/yikes-inc-easy-mailchimp-extender#437]
Hey,

I'm trying to create my first sign up form using the Yikes Easy Forms for MailChimp plugin for WordPress. Unfortunately, I keep getting the following error message: 
Error Creating Form

Please try again. If the error persists please get in contact with the YIKES Inc. support team.

This error has continued for a while now, so I figured I should contact you. I look forward to your response.

**Comment by followde** [comment]
same here!

i like some help too please, thanks

**Comment by EvanHerman** [comment]
Hi,

Can you both please try to de-activate and re-activate the plugin? It's possible that the necessary tables weren't created the first time around.


Thanks,
Evan

**Comment by followde** [comment]
did it but i get the same messege

**Comment by EvanHerman** [comment]
What version of the plugin are you using? Is this a fresh install?

**Comment by followde** [comment]
i just installed it. yikes-inc-easy-mailchimp-extender.6.0.4

**Comment by EvanHerman** [comment]
On the settings page, can you try setting the debug settings to 'enabled' and trying to create a form again. Ideally, the error message will be a bit more descriptive after debugging is turned on - and will help us pin point what's going wrong.


Thanks,
Evan

**Comment by followde** [comment]
i am sorry, were can i the debug settings exactly? I tryed to find it in the settings page. sorry i am just a beginner.

**Comment by EvanHerman** [comment]
Have a look at the following knowledge base article on locating the debug settings page:
https://yikesplugins.com/support/knowledge-base/debug-settings/


Evan

**Comment by followde** [comment]
ok thanks.

**Comment by followde** [comment]
now i get: Column 'list_id' cannot be null

**Comment by EvanHerman** [comment]
When you are creating the form, in the right hand column - are you selecting a list from the '**Associated List**' dropdown?

https://yikesplugins.com/support/knowledge-base/creating-forms/ - the second step down "Create a Form".


Evan

**Comment by ascott7007** [comment]
I've done the steps you described above, but it says that there are no lists found on the account (although I've already created lists for my account). I've reloaded after creating a list, but this does not change.

**Comment by EvanHerman** [comment]
Hi ascott7007,

If you created the lists after you initially installed the plugin, you may need to clear out your sites MailChimp cache (stored by this plugin).

Follow along with the directions here for clear instructions on how to do so:
https://yikesplugins.com/support/knowledge-base/api-cache-settings/

After the cache is cleared, you should then see the MailChimp lists you have setup on your account.


Evan

**Comment by TheTracyL** [comment]
Hi ascott7007,

Just checking in on this. Were you able to resolve the issue?
We have a knowledgebase article related to this: https://yikesplugins.com/support/knowledge-base/im-not-seeing-all-my-lists-on-the-drop-down-menu-when-i-go-to-make-a-new-form/

Thank you!
-Tracy

**Comment by followde** [comment]
Hello Tracy, i solved it thanks to the videos on your website. Thank you
very much for your help.

Isabel
Op 10 feb. 2016 17:27 schreef "Tracy Levesque" <notifications@github.com>
het volgende:

**Comment by TheTracyL** [comment]
Yay! I'm so glad you were able to get things working.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make a plugin developer's day :-)

Thank you!
-Tracy
