### ISSUE TITLE
Newsletter Title 

### ISSUE THREAD

**Issue by Dorothy2305** [yikesinc/yikes-inc-easy-mailchimp-extender#438]
I have previously had Easy Forms for Mailchimp installed with no problems.  During some modifications to the site, the plug-in was uninstalled and later re-installed, meaning I had to go through the set-up process again.   Now, this is what is displayed on my form and I cannot figure out how to get rid of the displayed coding.
![image](https://cloud.githubusercontent.com/assets/17134647/12906537/220d2df2-cf31-11e5-8773-24d8ca40ef75.png)

Any suggestions?
Dorothy

**Comment by TheTracyL** [comment]
Hello Dorothy,

Can you please provide a link to your form so I can take a look?

Thank you!
-Tracy

**Comment by Dorothy2305** [comment]
Hi Tracy

 

http://www.worklifejunction.com.au/offer1/

 

Do you need a link to the back end?

 

Dorothy

**Comment by Dorothy2305** [comment]
If you need the back-end link try this.

http://www.worklifejunction.com.au/wp-admin/

 

Dorothy

**Comment by TheTracyL** [comment]
Hi Dorothy,

Do you have reCAPTCHA turned on and configured for this widget? 

As a troublehshooting step, can you try un-enabling reCAPTCHA and see if the code is still there?
Here are instructions: https://yikesplugins.com/support/knowledge-base/recaptcha-settings/

Thank you!
-Tracy

**Comment by Dorothy2305** [comment]
Bingo!

 

De-selecting the reCAPTCHA did the trick.

 

Cheers

Dorothy

**Comment by TheTracyL** [comment]
Yay! So glad I was able to get things working for you.

Have a good day!
-Tracy
