### ISSUE TITLE
Getting "undefined" message in green box above form

### ISSUE THREAD

**Issue by MarkatBaker** [yikesinc/yikes-inc-easy-mailchimp-extender#440]
Hello! I am sometimes getting an "undefined" message in green box above the form after submissions. 
The form is on the sidebar on http://shannoncornish.com.au/ 
But subscribers are added OK... Any idea why?
Mark

![screen shot 2016-02-11 at 11 55 43 am](https://cloud.githubusercontent.com/assets/17170600/12967983/e6f0d69c-d0bb-11e5-865a-754678cc9748.png)

**Comment by EvanHerman** [comment]
Hi MarkatBaker,

Are you using the forms as an ajax form or non-ajax form? Also, what is the setting that you have setup inside of the custom messages on the edit form page?

https://yikesplugins.com/support/knowledge-base/custom-form-messages/

Thanks,
Evan

**Comment by MarkatBaker** [comment]
I did have the default messages, and inserted slightly customised ones earlier to see if that helped... It didn't.
Have now disabled AJAX sunmission and now seems to be working OK :) Thanks!

**Comment by MarkatBaker** [comment]
Can you explain why that was happening? :)

**Comment by EvanHerman** [comment]
Hey Mark,

I'm not entirely sure why that would be happening - other than the javascript variable containing the success message is conflicting with another plugin that you have installed.

I have been working on a  6.0.4.1 update, and am going to refactor some of this code to hopefully prevent this issue moving forward. I'm not entirely sure of a release date, but I am working diligently on getting some additional issues resolved for our users.


Thanks,
Evan

**Comment by MarkatBaker** [comment]
The text is almost the same as what was in there by default... And the issue was happening BEFORE i did that. Great too see you are actively improving this excellent product.

**Comment by TheTracyL** [comment]
Thank you so much. 

I am going to close out this ticket, because Evan is actively working on it.

Have a good day!
-Tracy
