### ISSUE TITLE
email notification of subscription

### ISSUE THREAD

**Issue by roxan37** [yikesinc/yikes-inc-easy-mailchimp-extender#444]
I just don't see where I can activate an email notification to my own email address when someone subscribes on my list.

**Comment by TheTracyL** [comment]
Hi Roxan,

Notifications are set up on your MailChimp account, not our plugin.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Please check out this thread for more info: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/403
