### ISSUE TITLE
Plugin only shows shortcode

### ISSUE THREAD

**Issue by JesperDramsch** [yikesinc/yikes-inc-easy-mailchimp-extender#445]
Hello,

the plugin sometimes will not show and display the shortcode instead.

Example: https://the-geophysicist.com/big-data-in-oil-and-gas-fuzzy-classification

How can I troubleshoot / fix this?

**Comment by EvanHerman** [comment]
Hi JesperDramsch,

Is the plugin installed and active right now? I am only seeing the shortcode.

Do you have any caching plugins installed or anything that may be referencing an old version of some files before you installed the plugin?


Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi Jesper,

Also, did you use our widget that comes with the plugin or did you enter a shortcode into a text widget? Shortcodes don't work in widgets by default. Please check our our KB article **[Adding Forms to Sidebars and other Widgetized Areas](https://yikesplugins.com/support/knowledge-base/adding-forms-to-sidebars-and-other-widgetized-areas/)
**

Thank you!
-Tracy

**Comment by JesperDramsch** [comment]
The plugin is installed and active. I used the widget not a shortcode.

W3C Total Cache is running in conjunction with cloudflare. The caches have been emptied though.

**Comment by EvanHerman** [comment]
Hi Jasper,

There is no reason that the shortcode shouldn't be working.

What theme are you running? Can you try temporarily switching to an alternate theme and trying again?


Thanks,
Evan

**Comment by JesperDramsch** [comment]
I think the 6.4.0.2 update fixed it.

Sorry for the bother.

**Comment by TheTracyL** [comment]
Awesome, I'm glad it's working.

Have a good day!
-Tracy
