### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by Garnet2086** [yikesinc/yikes-inc-easy-mailchimp-extender#446]
Hi

The plugin spits out this error after being updated. Used to appear nicely in my page's footer.

Warning: Missing argument 2 for yksemeProcessSnippet(), called in /home/lmv/public_html/wp-content/themes/landmark/footer.php on line 41 and defined in /home/lmv/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/helpers.php on line 14
Oh no...This form doesn't exist. Head back to the manage forms page and select a different form.

Snippet of code on line 42 in the footer is:  <?php echo yksemeProcessSnippet('fd9d7324f6'); ?>

My Newsletter form's shortcode​ is: [yikes-mailchimp form="1"]

**Comment by Garnet2086** [comment]
I also cannot edit the forms anymore, goes to a blank page. Creating a new form and attempting to edit yields the same error, goes to a blank page. Have also tried, deactivating the plugin, deleting and re-adding.

**Comment by EvanHerman** [comment]
Hey Garnet,

What version of the plugin are you currently using?

Did you check out the two URLs that I sent over that should help with the issue?
https://yikesplugins.com/support/knowledge-base/upgrading-to-version-6-performing-the-upgrade/
https://yikesplugins.com/support/knowledge-base/upgrading-to-version-6-troubleshooting/

The snippet <?php echo yksemeProcessSnippet('fd9d7324f6'); ?> no longer works in the newer versions, and should instead be updated to `<?php echo do_shortcode( '[yikes-mailchimp form="1"]' ); ?>` or whatever the form ID is that you would like to display.

If this is an upgrade from an earlier version, did you go through the upgrade process? 


Thanks,
Evan

**Comment by Garnet2086** [comment]
I've tried changing the snippet in the footer.php and doesn't seem to work, breaks my entire footer's structure. I am not sure if the user who upgraded went through the proper upgrading path outlined in the article. Let assume that it wasn't done, how do we fix.

**Comment by EvanHerman** [comment]
If the snippet that I provided is breaking your sites footer, than there is most likely a larger issue at hand. The snippet I provided above, shouldn't break anything as it is properly formatted.

Are you sure that you are adding it to the correct location? If your nesting `<?php` tags you're going to run into issues.

If the proper upgrade path was not taken, you'll need to uninstall and re-install the plugin from scratch. If you only need to setup one form, it shouldn't take too long to go this route, and may be the best course of action.


Evan

**Comment by Garnet2086** [comment]
So it looks like the snippet works however I get the following error now:

Warning: Invalid argument supplied for foreach() in /home/lmv/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 155
Whoops, it looks like you forgot to assign fields to this form.

I also cannot edit the form, still goes to blank page.

**Comment by Garnet2086** [comment]
Forgot to add the snippet of code on lne 155 in process_form_shortcode.php:

	// loop over each field, if it's set to hidden -- subtract it from the field count
	// this throws off the layout for inline forms setup below
	foreach( json_decode( $form_data['fields'] ) as $form_field ) {
		if( isset( $form_field->hide ) && $form_field->hide == 1 ) {
			$field_count--;

**Comment by EvanHerman** [comment]
Can you try uninstalling and re-installing the plugin. You shouldn't need to edit any of the code in any of the template files.


Evan

**Comment by Garnet2086** [comment]
Same error after uninstalling and re-installing the plugin.

**Comment by Garnet2086** [comment]
Any ideas. Maybe you want to poke around the site?

**Comment by EvanHerman** [comment]
What version of PHP is your site running? This error should not be occuring, and is not something that I can reproduce on my end.


Evan

**Comment by TheTracyL** [comment]
Hi Garnet,

We've pushed out a couple updates since you opened this ticket.

Are you still experiencing the same problems?

Thank you!
-Tracy

**Comment by Garnet2086** [comment]
Yes. Still the same issue.

**Comment by TheTracyL** [comment]
Hi,

Checking in on this again. When you uninstalled and re-installed, did you try totally starting over from scratch? Like entering the API key and rebuilding the form? 

Thank you!
-Tracy
