### ISSUE TITLE
 Column 'list_id' Cannot Be Null 

### ISSUE THREAD

**Issue by dusanantonijevic** [yikesinc/yikes-inc-easy-mailchimp-extender#448]
I've just installed this plugin and trying to create my first list but getting this error: 

" Column 'list_id' Cannot Be Null 	Page: Forms || Type: Creating a new form || Time: 17.02.2016. 19:07 "

How to fix this? I've made no modifications to plugin or WP files.

**Comment by EvanHerman** [comment]
Hi dusanantonijevic,

When you are creating your form, you'll want to ensure that you have selected a form from the 'Associated List' dropdown.

https://yikesplugins.com/support/knowledge-base/creating-forms/

If you have created a list or two, but your not seeing them display in that dropdown - you may need to clear your sites MailChimp API cache (which is essentially the mailchimp data stored on your site temporarily, increase performance. If you don't clear the cache, it auto clears after 1 hour).

For help with completing that task, feel free to check out our knowledge base article on the topic:
https://yikesplugins.com/support/knowledge-base/api-cache-settings/



Thanks,
Evan

**Comment by EvanHerman** [comment]
Hi dusanantonijevic,

Due to inactivity I am going to close out this issue. If you still require assistance, feel free to post back here.


Thanks,
Evan
