### ISSUE TITLE
Dismissed migration dialogue to version 6

### ISSUE THREAD

**Issue by gtolman** [yikesinc/yikes-inc-easy-mailchimp-extender#449]
Well, I went and accidentally dismissed the button to migrate my Easy Forms for MailChimp data from version 5 to 6.  It now does not work because it's version 6 with version 5 data.  

Does anyone know how to get the migration option back or to manually kick it off?

I appreciate the help.

**Comment by EvanHerman** [comment]
Hey gtolman,

I'm not entirely sure as the upgrade checks for a nonce being passed in for security purposes. I'm not sure once things are disabled if your going to be blocked from updating. You can try accessing the update page by going to the following page from your dashboard:

siteurl.com/wp-admin/admin.php?page=yikes-inc-easy-mailchimp-update


Thanks,
Evan

**Comment by TheTracyL** [comment]
Hello.

How many forms do you have? Like Evan mentioned above, the worst case scenario is you will need to uninstall then reinstall the plugin. It is very quick to set up new forms. We have a video showing how to do it in 90 seconds: https://youtu.be/NRZbW-Da1XA

I hope you're able to get your forms up again.

If you need further help, please reopen this ticket.

Thank you!
-Tracy

**Comment by gtolman** [comment]
Thank you for the help.  The update link says I need the api key.  I wasn't the original admin so I don't know how the form was setup prior.  I'll try to get the MailChimp login from the prior admin so I can recreate it.
