### ISSUE TITLE
Optin Settings Problem for Subscriber Updates

### ISSUE THREAD

**Issue by aschaevitz** [yikesinc/yikes-inc-easy-mailchimp-extender#450]
I have had Easy Forms for MailChimp implemented successfully for some time. I have been waiting until you supported 2-factor authentication for subscribers doing updates before I set the Optin Setting "Update Existing Subscriber" to "yes". It appears that you implemented that feature in the latest release (6.0.4.1), so I changed the setting. However, I continue to get the "already subscribed" message when I tested the feature. It seems that changing the setting had no effect. Could you give me some advice? The specific form page on my website is:
http://sprcoalition.org/support/signup/

Thanks,
Alan Schaevitz

**Comment by EvanHerman** [comment]
Hi Alan,

Nice to see you back around the forums - it's been quite some time!

Are you running any sort of caching on the site? The 'Already Subscribed' message should now read "It looks like you're already subscribed to this list. To update your proile please click here", where 'click here' is a link to send off the update email.

I will give your form a try and see what happens on my end.


Thanks,
Evan

**Comment by EvanHerman** [comment]
Any chance you can try setting the form to AJAX - to see if that helps alleviate the issue?


Thanks,
Evan

**Comment by EvanHerman** [comment]
Hey Alan,

I just set up a test instance on my end, and I was actually able to reproduce the issue - but only when I had 'Debug' turned on from the settings page. If you have that turned on, I would recommend disabling that setting and then testing again. With debug turned on your only going to see success/error messages returned by the MailChimp API.

Here is a knowledge base article we have setup to help illustrate what I am referencing and to walk you through the process.

https://yikesplugins.com/support/knowledge-base/debug-settings/



Thanks,
Evan

**Comment by aschaevitz** [comment]
Hi Evan,

Haven’t bugged you on the 2-factor feature for updaters because I understood it was low priority but was on your to-do list. So, I was content to wait.

The Debug setting was the key to the problem. However, while I now get the "It looks like you're already subscribed to this list. To update your profile, please click here.” message, nothing happens when I click on “click here” link.
____
Alan

**Comment by EvanHerman** [comment]
Hi Alan,

I just had a deeper look into the issue on my end, and I can visibly see what the issue is.

The .js file to trigger the email send was not properly added to the repo.

Give me about 30 minutes and I'll have a 6.0.4.2 patch out that should resolve things for you. Most of our users prefer the AJAX forms, so we were not yet aware of the issue.



Evan

**Comment by EvanHerman** [comment]
Hi Alan,

v6.0.4.2 should be up in the repo. I've done some testing on my end and things seem to be working ok now.

Please let us know the outcome, after you update to the latest release.


Thanks,
Evan

**Comment by aschaevitz** [comment]
Just did the update to the plugin and it works perfectly! Thank you so much, both for providing this feature and for so promptly dealing with this problem. I am delighted with the result.

Regards,
____
Alan

**Comment by TheTracyL** [comment]
Awesome! I'm so glad it's working for you, you were the most tenacious advocate for this feature.

Thank you for testing and providing feedback so we were able to iron out the bugs. We really appreciate it.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make a our day :-)

Thank you!
-Tracy

**Comment by aschaevitz** [comment]
Delighted to leave a glowing review. 

Alan Schaevitz
