### ISSUE TITLE
New Subscriber Notification

### ISSUE THREAD

**Issue by jlaw77** [yikesinc/yikes-inc-easy-mailchimp-extender#451]
Just checking to see if Mailchimp still requires I provide new subscribers with a double opt-in in order to receive a new subscriber notification. 

I use this as a contact us form on our website for general info/pricing requests. Id like someone to be able to ask a simple question without having to opt-in twice and i want to be able to answer that question as soon as possible. they may not want to double opt in and so i lose out on potential business.

any ideas on how i can provide a contact us form on our wordpress site, get notified instantly when someone submits and do it all without double opt-in?

Thank much!

**Comment by EvanHerman** [comment]
I would recommend using one of the 7 integrations we've included in our plugin, and adjusting the optin settings for that integration via the provided filters. 

Take a look at issue #433 . Towards the bottom of the page you'll find a block of code that allows you to toggle the integration for contact form 7 from double optin to single optin.

https://yikesplugins.com/support/knowledge-base/integration-settings/

```php
/**
*   Alter the API parameters for a given integration
*   Note: The following snippet sets the woocommerce integration to single optin    
*/
function YIKES_third_party_integration_filter( $api_params, $integration ) {
    if( $integration_type == 'contact_form_7' ) {
        $api_params['double_optin'] = 0;
    }
    return $api_params;
}
add_filter( 'yikes-mailchimp-checkbox-integration-subscribe-api-request', 'YIKES_third_party_integration_filter' );
```

Thanks!
Evan

**Comment by TheTracyL** [comment]
Hello.

According to MailChimp's article: http://kb.mailchimp.com/lists/managing-subscribers/change-subscribe-and-unsubscribe-notifications
> Lists must be set to double opt-in to trigger a subscription notification. 

Evan's suggestion of using Contact Form 7 is a great work-around. You can set Contact Form 7 to send you a notification and use Evan's code to make the MailChimp opt-in via our plugin Single opt-in.

If are not comfortable editing the functions.php file of your active theme, you can use this plugin https://wordpress.org/plugins/my-custom-functions/

If you need further help, please reopen this ticket.

Thank you!
-Tracy
