### ISSUE TITLE
Request Support for setting default country on Address Field

### ISSUE THREAD

**Issue by GrahamBruno** [yikesinc/yikes-inc-easy-mailchimp-extender#452]
Please could you consider support for setting a different default country on the mailchimp address field type?

At present the address field by default sets the country to United States. I am looking to operate a mailchimp mailing list in the United Kingdom and would like to implement a form where the country is set to United Kingdom by default.

Many thanks.

**Comment by TheTracyL** [comment]
Thank you, we love new requests -- especially to support better Internationalization.

Evan will look into these and get back to you.

-Tracy

**Comment by GrahamBruno** [comment]
Thank you for your quick response Tracy. Look forward to hearing from you guys in due course.

**Comment by EvanHerman** [comment]
Hi GrahamBruno,

We've just gone ahead and pushed out a 6.0.4.3 release, which now includes a new filter ``. This new filter allows you, as the site owner, to specify which value you want pre-selected as the default country.

I've gone ahead and setup a knowledge base article explaining how to carry out the task:

https://yikesplugins.com/support/knowledge-base/how-can-i-change-the-default-country-from-the-united-states-to-something-else-in-the-address-drop-down/

You'll want to add the snippet in that article to the bottom of your themes functions.php file. I've gone ahead and setup the example snippet for your use case - so you should have no problems simply copying over the snippet into your theme.

Let us know if you need help implementing that snippet, or if you run into any issues.

Thanks again for your suggestion!



Evan

**Comment by GrahamBruno** [comment]
Hi Evan,

Thanks for incorporating this suggestion into your latest release. I can confirm that adding this code to functions.php does indeed bias the address field to show United Kingdom.

I would consider this specific feature to be fully working. There are issues with the Post Code addressed which I have described in the other open issue. That notwithstanding, I would reckon this particular item can be closed!

Thanks again!

Graham
