### ISSUE TITLE
Request support for Post Code field on UK addresses

### ISSUE THREAD

**Issue by GrahamBruno** [yikesinc/yikes-inc-easy-mailchimp-extender#453]
At present when selecting United Kingdom as country on the address field the following address lines are given...

- Address
- Address 2 
- City

Please could a dedicated field for Post Code be added?

Many thanks.

**Comment by EvanHerman** [comment]
Hi GrahamBruno,

We just pushed out a 6.0.4.3 release, which should now include the Zip/Postal Code field when the United Kingdom is selected from the country dropdown.

Give things an update and let us know if things are working properly on your end.


Thanks,
Evan

**Comment by GrahamBruno** [comment]
Hey Evan and Tracy,

Firstly thank you for listening to my requests and for acting so quickly, you guys are awesome. I have tested the functionality and can advise of two outstanding issues (at least as they relate to the United Kingdom)...
  
1. The field appears with the label Zip rather than "Post Code". I would recommend if possible changing the label to either "Post Code" or use "Zip / Post Code" and that way you are covered for any country. (Minor - A polish point)

2. Users cannot fill in a Post Code in the Zip box that appears since  it fails validation which expects quote.. "a 5 digit zip code, numbers only". UK Post Codes are up to 6 characters (usually rendered with a space in between e.g. SW1A 1AA)

**Comment by EvanHerman** [comment]
Hi Graham,

Using some of the built in filters this can easily be achieved, similar to what we provided above.

You can use the following two snippets to alter things to your needs:

```php
/**
*	Change the 'Zip' field label to 'Postal Code' (beneficial for UK residents)
*	@reference: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/453
*/
function yikes_mailchimp_change_zip_label_to_postcode( $field_label ) {
	return 'Postal Code';
}
add_filter( 'yikes-mailchimp-address-zip-label', 'yikes_mailchimp_change_zip_label_to_postcode' );
```

The next step is to alter the regex pattern used to validate the zip/postal code fields. The easiest way to do this is to remove the regex pattern altogether with the following snippet:

```php
/**
*	Completley remove the regex patter for validating zip codes
*	@reference: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/453
*/
function yikes_mailchimp_remove_zip_regex_pattern( $regex_pattern ) {	
	$regex_pattern = '';
	return $regex_pattern;
}
add_filter( 'yikes-mailchimp-zip-pattern', 'yikes_mailchimp_remove_zip_regex_pattern' );
````

When used together, I think you'll find that the 'Zip' (now postal code) field should be working just as you anticipated it would.

Let us know if the above two snippets help out.


Thanks!
Evan

**Comment by GrahamBruno** [comment]
Hi Evan,

I can confirm that this has worked. Many thanks again for your help!

Kind Regards,


Graham

**Comment by TheTracyL** [comment]
Awesome! I'm so glad we were able to provide a solution for you. 

Have a good weekend!
-Tracy

**Comment by GrahamBruno** [comment]
Thanks! You too!

**Comment by GrahamBruno** [comment]
Hello,

Sorry to trouble you again on this issue. I have the code you provided below inserted into the functions.php file of my child theme. 

`/**
*   Completley remove the regex patter for validating zip codes
*   @reference: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/453
*/
function yikes_mailchimp_remove_zip_regex_pattern( $regex_pattern ) {   
    $regex_pattern = '';
    return $regex_pattern;
}
add_filter( 'yikes-mailchimp-zip-pattern', 'yikes_mailchimp_remove_zip_regex_pattern' );`

My initial impression was that this had removed the check and a few users have been able to sign up to my Event Promoters mailing list at 

http://christiandiary.com/sign-up 

I have however had a couple of folks come back to me however saying that they are still running into the check. The one thing they had in common was that they were all using Google Chrome on the desktop. I have tried Edge, Internet Explorer on my PC and Safari & Chrome on my ipad and did not encounter the validation check on the zip / postal code on any of these platforms. I did still encounter the check when using Google Chrome on the desktop. Could there be an issue with this browser? 

The check still came up even after clearing my cache or using Incognito mode.

Please could I ask if you could try filling in the Event Promoters form with a UK address and submitting it using Chrome on the desktop and also with another browser to see if you encounter the same issue? (If you do manage to submit the form during your testing it's double opt-in so any submission you make won't get added to the list unless you confirm the email.)

Many thanks in advance for your time.

Graham

**Comment by EvanHerman** [comment]
Hi Graham,

You are correct - it looks like I'm running into an issue on chrome as well.

Try the following, which should accept <b>all</b> values in the postal code field:

```php
/**
*   Completley remove the regex patter for validating zip codes
*   @reference: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/453
*/
function yikes_mailchimp_remove_zip_regex_pattern( $regex_pattern ) {   
    $regex_pattern = '[\s\S]*';
    return $regex_pattern;
}
add_filter( 'yikes-mailchimp-zip-pattern', 'yikes_mailchimp_remove_zip_regex_pattern' );
```

I was able to add `[\s\S]*` to the pattern="" parameter of the postal code field in my browser, and your form appeared to be working without any issues.

Go ahead and update the snippet to what I have above, and things should work properly for you.


Thanks!
Evan

**Comment by GrahamBruno** [comment]
Hi Evan,

Thanks for providing this code. Initial tests are promising. Would it be possible to incorporate into the roadmap for your main code-base something that drops the checks on non US addresses? Additionally, the capability to set the default country from within the UI would be useful. I appreciate that your code snippits have got me up and working. The fact that this code change is essentially required to get all non-US submissions to work would suggest that code that enforces zip code validation on US addresses, validates post codes for other countries according to the convention for that country (or at least gets out the way) would be worthwhile incorporating into your main code-base. Providing the ability to set the default address country within the settings UI for the plugin may also be a useful incorporation to reduce barriers to entry for potential users.

Thanks again.

Graham

**Comment by EvanHerman** [comment]
Hi Graham,

I can take a look, but as you can already tell, the edit form page is quite crowded with options as is. We're trying to keep the options down to a minimum, as to not overwhelm the user.

I'll take a look and see what we can come up with in future updates in terms of setting a default country.

In terms of the pattern, I'll certainly include that in our road map, so when user selects UK the regex pattern on the input field is also updated.

I can get that in the next release.


Evan
