### ISSUE TITLE
change background of text area

### ISSUE THREAD

**Issue by aimes555** [yikesinc/yikes-inc-easy-mailchimp-extender#454]
Hi, I feel like I've tried a million things and nothings worked. I want to change the background color of the text area to be white not grey. You can see my form in the footer of my site here: [amynicolestudio.com](url) 

I was able to change the background color of the submit button but cant for the life of me figure out the css to change the color of the text area.

Thanks

**Comment by TheTracyL** [comment]
Hi Amy,

This code should make the fields white:
```
.yikes-easy-mc-form input[type="text"], .yikes-easy-mc-form input[type="url"], .yikes-easy-mc-form input[type="email"], .yikes-easy-mc-form input[type="number"], .yikes-easy-mc-form select {
    background-color: #fff;
}
```

You have a few different options for adding this CSS code.

<ul>
 <li>If you created this theme yourself, you can just add it to your style.css file</li>
 <li>If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file</li>
 <li>Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.</li>
 <li>You can use a plugin like <a href="https://wordpress.org/plugins/simple-custom-css/">Simple Custom CSS</a> or Jetpack and enter the code in their Custom CSS area</li>
</ul>

Let me know if you have further questions!
-Tracy

**Comment by aimes555** [comment]
Thanks so much for your quick response. I pasted the code into my style.css file of my theme and it still didn't work :( Is there something else I can try?  


~AmyAmyNicoleStudio.com

...He is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us...
Ephesians 3:20-21 

    On Sunday, February 21, 2016 9:56 AM, Tracy Levesque <notifications@github.com> wrote:
 

 Hi Amy,This code should make the fields white:.yikes-easy-mc-form input[type="text"], .yikes-easy-mc-form input[type="url"], .yikes-easy-mc-form input[type="email"], .yikes-easy-mc-form input[type="number"], .yikes-easy-mc-form select {
    background-color: #fff;
}
You have a few different options for adding this CSS code.   
   - If you created this theme yourself, you can just add it to your style.css file
   - If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
   - Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
   - You can use a plugin like Simple Custom CSS or Jetpack and enter the code in their Custom CSS area
Let me know if you have further questions!
-Tracy—

**Comment by TheTracyL** [comment]
Try this:

```css
.yikes-easy-mc-form input[type="text"], .yikes-easy-mc-form input[type="url"], 
.yikes-easy-mc-form input[type="email"], .yikes-easy-mc-form input[type="number"], 
.yikes-easy-mc-form select {
    background-color: #fff !important;
}
```

**Comment by aimes555** [comment]
IT WORKED!!!! thank you thank you thank you!  


~AmyAmyNicoleStudio.com

...He is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us...
Ephesians 3:20-21 

    On Sunday, February 21, 2016 4:45 PM, Tracy Levesque <notifications@github.com> wrote:
 

 Try this:.yikes-easy-mc-form input[type="text"], .yikes-easy-mc-form input[type="url"], 
.yikes-easy-mc-form input[type="email"], .yikes-easy-mc-form input[type="number"], 
.yikes-easy-mc-form select {
    background-color: #fff !important;
}—

**Comment by TheTracyL** [comment]
Woot!

I'm so glad I was able to help you out with that.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make a plugin developer's day :-)

Thank you!
-Tracy
