### ISSUE TITLE
Adding Name to thanks message

### ISSUE THREAD

**Issue by improve21** [yikesinc/yikes-inc-easy-mailchimp-extender#455]
Hi. I was thinking I might like to include the name in the thank you for subscribing message after someone hits the submit button, using the name provided in the signup form (we have the name field included on the form).

Perhaps there is a hook for this? eg:
"Thanks for subscribing [name here], please check your inbox...."

**Comment by EvanHerman** [comment]
Hi Improve21,

I can certainly see the benefit in such a feature. I am currently working on building some filters in to allow you to filter the success response, and use the submitted data in the response.

I will be pushing out an update today, and creating a knowledge base article on how to achieve what you are after.

Thanks for the suggestion!


Evan

**Comment by EvanHerman** [comment]
Hi Improve21,

I've gone ahead and pushed out a 6.0.4.3 release which now includes the necessary functionality to carry out what you are after.

I've gone ahead and setup a knowledge base article to help you through the process:
https://yikesplugins.com/support/knowledge-base/alter-the-success-message-when-a-user-subscribes-to-a-list/

Give things a try and let us know how they work out on your end.


Thanks!
Evan

**Comment by improve21** [comment]
Hi Evan,

 

I appreciate you taking my request as having some value and updating your scripts.

I have updated to your latest version.

 

However, the how-to page wasn't too clear for me and I can't make it work. Here's what I have tried:

 

1) in the custom messages area box, I tried using the following codes after "thanks for subscribing...," 

- $merge_vars[‘FNAME’]

- $merge_vars['FNAME']

- [FNAME]

- [‘FNAME’]

- ['FNAME']

None of these worked. They just showed what I entered above.

 

2) Then I thought perhaps if I remove my custom message and left it blank that it would auto show up as per the sample code you showed on your how-to page, which should be in some file somewhere.  It didn't work either.

 

3) Then I thought maybe it only works if I specifically edit the file for which you showed an example code on the how-to page. I can't find the relevant page, even doing a keyword search thru your folders.

 

However, my preference would be to be able to make my changes in edit custom message box, rather than from within a file, because it means that every time I want to change the message, I have to edit the relevant php file, then keep a backup copy of it so that future updates don’t overwrite my edits. And then having to remember to check for that each time I update your plugin (long process). 

It would be easier to simply make changes in the custom message box, using relevant code inserted where I want my mc fields to display. That would then make the custom message box not "redundant". eg, in the custom message box I would put:

Thanks blah blah [code for desired mc field], blah blah.

 

Is there a way I could do that?

 

If not, and I really do need to edit a file directly, then please point me to which file needs editing so that I can make sure only the first name field displays (although this may change in the future).

 

Thanks again for taking the time to update your program.  It's just the useage that is unclear.

 

Regards,
Janara

**Comment by TheTracyL** [comment]
Hi Improve21,

The code Evan provided in the article would go in the `functions.php` file of your active theme.

If are not comfortable editing the functions.php file of your active theme, you can use this plugin https://wordpress.org/plugins/my-custom-functions/

Thank you!
-Tracy

**Comment by improve21** [comment]
Thanks, that worked. 
It may be worth including that instruction in the how-to article, for those of us who aren't automatically aware.

I also like the plugin you suggested. That is way better a solution and I have downloaded it and will use it from now on, because I have come across many instances where I should edit the functions.php file and I resist doing it.  This plugin will eliminate fear of adding wrong code and mucking things up, plus don't have to worry about what happens when updating or switching themes.
Thanks for your swift response.

**Comment by TheTracyL** [comment]
Awesome! I'm so glad it worked for you!

Thank you for the feedback on clarifying where to put the code exactly. I will go through our snippet articles and make sure that is more clear.

I'm also happy that I was able to introduce you to a new, helpful plugin. I realize folks may not want to edit files directly, and if they are not using a Child Theme, there is danger of an edited file being wiped on on the next theme update. That plugin makes sure the theme in use is not modified.

If you're enjoying our plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make a plugin developer's day :-)

Best wishes for your website!
-Tracy

**Comment by improve21** [comment]
Done!

**Comment by improve21** [comment]
Hi again.

 

I see my topic has been closed now.  However, I have just discovered another little issue.

 

I have a newsletter page, and I added the shortcode to the page, and that works fine where the name field gets inserted in the success message.

 

But I also have a signup form in the sidebar and another in the bottom footer. I have created separate forms for all of these - 3 in all - one for the page, 1 for the sidebar, and 1 for the footer. The sidebar and the footer are widgets. And the widgets don't offer a spot to add "shortcode", instead they just display a dropdown list of which you pick which form you want.

 

Really, the only difference between the form that is on the newsletter page (with the shortcode) and the other two that are in widgets is that for the widgets forms I chose to close the signup form after submission (to save space in those spots).

 

It is these two which won't include the name field in the success message. I don't know what the difference is because they are still choosing from a form.

 

Any suggestions?

**Comment by TheTracyL** [comment]
Hi!

This part:
`php
if( $form_id == 1 ) {`

Says "if it's form ID 1 then show the custom message"

You may be able to put an array (list) of IDs in there. Evan can take a look and let you know later today.

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Hi Improve21,

To answer your first inquery, to carry out this task there is no easy non-code way to handle things. While the FNAME value may be a value in your form, it's not going to be a merge variable in ALL forms. So what works for you may not work for another user.

Moving forward, I can certainly look into adding the merge tags as available tags in the success message - so if you wanted to display the users first name, you could use a merge tag shortcode `[FNAME]` for example. If you change your merge variable name, this method will no longer work.

I can foresee this as being both beneficial and something that shouldn't be too challanging to carry out, but is going to have to be something we incorporate in the next iteration of the plugin.

In regards to the widgets, the form in the widgets don't actually have any additional settings, such as redirect, hide on submit etc.

We can provide some sort of filter that would allow you to add additional parameters to the widget form - but again this would involve a bit of coding on your end and not something that is exactly user friendly.

The next best solution would be to use a standard WordPress text widget, and enter the short code into that widget eg: `[yikes-mailchimp form="1"]`. Not all themes support the use of short codes in the widget areas, so you may need to enable it on your site.

When I first began with WordPress, this article helped me to enable the functionality needed to add shortcodes in the built in text widget: http://www.wpbeginner.com/wp-tutorials/how-to-use-shortcodes-in-your-wordpress-sidebar-widgets/

Once you enable it, you can simply drop the shortcode into the widget area, and all of the form settings (redirect, hide, double optin, single optin etc.) will all effect the form in the widgets.


Thanks,
Evan

**Comment by improve21** [comment]
Hi Evan, 

 

Thanks for the detailed reply. And for considering making changes to your next update. It will be great to be able to do all this from within the settings area, rather than the functions file.

 

Also, thanks for the tip and code to add to the functions.php file that allows me to add shortcode to in a text widget - I have had frustration in that area for other applications.  

 

The forms in the widget areas (form id 2 and form id 3) already obeyed all my settings (including the hide after submission that I had set). Just the fname bit wouldn't work.

 

I went ahead and added the shortcode line in the functions php file. And then added your shortcode into a new test widget - except I used form id 2 because in form id 1 I didn't want the form to disappear on the main signup page - I only wanted it to disappear in the widget areas (form id2 and form id 3).

 

Testing the widget form, it still didn't display the fname field.

So I decided to look closer at the code you asked me to add in the functions.php file and noticed that it only referred to form id 1:

if( $form_id == 1 ) {

 

So in the widget I changed the form id back to 1 to see what would happen - and it worked! That part is great.

 

However, I want the widget areas to disappear the form (space saving).  So I guess the solution is to manually add the extra form ids into:
if( $form_id == 1 ) {

 

Would you be able to provide the correct syntax for that? It would be form id 2 and form id 3.

That way, the fname will appear on all my forms.

And once I see how that looks, in the future I will know how to add/edit that line as needed.

 

Thanks.

**Comment by EvanHerman** [comment]
Hi improve21,

I get what your saying now sorry for the confusion. I'm glad you were able to get everything working this far :). 

In regards to the correct syntax for that line, you can add an or statement to check if the form id matches 1 or matches 2 by doing something like this:

If( $form_id == 1 || $form_id == 2 ) {

You'll notice the || inside the brackets. That symbol means or in php. So if you wanted to add additional form ids you can add a new or statement in there.

'''php
If( $form_id == 1 || $form_id == 2 || $form_id == 3 ) {
'''

Alternatively, and a more clean approach to the solution is to define an array, and check if the form id exists in that array. There is less code to maintain, and easier to add or remove form ids moving forward. 

'''php
$form_id_array = array( 1, 2, 3 );

if( in_array( $form_id, $form_id_array ) ) {
'''

You can add or remove ids from the $form_id_array array as needed, just separate them with a comma. The last one should not have a comma after it. 

Either way will work but I find the second way to be cleaner. 


Thanks,
Evan

**Comment by improve21** [comment]
Thanks.

That worked. I used the simple one separated with commas.

**Comment by improve21** [comment]
Hi again,

I have a little problem with the form again - in relation to the message after hitting the submit button.
I had it all working just fine, as per all your instructions.  And then one day, I did something wrong (don't know what) in the My Custom Functions plugin file, and the website got the "white screen".  I nailed it down to this plugin.  I deleted and reinstalled it, and added as many of the things I had in there I could remember, including the yikes extra coding.  But from then on I could no longer get my messages to work as they did.  Also, no matter what I even enter in the Custom Message area, not even that works - I can leave it blank or I can enter anything into it - it still just displays the default message. 

So, something I did is wrong.  I have looked and looked at the code, but it all looks exactly as I think it should.  But, maybe I am missing something and my code has an error in it, or maybe there was some other thing to fix that was there before I re-installed My Custom Functions, that I have forgotten about.

I was wondering if you could just take a look below, including the attached image, to make sure my Yikes coding isn't awry, and perhaps offer me some other place to look to try to get it working properly how it did before.

1) Attached is the code used in My Custom Functions. The array includes all my forms ... -id1, id2 & id3.
http://www.improve21.com.au/mycustomfunctions.jpg

2) In the forms setup area, under "Custom Messages", I currently have that blank (this is the same for all the created forms). Although it makes no difference what I put there, I still get the default message.

3) The shortcodes used are: [yikes-mailchimp form="1"] [yikes-mailchimp form="2"] [yikes-mailchimp form="3"]

I am sure this was all I needed to do. But perhaps I missed something when I re-installed My Custom Functions, that I can't remember, as I didn't backup the files I edited :(

Can you please take a look at the above and see if there is anything I missed? Thanks in advance.
