### ISSUE TITLE
Request ability to add Red Asterisk next to Mandatory fields

### ISSUE THREAD

**Issue by GrahamBruno** [yikesinc/yikes-inc-easy-mailchimp-extender#456]
Please could I request the capability for the plugin to add a little red asterisk next to fields which are compulsory to fill in on forms I have built?

There are a number of forms where I have not designated fields as mandatory in the settings on mailchimp.com but have designated them as mandatory using the plugin and would be keen to be able to have the red asterisk display for these fields.

Ideally I would would like to request that this be added as a checkbox that could be activated on a per form basis. I have purchased the form customiser and would be willing to add custom CSS if that would be required to accomplish this.

Many thanks.

**Comment by TheTracyL** [comment]
Hi Graham.

We actually have a code snippet to do exactly what you want: https://yikesplugins.com/support/knowledge-base/apply-an-asterisk-to-specified-mailchimp-form-fields/

In that article we also explain why this functionality it not included with the plugin.

If are not comfortable editing the functions.php file of your active theme, you can use this plugin https://wordpress.org/plugins/my-custom-functions/

Thank you!
-Tracy
