### ISSUE TITLE
Form Submition not working

### ISSUE THREAD

**Issue by rpeladeau** [yikesinc/yikes-inc-easy-mailchimp-extender#457]
Hi, i've implement Yikes into my website here : http://www.belleetmincelaval.com/promotion/, and when i submit the Form, nothing happen. It refresh automatically at the same page.

Thanks for you help

**Comment by TheTracyL** [comment]
Hi Rpeladeau,

Please check out our Knowledge Base article on this exact problem: https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

This is a result of Javascript conflicts from other plugins or the theme itself.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Rpeladeau,

Were you able to resolve things?
Let us know.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Rpeladeau,

I am going to close this ticket, because we haven't heard back from you. If you need more help, please reopen it and we'll be happy to help you further.

Thank you!
-Tracy
