### ISSUE TITLE
Bug with accents since version 6.0.4.3

### ISSUE THREAD

**Issue by DenPaq** [yikesinc/yikes-inc-easy-mailchimp-extender#458]
Hi,
First, thanks for this great plugin. It works great and is so easy to setup...

I have a  bug since I have updated to version 6.0.4.3 this morning. My form is in french and now a checkbox with accents (é, ê, è etc) is showing the unicode version of the characters. 

Example:
> Je veux aussi u00eatre contactu00e9(e) par tu00e9lu00e9phone lorsque les inscriptions seront ouvertes.

Instead of:
> Je veux aussi être contactée par téléphone lorsque les inscriptions seront ouvertes.

See this page (at the end of the form): [http://dev.chezbrutus.com/admedica/preinscription/](url)

Do you know what can cause this? And can I reinstall the previous version of the plugin?

Thanks again for you great work!

**Comment by DenPaq** [comment]
UPDATE******
I have found the previous version and replaced version 6.0.4.3 with it but the problem is still there...

**Comment by TheTracyL** [comment]
Hello DenPaq,

What kinds of fields are those? Are they interest groups or other checkboxes? I want to set up a similar form on my end to see if I get the error as well. The other fields have kept their accents (Téléphone, etc.) so it must be something unique to that field type.

Thank you!
-Tracy

**Comment by DenPaq** [comment]
Hello Tracy!
Thanks for your very fast reply...
Yes they are interest groups checkboxes. 
In Wordpress, after I click on Add to form builder in the interest Groups tab, everything looks perfect. But it's when I update the form that the characters are switching to unicode...
Like you said, the other fields with accents are ok...

Thank you!

**Comment by DenPaq** [comment]
Hi again!
I have installed the version 6.0.4 and the accents are now showing ok: [http://dev.chezbrutus.com/admedica/preinscription/](url)

**Comment by TheTracyL** [comment]
Hi.

Whew! I'm glad that resolved itself. Thank you for bringing it to our attention. I will keep an eye out for this issue in the future.

Have a good day!
-Tracy

**Comment by DenPaq** [comment]
Hello,
Ok if the issue is resolved, I will  see a mention on a future update?

A nice day to you too!

**Comment by TheTracyL** [comment]
Oh, I'm sorry, I didn't realize you restored to 3 versions back, we will look into this.

**Comment by DenPaq** [comment]
Yes I was sure that the bug was not there on a previous version...

Thanks a lot for your help!

**Comment by TheTracyL** [comment]
Hi DenPaq,

We have been able to reproduce the bug on our end and we will be pushing out a fix for it soon.

Thank you!
-Tracy

**Comment by DenPaq** [comment]
Ok thank you Tracy!

On Feb 27, 2016, at 10:22 AM, Tracy Levesque <notifications@github.com> wrote:

Hi DenPaq,

We have been able to reproduce the bug on our end and we will be pushing out a fix for it soon.

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Hi DenPaq,

I just pushed out a 6.0.4.4 which should now hopefully resolve the issue for you. I've tested using all of the form fields and interest groups using a variety of foreign languages.

Feel free to update and give things another test, and let us know how things work after the update.


Thanks!
Evan

**Comment by EvanHerman** [comment]
I am going to close out this issue. If you are still having issue after the update, please let us know.

Thanks,
Evan
