### ISSUE TITLE
The reCaptcha not working in the Forms

### ISSUE THREAD

**Issue by sergeybruh** [yikesinc/yikes-inc-easy-mailchimp-extender#459]
When i press submit the request sent to the service without reCaptchaa's confirmation

**Comment by TheTracyL** [comment]
Hi Sergey,

Can you please provide a link to your form?

Thank you!
-Tracy

**Comment by sergeybruh** [comment]
Ya, sure http://frenchradiolondon.com/.
I am trying to solve the problem with spam bots which attacked the web-site frenchradiolondon.com.
They always fill out the form and when it's done your plugin eats all memory in the server.

**Comment by TheTracyL** [comment]
Hi Sergey,

Do you have all required fields assigned to the form? Are there any required fields or interest groups that exist in MailChimp, but are not on that form?

Let me know, thank you!
-Tracy

**Comment by sergeybruh** [comment]
Hi Tracy,

Thank you for response.

--- Do you have all required fields assigned to the form - No. Only the Email address filed is required. Do all the fields need to be required for the form to work?
--- Are there any required fields or interest groups that exist in MailChimp, but are not on that form? - No, all the required and non-required fields match between the MailChimp form and the plugin form.

We can give you a TeamViewer access to one of our machines so you can connect and see the settings yourself if it will make it easier.

Look forward to hearing back from you.

Kind regards,

Sergey.

**Comment by TheTracyL** [comment]
One more troubleshooting step - can you please [set the form to non-ajax](https://yikesplugins.com/support/knowledge-base/submission-settings/) and see if the problem still happens. Let me know when you do that, because I would like to test as well.

**Comment by sergeybruh** [comment]
Here is the screenshot with configurations: http://joxi.ru/EA46VKnuDnX5Qm
We’re using CDN (we’ve temporarily disabled it, but I recommend you to clean up cache or to use Cache Killer.)
I’m thinking about writing something like tihis.

**Comment by EvanHerman** [comment]
Hi Sergey,

It looks like you're using an older version of the plugin (6.0.4). I just pushed out a rleease for v 6.0.4.4 which should now resolve the issue you are facing.

The check was running, but the page was still continuing to execute even when the check failed. I went ahead and added some code to prevent the execution when the reCAPTCHA is empty.

Additionally, I've fixed the issue of foreign characters causing issues on some fields - so feel free to update to the latest release and give things another shot.


Thanks!
Evan

**Comment by TheTracyL** [comment]
Hi Sergey,

Just checking in. 

Did you try the new update, did that work for you?

Let us know.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Sergey,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy

**Comment by sergeybruh** [comment]
The issues seems to be resolved. Thank you a lot for all your help!

**Comment by TheTracyL** [comment]
Awesome, glad to hear it!

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy
