### ISSUE TITLE
"No lists were found on the account" error

### ISSUE THREAD

**Issue by Phriend2** [yikesinc/yikes-inc-easy-mailchimp-extender#461]
When attempting to "Create a New Signup Form", I receive a _"No lists were found on the account"_ error -- despite the fact that I had already signed-up on the MailChimp website and created a mailing list there. (Perhaps this list is not getting imported into the WordPress plugin?)

I created an API key and entered it in my Easy Forms for MailChimp plugin, too.

Anyone know what the problem could be?

**Comment by EvanHerman** [comment]
Hi,

You'll want to clear you API cache if you created the form after entering your API key. 

See the following knowledge base article for help:
https://yikesplugins.com/support/knowledge-base/api-cache-settings/

Evan

**Comment by EvanHerman** [comment]
Hi Phriend2,

I'm going to close out this issue. If you are still having issues and require assistance, feel free to comment back here.

Thanks,
Evan
