### ISSUE TITLE
i18n: split strings / typos

### ISSUE THREAD

**Issue by naokomc** [yikesinc/yikes-inc-easy-mailchimp-extender#464]
I grouped some things I noticed about the strings while translating the plugin. Excuse me for using translate.wordpress.org or plugins.trac.wordpress.org links, since they were easier to find while translating than the Github repo links.

## Split Strings
I've marked strings that are broken into pieces as "low" priority. See the strings with ↓ on the right column on [these pages](https://translate.wordpress.org/projects/wp-plugins/yikes-inc-easy-mailchimp-extender/dev/ja/default?page=42).

Because word order can be different in some languages, split strings are hard or impossible to translate. For explaination on split strings, please see the "[Best Practices](https://developer.wordpress.org/themes/functionality/internationalization/#best-practices-for-writing-strings)" section of the theme developer handbook.

## Typos
- [Github.org](https://plugins.trac.wordpress.org/browser/yikes-inc-easy-mailchimp-extender/trunk/admin/partials/menu/support.php#L36) - should be github.com
- [In version 6.0.3.8...](plugins.trac.wordpress.org) - An extra apostrophy at the end of the string

## Inconcistencies

- [reCAPTCHA & reCaptcha](https://translate.wordpress.org/projects/wp-plugins/yikes-inc-easy-mailchimp-extender/dev/ja/default?filters%5Bterm%5D=recap&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
- [optin](https://translate.wordpress.org/projects/wp-plugins/yikes-inc-easy-mailchimp-extender/dev/ja/default?filters%5Bterm%5D=optin&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) / [opt-in & Opt-in](https://translate.wordpress.org/projects/wp-plugins/yikes-inc-easy-mailchimp-extender/dev/ja/default?filters%5Bterm%5D=opt-in&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

**Comment by EvanHerman** [comment]
Hey naokomc,

Thank you for bringing that to our attention. We certainly don't want that to happen.

Those strings may have gone overlooked during development. I will take an additional look and repair any broken strings we have within the plugin as to not run into any issues.

Thanks again!
Evan

**Comment by TheTracyL** [comment]
Thank you SO MUCH for all that translation. I can't express how much we appreciate it.

Also, thank you for the guidance on the strings, Evan pushed a fix out for them over the weekend.
