### ISSUE TITLE
Getting issues when not logged in: Warning: key() expects parameter 1 to be array

### ISSUE THREAD

**Issue by patrickjc** [yikesinc/yikes-inc-easy-mailchimp-extender#465]
`Warning: end() expects parameter 1 to be array, null given in /home/susanbur/public_html/linkedinsuccessacademy.com/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 220`

`Warning: key() expects parameter 1 to be array, null given in /home/susanbur/public_html/linkedinsuccessacademy.com/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 221
`
I'm having this issues when not logged in but when logged in everything look fine.
Im using OptimizePress so wondering if there is a compatability issue.

Any help would be appreciated, thanks.

[http://snag.gy/VU7wI.jpg](url)

Here is a link to the page [https://goo.gl/MDqZ9F](url)

**Comment by EvanHerman** [comment]
Hi patrickjc,

Can you share a link to a page with your form on it? There should be no difference between logged in and not logged in users. They both use the same file to process the submission request to the MailChimp API.


Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi patrickjc,

Just following up on this. Are you still experiencing the problem?

Thank you!
-Tracy

**Comment by patrickjc** [comment]
Hi sorry,

I was working to a deadline so had to ditch using the plugin and go with a different option that worked but more than likely it's a comparability issue with optimizepress.

Patrick.

**Comment by TheTracyL** [comment]
Ah, ok. Thank you for the update.

Best wishes,
-Tracy
