### ISSUE TITLE
Submission form is not working

### ISSUE THREAD

**Issue by Stephanie3636** [yikesinc/yikes-inc-easy-mailchimp-extender#466]
Hi,
I downloaded the plugin not too long ago and when I tried to test out the plugin it does not send out a welcome email and does not show a new subscriber.  I also tried turning AJAX off, still doesn't work.

My site: dev.stephaniesegal.com/mailing-list/

Thanks

**Comment by EvanHerman** [comment]
Hi Stephanie,

Do you have a redirect setup for that form? It looks like I am getting redirected to the homepage after I submit the form. Can you try disabling the redirect temporarily?


Thanks,
Evan

**Comment by Stephanie3636** [comment]
Hi Evan,

Thank you so much for the quick reply! I am copying Gavin Fong who is helping me with my website so he can read your instruction below and he can answer this better than me.

Thank you!
Stephanie


Sent from my iPhone. Please excuse strange spelling & punctuation.

On Mar 7, 2016, at 1:02 PM, Evan Herman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stephanie,

Do you have a redirect setup for that form? It looks like I am getting redirected to the homepage after I submit the form. Can you try disabling the redirect temporarily?

Thanks,
Evan

-

**Comment by Stephanie3636** [comment]
I disable the redirecton

On Mon, Mar 7, 2016 at 1:12 PM, Stephanie Segal <Stephanie.Segal@neacinc.com
> wrote:

> Hi Evan,
>
> Thank you so much for the quick reply! I am copying Gavin Fong who is
> helping me with my website so he can read your instruction below and he can
> answer this better than me.
>
> Thank you!
> Stephanie
>
>
> Sent from my iPhone. Please excuse strange spelling & punctuation.
>

**Comment by Stephanie3636** [comment]
Any luck Evan? Gavin disabled the redirect. Thanks! Stephanie

**Comment by TheTracyL** [comment]
Hi Stephanie,

I tested the form a couple times with different emails. I get the confirmation message fine, but I never receive the opt-in email. I'm not sure what could be happening, because the opt-in email gets sent by MailChimp.

Can you please make sure you're on the newest version of the plugin and then turn Debugging on: https://yikesplugins.com/support/knowledge-base/debug-settings/ 

We can try again after that and see if it shows any errors from MailChimp.

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Hi Tracy!

I am copying Gavin, who is helping me with my website. We just loaded the plug-in last week and I remember he said that it was the latest version. Let me see if I can figure out how to do the debugging that you suggested. I don't have high hopes for myself though. LOL.

Sent from my iPhone. Please excuse strange spelling & punctuation.

On Mar 8, 2016, at 9:26 PM, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stephanie,

I tested the form a couple times with different emails. I get the confirmation message fine, but I never receive the opt-in email. I'm not sure what could be happening, because the opt-in email gets sent by MailChimp.

Can you please make sure you're on the newest version of the plugin and then turn Debugging on: https://yikesplugins.com/support/knowledge-base/debug-settings/

We can try again after that and see if it shows any errors from MailChimp.

Thank you!
-Tracy

-

**Comment by Stephanie3636** [comment]
It's a miracle! I was able to "enable debugging"

Sent from my iPhone. Please excuse strange spelling & punctuation.

On Mar 8, 2016, at 9:26 PM, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stephanie,

I tested the form a couple times with different emails. I get the confirmation message fine, but I never receive the opt-in email. I'm not sure what could be happening, because the opt-in email gets sent by MailChimp.

Can you please make sure you're on the newest version of the plugin and then turn Debugging on: https://yikesplugins.com/support/knowledge-base/debug-settings/

We can try again after that and see if it shows any errors from MailChimp.

Thank you!
-Tracy

-

**Comment by TheTracyL** [comment]
Great! Also, please double make sure you're on the newest version of the plugin, we did push out updates since last week. To do that go to Dashboard and click on Updates. See if our plugin is in the updates list and if so, update it.

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Done!

**Comment by TheTracyL** [comment]
Hi Stephanie,

I sent a couple test submissions. Can you please check the error log and see if anything shows up?

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Hi Tracy,

Apologies for the delayed reply. I have been out all day and will look at it tomorrow and get back to you. Thank you so much for your help!

Stephanie

Sent from my iPhone. Please excuse strange spelling & punctuation.

On Mar 9, 2016, at 10:23 AM, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stephanie,

I sent a couple test submissions. Can you please check the error log and see if anything shows up?

Thank you!
-Tracy

-

**Comment by TheTracyL** [comment]
Hi Stephanie.

We just pushed out another update, can you please update the plugin and try again?

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Tracy,

I did the update and also tried to send a test email from the website, but didn’t show up.

Stephanie

**Comment by TheTracyL** [comment]
Can you please let me know if there is anything in the error log?

**Comment by Stephanie3636** [comment]
<<[contact-form-7 id="71" title="Contact form 1"]>>

I found this where it asked for the validation of the contact form.

Where else should I look? I am really a newbie and the guys setting up my website are on spring break. ☹

**Comment by TheTracyL** [comment]
Hi Stephanie.

That code is for another plugin.

Here are instructions on how to get to the debig log: https://yikesplugins.com/support/knowledge-base/debug-settings/

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Thank you for the instructions!
Here’s the log:
Error Message

Error Details

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission_ajax.php || Type: Subscribe New User || Time: March 11, 2016 4:50 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission_ajax.php || Type: Subscribe New User || Time: March 11, 2016 4:49 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission.php || Type: Subscribe New User || Time: March 11, 2016 4:49 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission.php || Type: Subscribe New User || Time: March 11, 2016 4:49 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission.php || Type: Subscribe New User || Time: March 11, 2016 4:48 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission.php || Type: Subscribe New User || Time: March 11, 2016 4:48 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission.php || Type: Subscribe New User || Time: March 11, 2016 4:48 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission.php || Type: Subscribe New User || Time: March 11, 2016 4:47 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission.php || Type: Subscribe New User || Time: March 11, 2016 4:45 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission_ajax.php || Type: Subscribe New User || Time: March 11, 2016 4:44 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission_ajax.php || Type: Subscribe New User || Time: March 11, 2016 4:43 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission_ajax.php || Type: Subscribe New User || Time: March 11, 2016 4:43 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission_ajax.php || Type: Subscribe New User || Time: March 11, 2016 4:42 pm

The Email Parameter Should Include An Email, Euid, Or Leid Key

Page: process_form_submission_ajax.php || Type: Subscribe New User || Time: March 11, 2016 4:34 pm

You Must Specify A Apikey Value

Page: Add Interest Group to Form || Type: Get Interest Groups || Time: March 11, 2016 11:20 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:20 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:19 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:18 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:17 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:16 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:01 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:01 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 11:00 am

You Must Specify A Apikey Value

Page: Add Field to Form || Type: Get Merge Variables || Time: March 11, 2016 10:59 am

**Comment by EvanHerman** [comment]
Hi Stephanie,

Can you let us know what errors you have in the debug log from today. Additionally, what version of the plugin do you currently have installed? What are the settings that you are using for your form? I can see that it is set to non-ajax, but are things set to single/double opt-in? Is the welcome email enabled or disabled on the form?

Thanks,
Evan

**Comment by Stephanie3636** [comment]
Hi Evan,

Thank you so much. I’m sorry I dropped the ball on this. I am passing your email and instructions to the team working on my website and setting up the mail chimp. I

Gavin-can you be in direct contact with Evan (and Tracy) to work this out? I will be on a plane shortly and out of communication  until tomorrow.

Thanks!
Stephanie

**Comment by TheTracyL** [comment]
Hi Stephanie,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Tracy! The student Gavin I am working with sent several emails and didn't hear back! I copied him in the emails and he sent a few to the other gentleman. It's still not working. What should we do?! Do you want him to forward those emails to you.
Thanks, Stephanie


Sent from my iPhone. Please excuse strange spelling & punctuation.

On Apr 6, 2016, at 1:19 AM, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stephanie,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy

-

**Comment by TheTracyL** [comment]
What email address is Gavin sending the emails to? I haven't received anything.

**Comment by Stephanie3636** [comment]
Gavin- can you forward the emails you smelt to Tracy? Everyone make sure you hit reply all!

Sent from my iPhone. Please excuse strange spelling & punctuation.

On Apr 6, 2016, at 7:22 AM, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


What email address is Gavin sending the emails to? I haven't received anything.

-

**Comment by Stephanie3636** [comment]
the e-mail i was sending to was notifications@github.com, i guess that
wasn't the right one...

the message I was trying to send before:

Hi Evan,

I am helping Stephanie(stephanie.segal@neacinc.com) with her website, she
is going away for awhile so I it will just be me.

The errors says *This List Does Not Have Interest Groups Enabled.  *There
are 2 of them.
The version that I installed before I updated to the latest was 6.0.5.2.
It is double opt-in and the welcome email is enabled.

Thanks,
Gavin

On Tue, Apr 5, 2016 at 7:57 PM, Stephanie Segal <Stephanie.Segal@neacinc.com

**Comment by Stephanie3636** [comment]
Tracy/ Gavin/Evan,

Is all worked out? Are we back on track?

Thanks!
Stephanie

**Comment by TheTracyL** [comment]
I think the communication issue here is Evan and I are posting to [the thread on Github](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/466#issuecomment-206030856) and you all are replying to the notification emails.

Gavin, if you could please email us at plugins@yiksesinc.com that will go to both Evan and me. We will be able to resolve this more quickly that way.

Evan is out today, but we will be able to look into this tomorrow.

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Thanks Tracy! Gavin, please use the email address Tracy provided below and also copy me so I stay in the loop. Here is the email to start using and send your past correspondence: plugins@yiksesinc.com<mailto:plugins@yiksesinc.com>

Sent from my iPhone. Please excuse strange spelling & punctuation.

On Apr 7, 2016, at 10:20 PM, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the communication issue here is Evan and I are posting to the thread on Github<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/466#issuecomment-206030856> and you all are replying to the notification emails.

Gavin, if you could please email us at plugins@yiksesinc.com<mailto:plugins@yiksesinc.com> that will go to both Evan and me. We will be able to resolve this more quickly that way.

Evan is out today, but we will be able to look into this tomorrow.

Thank you!
-Tracy

-

**Comment by Stephanie3636** [comment]
it says that the address doesn't exist

**Comment by TheTracyL** [comment]
plugins@yikesinc.com ?

**Comment by Stephanie3636** [comment]
Not sure how to proceed. I asked Gavin if he sent the address, he wrote:yeah i try to send it to that address but got a email back that the address doesn't exist

What to do? Please hit reply all so he gets a copy of what you write.
Thanks.

Sent from my iPhone. Please excuse strange spelling & punctuation.

On Apr 8, 2016, at 4:15 AM, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


plugins@yikesinc.com<mailto:plugins@yikesinc.com> ?

-

**Comment by Stephanie3636** [comment]
Other than the mail chimp, is there still anything you want to change on
the site?

On Sat, Apr 9, 2016 at 7:27 AM, Stephanie Segal <Stephanie.Segal@neacinc.com

**Comment by TheTracyL** [comment]
Hello.

I just tested sending an email to plugins@yikesinc.com and it went through 

We really want to help you all. Either send an email to that address or start posting via [the Github forums](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/466).

Replying to the notification emails doesn't go directly to us.

Thank you!
-Tracy

**Comment by Stephanie3636** [comment]
Tracy,

I think we are up and running! I am copying Gavin and praying this email gets to you. I am traveling and the server/connection is crap.

Stephanie

**Comment by TheTracyL** [comment]
That's great news!
