### ISSUE TITLE
Update - email failed to send

### ISSUE THREAD

**Issue by SoMuch2Do** [yikesinc/yikes-inc-easy-mailchimp-extender#467]
I want to be able to update a subscribers mailchimp profile. I got this working (6.0.4.1).  I retested it after the last couple of updates only to find it is failing. I have deleted plugin and forms and re-installed but cannot get it to work. Plugin and WP are latest versions. Mailchimp list is connected.

My form is just the 2 required fields for the relevant MC form and I get the message
"Update your profile. To update your Mailchimp profile, please click to send yourself an update link"
_ (can you remove the duplicate text sometime please?)_
But when I do click,  I get the error message "Email failed to send. Please contact site administrator"
The email is valid. The form id is correct but nothing is received in the user supplied email address.

Help please.

**Comment by EvanHerman** [comment]
Hi,

When you receive this error, it means that the function `wp_mail()` is not working on your server. Therefore things such as password reset, comment notifications etc will also not function properly.

My recommendation would be to reach out to your hosting provider, and ask them what the issue is - as this error generally occurs on shared hosting.

Your other option is to install a third party plugin to re-route wp_mail through an SMTP mail service such as GMAIL.

This is one I recommend:
https://wordpress.org/plugins/wp-smtp/


Thank you,
Evan

**Comment by TheTracyL** [comment]
The reason we added the email verification is because it's a security issue without it. 

Let us know if you need further help. The SMTP plugin is a good way to go.

Thank you!
-Tracy

**Comment by SoMuch2Do** [comment]
HI TracyL, thanks for your comment.  I was able to get the update email to be sent successfully with v6.0.4.2 but not since.  I have ascertained that the wp_mail() function works but not with your plugin.  I note from the plugin documentation that there is now a two factor authentication but cannot find any further documentation (knowledgebase) on what this means.  My test user is logged into the Wordpress system - is this sufficient?  Apologies but could you spell out what steps I need to get this working again please. Thanks.

**Comment by TheTracyL** [comment]
Hi SoMuch2Do,

All two-factor authentication means is users get the "...To update your MailChimp profile, please click to send yourself an update link." message when they enter an email that is already subscribed to the list.

Thank you for the notes, Evan can take a look at them on Monday.

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Hi SoMuch2Do,

The wp_mail() funciton included in the plugin is the standard wp_mail() function used through out WordPress core. Can you confirm that wp_mail() is working on your server?

What version of the plugin do you have installed? Can you share a link to your site in question?


Thanks,
Evan

**Comment by SoMuch2Do** [comment]
Evan, apologies for the delay. The wp-mail() is working, so I don't think this is the problem.   I think I have worked out what is happening, but cannot see the reason.  
To explain I have a membership login system - using Simple Membership - this updates the WP and SM user lists and does not link to the MC list. The Yikes form connects to MC and only displays three fields.  
I have set up a [test page](http://dc64.wine-food.club/cm/tests/) - where you can create a new user (SM) and use the Yikes form to see the different results.

If I use the Yikes form to create a new member, it is added to the existing Mailchimp list.  Revisiting this form will generate the message that the user exists and clicking on the link will generate the necessary email. AKA all works. BUT if I use the Yikes form for a user that is already on the MC list, it will confirm the user exists but fails to send the email.  It doesn't seem to matter if I am logged into SM or not. I've cleared the api cache and checked the Yikes form settings which are. 
Option settings:
Single or Double Opt-in  Single 
Welcome Email   No
Update Existing Subscriber Yes

Submission settings
Ajax No
Redirect No
Hide form No
Existing Interest Replace

Form settings
Require Login ticked and unticked (current)

**Comment by EvanHerman** [comment]
I will have to do some testing on my end. I can see the error on the front end of your site, and can see the javascript error returned is as follows:

`Uncaught TypeError: Cannot read property 'response_text' of undefined`

I'm not sure why, so I will have to do some digging to see if I can reproduce the issue on my end - and come up with a fix for this issue.

Thanks,
Evan

**Comment by TheTracyL** [comment]
Hello,

We added an article on how to turn email validation off for profile updates. You can use this as a work around: https://yikesplugins.com/support/knowledge-base/turn-off-email-verification-profile-updates/

Thank you!
-Tracy
