### ISSUE TITLE
updated mailchimp extender - form not working - errors Warning: Invalid argument supplied for foreach() in

### ISSUE THREAD

**Issue by DTade** [yikesinc/yikes-inc-easy-mailchimp-extender#468]
Hello I just updated my Yikes-inc=easy-mailchimp-extender and it seems to have broken my form on my site. I have deactivated and reactivated the plug-in do you have any tips on how I should approach this? 

http://coholiving.com/register/

anything will help!

Thank you,

**Comment by EvanHerman** [comment]
Please clear out your API cache and test again:
https://yikesplugins.com/support/knowledge-base/api-cache-settings/


Thank you,
Evan

**Comment by TheTracyL** [comment]
Hi DTrade,

It looks like your form is cleared up.

We're glad things got resolved.

Thank you!
-Tracy

**Comment by DTade** [comment]
Thanks so much for the quick reply! 

I also removed the form and put it back in, that did the trick



Denise Tade, Graphic Designer
dftade@gmail.com
