### ISSUE TITLE
Display timing on the Success Message

### ISSUE THREAD

**Issue by DStarkJr** [yikesinc/yikes-inc-easy-mailchimp-extender#469]
Is it possible to change the timing of the Success Message before the redirect takes place?

**Comment by EvanHerman** [comment]
Hi,

Yes you can alter the timing of the redirect using the built in filter, `yikes-mailchimp-redirect-timer`. The default time is 1.5 second.

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/9cba04ed417613b8659109a35f1cdb7f9c6fd055/plugin_core/public/partials/shortcodes/process/process_form_submission_ajax.php#L246

```php
function alter_timer( $time ) {
   return 3000;  /* Return time in ms */
}
add_filter( 'yikes-mailchimp-redirect-timer', 'alter_timer' );
```


Thanks,
Evan

**Comment by DStarkJr** [comment]
Thank you.
