### ISSUE TITLE
update existing user

### ISSUE THREAD

**Issue by garrymansfield** [yikesinc/yikes-inc-easy-mailchimp-extender#470]
hi, i also added this to  a thread that provided some good information. but not sure if it was closed. 

hello
we use the plugin to add groups of interests for campaigns for users in mailchimp. since the upgrades I cannot upgrade group information for an existing user. you have provided some code above that you seem to indicate will fix the problem... but i am not a programmer and it is not clear what i have to do with this.can you help?

I do not want a user to get an email other than the document they requested in the form.

thanks
Garry

**Comment by TheTracyL** [comment]
Answered on the other thread.
