### ISSUE TITLE
Subscribers not recived final welcome email 

### ISSUE THREAD

**Issue by morio2** [yikesinc/yikes-inc-easy-mailchimp-extender#471]
Hello,
I have add the opt-in checkbox to the contact form 7, but when subscribers put them email and checkbox and click send then they not received the success subscribe email or the final welcome email like i have set it in mailchimp, so they not receive any email at all.
But if i add the opt-in checkbox to WordPress Comment Form, then everything is work fine and they received the final welcome email as have set in mailchimp.
I hope you can help me resolve this problem.
Thank you
![untitled](https://cloud.githubusercontent.com/assets/17171570/13809797/23196034-eb75-11e5-8275-524eae274108.png)

**Comment by EvanHerman** [comment]
Hi,

We will look into the issue and report back here with our findings.


Thank you,
Evan

**Comment by TheTracyL** [comment]
Hi Morio,

I noticed you have `"form=3"` in the shortcode. Can you try the integration without it? That is not a valid shortcode parameter.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Morio,

I just did some testing with Contact Form 7 and all of my tests worked. Let me know if that extra variable is the issue.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Morio,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
