### ISSUE TITLE
Custom form

### ISSUE THREAD

**Issue by morio2** [yikesinc/yikes-inc-easy-mailchimp-extender#472]
Hello,
I just install the YIKES Easy Forms for MailChimp plugin and create custom form and copy the shortcode for this form and paste it into new page, but the looking for this form is different than my theme looking as you see in picture.
Form is different size and color and looking than my theme.
I hope you can help me in this case.
Thank you
![untitled](https://cloud.githubusercontent.com/assets/17171570/13810216/54e81b3a-eb77-11e5-8033-097b823234d1.png)

**Comment by TheTracyL** [comment]
Hi Morio2,

May I please have a link to your form? Also, do you have the form set to inline?
https://yikesplugins.com/support/knowledge-base/how-do-i-place-all-of-my-form-fields-on-one-line/

Thank you!
-Tracy

**Comment by morio2** [comment]
Hello Tracy,
Yes i have try it with inline disable and enable but what change is only (send) box become smaller.
here is the link, you have to go end of the page and you will see 2 subscription form, first one is how it should be, and last one is yikes form with inline enable.
https://www.wikiasema.fi/contact-us/
Thank you

**Comment by TheTracyL** [comment]
Hi Morio2,

I see the form as inline. Is the issue that you want the style to be the same as the form above it?

Let me know, thank you.
-Tracy

**Comment by morio2** [comment]
Hello Tracy,
Yes, i want the style to be the same as the form above it.

**Comment by TheTracyL** [comment]
Hi Morio2,

I went in to make those styles for you and I can no longer connect to the site.

Is this a temporary issue, or will the site be up again?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Morio2,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
