### ISSUE TITLE
reCAPTCHA Settings

### ISSUE THREAD

**Issue by morio2** [yikesinc/yikes-inc-easy-mailchimp-extender#473]
Hello,
I have active reCAPTCHA in plugin Settings and insert reCAPTCHA Site Key and reCAPTCHA Secret Key, but reCAPTCHA dose not show anywhere like custom form or WordPress Comment Form or WordPress Registration Form or Contact Form 7.
Thank you

**Comment by EvanHerman** [comment]
Hi Morio2,

The recaptcha only appears on the actual form itself when you are using our shortcode or the widget. The recaptcha will not appear in our integrations such as the comment form, or contact form 7.

If you need recaptchas for those forms, you may want to look into installing a recaptcha plugin to extend those plugins specifically. There is no way for us to validate the recaptcha coming from our plugin within contact form 7 or another third party plugin.

Thanks,
Evan
