### ISSUE TITLE
Interest Groups field values cleared after submission

### ISSUE THREAD

**Issue by lcyoong** [yikesinc/yikes-inc-easy-mailchimp-extender#474]
Hi,

I'm trying out MailChimp extended here http://ckflanding2.creino.com on Firefox and when I submit the form, the info is captured on MailChimp with success message displayed. However, when I try again right after that, I noticed that the field values for the Interest Groups become blank. Any take on this?

Cheers

**Comment by TheTracyL** [comment]
Hi Lcyoong,

I'm not totally sure what the issue is that you're describing. If you refresh the page are they back?

Also I visited that page and I didn't see interest groups on the form.

Thank you!
-Tracy

**Comment by lcyoong** [comment]
Hi,

The interest groups are hidden in the form. When the page is first loaded, the values are present. But, after submitting the first time and trying to submit again, it is still successful. But, the second submission has blank interest groups and when I view the source, after the first submission, the interest groups value becomes blank. Hope that's clear enough.

Thanks.

**Comment by TheTracyL** [comment]
Are they there if you refresh the page?

**Comment by lcyoong** [comment]
Yes. It will reappear if I refresh the page. But it's missing right after submitting the form.

**Comment by TheTracyL** [comment]
I don't know exactly why this is happening, maybe Evan can chime in, but it is not a typical use case for the form, so I don't think it is an issue.
