### ISSUE TITLE
Ajax submission issue on Chrome

### ISSUE THREAD

**Issue by lcyoong** [yikesinc/yikes-inc-easy-mailchimp-extender#475]
Hi,

I am trying out the MailChimp extender on this link http://ckflanding2.creino.com/ and the form doesn't submit for Ajax on Chrome. It works on Firefox and if I turned the Ajax off, it will work on Chrome as well.

I picked these debug messages from the console 
POST http://ckflanding2.creino.com/wp-admin/admin-ajax.php net::ERR_CONNECTION_RESET
Object {readyState: 0, responseText: "", status: 0, statusText: "error"}

Cheers

**Comment by EvanHerman** [comment]
Hi Icyoong,

I just tested things out using the link you provided and didn't seem to encounter any issues.

Are you still seeing the errors on your end?

![screenshot](https://www.diigo.com/file/image/rabssqszdaqqarrrdzccdpccsd/Charles+Knight+Finance+-+Charles+Knight+Finance.jpg)

Thanks,
Evan

**Comment by lcyoong** [comment]
Hi,

Mine is Chrome on Mac. Does it make any difference between Mac and Windows? Yes, I still got the mentioned errors on console debugging.

Thanks

**Comment by EvanHerman** [comment]
Hi Icyoong,

Sorry for the delay in responses. I don't have a mac readily handy to test on, but I can get around to it in the next day or so. I don't think tested on a mac vs a PC should make a difference.

Thanks,
Evan

**Comment by CLBeckmann** [comment]
I think I'm having a similar issue. This post: http://www.cyw.academy/32-strategies/ 

Every time I enter an email address the page just refreshes. The email address is never submitted to MailChimp and the page is not redirected to the PDF page. I'm on a Mac using Chrome. I've also tested on Firefox and Safari - but having the same issue.

**Comment by EvanHerman** [comment]
Please switch over from the ajax submission. You're theme/site has a javascript issue and is causing issues. Without resolving the js error, the form will not work unless it is set to NON-AJAX.

Thank you,
Evan

**Comment by TheTracyL** [comment]
You can turn Ajax submissions off under submission settings: https://yikesplugins.com/support/knowledge-base/submission-settings/

**Comment by TheTracyL** [comment]
We also have this article: https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/
