### ISSUE TITLE
Forms not working

### ISSUE THREAD

**Issue by steventkd** [yikesinc/yikes-inc-easy-mailchimp-extender#480]
I believe I have everything setup correctly but my forms are not working with mailchimp.  The forms are created and show up in my wp site, in the yikes plugin.  The forms display correctly on the home page and widgets.  When the information is filled out people aren't added to the list and they are not receiving a welcome email I created.  Can someone help?  I get good traffic to the site and I don't want to miss opportunities.  Thanks.

**Comment by EvanHerman** [comment]
Hi,

Can you please share a link to your site? Additionally, do you have the forms setup as AJAX or non-ajax forms?

Thanks,
Evan

**Comment by steventkd** [comment]
http://carpetcleaningkansascitymissouri.com/

It is set up as Ajax.

On Tue, Mar 29, 2016 at 8:54 AM, Evan Herman <notifications@github.com>
wrote:

> Hi,
>
> Can you please share a link to your site? Additionally, do you have the
> forms setup as AJAX or non-ajax forms?
>
> Thanks,
> Evan
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/480#issuecomment-202904258>
>



-- 
Steven White
                                                  Brooke's Chem-Dry

                         Like us on Facebook
<https://www.facebook.com/Brookes-Chem-Dry-Kansas-City-447512298691366/>

**Comment by EvanHerman** [comment]
Can you try setting it to non-ajax and testing again. From what I can see, you are running into a JavaScript error on your site - which is conflicting with our plugin and preventing the functionality from working properly.


Thanks,
Evan

**Comment by steventkd** [comment]
I was using Gravity Forms should I deactivate that plugin?  Could that
cause a problem?

On Tue, Mar 29, 2016 at 10:07 AM, Evan Herman <notifications@github.com>
wrote:

> Can you try setting it to non-ajax and testing again. From what I can see,
> you are running into a JavaScript error on your site - which is conflicting
> with our plugin and preventing the functionality from working properly.
>
> Thanks,
> Evan
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/480#issuecomment-202945242>
>



-- 
Steven White
                                                  Brooke's Chem-Dry

                         Like us on Facebook
<https://www.facebook.com/Brookes-Chem-Dry-Kansas-City-447512298691366/>

**Comment by steventkd** [comment]
Hi Evan,

My wife filled out both forms, on the contact form, it shows she was added
to the list.  She received the welcome email.  I need to be able to receive
an email with the information the customer enters so I can follow up with
them.  I thought I did that but is there a way to check?

Also the other form, schedule an appointment, she filled out but it doesn't
show she was added to the list.  Please help.  Thanks.

On Tue, Mar 29, 2016 at 10:25 AM, Steven White <steven@brookeschemdry.com>
wrote:

> I was using Gravity Forms should I deactivate that plugin?  Could that
> cause a problem?
>
> On Tue, Mar 29, 2016 at 10:07 AM, Evan Herman <notifications@github.com>
> wrote:
>
>> Can you try setting it to non-ajax and testing again. From what I can
>> see, you are running into a JavaScript error on your site - which is
>> conflicting with our plugin and preventing the functionality from working
>> properly.
>>
>> Thanks,
>> Evan
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/480#issuecomment-202945242>
>>
>
>
>
> --
> Steven White
>                                                   Brooke's Chem-Dry
>
>                          Like us on Facebook
> <https://www.facebook.com/Brookes-Chem-Dry-Kansas-City-447512298691366/>
>



-- 
Steven White
                                                  Brooke's Chem-Dry

                         Like us on Facebook
<https://www.facebook.com/Brookes-Chem-Dry-Kansas-City-447512298691366/>

**Comment by TheTracyL** [comment]
Did you try disabling AJAX first before testing?

**Comment by steventkd** [comment]
Yes, but let me try it with my information.

On Tue, Mar 29, 2016 at 11:05 AM, Tracy Levesque <notifications@github.com>
wrote:

> Did you try disabling AJAX first before testing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/480#issuecomment-202976706>
>



-- 
Steven White
                                                  Brooke's Chem-Dry

                         Like us on Facebook
<https://www.facebook.com/Brookes-Chem-Dry-Kansas-City-447512298691366/>

**Comment by steventkd** [comment]
No it didn't work.

On Tue, Mar 29, 2016 at 11:07 AM, Steven White <steven@brookeschemdry.com>
wrote:

> Yes, but let me try it with my information.
>
> On Tue, Mar 29, 2016 at 11:05 AM, Tracy Levesque <notifications@github.com
> > wrote:
>
>> Did you try disabling AJAX first before testing?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/480#issuecomment-202976706>
>>
>
>
>
> --
> Steven White
>                                                   Brooke's Chem-Dry
>
>                          Like us on Facebook
> <https://www.facebook.com/Brookes-Chem-Dry-Kansas-City-447512298691366/>
>



-- 
Steven White
                                                  Brooke's Chem-Dry

                         Like us on Facebook
<https://www.facebook.com/Brookes-Chem-Dry-Kansas-City-447512298691366/>

**Comment by EvanHerman** [comment]
Hi Steven,

If you are looking to receive notification emails each time someone submits the form - you can do one of two things.

1) MailChimp allows such a feature. It is called 'Subscribe and Unsubscribe Notifications'. You can set these up on a per form basis. Please take a look at the following knowledge base article on how to achieve that:
http://kb.mailchimp.com/lists/managing-subscribers/change-subscribe-and-unsubscribe-notifications

2) You can hook into our plugin, and  on the action [yikes-mailchimp-after-submissio](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/partials/shortcodes/process/process_form_submission.php#L279) you can capture the submitted user data in the `$merve_variables` variable. You should have no issues firing off emails using` wp_mail()` each time the form is submitted.

I would recommend going the first route if you are unfamiliar with writing custom code for WordPress, as route 2 is a bit more advanced.


Thanks!
Evan

**Comment by TheTracyL** [comment]
Hi Steven,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
