### ISSUE TITLE
I can't create a form

### ISSUE THREAD

**Issue by pbcreativesolutions** [yikesinc/yikes-inc-easy-mailchimp-extender#481]
Hi, 

I'm new of mailchimp and of this plugin.
I have setup and connected my mailchimp account with the plugin, I have created a list on my mailchimo account, but I can't create my first form.
There is a message "no lists were found on the account".
Can you help me?

![screenshot-2016-03-29 18-06-21](https://cloud.githubusercontent.com/assets/17281503/14114866/15a80fea-f5d9-11e5-9a18-b0e22062e3c9.png)
![screenshot-2016-03-29 18-05-54](https://cloud.githubusercontent.com/assets/17281503/14114867/15adce12-f5d9-11e5-9e41-47def0627835.png)

**Comment by TheTracyL** [comment]
Hello!

This Knowledge Base article will give you the information you need on this issue.
https://yikesplugins.com/support/knowledge-base/im-not-seeing-all-my-lists-on-the-drop-down-menu-when-i-go-to-make-a-new-form/

Thank you!
-Tracy

**Comment by pbcreativesolutions** [comment]
Oh thank you very much! and excuse-me!

**Comment by TheTracyL** [comment]
You're welcome!

Have a good day :-)
-Tracy
