### ISSUE TITLE
Preset words on form fields

### ISSUE THREAD

**Issue by sacarmi** [yikesinc/yikes-inc-easy-mailchimp-extender#482]
Hi i have just created a form using Yikes for mailchimp on a wordpress ste - all went well! However I wonder - can I edit the field titles - ie it says Best email address - I would prefer just "Email Address" can I do this?
Thanks
Melanie

**Comment by EvanHerman** [comment]
Hi Sacarmi,

The field labels are controlled via MailChimp. Once you import the fields, the labels are stored in your database to prevent additional API calls.

What I would recommend, is updating the name of the field over on MailChimp side, and once completed - re-add the fields to your form. You'll find the labels are then updated as well.

If you would like additional help, we have setup a knowledge base article on this exact subject:
https://yikesplugins.com/support/knowledge-base/how-do-i-change-the-field-labels/

Let us know if that helps at all!


Thanks,
Evan

**Comment by sacarmi** [comment]
Thank you that worked perfectly!
Melanie

Sent from my iPhone

On 31 Mar 2016, at 1:19 pm, Evan Herman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Sacarmi,

The field labels are controlled via MailChimp. Once you import the fields, the labels are stored in your database to prevent additional API calls.

What I would recommend, is updating the name of the field over on MailChimp side, and once completed - re-add the fields to your form. You'll find the labels are then updated as well.

If you would like additional help, we have setup a knowledge base article on this exact subject:
https://yikesplugins.com/support/knowledge-base/how-do-i-change-the-field-labels/

Let us know if that helps at all!

Thanks,
Evan

-

**Comment by EvanHerman** [comment]
Awesome, so glad that worked for you and it was a simple fix :+1: 

If you are enjoying the plugin, we would love it if you could leave us a positive review.
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender

Thanks again for keeping us posted on the issue,
Have a wonderful rest of your week!


Evan
