### ISSUE TITLE
Easy Forms for MailChimp - Fatal Error on Acivate

### ISSUE THREAD

**Issue by smart7ss** [yikesinc/yikes-inc-easy-mailchimp-extender#483]
Hello

I'm getting a fatal error on 'activate' and also I can't delete the plugin.

Please can you help?

Thanks very much, Simon

**Comment by TheTracyL** [comment]
Working on this offline.

**Comment by EvanHerman** [comment]
I have worked with Simon this morning, this issue should now be resolved. For some reason - the plugin directory was missing some key files/directories and thus throwing a fatal error on activation.

I connected via FTP, and was able to remove the existing directory for our plugin.

Once removed, I re-installed the plugin from the WordPress.org repository. The installation went smoothly and things seem to be up and running now without issue.

If things are not working, @smart7ss, feel free to comment back here to re-open the issue.

Thanks!
Evan
