### ISSUE TITLE
Duplication of Form on Page

### ISSUE THREAD

**Issue by jvoz** [yikesinc/yikes-inc-easy-mailchimp-extender#484]
Hello,

I have created a Yikes form and embedded it in the Widget for the default sidebar.  Now when I use that sidebar, the form is displayed twice - once in the sidebar and once at the end of the page. An example of the duplication is at http://www.infocube.com.au/infocube-foundation/

Can you please help me resolve this problem?

I have set you up with an Admin account to my site and you have been emailed login details. Please note that we use Clef.

Thanks

John

**Comment by TheTracyL** [comment]
Hi John,

I took a look and the form at the bottom is in a container with the note
`<!--Visible Only Iphone Class Start -->`

It looks like that section at the bottom is meant to only be visible on phones, but something must be off with the CSS so it is displaying on desktop.

Does the Theme author provide support for issues like this?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi John,

Just checking in on this, were you able to contact the theme developer?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi John,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
