### ISSUE TITLE
Your contact page

### ISSUE THREAD

**Issue by sacarmi** [yikesinc/yikes-inc-easy-mailchimp-extender#485]
Hi we have a contact page and a subscribe page on our website - on the contact page which is for people to ask us questions about our service (the form is like the one on your contact page - ie quite big)  we would also like a subscribe to newsletter box but  smaller than the other fomr again like the one on your contact page - right hand side http://www.yikesinc.com/contact-yikes/ - can this be done with your easy forms for Mailchimp plugin?
Thanks

**Comment by EvanHerman** [comment]
It depends what plugin you are using the generate that contact form. If you are using a plugin that we have built out an integration for, than yes. If not - then you'll need to write some custom code to hook our plugin into your forms - which would be outside the scope of support for our free plugin.


Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi there.

Our plugin would be used to make the subscribe box. The plugin has a widget to easily add a box like that to any widget area.

You can add an opt-in checkbox to a contact form, but it has to be built with one we have an integration for, like Contact Form 7. You can't create a contact form with our plugin.

Thank you!
-Tracy
