### ISSUE TITLE
Form has disappeared

### ISSUE THREAD

**Issue by sacarmi** [yikesinc/yikes-inc-easy-mailchimp-extender#486]
Hi me again! 
I wanted to edit the fields of a form which I did on wordpress (maybe should have done  in Mailchimp?) now the form doesnt appear at all on the website and has error message - the screenshot of the page on wordpress is attached - how do i recreate my form please? It is ID 2
![screen shot 2016-04-02 at 12 59 18](https://cloud.githubusercontent.com/assets/16224745/14226195/d663f8c4-f8d2-11e5-9cc7-77d3de1ea585.png)

**Comment by TheTracyL** [comment]
When you edit the form are you able to re-choose the list you want?

**Comment by TheTracyL** [comment]
You may also need to clear your API cache: https://yikesplugins.com/support/knowledge-base/api-cache-settings/

**Comment by sacarmi** [comment]
No ?

Sent from my iPhone

On 2 Apr 2016, at 1:07 pm, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


When you edit the form are you able to re-choose the list you want?

-

**Comment by sacarmi** [comment]
Ok I've cleared that but it still says we've encountered an error no list ID was sent

Sent from my iPhone

On 2 Apr 2016, at 1:08 pm, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


You may also need to clear your API cache: https://yikesplugins.com/support/knowledge-base/api-cache-settings/

-

**Comment by TheTracyL** [comment]
You need to reassign the list to the form.

In the upper right corner when you edit a form there is an "Associated List Settings" section. Click on that and reassign the form to the correct list.

If that doesn't work you can just start over and make the form again.

**Comment by sacarmi** [comment]
Thank you - isn't it easy when you know how!
Sorry for the multi stupid questions!

Sent from my iPhone

On 2 Apr 2016, at 1:19 pm, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to reassign the list to the form.

In the upper right corner when you edit a form there is an "Associated List Settings" section. Click on that and reassign the form to the correct list.

If that doesn't work you can just start over and make the form again.

-

**Comment by TheTracyL** [comment]
No worries. And no questions are stupid!!

We are happy to help.
-Tracy

**Comment by sacarmi** [comment]
?

Sent from my iPhone

On 2 Apr 2016, at 2:04 pm, Tracy Levesque <notifications@github.com<mailto:notifications@github.com>> wrote:


No worries. And no questions are stupid!!

We are happy to help.
-Tracy

-
