### ISSUE TITLE
Address Fields Still Showing with Easy Forms for Mailchimp Zip Lookup Extension 

### ISSUE THREAD

**Issue by xeroxerox88** [yikesinc/yikes-inc-easy-mailchimp-extender#487]
Hi there -

I've downloaded your Wordpress plugin, Easy Forms for MailChimp Zip Lookup Extension, and from what I've read the plugin should work automatically once I include an Address field in my signup form. 

I've created a form in Mailchimp, including an Address field (the email list also has the Address field selected). However the address fields (city, state, country) are still showing up on the form once I embed it on my site -- and the zip code lookup isn't working either. 

Not sure what I'm doing wrong here. I don't see the option to add address fields via the Yikes Easy Forms plugin form builder -- which led me to build the form in Mailchimp. Any direction you can give me would be most appreciated.

Many thanks.

**Comment by TheTracyL** [comment]
Hello.

The zip add-on only works with a form created with our base plugin. The address field will appear in the form builder, however our plugin caches the info from your MailChimp account for about an hour. 

You will need to clear the cache, here is instructions on how to do that: https://yikesplugins.com/support/knowledge-base/api-cache-settings/

Thank you!
-Tracy

**Comment by xeroxerox88** [comment]
Thank you so much for your quick response. I've since cleared the cache and was able to add the Address field via the Easy Form plugin. 

However, I tested out the form, making sure to enter my zip code, and it doesn't look like the zip code look up extension worked. I checked the email list on Mailchimp's end, and the City and State fields were still empty... again, any info you can provide is appreciated.

**Comment by TheTracyL** [comment]
Hi there,

Can you please provide a link to your form so we can take a look?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi xeroxerox88,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
