### ISSUE TITLE
Submissions, but no Sign Ups

### ISSUE THREAD

**Issue by KerriLowe** [yikesinc/yikes-inc-easy-mailchimp-extender#488]
Hello. 

I am seeing that there are much larger numbers of submissions than people who end up actually on the list. I assume this is because their confirmation email went to spam and they never got it. Is there any way to see the addresses of people who filled out the form so we can follow up individually? Thanks so much.

**Comment by TheTracyL** [comment]
Hi Kerry,

No, we don't capture that information. The info is only captured in MailChimp if the people opt-in to join the list. 

Thank you!
-Tracy
