### ISSUE TITLE
Widget for footer not working

### ISSUE THREAD

**Issue by VladAdam** [yikesinc/yikes-inc-easy-mailchimp-extender#490]
Hi Yikes,

Unfortunately when a visitor to the site enters their email, first and last name then clicks submit nothing happens. No success message appears on screen and their details that they have just entered are not sent to Mailchimp. I have checked the API key it is showing that your plugin and Mailchimp have connected successfully.

Please advice what I can do to fix this issue.

The plugin is located in the footer.
http://www.fantasyhq.com.au/

Thank you,
Vlad

**Comment by TheTracyL** [comment]
Hi Vlad.

I just tested the submission and I see the success message:

![image](https://cloud.githubusercontent.com/assets/1252286/14429727/9ac18524-ffcc-11e5-9c2b-36513cc87167.png)

I also got the confirmation email for FantasyHQ mailing list.

I am wondering if you found this article and resolved the issue: https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

Thank you!
-Tracy
