### ISSUE TITLE
Problem with Incentives for Easy Forms for MailChimp after install

### ISSUE THREAD

**Issue by putti23** [yikesinc/yikes-inc-easy-mailchimp-extender#491]
Signup Incentives
Add file attachments to send to the user once they have successfully signed up using this form.

Fatal error: Class 'MailChimp' not found in /home/wcscom2015/download/wp-content/plugins/yikes-inc-easy-mailchimp-incentives-extension/yikes-inc-easy-mailchimp-incentives-extension.php on line 403

**Comment by TheTracyL** [comment]
Hello,

Please open up a premium support ticket for this issue, because we will be able to help you more easily there.

Here are instructions: https://yikesplugins.com/support/knowledge-base/how-do-i-get-premium-support/

Thank you!
-Tracy
