### ISSUE TITLE
Warning displayed when not logged in

### ISSUE THREAD

**Issue by jranc43** [yikesinc/yikes-inc-easy-mailchimp-extender#492]
Hello,

I am getting these warning when not logged in:

```
Warning: end() expects parameter 1 to be array, null given in /xxxxx/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 223

Warning: key() expects parameter 1 to be array, null given in /xxxxx/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 224
```

WP and all plugins are up to date.

Also, I used to log in via mywebsite.com/admin, but this does not work (same warnings). only /wp-admin/ works.

Thanks for your help.

**Comment by EvanHerman** [comment]
Hi,

First: can you share a link to your site?

Second: The second issue that you mentioned seems related to a different plugin, or something else going on on your site. I would recommend deactivating all of the other plugins but our plugin and testing again.

Thanks!
Evan

**Comment by TheTracyL** [comment]
Hi jranc43,

Let us know if you can post a link to your site and if you were able to perform the troubleshooting steps outlined by Evan.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi jranc43,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
