### ISSUE TITLE
Incentives for Easy Forms for MailChimp file didn't download in the zip format.

### ISSUE THREAD

**Issue by chloeflowers** [yikesinc/yikes-inc-easy-mailchimp-extender#493]
I have no idea how to upload this new plug-in, since it did not download in a zip format.

**Comment by EvanHerman** [comment]
The most stable release can be found in the WordPress.org plugin repository:
https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/

This repository is for development of the plugin for future versions.

Thanks,
Evan

**Comment by TheTracyL** [comment]
Hello,

What that happens your computer is either hiding the file extension or automatically unzipping it for you after it downloads.

This often happens on a Mac. There are a few articles out there that show how to stop this from happening: http://apple.stackexchange.com/questions/961/how-to-stop-safari-from-unzipping-files-after-download

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
This one has comments by someone having your exact problem, but with a WordPress theme. http://www.shilling.id.au/2012/07/12/safari-stop-unzipping-downloads/

**Comment by chloeflowers** [comment]
GOD BLESS YOU!

Thanks tons!!

**Comment by TheTracyL** [comment]
Ha ha, you're welcome :-)

Have a good day.
