### ISSUE TITLE
After clicking on submit or subscribe button, nothing happens

### ISSUE THREAD

**Issue by jhl217** [yikesinc/yikes-inc-easy-mailchimp-extender#494]
It is similar to the issue listed on the below link where nothing happens after clicking on the submit or subscribe button.  This issue happened after the latest update in mailchimp plugin in wordpress.  I even enabled debug logging but no logs shows up.  It shows that the plugin is connected to mailchimp and it shows the previous subscription logs and user lists.

http://kb.mailchimp.com/lists/signup-forms/troubleshooting-the-embedded-signup-form

I am using WordPress 4.5.2 running Zerif Lite theme.

**Comment by EvanHerman** [comment]
Hello,

Can you please deactivate all other plugins and switch themes and test again? Chances are you have a JavaScript error coming from another plugin or from your theme. If it works, switch back to your current theme and test again. If it still works, re-activate your plugins one at a time and test until you are able to locate the plugin causing the issue. 

Additionally, please include a link to your site so we can take a look. 

Thank you,
Evan

**Comment by TheTracyL** [comment]
Hello,

Please let us know if you were able to perform the troubleshooting steps Evan outlined above.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
