### ISSUE TITLE
Can't Add Easy Forms license key  to Wordpress Admin Page

### ISSUE THREAD

**Issue by speechexpress11** [yikesinc/yikes-inc-easy-mailchimp-extender#495]
I bought the Easy Forms Add On (Customize forms), but couldn't add the license key in the wordpress admin page. The interface is different from your tutorial. Can you help me fix this issue? Thanks. 
![screenshot 2016-05-08 22 51 26](https://cloud.githubusercontent.com/assets/19252149/15098403/7c94ef24-156f-11e6-9100-db496d950ec0.png)

**Comment by TheTracyL** [comment]
Hello,

It looks like the add-on is not yet installed. Here are instructions on how to do that: https://yikesplugins.com/support/knowledge-base/how-to-install-add-ons/

There are also instructions in the email receipt you received after purchasing the add-on.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello,

Did that solve your issues?

Let us know.

Thank you!
-Tracy

**Comment by speechexpress11** [comment]
Yes, thank you.

**Comment by TheTracyL** [comment]
Awesome!

Have a good  day :-)
-Tracy
