### ISSUE TITLE
Getting Subscriber Information with the Yikes Plugin

### ISSUE THREAD

**Issue by Gyles1** [yikesinc/yikes-inc-easy-mailchimp-extender#496]
Hi Guys,

We're having a little issue I'm hoping to get some help with. 

It's for this website: www.wyntersuncarnivalholidays.com

We went to a Carnival Expo event last week and had a lot of people show interest at our stall. People signed up to our newsletter on the spot, but we forgot to mention the Double Opt-in policy.

A lot of people didn't hit the double opt-in confirmation email. We also forgot to mention they had to. 

You can see 50 signups in our back-end: http://www.awesomescreenshot.com/image/1232046/b21a0182142bb74264bea6befb894e76

Please can you help us retrieve those emails by any chance? Do the submission get stored on system somewhere.

We just think it would be such a shame not to be able to contact those people. Many are busy and forget to confirm their subscription.

Help?

Thanks,

Gyles

**Comment by TheTracyL** [comment]
Hi Gyles,

The email address is not captured until they confirm the double opt-in. Additionally our form is just a means for your website to communicate with MailChimp. If those email address were captured in any way it would be on the MailChimp end. Our plugin does not store user data, it just displays that data from MailChimp.

Sorry we can't help you contact those folks.

Thank you!
-Tracy

**Comment by Gyles1** [comment]
Ok,

Thanks Tracy. Have a great week!
