### ISSUE TITLE
PHP 5.6 ?

### ISSUE THREAD

**Issue by danreitzdotcom** [yikesinc/yikes-inc-easy-mailchimp-extender#497]
Receiving this message:

> YIKES Inc. Easy Forms for MailChimp requires a minimum of PHP 5.3. The plugin will not function properly until you update. Reach out to your host provider for assistance.

We are running PHP 5.6

Is there a way to get the plugin to work again?

The site is http://www.davidzweig.com

**Comment by EvanHerman** [comment]
Hi Danreitzdotcom,

Who is the host provider? And what OS are you running? We haven't seen this issue reported before - so I'm wondering if it's something to do with your setup (nginx?).


Thanks!
Evan

**Comment by danreitzdotcom** [comment]
I just remembered he hosts his site on a different server.

Sorry to waste your time!

**Comment by EvanHerman** [comment]
Hey - No worries at all! I'm glad that it wasn't anything larger at hand, and you were able to get things resolved.

Thanks!
Evan
