### ISSUE TITLE
Cant assign fields to forms

### ISSUE THREAD

**Issue by LobsterDM** [yikesinc/yikes-inc-easy-mailchimp-extender#498]
Hi,
I'm trying to set up your MailChimp plugin. I've connected it to the mailchimp account and created a list in mailchimp. When I try to add the form in your plugin I get a blank page and can not assign the fields to the form.

Could someone help?

Thanks

**Comment by TheTracyL** [comment]
Hello.

Are you not seeing the lists? If so, this Knowledge Base article will give you the information you need on this issue.
https://yikesplugins.com/support/knowledge-base/im-not-seeing-all-my-lists-on-the-drop-down-menu-when-i-go-to-make-a-new-form/

Thank you!
-Tracy

**Comment by LobsterDM** [comment]
Hi,
No that's not the problem. When I try to edit the Form i've created I just
get a blank page - I can't assign fields in my form to the fields in the
list.

Russ

Many thanks
Russell




Russell Davies
Director

Follow me on Twitter <http://twitter.com/lobsterdm>

Lobster Digital Marketing
Tel: 02920 487822
Web: www.lobsterdigitalmarketing.co.uk



Registered in the UK under company number 4740318
VAT Registration No. 827 0433 43
Telephone: 02920 487 822
Email: info@lobsterdm.co.uk

**Comment by TheTracyL** [comment]
Hi Russell,

Did you try clearing the API cache? That may resolve that problem as well.

Are you starting with a new install or are you upgrading the plugin from version 5.x?

Thank you!
-Tracy

**Comment by LobsterDM** [comment]
New install and yes I cleared the cache



Russell Davies
Director

Lobster Digital Marketing Limited
Tel: 02920487822

Registered in the UK under company number 4740318

VAT Registration number 827 0433 43

**Comment by EvanHerman** [comment]
Hi Russel,

Who is your host provider? We had another user reporting similar issues when entering the API key, but it was due to CURL not being installed and active on the server.

See Issue #443 

Thanks,
Evan

**Comment by LobsterDM** [comment]
We use heart internet. Don't normally have any issues but I can ask them to look into it




Russell Davies
Director

Lobster Digital Marketing Limited
Tel: 02920487822

Registered in the UK under company number 4740318

VAT Registration number 827 0433 43

**Comment by LobsterDM** [comment]
Hi,
The hosting company have given this response. Is there anything you can do?

Russ

By default Curl is enabled on the shared hosting platform only for external
requests.
Unfortunately, if you require curl for internal request you will require a
VPS server.
You could also contact your developer and ask him if a workaround is
possible.

Many thanks
Russell




Russell Davies
Director

Follow me on Twitter <http://twitter.com/lobsterdm>

Lobster Digital Marketing
Tel: 02920 487822
Web: www.lobsterdigitalmarketing.co.uk



Registered in the UK under company number 4740318
VAT Registration No. 827 0433 43
Telephone: 02920 487 822
Email: info@lobsterdm.co.uk

**Comment by EvanHerman** [comment]
Hi Russel,

If you want to email us at plugins@yikesinc.com, we can discuss some options there. I can't think of anything that may be preventing access to the form creation/edit screen - but would be more than happy to work with you off of a public forum to get things up and runngin. If and when we can figure things out - we can post the solution here for others who may be facing similar issues.

Thanks,
Evan

**Comment by TheTracyL** [comment]
Support moved offline.
