### ISSUE TITLE
Some changes if possible to help

### ISSUE THREAD

**Issue by afromanperl** [yikesinc/yikes-inc-easy-mailchimp-extender#499]
Hello there,
Really sorry for bothering you, i know you are offering a free product i need your help on what i believe is an easy matter to solve. I am using your Easy Forms for MailChimp and i want to change 3 things but i don't know how to create classes and css and all of this coding stuff. I am using a single email form on top of my footer. What i want is :
-to make the submit button of the form blue-ish
-to move the button next to the email field so they are touching
-to remove the title email address
If you can help me at all by telling me what to change where i would really appreciate it. I 've looked in your support pages but i couldn't find anything that could help. What i found required to know more stuff which i dont know :(
Thanks a lot and keep up the good work

**Comment by TheTracyL** [comment]
Hello.

Can you please provide a link to the form on your site?

Thank you!
-Tracy

**Comment by afromanperl** [comment]
Hey thanks for the fast reply. www.wrightwatches.com bottom right footer

**Comment by afromanperl** [comment]
Did i gave a wrong link?

**Comment by TheTracyL** [comment]
No, it looks correct. I can see it. I can provide some code in a bit.

**Comment by afromanperl** [comment]
Perfect, thanks a lot TheTracyL

**Comment by TheTracyL** [comment]
There is not enough horizontal space in the footer area to allow the button to be inline with the email field. That is defined by your theme.

To hide the field label check out [the instructions on this blog post](https://yikesplugins.com/the-ultimate-guide-to-translating-mailchimp-forms-on-wordpress-sites/). Look towards the bottom under "Bonus Step – Translate the Placeholder Text"

Here is the CSS code you can use to change the button color. Change the value to adjust to the color you want.

```CSS
.yikes-easy-mc-form button.yikes-easy-mc-submit-button {
    background-color: blue;
}
```

You have a few options to add CSS code:

- If you created this theme yourself, you can just add it to your style.css file
- If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
- Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
- You can use a plugin like <a href="https://wordpress.org/plugins/simple-custom-css/">Simple Custom CSS</a> or Jetpack and enter the code in their Custom CSS area

Thank you!
-Tracy

**Comment by afromanperl** [comment]
Hey thanks, i do have a custom.css file that i can use to add the css if i want to do that what code do i need to place in it?
Also if i dot like the final outcome due to limited space how do i make the button light blue!

**Comment by TheTracyL** [comment]
I have the code pasted above in my last post. ^

**Comment by afromanperl** [comment]
From what i understood that code is only for the button color not the placement! Although now that i read it again means i cant place it next to it whatever the code because of the theme so is not an easy thing to do! I ll check when i get home the toggle field and the code and i will let you know asap if it worked

**Comment by TheTracyL** [comment]
Yes, you are correct. The button can not be placed inline with the form field, because there is not enough horizontal space in the footer widget areas. The width of those areas are defined by your theme.

You can see how wide they are if I put a border on them.

![image](https://cloud.githubusercontent.com/assets/1252286/15224881/b930a18a-1849-11e6-8cd4-7077b75f2919.png)

**Comment by afromanperl** [comment]
How about if i make the footer 3 columns will that help? Also i am using visual composer for the footer and i think i can set the width of each column

**Comment by TheTracyL** [comment]
Yeah, try playing with it until it displays inline.

**Comment by afromanperl** [comment]
I ll try that but wont i need a code for the button to be moved though apart from the color? In visual composer i can only expand the width of the column! I think i ll need a code to move the button aswell

**Comment by TheTracyL** [comment]
No, if you have [the form set to inline](https://yikesplugins.com/support/knowledge-base/how-do-i-place-all-of-my-form-fields-on-one-line/), it will become inline when it has enough horizontal space to do so.

**Comment by afromanperl** [comment]
Okay will try and let you know thanks so much

**Comment by TheTracyL** [comment]
Great!

**Comment by afromanperl** [comment]
Hey, i managed to put the color of the background and i also managed to change the color of the text. Although i expanded the column as we discussed but the email form got stretched now. Any idea?
Thanks

**Comment by TheTracyL** [comment]
Hi there.

I went to take a look and your site seems to not be loading CSS. :-/

![image](https://cloud.githubusercontent.com/assets/1252286/15249772/65f6a41e-18ef-11e6-8e8e-8795b63378d7.png)

**Comment by afromanperl** [comment]
Can you try again?

**Comment by TheTracyL** [comment]
Still looks the same. I tried in a couple browsers, cleared the cache, etc.

**Comment by afromanperl** [comment]
I tried 3 times now from 3 different browsers :S looks okay to me!
www.wrightwatches.com
wrightwatches.com
both links work fine

**Comment by TheTracyL** [comment]
Yeah, styles are still not loading for me. It's forcing https:// maybe that has something to do with it.

**Comment by afromanperl** [comment]
I've been trying to figure out how to fix that ssl problem all day today, and i cant!

**Comment by afromanperl** [comment]
Are you able to see the css now ?

**Comment by TheTracyL** [comment]
Now I'm getting an infinite loop.

![image](https://cloud.githubusercontent.com/assets/1252286/15251211/4f3ef738-18f6-11e6-9ea2-bb92a9375f58.png)

**Comment by afromanperl** [comment]
Now?

**Comment by TheTracyL** [comment]
Nope, sorry!

**Comment by afromanperl** [comment]
That's very weird, i cleared cookies and everything and however i write the address is opening fine :'/

**Comment by EvanHerman** [comment]
All of your content is being loaded via HTTP, whereas your site is attempting to load everything over HTTPS. You are running into a CORS (Cross-Origin Resource Sharing) problem.

You need to load all of your assets via HTTPS url, not the standard HTTP as you are now. For example - if all of your assets are being loaded properly (ie: via the wp_enqueue_script/wp_enqueue_style hooks) _and_ you changed the site URLs in 'General > Settings' - your assets should be loading properly.

If you are using a caching plugin you may want to disable the plugin while you set up the SSL certs.


Thanks,
Evan

**Comment by afromanperl** [comment]
Hey thanks for the detailed reply. Although in my settings i am running https:// for both urls
Also i am using w3total cache alongside cloudflare to  minify. and cache only cloudflare

**Comment by afromanperl** [comment]
I removed the w3tc try again pls

**Comment by EvanHerman** [comment]
I am still hitting the same error. Take a look at the screenshot I posted above. It is a side by side view of your site - and my developer console.

**Comment by TheTracyL** [comment]
I think we have to table this until the SSL issues are worked out :-) It's beyond the scope of our MailChimp plugin.

When you have this sorted let us know and I will take a look at the form in the footer widget.

Thank you!
-Tracy

**Comment by afromanperl** [comment]
Of course, the thing is to me it loads perfectly fine, how will i know if it will work for u ? :D

**Comment by EvanHerman** [comment]
I did just try loading it in a private browsing window - in Chrome and it now appears to be working for me. I also cleared my cache and it works in my regular browser. @TheTracyL Tracy can chime back in when she is ready.


Evan

**Comment by afromanperl** [comment]
Yea, delete w3tc and cloudflare alltogether, i never seem to configure them right!

**Comment by TheTracyL** [comment]
Ok, we're back in business.

Try this

```CSS
.yikes-easy-mc-form.yikes-easy-mc-form-1 label.label-inline {
    width: calc( 100% - 40% );
}

.yikes-easy-mc-form.yikes-mailchimp-form-inline empty-label.empty-label {
	display: none;
}
```

**Comment by afromanperl** [comment]
Didn't do anything :p

**Comment by afromanperl** [comment]
This is the whole code i have for the button

.yikes-easy-mc-form button.yikes-easy-mc-submit-button {
    background-color:#008dd6; 
color:white;
}

.yikes-easy-mc-form.yikes-easy-mc-form-1 label.label-inline {
    width: calc( 100% - 40% );
}

.yikes-easy-mc-form.yikes-mailchimp-form-inline empty-label.empty-label {
    display: none;
}

**Comment by TheTracyL** [comment]
The styles are not loading. Is there are server-side cache that needs to be cleared?

**Comment by afromanperl** [comment]
Yea just cleared them!

**Comment by TheTracyL** [comment]
Ok they are there now, it just took a minute.

One change, use this:

```CSS
.yikes-easy-mc-form button.yikes-easy-mc-submit-button {
	background-color:#008dd6; 
	color:white;
}

.yikes-easy-mc-form.yikes-easy-mc-form-1 label.label-inline {
    width: calc( 100% - 40% );
}

.yikes-easy-mc-form-1.yikes-mailchimp-form-inline .empty-label {
	display: none;
}
```

**Comment by afromanperl** [comment]
still doesnt match! Sorry for taking so much of your time by the way

**Comment by TheTracyL** [comment]
I see it working.

![image](https://cloud.githubusercontent.com/assets/1252286/15252708/3174f58e-18fd-11e6-84af-8fadb39af5c3.png)

**Comment by afromanperl** [comment]
Ah now i see it too, any way we can make the border of the button a bit smaller so it matches the your email address box ?

**Comment by TheTracyL** [comment]
```CSS
.yikes-easy-mc-form button.yikes-easy-mc-submit-button {
    background-color: #008dd6;
    color: white;
    border: 0;
    padding: 9px;
    min-height: 37px;
}
```

**Comment by afromanperl** [comment]
Perfect, thanks so much! where can i leave a review for the plugin?|??

**Comment by TheTracyL** [comment]
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy

**Comment by afromanperl** [comment]
Done :) username sporbillis

**Comment by afromanperl** [comment]
Hello it's me again, really sorry for bothering you again. I just configured w3 total cache to minify many stuff on the site and the button now went back to the original position. Any way we can fix it? I replied the code in the child theme but it doesnt work :(
Thanks
