### ISSUE TITLE
Downloaded impossible

### ISSUE THREAD

**Issue by lfaguer** [yikesinc/yikes-inc-easy-mailchimp-extender#500]
Hi
I buy Customized form. I receive the file to downlaoded. I do it, put it on my computer. Then impossible, in WordPress, to activate it.
Please help me as soon as possible.
Best
Laurence Faguer

**Comment by lfaguer** [comment]
Additionnal informations. It say :
L’archive n’a pas pu être installée. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature


My information
Single Site License: fd975f6b701352b6f78665580ab4b241


Purchase Information

Purchaser: laurence Faguer
Date: May 15, 2016

Subtotal: $29.99
Taxes: $0.00
Total: $29.99

**Comment by TheTracyL** [comment]
Hello. When do get this error? After you install it and try to activate it? Or are you unable to activate it at all?

**Comment by lfaguer** [comment]
Hi, thanks for your email.


I buy the Form Customizer for Easy Forms (bellow my receipt)
I download it

I store the files on my computer :


[image: Images intégrées 3]




When I open the file, I have these files :

 [image: Images intégrées 4]






When I go to my blog on Wordpress, to install the add-on, I click on the
files stored on my computer and I have the error message I sent to you
previously.

Thanks for your help, as it is important for me.

Best,

Laurence Faguer



[image: Images intégrées 2]

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-15 18:51 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Are you on a Mac? Macs sometimes automatically unzip zip files after download.

Please check out this article: https://wiki.umbc.edu/plugins/servlet/mobile#content/view/31919091

Let me know if that is the issue.

Thank you!
-Tracy

**Comment by lfaguer** [comment]
Tracy ,
thanks for your implication in helping me.
I really appreciate.

I follow your instruction (in the article), but it doesn't work,
In fact, when I download the file and keep it on my computer, I have this
link :
[image: Images intégrées 1]
Then I clic on the link with 'Choose' (to make it open), but then I arrive
on this list of files (bellow) and then I try each of them, it doesn't work.




[image: Images intégrées 2]


I always have this message:




[image: Images intégrées 3]


I should have receive a file with this name (zip) and I never receive a
file with this name;

[image: Images intégrées 4]




Other finding :

I read I have to add the key. Can you chek this point also ?

Thanks for your help, I really need this form.
Best


Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-15 19:59 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by lfaguer** [comment]
Tracy,
Is it possible to send me an other Zip file ?

Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-15 20:39 GMT+02:00 Laurence Faguer <lfaguer@gmail.com>:

**Comment by TheTracyL** [comment]
You can re-download it from the email. As long as you made those settings changes it should download as a zip and not automatically unzip.

**Comment by lfaguer** [comment]
Tracy, thank you.
I don't respond right away, as it was the night in France (where I am).
I do that.
Thanks 

Best,
Laurence

**Comment by lfaguer** [comment]
Tracy,
It doesn't work. Either in Safari or Chrome.
Please help me, as it going to be urgent. Must find a solution today.
Best
Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-15 21:41 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by mialevesque** [comment]
Bonjour.
S'il vous plaît, essayez:
1. Supprimer tous les fichiers que vous avez deja téléchargé.
2. Changer: Safari > Preferences > General > Open "safe" files after downloading: uncheck. (décochez)
l’image est ici: http://browsers.about.com/od/safar1/ht/safarisafefiles.htm
3. Il y a un lien dans l'e-mail pour télécharger le fichier zip. Il faut avoir une extension au format .zip. 
<img width="1069" alt="ajouter" src="https://cloud.githubusercontent.com/assets/1168142/15294136/fa423884-1b58-11e6-860c-cfe5960e164d.png">

Nous pouvons renvoyer l' e-mail si vous en avez besoin.
Cordialement,
Mia

**Comment by lfaguer** [comment]
Hi Mia,
Thanks a lot : it works!
I don't think I have done other things that previously, but it works,
thanks to your email !

Can I just ask you a question : now the extension is on my blog (bellow),
but how can I go to the page where I can configure a customized form ?

Thanks again for your help and the help of Tracy.
Best,

Laurence

[image: Images intégrées 1]

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com

**Comment by TheTracyL** [comment]
Great!

Here is our article on using the Customizer: https://yikesplugins.com/support/knowledge-base/form-customizer-for-easy-forms-for-mailchimp/

Let us know if that answers your questions.

Thank you!
-Tracy

**Comment by lfaguer** [comment]
Tracy


Thanks a lot !
I really appreciate your so fast answer. Wonderful Customer Relationship !

Best,

Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-16 18:33 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
We appreciate your kind words. We really want to help our customers.

Thank you!
-Tracy

**Comment by lfaguer** [comment]
Thanks. If you have a Twitter account on whish I can tweet a nice words, I
will do it.
Thanks again.
Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-16 18:35 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
We do have a Twitter - https://twitter.com/yikesinc

But better yet, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy

**Comment by lfaguer** [comment]
Thanks Tracy,
I do that with great pleasure, at the end of my day.

Best,

Laurence


Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-16 18:39 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by lfaguer** [comment]
Hi Tracy,
Sorry to come back again, but I have difficulties to edit the form.
My 2 questions :

#1 : When I edit the form, the form is edit  righ away on the firt post of
my blog. In fact; I would like to add the form at the bottow of a post in
particular, with the feature permitting to add the 'link' of the form. I
understant this process, but I don't understand how to stop having the form
at the top of the first post of my blog.

#2 : I buy the add-on 'customized form' but I can't see at what step I can
go to the features allowed by the add-on customized form (instead of an
easy form).

Thank you for your help.

Best,

Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-05-16 20:42 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Hi Laurence.

I'm not totally sure what you mean for #1. Would you mind explaining the issue in French? Then @mialevesque can take a look.

For #2, Were you able to install and activate the plugin? If so, you should see the customize options shown in this article: https://yikesplugins.com/support/knowledge-base/form-customizer-for-easy-forms-for-mailchimp/

Let me know.

Thank you!
-Tracy

**Comment by lfaguer** [comment]
Tracy, thank you. I will ask my question to your collegue @mialevesque
<https://github.com/mialevesque>

Thanks !

Best,

Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-06-02 18:23 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by lfaguer** [comment]
Hi Mia,
Je vous écris en Français, après avoir posé ma question à votre collegue en
anglais.
Merci pour votre réponse.
J'ai acheté et mis en place la version Add on 'Customized form'

#1 : Lorsque je fais "edit the form" le formulaire se place en haut de tous
mes posts. Alors que je voudrais utiliser le formulaire en le plaçant en
bas d'un seul de mes posts (pas sur tous les posts) et en ajoutant le lien
du formulaire (ou via la fonctionnalité avec la petite icone).

Merci pour votre aide qui m'est très précieuse !

Très sincèrement,

Laurence



Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-06-02 19:38 GMT+02:00 Laurence Faguer <lfaguer@gmail.com>:

**Comment by mialevesque** [comment]
Bonjour Laurence.
Merci pour l'information. Voulez-vous nous envoyer un lien vers votre site. Aussi, utilisez-vous un "shortcode"?

Merci encore,
Mia

**Comment by lfaguer** [comment]
Merci Mia.

Voici le lien vers mon site, sur wordpress :
http://customer-insight-consulting.com
Et le lien vers le 'centre de commande" ou j'accede à Easy Form :
http://customer-insight-consulting.com/wp-admin/

Ci-joint l'image du formulaire qui se place au dessus d'un post
Ma question : pourquoi le formulaire vient se place en haut de chaque post ?
Merci pour votre aide



Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-06-02 20:37 GMT+02:00 Mia Levesque <notifications@github.com>:

**Comment by lfaguer** [comment]
Bonjour,
Avez-vous bien reçu ma question ?
Merci !

(did you well received my question ?
Thanks !)

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com

**Comment by mialevesque** [comment]
Bonjour.
Nous voyons le formulaire en haut du colonne latérale (voir l'image "sidebar"). Ou voulez-vous le formulaire? Il n'est pas en haut de l'article singulaire. Peut-être que vous voulez le formulaire là ( voir l'image "article").
Merci.
Mia

![article](https://cloud.githubusercontent.com/assets/1168142/15779107/6ca1e7a4-2968-11e6-866b-1c4a22dd6dfa.png)
![sidebar](https://cloud.githubusercontent.com/assets/1168142/15779108/6ca20496-2968-11e6-8b7f-d5970c42585e.png)

**Comment by lfaguer** [comment]
Merci.
Le formulaire que vous pointez (fleche jaune) est un ancien formulaire créé
avant d'acheter Easy Form.
Vous trouverez ci-dessous l'image de ce qui apparait, quand j'utilise Easy
form.


Ma question:

Avez-vous un manuel correct : comment créer un formulaire?
J'avoue être très déçue, passer beaucoup de temps et depuis deux semaines
n'arriver  à rien du tout.

Cordialement

LF

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com

**Comment by mialevesque** [comment]
Bonjour Laurence.
Nous sommes désolés que vous avez éprouvé des problèmes. Nous avons une base de connaissances et un article qui devrait aider. Malheureusement, ils sont en anglais. Je les traduirais si cela vous aider.

Merci, 
Mia

La création de formulaires
https://yikesplugins.com/support/knowledge-base/creating-forms/ 

La Base de connaissances
https://yikesplugins.com/support/knowledge-base/product/usage-easy-forms-for-mailchimp/

**Comment by lfaguer** [comment]
Mia,
Thank you.
I already have had the link.
Again an afternoon lost to try to create and publish a form.
No succès.

By,
LF

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com

**Comment by TheTracyL** [comment]
Where, exactly, are you running into a problem? Are you seeing an error? What are the exact steps you are taking and where do things go wrong?

We really want to help you.

If you like, you could grant us a temporary admin login and let us make the form for you and see where things go wrong in the process. If you want to do that email us at plugins@yikesinc.com

We also have this video that demos the entire process:
http://youtu.be/NRZbW-Da1XA

**Comment by lfaguer** [comment]
Thank you Tracy.
I already saw the video.

My problem is that the form that I create goes directly to each post of my
blog, and at the top of each article (see picture attached).
My objective is to :
write an article
at the bottow of the article, to place the form (with short code or with
the little icone ).


Thanks to offer me to give you my code to let you make the form for me.
My code are on wordpress are :
customeric
PW : lolalola


Then a form would be :
*Sentence 'title' of the form :*

Recevez gratuitement votre document

*The row of the form:*
Prénom
Nom
Adresse mail professionnelle
Société


*Sentence when the person sumitt the form :*

Merci !



Thank you for your help. I really appreciate !

Best,

Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-06-04 18:12 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Hello,

Quick question: which list do you want to make a form for? You have a few and I want to make sure the form is connected to the correct list.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello again.

I took a look and I see here that you created a form and it is displaying at the end of the article, not at the top: http://customer-insight-consulting.com/2016/05/31/internet-retailer-demarre-dans-7-jours-a-chicago-%e2%96%ba-le-guide/

I do see that our styles are not loading though. I can have our programmer look at that. But otherwise I don't see the problem with forms appearing at the top of articles. I am really sorry, I'm still not 100% understanding the issue.

Thank you!
-Tracy

**Comment by lfaguer** [comment]
Thank you Tracy !
I really appreciate your help.

The list is : Inscrits CIC
There is just 1 person in it. Because my purpose is to have more people
giving me their email adress (as prospects for my business of consultant).
Thanks again for your help.
Best,

Laurence

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-06-05 15:58 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by lfaguer** [comment]
Tracy,
Thank you for the help you provide me.
I appreciate.
Unfortunately, the form doesn't sinchro on my blog (Image bellow).
So I will try to delete it and forget Easy chimp.
Sorry about that, but thanks trying.
Best,

Laurence

The form

Laurence Faguer
Customer Insight
Mobile : 06 12 83 39 28
Twitter : https://twitter.com/lfaguer
lfaguer@customer-insight.fr
www.customer-insight-consulting.com



2016-06-05 17:35 GMT+02:00 Laurence Faguer <lfaguer@gmail.com>:
