### ISSUE TITLE
Installation of Form Customizer for Easy Forms for MailChimp

### ISSUE THREAD

**Issue by chiaramerlin** [yikesinc/yikes-inc-easy-mailchimp-extender#501]
I just bought an add on for my YIKES Easy Forms for MailChimp to use on WordPress (latest version).
When I try to install it I get a message telling that it's impossible to copy the file. yikes-inc-easy-mailchimp-form-customizer-extension/includes/classes/customizer/additional-fields/form-submit-button-width-slider-field-control.php

What do I have to do?
Thanks

**Comment by EvanHerman** [comment]
Hi chiaramerlin,

What is the exact message that you are receiving? I haven't encountered any issues during installation - but I can double check to confirm that there are no errors on my end.

Thanks,
Evan

**Comment by chiaramerlin** [comment]
I try to install the add on from the "add plugin" page on Wordpress.
This is the message:
impossible to copy the file. yikes-inc-easy-mailchimp-form-customizer-extension/includes/classes/customizer/additional-fields/form-submit-button-width-slider-field-control.php

Just asking: do I have to remove the free version before installing the add on?

Thanks

**Comment by EvanHerman** [comment]
No, the add-on should be installed right alongside the free version. I will do some research to try and figure out what's going on. I've never seen that error before in WordPress itself, and I don't think that error is built into our plugin.

Evan

**Comment by chiaramerlin** [comment]
Thank you so much.
Waiting..... and hoping :)

**Comment by EvanHerman** [comment]
Do you have any security plugins installed by chance? From what I've found so far - it seems like a security measure or something similar. Is this is a single site, or multi-site install?


Thanks,
Evan

**Comment by chiaramerlin** [comment]
I don't think I have security plugins. No, no... I just have Mail Chimp widget and a Slider.
It's a single site install.

**Comment by EvanHerman** [comment]
Hi chiaramerlin,

Can you email us at plugins@yikesinc.com, maybe we can login and attempt an install on our end - to see if we too are running into the issue.

Thanks,
Evan

**Comment by chiaramerlin** [comment]
Thank you anyway for the help
