### ISSUE TITLE
No indication that form has been pressed...

### ISSUE THREAD

**Issue by naujavan** [yikesinc/yikes-inc-easy-mailchimp-extender#502]
Hi, 

When I click on the submit button on a form I've created. There is no indication, i.e (Spinning wheel or Hour Glass) that the form has been pressed.  The form is pretty quick to respond but should there be something to inform the user?

Thanks

**Comment by EvanHerman** [comment]
Hi Naujavan,

This is on our list of "To Dos" for a future release - ideally the next patch that we put out will include this.

See Issue #353

Thanks!
Evan

**Comment by TheTracyL** [comment]
Hi Naujavan,

I am going to close this ticket, because it's on the list of features for the next release.

Thank you!
-Tracy
