### ISSUE TITLE
oh no can't collect submits

### ISSUE THREAD

**Issue by jrd99** [yikesinc/yikes-inc-easy-mailchimp-extender#503]
have built the form to submit to mail chimp but the submit doesn't submit.  please help.  www.w3faithchurch.com

Thanks 
JD

**Comment by TheTracyL** [comment]
Hi JD.

Please take a look at our article with troubleshooting steps for this issue: https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

JavaScript conflicts are usually the cause of this issue.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi JD,

Just checking in. Did that article help?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi JD,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
