### ISSUE TITLE
error yikes-inc-easy-mailchimp-extender

### ISSUE THREAD

**Issue by micolf** [yikesinc/yikes-inc-easy-mailchimp-extender#504]
Warning: Invalid argument supplied for foreach() in /home/jj1fiwjf/public_html/otveyewear.com/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 999

**Comment by micolf** [comment]
my web site is http://www.otveyewear.com

**Comment by EvanHerman** [comment]
Hi,

What fields do you have assigned in your form builder vs what is set up in MailChimp? Do you have any interest groups setup and assigned to the form? What are the field labels of each field?


Thanks,
Evan

**Comment by micolf** [comment]
yes the check box for privacy policy

**Comment by micolf** [comment]
Interest Groups
Select a field below to add to the form builder.

Select an interest group below to add to the form builder.
PRIVACY POLICY checkboxes

**Comment by EvanHerman** [comment]
The privacy policy is an interest group checkbox field setup on MailChimp - with just one option?


Evan

**Comment by micolf** [comment]
<img width="1636" alt="schermata 2016-05-27 alle 16 00 27" src="https://cloud.githubusercontent.com/assets/442142/15610172/3130efc4-2424-11e6-9edd-1c3187231682.png">

**Comment by micolf** [comment]
<img width="1367" alt="schermata 2016-05-27 alle 16 05 29" src="https://cloud.githubusercontent.com/assets/442142/15610309/dfbf2790-2424-11e6-9cb9-fd26a8e01efc.png">

**Comment by EvanHerman** [comment]
What are the field labels of each field?

**Comment by micolf** [comment]
<img width="1258" alt="schermata 2016-05-27 alle 16 24 07" src="https://cloud.githubusercontent.com/assets/442142/15610822/8d429ca6-2427-11e6-9424-615db9226be8.png">

**Comment by micolf** [comment]
ok now it's correct
i save again my form
and now the plugin works

thanks so much

**Comment by EvanHerman** [comment]
Great - I'm glad that you were able to get things resolved. 

I'm not sure what might have happened - but very happy to hear that things are working for you.

If you have any other issues, feel free to reach back out.

Thanks again!
Evan
