### ISSUE TITLE
Can I use the form code instead of the shortcode

### ISSUE THREAD

**Issue by SteveReview** [yikesinc/yikes-inc-easy-mailchimp-extender#505]
Hi there,

I have a plugin that lets me add the mailchimp form code into the area but it doesn't accept the shortcode that YIkes Easy Mailchimp creates. How can I use the code that the Yikes Easy Mailchimp creates instead of using the short codes?

Thank you,
Steve

**Comment by TheTracyL** [comment]
Our plugin is not set up to do that. The code alone wont work properly.

Does the other plugin accept php code?
