### ISSUE TITLE
Custom Tab Title appears again within the tab. I need the repeat off please.

### ISSUE THREAD

**Issue by famtastic** [yikesinc/yikes-inc-easy-mailchimp-extender#506]
I don't know why anyone would want to repeat the Custom Tab Title again in the tab itself - but that's how it's set up and could you please tell me how to get rid of that repeat in the tab?

Thank you!!

**Comment by TheTracyL** [comment]
Hello.

This has been answered in this thread: https://github.com/yikesinc/yikes-inc-easy-custom-woocommerce-product-tabs/issues/32

Thank you!
-Tracy
