### ISSUE TITLE
Site Origin Page builder issue saving the widget form IDs.

### ISSUE THREAD

**Issue by SusanneBexten** [yikesinc/yikes-inc-easy-mailchimp-extender#507]
Hi,
in changelog 6.0.3 the bugfix was reported:
"Fix Site Origin Page builder issues saving the widget form IDs."

With the actual version 6.0.5.5 I'm having that exact issue. I have two different forms with different settings, but the widget in my homepage (using page builder from siteorigin / vantage theme) keeps setting it back to the wrong one.

Maybe you re-introduced the bug with one of the latest updates?
Is there a workaround or can you fix that soon?

Kind regards
Susanne

**Comment by EvanHerman** [comment]
Hi Susanne,

We will take a second look into the issue. The original user of the plugin was in talks with the developers behind the site origin plugin. From what I gathered, the patch was necessary to come from them - as the site builder plugin was the one causing the issue.

Here are the resources in relation to that issue:
https://wordpress.org/support/topic/with-pagebuilder-plugin-the-proper-form-is-not-chosen
https://siteorigin.com/thread/problem-with-easy-forms-for-mailchimp-widget/

We will have to take a look and double check the issue. We don't recommend page builders as they seem to cause more harm than good - but we can see why people would use them. I will have to install both plugins and set up a test instance before I can come up with a solution to the issue.


Thanks,
Evan

**Comment by SusanneBexten** [comment]
Hi Evan,
thanks for the reply. I am responsible for a number of different wordpress-sites and I use siteorigins page builder a lot. When I first used the easy mailchimp forms widget, it was version 6.0.3 or later and everything was fine. I don't know the version when the problem first occured - I just realised it yesterday with version 6.0.5.5. Then I looked in the changelog and read that the exact same behavior was an issue before and fixed with version 6.0.3. That's why I think you already have a solution for the problem. At least I hope so :)

**Comment by TheTracyL** [comment]
Hi Susanne,

If you follow those threads you'll see there is a patch the Site Origin folks need to make to permanently fix the issue: https://siteorigin.com/thread/problem-with-easy-forms-for-mailchimp-widget/#comment-82633

Also, I just tested the Page Builder with our plugin and I can see it and select it under widgets.

![page builder](https://cloud.githubusercontent.com/assets/1252286/16674665/752c51bc-4488-11e6-9dc5-8f296432d352.png)

When I add it using the Page Builder it shows up on my site.

I'm not sure why it's working for you. Let me know if you took other steps to create the issue.

Thank you!
-Tracy
