### ISSUE TITLE
Adding a form to a post

### ISSUE THREAD

**Issue by beckyj17** [yikesinc/yikes-inc-easy-mailchimp-extender#508]
I am trying to add an opt in form to a post but it isn't working. I pasted the short code but when I preview the post instead of displaying the form it says "Whoops, it looks like you forgot to assign fields to this form."

**Comment by EvanHerman** [comment]
Hello,

We will need more information than what you have provided us.

Have you actually created a form, and assigned fields to it? What is the shortcode you are using? What is the ID of the form that you created?

The information you have provided us is not nearly enough for us to help debug the issue at hand. Screenshots, a link to your site or some other visual indicator will also help us provide you with better support.

Thank you,
Evan

**Comment by beckyj17** [comment]
I created the form and assigned the fields then started a new post and used the mailchimp button to select the form I wanted. I have attached screen shots so you can see what I am talking about.


________________________________

**Comment by EvanHerman** [comment]
If you are replying to this via email, it is recommended that you actually head over to the GitHub site.

Your screenshots are not visible on my end (On the github site).

Thanks,
Evan

**Comment by TheTracyL** [comment]
Hi Becky,

Please go to https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/508 and post the screen shots there. That way we will be able to see them.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Becky,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
