### ISSUE TITLE
Issue with Visual Compose plugin integration

### ISSUE THREAD

**Issue by olegGist** [yikesinc/yikes-inc-easy-mailchimp-extender#510]
Hi,

There is an issue when inserting [yikes-mailchimp] shortcode via Visual Composer plugin - form id is not saved in params if 1-st form is selected.

To fix this you need to add 'save_always' option for 'form' attribute in 'visual-composer.php' on line 46, something like this:

`
array(
				  "type" => "dropdown",
				  "holder" => "div",
				  "class" => "",
				  "heading" => __( "MailChimp Opt-In Form", "yikes-inc-easy-mailchimp-extender" ),
				  "param_name" => "form",
				  "value" => self::yikes_mailchimp_retreive_user_created_forms(),
				  "description" => __( "Select which form to display.", "yikes-inc-easy-mailchimp-extender" ),
				  "save_always" => true,
				),
`

Thanks!

**Comment by EvanHerman** [comment]
Hello,

Thank you. We will take a look into the issue. We do not have access to visual composer, so we will have to take your word for it.

This will have to be included in a future release, and will be added to our to-do list.

Thanks,
Evan
