### ISSUE TITLE
RSS Feed Error

### ISSUE THREAD

**Issue by EvanHerman** [yikesinc/yikes-inc-easy-mailchimp-extender#515]
Make it so no error is thrown if RSS feed is not available.

**Comment by TheTracyL** [comment]
@EvanHerman Instead of fixing this bug, let's move the files locally and get rid of the RSS feed to make sure we are in compliance with WP Plugin directory guidelines.

**Comment by EvanHerman** [comment]
This issue has been patched in the latest release of Easy Forms for MailChimp v6.1.

Any and all reference to RSS feeds over at yikesplugins.com has been removed, and bundled locally.
