### ISSUE TITLE
Customize Profile Validation Message

### ISSUE THREAD

**Issue by EvanHerman** [yikesinc/yikes-inc-easy-mailchimp-extender#525]
Add option to customize Profile validation message and email for I8n.

_(needs clarification)_

I believe this is in reference to :

"user@example.com is already subscribed to the list. To update your MailChimp profile, please click to send yourself an update link."

**Comment by TheTracyL** [comment]
Yes, that is correct. This message, and the verification email message the user receives currently can not be translated. 

I was thinking we could add it to the "Custom Messages" tab. If the verification email is toggled off we can hide that section.

**Comment by EvanHerman** [comment]
This issue has been patched in the latest release of Easy Forms for MailChimp v6.1.

We have gone ahead and added a new field under the 'Custom Messages' tab, where users can customize the MailChimp response.

Users can set their own 'Update' link, by wrapping text in a `[link][/link]` tags.

**Screenshot:**
![Custom Messages](https://cldup.com/UxWnmRTuj8.png)
