### ISSUE TITLE
WordPress PopUp Plugin Conflict

### ISSUE THREAD

**Issue by EvanHerman** [yikesinc/yikes-inc-easy-mailchimp-extender#527]
Investigate `Whoops, it looks like you forgot to specify a form to display.` error with the [WordPress PopUp](https://wordpress.org/plugins/wordpress-popup/) plugin.

__Note:__
This seems to only occur on the dashboard. Front end still works fine.

**Comment by TheTracyL** [comment]
I am closing this now that we offer our own popup plugin.
