### ISSUE TITLE
Custom Form Columns

### ISSUE THREAD

**Issue by EvanHerman** [yikesinc/yikes-inc-easy-mailchimp-extender#532]
Define hooks/filters to allow users to specify a custom column on the 'View List' page (remove and/or add additional columns alongside 'Email Client').

This may require re-writing the way our admin table is generated, and building in filters to allow for users to define new columns and set up the data to display.

**Comment by TheTracyL** [comment]
Closing this because user profile endpoints are not in v3 of the  API.
