### ISSUE TITLE
Vivian

### ISSUE THREAD

**Issue by vivianharte** [yikesinc/yikes-inc-easy-mailchimp-extender#538]
I  have Easy Forms for Mail Chimp by YIKES.  I want my users to give me their names and e-mail addresses to get free kits and reports from throughout my website.  Many of these people will already be on my list since I'll be sending out newsletters to my list to introduce them to these free things.  Now people from my list get a message that they're already on the list and are not allowed to download anything free from my site.

1 - How do I eliminate "Email already subscribed" in Custom Messages?
2 - How do I allow people on my list to download free things on my website or people who have already downloaded something free and who are now on my list to download other free things on my website?

**Comment by TheTracyL** [comment]
Hi Vivian,

It seems like what you really want to do is offer your subscribers premium content. Our plugin is not meant for that exact purpose, it would better be handled with a membership plugin or a restricted content plugin. However, even though that is the case, I do think you can achieve what you want with our plugin. It's a little hack-y but it will work.

1. Under [Opt-in Settings](https://yikesplugins.com/support/knowledge-base/opt-in-settings/) set **Update Existing Subscriber** to "Yes" and **Send Update Email** to "No." With these settings users will update their current profile with the info they enter into the form.

2. Under [Submissions Settings](https://yikesplugins.com/support/knowledge-base/submission-settings/) set **Redirect On Submission** to Yes and select the page or post with the download. You will need to create a form and page for each download you want to offer.

I hope this helps!
-Tracy

**Comment by vivianharte** [comment]
Hi, Tracy,

Thank you so much!  I see where to do these changes.

Vivian
​ Harte​

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
Awesome! Glad I could help.
-Tracy

**Comment by vivianharte** [comment]
Oops!  I should have tried it first before I replied.  When I entered my
husband's name and e-mail, this came up in a red box:

solartoby@gmail.com is already subscribed to the list. To update your
MailChimp profile, please click to send yourself an update link
<http://self-esteem-for-me.com/free-kit-reach-your-goals-and-create-positive-habits/#>
.

When I clicked on the link, this came up:

✕ Error sending update profile email. *Error: API keys belonging to users
with "manager" roles are not permitted to access helper/account-details*.
Please contact the site administrator.

So this isn't working as I had hoped.

Vivian
​ Harte​

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by EvanHerman** [comment]
My recommendation would be to refresh your API key, or generate a new one altogether. For some reason the API you have provided does not have the correct user access, so you are unable to properly access the necessary API endpoints.

You need 'Admin' permissions, not 'Manager' permissions.

Thanks,
Evan

**Comment by TheTracyL** [comment]
Also, do you definitely have **Send Update Email** set to No?

![update](https://cloud.githubusercontent.com/assets/1252286/16781260/5e7abff8-4848-11e6-9efe-f4ced229fdfb.png)

I just tested toggling on and off the Send update email and it worked for me.

**Comment by vivianharte** [comment]
I put in a new API Key.  There is no "Send Update Email."  There is only
"Send Welcome Email."

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
It looks like you need to update to the latest version of our plugin. We added that feature today.

**Comment by vivianharte** [comment]
How do I update?

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
Go to Dashboard > Updates and you should see our plugin listed there.

This site has a nice guide to updates: https://www.sitepoint.com/a-guide-to-updating-wordpress/

**Comment by vivianharte** [comment]
It works!  I just updated the plugin and it works just fine.  Thanks so
much for your help!

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by vivianharte** [comment]
I wanted to let you know that the little box that comes up after the user
clicks the button to download the free report has so much language that I
couldn't get all the way through it before it switched to the page I
directed them to.  It would be better to either have less language in the
box or allow the user to have more time to read what's in the box before
the new page is loaded.

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>
