### ISSUE TITLE
Problem with Inline Form

### ISSUE THREAD

**Issue by vivianharte** [yikesinc/yikes-inc-easy-mailchimp-extender#540]
When I put "Enable" in the Inline Form part of Form Settings, on the page I get a large purple line that says:

"Warning: Division by zero in /home/content/64/2689764/html/coursesite/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 245

Warning: Division by zero in /home/content/64/2689764/html/coursesite/wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 246"

Then at the bottom of this is the following:
"Whoops, it looks like you forgot to assign fields to this form.
Edit Form"

Please tell me what to do to make this work.

Thanks so much!

**Comment by TheTracyL** [comment]
Hello.

That error shows when there are no fields assigned to the form.

Go to the form you are trying to place on that page and make sure there are fields assigned to it.

Thank you!
-Tracy

**Comment by vivianharte** [comment]
Hi, Tracy,

Thanks for getting back to me so quickly.  I looked at the form, and now I
understand "fields" means "first name," "last name," and "e-mail address."
I added those, and it works fine.

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
Great!
