### ISSUE TITLE
Button is not at the same level at the email field

### ISSUE THREAD

**Issue by etereshchenkova** [yikesinc/yikes-inc-easy-mailchimp-extender#544]
First, thanks for the great plugin! It looks great and easy to use.

I haven't changed anything on my website, but for some reason the form now looks like this: 

<img width="1022" alt="2016-07-16 22 50 45" src="https://cloud.githubusercontent.com/assets/20494348/16896835/a2cce09e-4bb0-11e6-8124-76ac59a9b98f.png">

I know that I probably should change something in css, but I'm not sure what. Any advice?

Thanks!

**Comment by TheTracyL** [comment]
Hello,

This is a known issue (https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/542) and I am really sorry about that.

We are working on a fix, but in the meantime, this CSS code should fix it:

```
.yikes-easy-mc-form .empty-form-inline-label .empty-label {
    display: inherit;
}
```

Let me know if you need any more help.

Thank you!
-Tracy

**Comment by etereshchenkova** [comment]
Hi Tracy,

Thanks for getting back to me.

The CSS code doesn’t seen to work. I tried pasting it both via the Simple Custom CSS plugin and directly into style.css file, the result is the same.

Is there any other way to solve this issue?

All the best,
Elena
-----------------------------------------------------------
Elena Tereshchenkova
English to Russian Translator
Marketing, Travel & Lifestyle

Web: wordsboutique.com <http://www.wordsboutique.com/>
Twitter: @etereshchenkova <https://twitter.com/etereshchenkova>
Skype: wordsboutique
Phone: +7 (903) 604 94 49




> 16 июля 2016 г., в 23:07, Tracy Levesque <notifications@github.com> написал(а):
> 
> .yikes-easy-mc-form .empty-form-inline-label .empty-label {
>     display: inherit;
> }

**Comment by TheTracyL** [comment]
Can you please post a link to your form?

**Comment by etereshchenkova** [comment]
Sure, the form is at the end of the page: http://ilovemondays.ru/alexandra-franzen-11-07-2016/
-----------------------------------------------------------
Elena Tereshchenkova
English to Russian Translator
Marketing, Travel & Lifestyle

Web: wordsboutique.com <http://www.wordsboutique.com/>
Twitter: @etereshchenkova <https://twitter.com/etereshchenkova>
Skype: wordsboutique
Phone: +7 (903) 604 94 49

**Comment by TheTracyL** [comment]
Hello,

Add an !important to the style and you should be all set. Like this:

```
.yikes-easy-mc-form .empty-form-inline-label .empty-label {
    display: inherit !important;
}
```

Thank you!
-Tracy

**Comment by etereshchenkova** [comment]
Hi Tracy,

It’s working! Thank you!
-----------------------------------------------------------
Elena Tereshchenkova
English to Russian Translator
Marketing, Travel & Lifestyle

Web: wordsboutique.com <http://www.wordsboutique.com/>
Twitter: @etereshchenkova <https://twitter.com/etereshchenkova>
Skype: wordsboutique
Phone: +7 (903) 604 94 49

**Comment by TheTracyL** [comment]
Awesome!

You're welcome!
-Tracy
