### ISSUE TITLE
yikes mail chimp plugin Submit not working

### ISSUE THREAD

**Issue by Annamal1** [yikesinc/yikes-inc-easy-mailchimp-extender#548]
Hey all I am working on a few sites and can't get the plugin to submit to the form and therefore no one can sign up does anyone have any fixes?

here is the URL
http://resonate.coach/

**Comment by TheTracyL** [comment]
Hi there,

Can you try the suggestions we have in this Knowledge base Article?
https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

Please let us know if that helps.

Thank you!
-Tracy
