### ISSUE TITLE
Unique Success message for existing subscribers & other custom messages.

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#552]
When an existing subscriber fills out a form, they get the same message as a new subscriber:

> Thank you for subscribing!

They should get a different message, something like:

> Thank you for already being a subscriber. Your profile has been updated.

We also need this added to "Custom Messages" for I8n and general customizableness :-)

**Comment by IrishKnight** [comment]
In addition to unique success message it would be also helpful to have a unique Thank you page for existing and new subscribers. 

For example, existing subscribers will see an actual bonus content page. And new ones will be redirected to "Please confirm your email" page.

**Comment by TheTracyL** [comment]
- [ ] Create the unique success message for existing subscribers and add to Custom Messages in the admin
- [ ] Break up single and double opt-in success messages and add them to Custom Messages in the admin
- [ ] Add the profile update verification email to Custom Messages in the admin
