### ISSUE TITLE
Attempting to install Yikes Pop-Up gives disconnection message.

### ISSUE THREAD

**Issue by Chalcifer** [yikesinc/yikes-inc-easy-mailchimp-extender#554]
Hello, I've bought the Yikes pop-up extension, downloaded it, and attempted to install it. I keep getting the same error message:

The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

This does not happen when I tried installing EU extension from your site. 
Any ideas?

**Comment by TheTracyL** [comment]
Hello,

I Googled the issue and it looks like a browser cache issue: 

- https://support.mozilla.org/en-US/questions/1024256
- https://support.mozilla.org/en-US/questions/1056868

Can you try clearing your cache? Here are instructions:
http://www.refreshyourcache.com/en/home/

Let us know how that goes.

Thank you!
-Tracy

**Comment by Chalcifer** [comment]
Tried that, erased my cookies. Same problem persists.

Benoit Chartier
Director of communications for OIW


Date: Fri, 29 Jul 2016 13:01:03 -0700

**Comment by Chalcifer** [comment]
Also tried with Explorer, with much the same result.

Benoit Chartier
Director of communications for OIW


Date: Fri, 29 Jul 2016 13:01:03 -0700

**Comment by TheTracyL** [comment]
Hello can you please submit a premium support ticket so we can help you there? 

There are instructions in the email receipt you received when you bought the add-on.

Thank you!
-Tracy

**Comment by Chalcifer** [comment]
I cannot enter my license key into my web site,
since I cannot unzip the file I purchased.
This is my license key:
58c4b88dd806240a9643d3c44f7aa6ac

Benoit Chartier
Director of communications for OIW


Date: Fri, 29 Jul 2016 13:20:08 -0700

**Comment by TheTracyL** [comment]
Hello,

There should be an email address for support in your email receipt you can use to create a ticket if you can not access the form.

Thank you!
-Tracy
