### ISSUE TITLE
"<email>  is an invalid email address." not translated.

### ISSUE THREAD

**Issue by n3t0cfg** [yikesinc/yikes-inc-easy-mailchimp-extender#555]
Hello:

I've been setting my response messages to french but there's a case where doesn't seem to be translated.

Is all good here, when is not a valid email address:

![French Result ](https://cloud.githubusercontent.com/assets/1394795/17299147/ac4e2a64-57d2-11e6-9bc9-930b641183b1.png)

But this case is not translated and is also an invalid email address.

![22](https://cloud.githubusercontent.com/assets/1394795/17299146/ac4c488e-57d2-11e6-96c4-034a79a0599e.png)

I've also set a few days ago the default language to french for API messages and forms:

![33](https://cloud.githubusercontent.com/assets/1394795/17300951/4992fa5a-57da-11e6-9506-2f351fd57837.png)

Plugin version: 6.1.3

**Comment by EvanHerman** [comment]
Hello,

The messages are generated and returned from MailChimp. If things are not translated properly, something may not be translating on there end. I would recommend reaching out to them and asking them why the messages return via the API are not translated, even tho the settings are set to french.

You can still customize the message from within the plugin. Take a look at the knowledge base article on the settings we have setup for customizing the message:
https://yikesplugins.com/support/knowledge-base/custom-form-messages/

Thanks,
Evan
