### ISSUE TITLE
Already subscribed

### ISSUE THREAD

**Issue by vivianharte** [yikesinc/yikes-inc-easy-mailchimp-extender#556]
There are a few places on my website where people can give their e-mail address, such as a free report and signing up for my blog.  In the Message section, there is this text: Already subscribed:  "Given email address is already subscribed, thank you!"  How can I get rid of that, send people a thank you message for the newsletter even when they've given it to me for something else, and make it so people can give me their e-mail address for several things on my site without being rejected??

**Comment by TheTracyL** [comment]
Hi Vivian.

You can adjust that under Opt-in settings: https://yikesplugins.com/support/knowledge-base/opt-in-settings/

Set "Update Existing Subscriber" to Yes and they will update their profile with the information they enter if they it matches an email address that is already subscribed. 

For security, we send the user a link to update their profile. Without that a user would only need another person's email address to change their information. However, you can turn that off under "Send Update Email"

Thank you!
-Tracy

**Comment by vivianharte** [comment]
Thanks, Tracy.  I changed the "Update Existing Subscriber" to "Yes".  I
couldn't find "Send Update Email" under any or the tabs.  Where can I find
it?

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
It should be right under "Update Existing Subscriber" If you don't see it you probably need to update to the newest version of our plugin.

![send update email](https://cloud.githubusercontent.com/assets/1252286/17410409/9180d774-5a41-11e6-867c-fb5838e08508.png)

**Comment by vivianharte** [comment]
I haven't been told of any new updates to this plugin.  It's 6.1.3. Is
there a newer update that hasn't come to me yet?

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
Hi Vivian,

6.1.3 is the newest version.  I don't know why the Send Update Email options would not be there. Can you please send a screen shot of what you are seeing?

Thank you!
-Tracy

**Comment by vivianharte** [comment]
Here it is.

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
Hi Vivian,

You need to post it to the [Github issue tracker](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/556#issuecomment-237626731). Attachments don't come through from replying to the email.

Thank you!
-Tracy

**Comment by vivianharte** [comment]
Here it is again.
[Yikes form.docx](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/files/402308/Yikes.form.docx)

**Comment by TheTracyL** [comment]
Hi Vivian,

That is actually not our plugin, it is another MailChimp plugin.

No worries, though! If you need help with our plugin in the future we'll be happy to help.

Take care,
-Tracy

**Comment by vivianharte** [comment]
I'm confused.  This is the link to github to get help with this plugin.  I went to the plugin itself, clicked on "View Details" then scrolled to the bottom of the page and clicked on "If you experience any problems, please submit a New Issue on our Github Issue Tracker. We respond to issues regarding the free plugin within a week."  You are Yikes, aren't you?  This is where the plugin said to go to help, isn't it?

**Comment by TheTracyL** [comment]
Hi Vivian,

Yes, we are YIKES and the developers of Easy Forms for MailChimp. However, the screen shot you gave me is of a different plugin - MailChimp for WordPress.

![image](https://cloud.githubusercontent.com/assets/1252286/17413506/752b96b4-5a4f-11e6-98f6-6a92138baaf7.png)

Our settings screen looks like this:
![image](https://cloud.githubusercontent.com/assets/1252286/17413538/9461e18c-5a4f-11e6-853d-a8ea1e7c4749.png)

Their support forum is here: https://wordpress.org/support/plugin/mailchimp-for-wp

Thank you.
-Tracy

**Comment by TheTracyL** [comment]
If you send me a link to your form I can help determine which plugin you are actively using.

**Comment by vivianharte** [comment]
Thank you, Tracy.  My mistake.  I fixed it on their plugin.  Should I still
keep it "Update Existing Subscriber" on yours?

Vivian

Co-Author, *Self-Esteem for Dummies*
520-883-8880
www.self-esteem-for-me.com <http://www.self-esteem-course.com>

**Comment by TheTracyL** [comment]
Only if you are also using our plugin. If not, then you don't need to adjust the settings.

Thank you!
-Tracy
