### ISSUE TITLE
How to add placeholder text to dropdown

### ISSUE THREAD

**Issue by msaz** [yikesinc/yikes-inc-easy-mailchimp-extender#559]
I have a form.

In the form I added a dropdown field for "How Did You Hear About Us?".

<img width="792" alt="screen shot 2016-08-06 at 11 38 46 pm" src="https://cloud.githubusercontent.com/assets/10932652/17460934/d5ee9f88-5c2e-11e6-8847-06930ddf992a.png">

The way the form is displayed, the user cannot see the field labels (e.g. First Name, Last Name).

The user only sees the placeholder text (e.g. "First Name *", "Phone Number").

<img width="295" alt="screen shot 2016-08-06 at 11 37 52 pm" src="https://cloud.githubusercontent.com/assets/10932652/17460932/aef7ed1c-5c2e-11e6-9ad9-4961e1bec965.png">

BUT, I can't get the placeholder text for the dropdown field to appear ("How did you hear about us? *").

How can I get placeholder text for the dropdown field to be displayed just like the placeholder text  for the non-dropdown fields are being displayed?

**Comment by TheTracyL** [comment]
Hi There.

Select boxes don’t currently support the ‘placeholder’ attribute. What people usually do it make the first item "Select how you heard about us" and make that the default choice. There are also JavaScript workarounds, but they are not built into our plugin.

Also, for our plugin, labels and placeholders are managed in the Form Builder: https://yikesplugins.com/support/knowledge-base/hide-field-labels/

Thank you!
-Tracy
