### ISSUE TITLE
yikes css stylesheet is not loaded on several pages

### ISSUE THREAD

**Issue by czoper** [yikesinc/yikes-inc-easy-mailchimp-extender#560]
Hi,

I'm using the Yikes plugin for Mailchimp. I have it set up so that it is shown under every post on the page.
However, a few days ago I discovered that it looks differently for different posts and I'm not able to pinpoint the exact thing that causes it, eg.

http://www.tropimy.com/route-66/ this one looks ok (the form is at the bottom)
http://www.tropimy.com/los-angeles-san-francisco-nowy-film-usa/ this one however looks wrong,

The problem is that the stylesheet for the plugin is not loaded in the second post. I do not know why that happens, the second post contains iframe with youtube video, I thought the iframe may be a cause, but in other places I have google maps embedded also in an iframe, and the form looks ok there.

I'd appreciate if you could point me in any direction how to check it. I'll be happy to provide more info if required.
Cheers
Przemek

**Comment by EvanHerman** [comment]
Hi Przemek,

I'm not sure why the stylesheet isn't being loaded on that page. It looks like you are using some form of minification plugin to combine the stylesheets, and serve a single file.

Can you try disabling your minification plugin and re-testing to see if the stylesheet loads properly?

The stylesheet should load wherever the shortcode or widget is being used.


Thanks,
Evan

**Comment by czoper** [comment]
Hi Evan,

sorry for the delay - I was away from computer for the extended weekend.
I tried disabling the minification plugin and clearing the cache even
before I setup the issue on github - unfortunately it did not help.
I think this might be somehow connected with some specific combination of
content and plugin, but I don't have a test environment for Wordpress to
check which plugin may cause this.

Does the loading of the stylesheet depend on anything?
Cheers,
Przemek

2016-08-12 16:48 GMT+02:00 Evan Herman <notifications@github.com>:

**Comment by czoper** [comment]
Hi Evan,
one thing that I forgot to mention is that I'm not putting the form shortcode inside a post or widget directly, but through registering a filter adding content to all blog posts. The function looks like that:

`add_filter('the_content', 'append_content_text'); 
function append_content_text($content) {
    if(!is_single()) {
	return $content;
    }
    $content .= do_shortcode('[yikes-mailchimp form="1" title="1" description="1" submit="Submit!"]');
    return $content;
}`

And that call expands the form shortcode, however - with the youtube video above the form the stylesheet is not loaded (the <link rel="stylesheet" id="yikes... is not there with or without the minification plugin). I tried calling wp_enqueue_style() with absolute path to the yikes stylesheet in my append_content_text function, but it did not help.

Is there anything more I can do to try to fix it?

**Comment by TheTracyL** [comment]
Hi Czoper,

Just checking in on this issue. Are you still having this problem?

Thank you!
-Tracy

**Comment by czoper** [comment]
Hi Tracy,

I did a workaround on this problem by manually including the stylesheet on
pages that have the form, but it's a hack.
I suspect that if I turned the hack off, the stylesheet would not be loaded
properly as I described in the bug report.

Kind regards,
Przemysław "Czoper" Czatrowski

2016-11-04 16:29 GMT+01:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Hi Czoper,

Thank you for the update. 
Let us know if you need anything else!
-Tracy
