### ISSUE TITLE
Create form not working

### ISSUE THREAD

**Issue by pwpyle62** [yikesinc/yikes-inc-easy-mailchimp-extender#561]
New install. Connected to Mail Chimp account. Went to create a form. After filling in name, description, and attach to list...nothing happens. No form is created or added to form list.
WP 4.5.3
Beaver Builder Plugin (Pro Version) - Version 1.8.4

**Comment by EvanHerman** [comment]
Hi,

What happens when you create the form? Does the page refresh?

Can you try disabling your other plugins and re-testing. Another plugin may be overriding our re-direct.


Thanks,
Evan

**Comment by pwpyle62** [comment]
Yes. It refreshes.

**Comment by EvanHerman** [comment]
Can you try disabling your other plugins and re-testing. Another plugin may be overriding our re-direct.

If it still does not work, please try switching themes with the plugins disabled.

Report back here with your findings.


Thank you,
Evan

**Comment by TheTracyL** [comment]
Hello,

Just checking in on this issue. Were you able to follow the troubleshooting steps above?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello.

We haven't heard back from you in awhile, so I am going to close out this ticket.

If you need further help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
