### ISSUE TITLE
several KILLED QUERY errors filling up my servers logs. 

### ISSUE THREAD

**Issue by joe704la** [yikesinc/yikes-inc-easy-mailchimp-extender#563]
The error below is being thrown over and over again on my wordpress site. I just installed this plugin yesterday. Any Ideas?

This is part of the code that appears to be causing the error and causing the very long query to be killed. We have thousands of posts it is trying to pull into the query. 

// loop over registered post types, and query!
foreach( $post_types as $registered_post_type ) {
// exclude a few built in custom post types
if( ! in_array( $registered_post_type , array( 'attachment' , 'revision' , 'nav_menu_item' ) ) ) {
// run our query, to retreive the posts
$pages = get_posts( array(...

Here is part of the error it throws. I shortened it to post here. But it was much longer showing thousands of post ids.
Mon Aug 15 23:28:10.460525 2016] [:error] [pid 22817] [client] KILLED QUERY (72434 characters long generated in ...wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php:1561): SELECT t.*, tt.*, tr.object_id FROM wp_terms AS t INNER JOIN wp_term_taxonomy AS tt ON tt.term_id = t.term_id INNER JOIN wp_term_relationships AS tr ON tr.term_taxonomy_id = tt.term_taxonomy_id  WHERE tt.taxonomy IN ('event-tags', 'event-categories') AND tr.object_id IN (11520, 11776, 11521, ...

**Comment by EvanHerman** [comment]
Hi Joe,

What version of WordPress is your site running? There shouldn't be any errors when querying and looping over the post types, removing them etc.

What version of PHP does your server run?

I haven't seen that error popup before for any of our users, so I'm curious as to what may be the root of the problem.


Thanks,
Evan

**Comment by joe704la** [comment]
We are using WordPress version 4.5.3
We are using PHP version 5.5.9

We use https://wpengine.com/ for hosting

**Comment by EvanHerman** [comment]
Does it say where the errors are coming from?

Can you paste a few lines from your error logs here?

We run this plugin on a few wpengine installs without any issue, so it's strange you are encountering issues on their platform.

Can you try de-activating and re-activating the plugin? Maybe the necessary tables don't exist in the database (even tho there should be an error message if that is the case).

Thanks,
Evan

**Comment by joe704la** [comment]
It seems to be coming from this loop. I am guessing if you just do a find for the comment in the code "// loop over registered post types, and query!" you will see where the issue is. 

// loop over registered post types, and query!
foreach( $post_types as $registered_post_type ) {
// exclude a few built in custom post types
if( ! in_array( $registered_post_type , array( 'attachment' , 'revision' , 'nav_menu_item' ) ) ) {
// run our query, to retreive the posts
$pages = get_posts( array(...


This is most of the error, scaled back to fit in here. 

Mon Aug 15 23:28:10.460525 2016] [:error] [pid 22817] [client ] KILLED QUERY (72434 characters long generated in ...wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php:1561): SELECT t., tt., tr.object_id FROM wp_terms AS t INNER JOIN wp_term_taxonomy AS tt ON tt.term_id = t.term_id INNER JOIN wp_term_relationships AS tr ON tr.term_taxonomy_id = tt.term_taxonomy_id WHERE tt.taxonomy IN ('event-tags', 'event-categories') AND tr.object_id IN (11520, 11776, 11521, ...

**Comment by joe704la** [comment]
I did just deactivate and reactivated the plugin. But still seems to be throwing the error.

**Comment by EvanHerman** [comment]
If you can email us at info@yikesplugins.com we would more more than happy to take a first hand look. It would be much easier trying to find a solution if I can see it first hand. 

I can't think of anything off the top of my head that would cause the issue.


Thanks,
Evan

**Comment by joe704la** [comment]
I tried emailing that email and it failed.

**Comment by TheTracyL** [comment]
Sorry about that! It should be plugins@yikesinc.com

**Comment by EvanHerman** [comment]
@joe704la Sorry about that Joe!
