### ISSUE TITLE
Submit not working

### ISSUE THREAD

**Issue by emmettculley** [yikesinc/yikes-inc-easy-mailchimp-extender#564]
Researched all the documentation.  We had one form that was working, but then changed to a different Mailchimp account, and not it does not work.  There is no response at all. 
*We have the response message added
*All the fields are mapped
*We even used single click for faster test response
* we have hide form after submission

Any suggestions?

**Comment by EvanHerman** [comment]
Hi emmettculley,

Does the form work if you switch it to non-Ajax? It's possible you have a JavaScript error on your page and our scripts are not working properly. 

Can you share a link to the form for further investigation?

Thanks,
Evan

**Comment by emmettculley** [comment]
I'll check the Ajax setting .  In the meanwhile.  Here is the site:  http://soulmateplan.com

**Comment by TheTracyL** [comment]
Hi Emmett,

Did you test the Ajax setting? Let us know how it went.
Here is an article on this specific issue: https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Emmett,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
