### ISSUE TITLE
Popup Extension - How to get popup on home page

### ISSUE THREAD

**Issue by MaryGMB** [yikesinc/yikes-inc-easy-mailchimp-extender#565]
How can I get my newly created popup to pop up on the home page? The home page for this site is not in the page list under "Popup Location", and that's the only page I want it on.

By the way, my client really likes your MailChimp plugin, and so do I.
Mary B.

**Comment by TheTracyL** [comment]
Hi Mary.

I just checked the page settings, and I can see the home page on the list of pages:

![home](https://cloud.githubusercontent.com/assets/1252286/17832295/65444658-66cd-11e6-8184-8ba4a4653722.png)

Is the page maybe not named "Home" on your site? What is the first page that comes up on the list after the word "Page" in bold?

Thank you!
-Tracy

**Comment by MaryGMB** [comment]
On this site, the homepage is dynamically generated from the theme options settings. The theme in use is a child theme based on CyberChimps' Responsive theme. The home page is not actually a "page" in the database - so is not available in the list. The first page in the list is "About Karen". If I choose that page, the popup appears when I load that page, so we know everything is working correctly.

When my(Karen's) home page is loaded and the popup is triggered, it needs to ignore the fact that I have selected neither Global Popup or a page from the list, and just look at my selection for Conditionals. I did select the conditional "Display on front page", but that doesn't seem to trigger the popup.

**Comment by TheTracyL** [comment]
Hi Mary,

Did you try using the Conditional "On a Specific URL?"

![image](https://cloud.githubusercontent.com/assets/1252286/17832662/4660cc08-66d6-11e6-867f-6137a8c07996.png)

The the theme is generating this page from theme options "Front Page" may not work because our plugin uses the page that is set as the "Front Page" under settings.

Please let me know if adding the home page URL works there. I hope it does because if the Home page is not an actual post or page our plugin may not have anything to hook into to trigger  the popup.

And thank you for the kind words about our plugin!
-Tracy

**Comment by MaryGMB** [comment]
I just now put http://karenbentley.com into that conditional and tested. No joy. That's what I expected - the function I referenced requires 'something' to be selected in the Popup Location section in order to trigger the popup.

**Comment by MaryGMB** [comment]
Well, I figured out a workaround. I coded a custom template that works with the theme option settings for the home page, and created an actual page and assigned it my new template. It's a pretty clunky solution, but it works. I'm sure I'm not the only person using a theme that features a custom home page that isn't really a page or a post. Might be worth looking into if you want your plugin to be compatible with these themes.  :o)

**Comment by TheTracyL** [comment]
Hi Mary,

Sorry about the inconvenience of having to find a workaround, but I am glad you were able to find a solution.

The theme you are using is free, so we can test it out and find a better fix.

Thank you for bringing this to our attention.
-Tracy
