### ISSUE TITLE
Global Popup Doesn't Display on Home

### ISSUE THREAD

**Issue by lepittenger** [yikesinc/yikes-inc-easy-mailchimp-extender#567]
I'm using the "Easy Forms for MailChimp Popup Extension by YIKES" add-on to make a popup with "Popup Location" set to Global but it doesn't appear on the home page. All of the "Popup Conditionals" are unchecked.

**Comment by TheTracyL** [comment]
Hi Lauren,

Do you have the newest version? You may have an early one. It's up to 1.06 I believe.

Let us know!
-Tracy

**Comment by TheTracyL** [comment]
Oh, also, if your theme does not have a real home page that is set as the "front page" under settings and instead uses theme settings to generate a home page, that can be an issue as well.

**Comment by lepittenger** [comment]
Hi Tracy,

Thanks for getting back to me! Sorry for my delay - I expected to get an email alert about a reply and didn't get one for some reason.

Anyway, for whatever reason, the plugin wasn't showing an available update on the staging site where I'm working (behind a password). I downloaded the new version and have that running and it seems to be working on the home page now. Thanks for pointing that out to me!

Lauren

**Comment by TheTracyL** [comment]
Yay!
