### ISSUE TITLE
Preloader Image

### ISSUE THREAD

**Issue by Pixelous** [yikesinc/yikes-inc-easy-mailchimp-extender#569]
Hi,

can you please add filter for replacing built-in preloader image with custom one?

**Comment by TheTracyL** [comment]
We'll add this to the suggested to-do list.

Thank you!
-Tracy

**Comment by EvanHerman** [comment]
Hey Pixelous,

We should already have a filter in place to handle this:

`yikes-mailchimp-preloader` - This is the preloader image that gets overlaid on AJAX forms.

and

`yikes-mailchimp-loading-dots` - These are the loading dots on the submit button, when an AJAX Form is submitted.

Both can be found in [public/partials/shortcodes/process_form_shortcode.php](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/75f6d6b453f3ed63955d294abef78ab1f2ce1e16/public/partials/shortcodes/process_form_shortcode.php#L346-L347).

An example usage of each filter:

```php
/**
 * Alter the preloader image that is overlaid on the AJAX forms
 * @param string $url The URL to the preloader image you want to use (default: admin_url( 'images/wpspin_light.gif' ) )
 */
function alter_yikes_mailchimp_preloader( $url ) {
   return 'https://www.groupecreditagricole.jobs/bundles/casarhcasajobs/images/preloader.gif';
}
add_filter( 'yikes-mailchimp-preloader', 'alter_yikes_mailchimp_preloader' );
```

```php
/**
 * Alter the three dots gif that gets added to the submit button on AJAX forms.
 * @param string $url The URL to the three dots preloader image you want to use (default: YIKES_MC_URL . 'includes/images/loading-dots.gif' )
 */
function alter_yikes_mailchimp_three_dots( $url ) {
   return get_stylesheet_directory_uri() . '/images/some_loading_gif.png';
}
add_filter( 'yikes-mailchimp-preloader', 'alter_yikes_mailchimp_three_dots' );
```

**Comment by Pixelous** [comment]
Thanks.
