### ISSUE TITLE
Possible to use a signup form designed on mailchimp embedded on a wordpress page?

### ISSUE THREAD

**Issue by ssandra001** [yikesinc/yikes-inc-easy-mailchimp-extender#570]
Hi,
I appologize if I am not clear in my question, I am not a professional developer or anything..

I have created a Mailchimp signup form (the one that gives you a link) and I like the way that one looks. Now I would like to use that exact form embedded in a wordpress page so I don't have to send people to a site outside of my own.

1. Is this even possible?
2. If it is possible, how do I do this?

(I am not asking how to embed a normal sign up form on a wordpress page. I am asking how to embed a signup form that I have already edited with colors and text size, etc, to embed that to a WP page.)

Thanks in advance for any help you can possibly give me!!

Thanks!

**Comment by TheTracyL** [comment]
Hello.

If you are designing the form in your MailChimp account, that is a question you need to ask MailChimp. You need to ask them if they provide embed code to embed that exact form.

With our plugin you can add a form to any post, page or widgetized area on a WordPress site, but to get it looking like the form you made in MailChimp you will need to use CSS or our Customizer.

Thank you!
-Tracy

**Comment by ssandra001** [comment]
Thanks, that's what I thought! Would have loved if that was possible in a simple way, but I guess not.... :) Thanks for the quick answer anyway!!
