### ISSUE TITLE
Customized message + more

### ISSUE THREAD

**Issue by LouiseWinkler** [yikesinc/yikes-inc-easy-mailchimp-extender#573]
Hi,
I tested my customized messages, for example trying to subscribe twice with the same email. 
My message shows, but also "To update your MailChimp profile, please click to send yourself an update link"

What do I need to change to get rid of that part of the message?

kind regards,
Louise

**Comment by TheTracyL** [comment]
Hi Louise,

When you are already subscribed to a list, it will update your profile (if you have it set to update). We added that email verification step as a security measure to make sure it was the actual subscriber making that change and not someone else.

You can turn that security step off. Here is our article with instructions: https://yikesplugins.com/support/knowledge-base/turn-off-email-verification-profile-updates/

Thank you!
-Tracy

**Comment by LouiseWinkler** [comment]
Hi Tracy,

I must have been unclear. I d want to keep the security step, but I don't want the message about the email verification to be in english, since my site is in swedish.

Also the email that I get to verify the updates are in english. Is it possible for me to write my own message in swedish instead.

Kind regards,
Louise

**Comment by TheTracyL** [comment]
I am very sorry I misunderstood your question.

You can translate the link message. It should be last option under custom messages. We added that option in the last update of our plugin so if you do not see it you may need to update it to the latest version.

Unfortunately, we do have a way to translate the verification  email folks receive. We have that on our to-do list, because we understand the ability to translate all text is very important.

Thank you!
-Tracy

**Comment by LouiseWinkler** [comment]
No problem! :)
Ah, now I understand what that message was all about.

But I don't get it to work.
I translated the message: Vill du uppdatera din Mailchimp profile? [link] Klicka här så får du ett mejl med en uppdateringslänk[/link]
The message show, but, I get this error message after clicking the link: _Error sending update profile email. Error: Invalid MailChimp List ID: . Please contact the site administrator.

I tried again with the standard message and it works, I click the link, get the confirmation email and confirm my updates.

What do I do wrong this time? :)
Louise
