### ISSUE TITLE
"Edit form" under my sign up form

### ISSUE THREAD

**Issue by LouiseWinkler** [yikesinc/yikes-inc-easy-mailchimp-extender#574]
Hi,
I have installed your plug in and made all the set up succesfully.
Except that under my sign up form it says "Edit form". When I click it I get to the page to edit my email list.

what have I done wrong!

kind regards,
Louise

**Comment by TheTracyL** [comment]
Hello Louise,

You have done nothing wrong, the edit link it there for you as a logged in admin so you get to the form builder if you need to make a edit.

Only people who are logged into your dashboard with admin privileges see that link.

Thank you!
-Tracy
