### ISSUE TITLE
Renaming inline JSON

### ISSUE THREAD

**Issue by szepeviktor** [yikesinc/yikes-inc-easy-mailchimp-extender#575]
The current name is `object` for the inline JSON array.
Please consider a specific name, something like `yikes_easy_mc_data`
Thanks.

1. https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/1df65a8079251f400502716aeaf404493b750407/admin/js/yikes-inc-easy-mailchimp-extender-edit-form.js#L85
1. https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/ee5f7fec444bcd94c0aab9fefb58438eb473157b/admin/partials/dashboard-widgets/class.list-activity-widget.php#L26
1. https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/ee5f7fec444bcd94c0aab9fefb58438eb473157b/admin/partials/menu/lists.php#L41
1. https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/75f6d6b453f3ed63955d294abef78ab1f2ce1e16/public/partials/shortcodes/process_form_shortcode.php#L342
1. https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/9371182deb0bfadc7236fc23fcf91d6bd85048ec/admin/class-yikes-inc-easy-mailchimp-extender-admin.php#L694

**Comment by szepeviktor** [comment]
I was also wondering why every field of the post object is necessary.

**Comment by EvanHerman** [comment]
Hi @szepeviktor,

We certainly will consider changing this in the next release. I can see how this would cause some issues if another plugin is using 'object' to localize the data into their scripts.

To answer your second question, not all of the post object data is necessary. We included this so users could make use of the data. This was an oversight, and in hindsight we should just be passing in the $post->ID. Users would still have access to the post data using `get_post()` .

We will look into changing this as well.

Thanks,
Evan

**Comment by JPry** [comment]
This has been completed with c19de541450f4075a1c0dadf578c544e6d023493. Once this has been merged to `master`, this can be closed.

**Comment by szepeviktor** [comment]
Thank you!

Your progress is slow but **steady**

**Comment by szepeviktor** [comment]
@JPry You may say *Closes #575* in the commit message and GitHub will close this issue.

**Comment by JPry** [comment]
> @JPry You may say Closes #575 in the commit message and GitHub will close this issue.

Yes, I'm aware. I just happened to commit and push before I remembered. 😄

**Comment by szepeviktor** [comment]
Thank you.

Please consider validating the API key in yikes_get_mc_api_key().
Something like a forgiving regexp...
