### ISSUE TITLE
Need some help with CSS

### ISSUE THREAD

**Issue by stephaniecan** [yikesinc/yikes-inc-easy-mailchimp-extender#576]
Hi,

First of all, **thanks for this great plugin!** 
It's the only Mailchimp plugin that does exactly what I want and solve the problems that I add by only using the Mailchimp embedded forms (issues when embedding multiple forms).

I changed the mailchimp embedded forms CSS to make the forms look good on my website but I haven't been successful with tweaking your CSS... That's why I **need some help from you with CSS**. 

I am using WordPress with the avada theme so I can use custom CSS easily (my website is in "coming soon mode").

I have **two forms** (one for each list) which can **use the same CSS**. The only change is that **one of them only requires the email field**.
 
**Here are all the files for the indications below:** [Dropbox folder](https://www.dropbox.com/sh/2p6jyzs8uzdrvge/AAArqlAgNL4jhvJmaTwRvKDVa?dl=0).

**First form ("blog"):**
- mailchimp-blog-form.png: first mailchimp embedded form with style I want
- yikes-blog-form.png: how your form appears without changing CSS
- mailchimp-blog-form.txt: my custom mailchimp embedded form CSS

**Second form ("digital analytics"):**
- mailchimp-digital-analytics-form.png: second mailchimp embedded form with style I want
- yikes-digital-analytics-form.png: how your form appears without changing CSS
- mailchimp-digital-analytics-form.txt: my custom mailchimp embedded form CSS

Thanks a lot for your help!
Stephanie

**Comment by TheTracyL** [comment]
Hi Stephanie.

If you can provide a link to your forms I can give you the custom CSS you need to make the forms look the way you want. Every site is unique and without being able to inspect the code I wont be able to determine the exact CSS you need.

Thank you!
-Tracy

**Comment by stephaniecan** [comment]
Thanks for your quick reply Tracy :)

What do you mean by a link to my forms? 
The txt files with the **full code of the forms** aren't enough?
My website is in "coming soon mode" right now.

Sorry I am not a super tech-savy :)

**Comment by TheTracyL** [comment]
Hi Stephanie.

The code you provided is the MailChimp embed code. I would need to inspect the code generated by our plugin on your site, because the selectors are completely different.

Thank you!
-Tracy

**Comment by stephaniecan** [comment]
Thanks Tracy,

Are the following what you need? The code generated by your plugin on my page? 
Let me know if you need more than that.

[yikes-blog-form.txt](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/files/474716/yikes-blog-form.txt)
[yikes-digital-analytics-form.txt](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/files/474717/yikes-digital-analytics-form.txt)

Thank you :)
Stephanie

**Comment by TheTracyL** [comment]
Hi Stephanie.

I need to inspect the forms on your site using a browser. There are style sheets that get loaded by your site's theme, our plugin, and other plugins that affect the way the forms look. Without access to the form on your site, I can't reproduce the same environment on my computer.

I do understand your site is not live yet. If you would like to contact us privately about this you can use our contact form: https://yikesplugins.com/about/contact/

Thank you!
-Tracy

**Comment by stephaniecan** [comment]
Ok no worries, you just needed to ask (as I'm not a super tech-savy, I didn't know exactly what you needed).

I've put my website live until you are done. My website is new and you are super quick & effective so that's ok ;)

The webpage with both forms generated by your plugin: [http://www.stephaniecanovas.com/about/](http://www.stephaniecanovas.com/about)

Thanks a lot!!
Stephanie

**Comment by TheTracyL** [comment]
Hi Stephanie.

Please give this a try to start. We can further tweak from there.

#yikes-mailchimp-container-2 .yikes-easy-mc-form label.label-inline.EMAIL-label {
    margin-left: 134px;
}

```CSS
.yikes-mailchimp-container .yikes-easy-mc-form .yikes-easy-mc-submit-button {
	background-color: #f16334;
	border: 0;
	color: #fff;
	font-size: 15px;
	font-weight: 600;
	font-family: 'Lato';
	border-radius: 2px;
}
```

Thank you!
-Tracy

**Comment by stephaniecan** [comment]
Thanks a lot Tracy.

I added your custom CSS. However, I would like more customization...

- Get some margin between the form fields and the "background of my grey section" (with my mailchimp CSS I used width:210px for the name field, width:280px for the email and width:140px for the button. It was perfect).
- Lato font for the placeholders
- Font size of 16px for the placeholders (and 18px for the button as long as it doesn't get non-aligned. If not everything at the same 16px or 18px)
- Button hover with another color? #D5420F
- height:40px for all fields?

Basically about that:
#mc_embed_signup input.required {font-family: Lato; font-size: 16px; border: 1px solid #cccccc; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; color: #202020; background-color: #F8F8F8; box-sizing:border-box; height:40px; padding: 0px 0.4em; display: inline-block; margin: 0; width:210px; vertical-align:top;}
	#mc_embed_signup input.email {font-family: Lato; font-size: 16px; border: 1px solid #cccccc; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; color: #202020; background-color: #F8F8F8; box-sizing:border-box; height:40px; padding: 0px 0.4em; display: inline-block; margin: 0; width:280px; vertical-align:top;}
	#mc_embed_signup .button {font-family: Lato; font-size: 18px; font-weight:bold; border: 2px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; letter-spacing: .03em; color: #fff; background-color: #f16334; box-sizing:border-box; height:40px; line-height:32px; padding:0 18px; display: inline-block; margin: 0; transition: all 0.23s ease-in-out 0s; width:140px;}
	#mc_embed_signup .button:hover {background-color:#D5420F; cursor:pointer;}
	
Thanks a lot for your help Tracy!!
Stephanie

**Comment by TheTracyL** [comment]
Hi Stephanie,

I went to take a look and I see the forms were replaced with a MailChimp embed form. If you need any more help, just let me know.

Thank you!
-Tracy
