### ISSUE TITLE
Newletter pop up is not popping up

### ISSUE THREAD

**Issue by mmgood** [yikesinc/yikes-inc-easy-mailchimp-extender#577]
Hi all – I have a blog MmGood.com and the plug in easy forms for newsletters…the pop up for the plugin doesn’t come up any longer. I tried to do an update and still I am having an issue, any suggestions?

Thank you in advance!

Patty

**Comment by TheTracyL** [comment]
Hello Patty,

Are you using our Pop-up addon or another popup?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Patty.

I took a closer look at your site and it looks like you are using a different MailChimp plugin and a script called "Featherweight" to make the popup. I get the modal for the popup, but not the form itself.

Thank you!
-Tracy

**Comment by mmgood** [comment]
Thank you for getting back to me, looks like I am using yours.Patty


-------- Original Message --------
Subject: Re: [yikesinc/yikes-inc-easy-mailchimp-extender] Newletter pop
up is not popping up (#577)

**Comment by mmgood** [comment]
I do not have a different plug in or anything called featherweight as I just looked it up...


-------- Original Message --------
Subject: Re: [yikesinc/yikes-inc-easy-mailchimp-extender] Newletter pop
up is not popping up (#577)

**Comment by TheTracyL** [comment]
Hi Patty.

Our scripts and styles are not loading on the site, but I do see files from this one loading: https://wordpress.org/plugins/mailchimp-wp/

Do you have a page with the form on it?

Thank you!
-Tracy

**Comment by mmgood** [comment]
I am using mailchimp


-------- Original Message --------
Subject: Re: [yikesinc/yikes-inc-easy-mailchimp-extender] Newletter pop
up is not popping up (#577)

**Comment by TheTracyL** [comment]
Hi Patty.

I don't think you are using our MailChimp plugin, though. This is our plugin: https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/

If you can send me a link to one of your forms, I can determine exactly what plugin you are using.

Thank you!
-Tracy

**Comment by mmgood** [comment]
I'm using:Easy Forms for MailChimp by YIKESMailchimp Forms by Optin CatHow do i send you the link to forms?  I can set up a log in to my wordpress?  Thank you for your help!!!Patty


-------- Original Message --------
Subject: Re: [yikesinc/yikes-inc-easy-mailchimp-extender] Newletter pop
up is not popping up (#577)

**Comment by TheTracyL** [comment]
Hi Patty,

Those are 2 different plugins and it seems to me you are using the Optin Cat one.

If you have a form on any of the pages of your site (the front-end, public pages of your site), I can take a look at it and determine exactly which plugin you are using.

Thank you!
-Tracy

**Comment by mmgood** [comment]
Tracy -I've added you to my accountLogin:  tracyPassword:  MailchimpPatty


-------- Original Message --------
Subject: Re: [yikesinc/yikes-inc-easy-mailchimp-extender] Newletter pop
up is not popping up (#577)

**Comment by TheTracyL** [comment]
Hi Patty,

I removed the login info you posted, because it's really dangerous to have login info posted publicly.

I don't need access to your dashboard, I only need to see a signup form on your site, the part of your site the public can see. With that I can take a peek at the code and see which plugin you are using. 

I do believe you are using the Optin Cat plugin, because it's files are loading in the background and ours are not. Also, our base plugin does not have a pop-up, that is a paid add-on.

Thank you!
-Tracy

**Comment by mmgood** [comment]
Thank you for removing the information. I looked up my plugins and did a search on option cat and nothing showed up

**Comment by TheTracyL** [comment]
It's Optin Cat (not option cat). This one: https://wordpress.org/plugins/mailchimp-wp/

Can you send me a link to a page of your site with a form on it? I can figure out the exact plugin you are using if you do that. Also, we do not have a pop-up add-on included with our free plugin. 

Did you purchase this? https://yikesplugins.com/plugin/pop-ups-easy-forms-mailchimp/

That is the only way we provide pop-up functionality.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
