### ISSUE TITLE
problem with formatting of interest groups on form

### ISSUE THREAD

**Issue by SteveCavill** [yikesinc/yikes-inc-easy-mailchimp-extender#580]
Hi,
When I add interest groups to a form, the check boxes don't line up with the text of the interest group option.  I have attached a screenshot.  Not sure if this is a general problem or an issue specific to my theme (Brunch Pro on Genesis framework).
An additional issue may be an enhancement rather than a bug, but the form allows you to add a description. to the field.  This is added AFTER the field, which in the case of a interest group selection doesn't make a lot of sense, it would be more sensible above the field to explain the choices.
In my screenshot, the description is "Choose the options you want"
![yikes](https://cloud.githubusercontent.com/assets/22495776/18911827/77c18160-85c2-11e6-94d1-9ae57fd64865.jpg)

Thanks, Steve

**Comment by TheTracyL** [comment]
Hi Steve.

The formatting of your checkboxes is controlled by your theme's styles. If you give me a link to your form, I can help you adjust those styles.

I understand what you mean by the description being below the field. In the meantime, you could change it to "Choose the options you want, above" and with the checkboxes tightened up it will flow a lot better.

Thank you!
-Tracy

**Comment by SteveCavill** [comment]
Hi Tracy,
thanks a lot :)
The link to the form is http://test.thermofun.com/wp/wp-admin/admin.php?page=yikes-mailchimp-edit-form&id=1
Can I send you the username and password in a private message?
Thanks, Steve

**Comment by TheTracyL** [comment]
Hi Steve.

I don't need access to your admin. I only need the link to the page with the form on your site.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Steve,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
