### ISSUE TITLE
Customize My Newsletter Opt In Form

### ISSUE THREAD

**Issue by Bejn1978** [yikesinc/yikes-inc-easy-mailchimp-extender#581]
I want to change some part of my registration block to my newsletter:

- When I write my email or my name, my writing is white on white (look at the picture), I would like to change the color of writing to black.

- I would like to change the font of the opt in form to my website main font ("noto sans").

- I would like to change the color of the button too.

Can you help me please?

![capture 077](https://cloud.githubusercontent.com/assets/22632283/19108022/33217614-8aef-11e6-9467-9f2f393a5d64.JPG)

**Comment by TheTracyL** [comment]
Hello,

Can you please provide a link to your form?

Thank you!
-Tracy

**Comment by Bejn1978** [comment]
Hello Tracy,

I have found the answer to my questions with my theme support.

BUT, I do not like the graphisms of loading after clicking "suscribe"
(circle which rotates with three points under), with a dark skin it is not
really esthetical. Picture 1
I would prefer nothing, I just want the suscribing confimation in green,
that's cool and enough for me. Picture 2

Can you help me please ?

My website is :
https://linactuel.fr

Thank you,
Regards,

Benjamin.

2016-10-05 14:47 GMT+02:00 Tracy Levesque <notifications@github.com>:

**Comment by TheTracyL** [comment]
Hello Benjamin,

Picture 1 and Picture 2 did not come through. Can you post them here: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/581#issuecomment-251664239

Thank you!
-Tracy

**Comment by Bejn1978** [comment]
Ok Tracy, sorry,

![capture x](https://cloud.githubusercontent.com/assets/22632283/19120362/d2afaa1a-8b22-11e6-9ecd-7baed7b1ea41.JPG) BAD

![capture x1](https://cloud.githubusercontent.com/assets/22632283/19120370/d85a9150-8b22-11e6-83b6-770524a3a5fc.JPG) GOOD

(I'm french, I do my best to be understandable :))

**Comment by Bejn1978** [comment]
up :)

**Comment by TheTracyL** [comment]
Bonjour Benjamin,

This should take care of it:

```CSS
.yikes-mailchimp-preloader, img.loading-dots {
	display: none;
}
```

**You have a few options to add CSS code:**

- If you created this theme yourself, you can just add it to your style.css file
- If you're using a theme you downloaded or bought you can [make a child theme](https://codex.wordpress.org/Child_Themes#How_to_Create_a_Child_Theme) and add the code to your child theme's style.css file
- Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.</li>
- You can use a plugin like [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/) or Jetpack and enter the code in their Custom CSS area

Thank you!
-Tracy

**Comment by Bejn1978** [comment]
Thank you very much !
Very good job ;

best,

Benjamin.

**Comment by TheTracyL** [comment]
Super! I'm so glad I was able to help.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy
