### ISSUE TITLE
Unable to Change default interest group choices in Chrome / IE

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#584]
Reference: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/578

When you try to change the default choice for an Interest Group field (both checkboxes and radio buttons) in Chome or IE the change does not take after updating. It goes back to the first default you chose previously.

It does work in Firefox Developer edition.

**Comment by JPry** [comment]
I tested this on the latest version of `staging` today using Chrome, and couldn't reproduce the issue. @TheTracyL Could you test with the `staging` branch and Chrome to see if you can still see the issue?

**Comment by TheTracyL** [comment]
It worked for me!

**Comment by TheTracyL** [comment]
Hi @JPry 

I actually tried this again today and it is defaulting to the first choice I made yesterday. I can't switch the default choice in Chrome :-(

**Comment by TheTracyL** [comment]
Screencast: http://screencast-o-matic.com/watch/cD6DDJjANO

**Comment by TheTracyL** [comment]
It seems to be happening in Firefox, too. No matter what I choose, it goes back to "Volunteering." Every once in awhile it will work.

**Comment by JPry** [comment]
Let's see if we can look at it tomorrow in the office.
