### ISSUE TITLE
Subscribe font on widget is small

### ISSUE THREAD

**Issue by shanghaidavid** [yikesinc/yikes-inc-easy-mailchimp-extender#586]
The subscribe font of front page widget is H3 and looks small. How do I increase the size of the font?

**Comment by TheTracyL** [comment]
Hello,

May I please have a link to your site that has the widget on it?

Thank you!
-Tracy

**Comment by shanghaidavid** [comment]
Sorry about that!

http://yourfortress.ca <http://yourfortress.ca/>

**Comment by TheTracyL** [comment]
Hi,

Your theme is setting the size of widget titles. The CSS it's using, specifically, is:

```CSS
.widget-title {
    font-size: 18px;
}
```

If you wanted to change that, just for the MailChimp widget you could use:

```CSS
.widget_yikes_easy_mc_widget .widget-title {
    font-size: 20px;
}
```

You can change 20px to whatever size you like.

**You have a few options to add CSS code:**

- If you created this theme yourself, you can just add it to your style.css file
- If you're using a theme you downloaded or bought you can [make a child theme](https://codex.wordpress.org/Child_Themes#How_to_Create_a_Child_Theme) and add the code to your child theme's style.css file
- Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.</li>
- You can use a plugin like [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/) or Jetpack and enter the code in their Custom CSS area

Thank you!
-Tracy

**Comment by shanghaidavid** [comment]
Thank you!

**Comment by TheTracyL** [comment]
You're welcome!

Have a good day!
-Tracy
