### ISSUE TITLE
Localiztion

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#592]
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/staging/admin/class-yikes-inc-easy-mailchimp-extender-admin.php 

line 596

JS variable is "localized" manually instead of using `wp_localize_script()`

**Comment by EvanHerman** [comment]
I have addressed this in the [staging branch](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/tree/staging), in my [latest commit](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/commit/9e32c1691afcae1303eff56874fd0d86f242edaa). 

Whenever staging gets merged back into master, this issue can be closed out.

**Comment by TheTracyL** [comment]
Woot!
