### ISSUE TITLE
EU Law Compliance PHP Warning (shown both in Dashboard and front-end)

### ISSUE THREAD

**Issue by ChiaraBuzzi** [yikesinc/yikes-inc-easy-mailchimp-extender#596]
Hello,

First of all, thanks very much for your work with this plugin. 

I am testing the add-on EU Law Compliance, which is just what I’d need, however a warning message is shown:

In the dashboard (EU Law Compliance settings page):

Warning: json_decode() expects parameter 1 to be string, array given in …/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/partials/helpers/fields/yikes-mailchimp-select-field.php on line 8

And in the front-end (just above the checkbox):

Warning: json_decode() expects parameter 1 to be string, array given in …/wp-content/plugins/yikes-inc-easy-mailchimp-eu-law-compliance/yikes-inc-easy-mailchimp-eu-law-compliance.php on line 106

Can you please help me to remove this warning?

Otherwise the plugin seems to be just what I need, thanks again!
Chiara

P.S. I've also submitted this request on the WordPress forum, hope it's ok.

**Comment by TheTracyL** [comment]
Hello Chiara,

We made a major update to our base plugin which may be the cause of this issue.

We will look into it and make a fix ASAP.

We'll keep you updated on our progress.

Thank you!
-Tracy

**Comment by ChiaraBuzzi** [comment]
Hi Tracy, 
Many thanks for the quick reply. I'll  keep an eye open for the fix,
Chiara

**Comment by ChiaraBuzzi** [comment]
Hi @TheTracyL, hope you are well!

I am writing to ask if you have an update on the timeline for this fix? Unfortunately we are not able to use the add-on until this is fixed (the line of code also appears in the front-end). 

Many thanks in advance!

**Comment by TheTracyL** [comment]
Hi Chiara,

I'm sorry we fixed it. We submitted this plugin to the WordPress directory so it will be easier for our users to update. It's still in the queue, but for now you can download it from our site: https://yikesplugins.com/plugin/eu-compliance-extension-for-easy-mailchimp/

I'm sorry we didn't answer this sooner.

Have a good day!
-tracy

**Comment by ChiaraBuzzi** [comment]
Perfect, thank you! I will test this. I have another quick question: if I install the plugin through the link, will I still be able to receive the updates through the WP dashboard once these are released on the main WP directory? 

Thanks again!

**Comment by TheTracyL** [comment]
That is a good question. I believe it should just work, but you may want to delete and re-install from the official Directory to make sure.
