### ISSUE TITLE
Duplicate IDs when using multiple forms on the same page

### ISSUE THREAD

**Issue by AnneKlapwijk** [yikesinc/yikes-inc-easy-mailchimp-extender#597]
Hello,

If you use multiple subscribe forms on the same page there are duplicate IDs.
According to specifications an ID must be unique to the document:

> The id attribute specifies its element's unique identifier (ID).
https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute).

It would be nice if the IDs are made unique or converted to a class.

![image](https://cloud.githubusercontent.com/assets/3767167/19896912/472325c8-a056-11e6-8ee0-914a7b1f31d4.png)

**Comment by TheTracyL** [comment]
Hello Anne,

Thank you for bringing this to our attention. We will take this into consideration.

Have a good day!
-Tracy
