### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#598]
Double check the way the support page appears for premium/non-premium users.

**Comment by kpu23** [comment]
Form Customizer: https://github.com/yikesinc/yikes-inc-easy-mailchimp-form-customizer-extension/commit/0b407266372c8e6c4b4928f6072a48ae0e059a71
Popup Extension: https://github.com/yikesinc/yikes-inc-easy-mailchimp-popup-extension/commit/d18c260ea7da9e6ea36302f328b0aaf19930c14c
