### ISSUE TITLE
Easy Forms not passing emails to Mailchimp list

### ISSUE THREAD

**Issue by ChristinaRebuffet** [yikesinc/yikes-inc-easy-mailchimp-extender#599]
Hello,

I have Yikes Mailchimp easy forms installed on my site and use its opt-in forms in several key places (site footer, blog sidebar, embedded directly in strategic posts, etc.)

When checking my stats, I noticed that although I had 1200 people who submitted, I had a 0% conversion rate. 

I wanted to test the Yikes form by signing myself up to my Mailchimp list via the Yikes form. And nothing works! 

I tried changing it from double opt-in to single opt-in and back. Nothing. I updated the plugin. Nothing. 

So basically, if I understand correctly, I have 1200 people who wanted to subscribe to my site (and become potential customers) and who are lost because the form doesn't work. 

Can you please contact me to resolve this, as just the thought of losing out on so much potential income makes me feel queasy...

P.S. I just rechecked to verify the number of submissions and for some reason, the stats for the list "Un an de leçons gratuites?" has reset itself...It did say 711 submissions before, now it's at 0.

Please fix this because I can't leave dead forms on my site. Thanks

**Comment by TheTracyL** [comment]
Hello Christina.

First, can you please provide a link to your site so we can take a look? 

Second, can you please turn Ajax off for your forms and test again? When forms don't work it usually means another plugin has a JavaScript conflict. Here are instructions on how to do that: 
https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

Also the 1,200 number are impressions meaning the form loaded that number of times in a browser. That number goes up quickly when you have forms in the footer.

Please let us know if turning Ajax off works and shoot us a link to your site.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hello Christina,

Just double checking on this. Did you try turning off Ajax?

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Christina,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
