### ISSUE TITLE
Update Failed: Download failed. Too many redirects

### ISSUE THREAD

**Issue by mradicke** [yikesinc/yikes-inc-easy-mailchimp-extender#600]
When trying to update from ver. 1.0.3 to ver. 1.1.3 of Form Customizer for Easy Forms for MailChimp, I receive the error message:  Update Failed: Download failed. Too many redirects.  WordPress version is latest--4.6.1.  All other plug-ins are up to date, including 	Easy Forms for MailChimp by YIKES (ver. 6.2.3). 

The long form of the message is:

> The update process is starting. This process may take a while on some hosts, so please be patient.

> Enabling Maintenance mode…

> Updating Plugin Easy Forms for MailChimp Form Customizer Extension by YIKES (1/1)

> Downloading update from https://yikesplugins.com/edd-sl/package_download/MTQ3ODc4MjM4MzpjMTM5NDc1MjBlNzc4YTZlMGExNDcxNjhjYjkyY2NlMToxNzY6Y2M2ZjEyODE1YTgxYWM3NmQ0MzcwYmI1OTQ0YzM3YWQ6aHR0cEAvL2dhcmRuZXJ0eC53cGVuZ2luZS5jb20=…

> An error occurred while updating Easy Forms for MailChimp Form Customizer Extension by YIKES: Download failed. Too many redirects

> Disabling Maintenance mode…

Site is http://gardnertx.wpengine.com/

Thanks.  M

**Comment by TheTracyL** [comment]
Hello M.

Thank you so much for bringing this to our attention.

We have identified the issue and we're working on a fix for it now.

I'll post here when it is fixed and you can try again.

We apologize for the inconvenience.

Thank you!
-Tracy

**Comment by kpu23** [comment]
Hi M.

Sorry about that!

I believe we have fixed this issue; please try updating the plugin again.

 I'll close this ticket for now. If you experience any more problems feel free to make another.

Thanks,
Kevin.

**Comment by mradicke** [comment]
Now it says: Download failed.  Unauthorized.  I was getting this earlier, and found that my license wasn’t activated for some reason.  I activated it and then I started getting the error message.  Now the first error message is back.

**Comment by mradicke** [comment]
I tried again and it worked.  The cache probably hadn’t cleared the first time.  Thanks!  M

**Comment by TheTracyL** [comment]
Whew, great!
