### ISSUE TITLE
Google Analytics Support

### ISSUE THREAD

**Issue by kpu23** [yikesinc/yikes-inc-easy-mailchimp-extender#606]
Google Analytics support is a big task - and may not be limited to Google Analytics (there are similar event trackers that users may want). The basics of this task is to fire off custom JavaScript during certain events (e.g. subscription).

**Comment by therealjosh** [comment]
Is this a feature yet? I would love to be able to add tag/click triggers for GTM or other. Any update would be great.

**Comment by kpu23** [comment]
Hi @therealjosh,

This is not a feature yet. I have some progress in my local environment, about 20% of it, but there are some security issues that have arisen and I need to do some research before continuing.

I'll try to comment here when I'm starting so you'll have a good sense of when it'll be ready.

My current estimate is about 4 weeks.

Kevin.

**Comment by kpu23** [comment]
Hi @therealjosh - I forgot to post here - Google Analytics support is now live.
