### ISSUE TITLE
Mobile disabled in popup settings, popup still displaying on mobile

### ISSUE THREAD

**Issue by pulmccm** [yikesinc/yikes-inc-easy-mailchimp-extender#610]
I installed yikes this weekend (latest version). I don't want the popup to display on mobile, it does not render properly. I have "Not on mobile devices" ticked on in the Yikes  popup settings. Also have WP Touch Pro installed and have Yikes disabled in the WPTouch toggle settings.

Popup is still displaying on mobile at pulmccm.org.

![image](https://cloud.githubusercontent.com/assets/24363624/20863746/7482493e-b9a3-11e6-85f2-85eb1ceaaf31.png)

![image](https://cloud.githubusercontent.com/assets/24363624/20863766/2b648400-b9a4-11e6-9f56-a0ea117517a0.png)

**Comment by kpu23** [comment]
Hi pulmccm,

I am not sure _why_ it is happening, but I am able to reproduce this; it is a bug. I'm working on a solution now.

Kevin.

**Comment by kpu23** [comment]
Hi pulmccm,

A new version of the popups plugin, version 1.2.2, was just released. This should handle the issue you had with the mobile logic. Please let us know if this is working now.

Cheers,
Kevin.
