### ISSUE TITLE
MailChimp API key not recognized as valid

### ISSUE THREAD

**Issue by tmoore615** [yikesinc/yikes-inc-easy-mailchimp-extender#611]
Hi,
I'm running a Managed WordPress site via GoDaddy and have been using Easy Forms for several years without any problems. Today I did a check of the site because I haven't been getting any new signups. To test things I did a new-subscriber signup and it thanked me for signing up. I then realized that ReCaptcha hadn't been displayed and I didn't get an opt-in email from MailChimp.

I then took a look at the Easy Forms plugin and saw that there was an error message on my opt-in form. Sadly, I didn't write it down. I think it said something about an illegal or invalid offset in a table in some php file. I decided to try fixing things by deleting the plugin and reinstalling it. When I had it installed, I copied my MailChimp API key from their site and pasted it in Easy Forms. After I saved the key, EF did not connect. I repeated this a couple times with the same result. So, I created a new key on MailChimp and several attempts at copying and pasting the new key also failed to connect. 

I used Plugins/Add New in WordPress to add the plugin when reinstalling it.

Any ideas?

Thanks,
Terry

**Comment by kpu23** [comment]
Hi tmoore615,

A lot of times this kind of issue is due to servers unable to communicate with each other before a timeout is hit, and a lot of times they resolve themselves. Are you still having issues with your API key?

Please let us know,
Kevin.

**Comment by tmoore615** [comment]
No. It's working now! Next time I'll give it a day. Would "Clear MailChimp API Cache" help resolve this if it happens again? 

Thanks,
Terry

**Comment by kpu23** [comment]
Hi Terry,

It's difficult to know whether 'Clear MailChimp API Cache' would help because there are a number of different factors that could prevent the API key from being accepted. However, I can't think of a scenario where 'Clear MailChimp API Cache' would _hurt_!

Glad it's working - enjoy!
Kevin.

**Comment by TheTracyL** [comment]
Hooray!

Clearing the API cache clears the data that was pulled and tells the plugin to pull it again. Without a connection the first place I don't clearing it would help with this specific problem.

Have a good day!
-Tracy
