### ISSUE TITLE
Inline form option for subscription form is not working

### ISSUE THREAD

**Issue by VelvetLounger** [yikesinc/yikes-inc-easy-mailchimp-extender#613]
Hello. I am trying to get my Mailchimp subscription to use the Inline Form option. The default checkbox did not work. So I clicked on the Knowledgebase Article,

https://yikesplugins.com/support/knowledge-base/my-form-fields-are-not-fully-inline-after-enabling-the-inline-form-option-how-come/

And tried that. I placed the code in my child theme style.css. I placed in the special CSS location that is provided with my theme. When I tried to turn on the Jetpack CSS editor my whole page exploded.

So how can I force the fields to be smaller so they show up inline?

My blog is at http://earthtokeir.com

Thanks so much!
Keir

**Comment by TheTracyL** [comment]
Hello Keir.

I checked out the widget forms on your site (I'm assuming those are the ones you are referring to) in the sidebar and footer of your site. The forms are not set to "inline" meaning they do not have the classes and styles associated with it when a form is set to inline.

How are you turning inline on for that form? Are you using one of the methods described here?
https://yikesplugins.com/support/knowledge-base/how-do-i-place-all-of-my-form-fields-on-one-line/

Let me know and let me know if I'm not looking at the correct form. I will be happy to help you with CSS once we get inline turned on for that form :-)

Thank you!
-Tracy

**Comment by VelvetLounger** [comment]
Hello Tracy.

I had actually turned off the inline function because it just looked bad. If you check the site again I have re-enabled it. I have also added a second widget to the sidebar using the shortcode [yikes-mailchimp form="1" inline="1"].

Selecting the inline radio button, or using the short code has the same result where the Go! button is below the email field. I would like it to be inline with the email field just like the Blog Subscription widget displays.

The final thing I tried was entering the following code that I got from the Yikes suport page;

`
.yikes-easy-mc-form .submit-button-inline-label {
   width: 15% !important;
}`

This had absolutely no effect. I tried adding it to my child theme style.css file. I also added it to the area where my theme allows me to add CSS. Neither options worked.

Thanks for your help with this issue
Keir

**Comment by TheTracyL** [comment]
I'm on it :-)

**Comment by VelvetLounger** [comment]
Also, I ended up removing the CSS code because it had no effect

**Comment by TheTracyL** [comment]
Please give this a try, it should make it look the same as the form above it.

```CSS
.yikes-easy-mc-form.yikes-mailchimp-form-inline label.label-inline {
    width: calc( 100% - 24% );
    padding-right: 0;
}

.yikes-easy-mc-form.yikes-mailchimp-form-inline .submit-button-inline-label {
    width: 15%;
    min-width: 66px;
}
```

Let me know if that works.

Thank you!
-Tracy

**Comment by VelvetLounger** [comment]
Yes. That code works when I paste it into my Theme Options CSS form. However putting it into my Child theme style.css it did not work. Not sure why, but Ill keep it in the Theme Options CSS location for now and if I ever change my theme I'll deal with it then.

Thanks so much for your awesome help!
Keir

**Comment by TheTracyL** [comment]
Awesome! I'm so glad I was able to help! WordPress 4.7 now has a Custom CSS option built into the live previewer. That may be the best place to put it. 

Have a good day!
-Tracy

**Comment by VelvetLounger** [comment]
Ill give that location a shot. I know when I enabled the Jetpack CSS option the whole structure of the website fell totally apart. Just exploded.

**Comment by VelvetLounger** [comment]
Just an FYI. The code also worked in the Custom CSS section as well.

Thanks again
Keir
