### ISSUE TITLE
Warning: Illegal string offset 'total'

### ISSUE THREAD

**Issue by ebunton** [yikesinc/yikes-inc-easy-mailchimp-extender#614]
Warning: Illegal string offset 'total' in ....../public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/partials/menu/manage-forms.php on line 203

**Comment by kpu23** [comment]
Hi.

Thanks for letting us know. This has been fixed and will be included with the next version of the plugin.

Cheers,
Kevin.
