### ISSUE TITLE
Editing the html/css

### ISSUE THREAD

**Issue by Cooperwoman** [yikesinc/yikes-inc-easy-mailchimp-extender#615]
My form has larger gaps than I want between the fields, created by repeated <p></p> tags. How do I remove some of these tags so that the fileds are closer together?

**Comment by kpu23** [comment]
Hi,

I'm not quite sure what you mean. Could you send over a URL to your site or a screenshot so we can understand the problem better?

Thanks,
Kevin.

**Comment by TheTracyL** [comment]
Hi Cooperwoman,

If you send us a link to an example, we can help you with some CSS to adjust the gaps.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Cooperwoman,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
