### ISSUE TITLE
"Warning: Illegal string offset 'total' in /.../manage-forms.php on line 203”

### ISSUE THREAD

**Issue by bradley2083** [yikesinc/yikes-inc-easy-mailchimp-extender#618]
Hey, guys. 

I'm getting this message any time a user tries to complete an opt-in on our site.  Any ideas or recommendations?  

I can provide more info, just let me know what would be useful.  

Thank you!

**Comment by kpu23** [comment]
Hi bradley2083,

Thanks for bringing this to our attention. I believe I fixed this exact issue a week ago, but we're still prepping a release so the latest version is not available yet. However, if you have access to your server's file system you could replace the file. That is, you can replace `/wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/partials/menu/manage-forms.php` with the page from our GitHub, [here](https://raw.githubusercontent.com/yikesinc/yikes-inc-easy-mailchimp-extender/19df5a47a0686cf43bf10df7ae6c85b022913ad8/admin/partials/menu/manage-forms.php). Let me know if that's possible! If not, we will have a new release within the next two weeks.

Kevin.

**Comment by bradley2083** [comment]
Rad, thanks!
