### ISSUE TITLE
Eliminate duplicate files

### ISSUE THREAD

**Issue by JPry** [yikesinc/yikes-inc-easy-mailchimp-extender#620]
In processing a form submission, there are two separate files that do almost exactly the same thing:
* `public/partials/shortcodes/process/process_form_submission_ajax.php`
* `public/partials/shortcodes/process/process_form_submission.php`

The only difference between these files is the Ajax-specific handling in the Ajax file. These should be refactored into a single file, preferably a set of classes that handle the submission.

**Comment by kpu23** [comment]
`public\classes\process\class.process_form_submission_handler.php`
