### ISSUE TITLE
Ability to Change field labels

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#623]
With v3 of the MailChimp api we can add the ability to edit field lables - Yay! 

Let's do this by either adding an "Edit Label" button or clicking on the name to edit it.

![image](https://cloud.githubusercontent.com/assets/1252286/21940218/52e69222-d991-11e6-9a5e-9d82cae62370.png)

**Comment by kpu23** [comment]
This feature is currently in the staging branch.
