### ISSUE TITLE
Customising Field Options and Colours

### ISSUE THREAD

**Issue by russell0670** [yikesinc/yikes-inc-easy-mailchimp-extender#624]
Where can i edit visual items of the forms.  Things link the button background and text colour, and the input text box colour.

I have looked in all the settings but cannot find anything to do this.

**Comment by TheTracyL** [comment]
Hi there.

Are you referring to the base free plugin, or our Customizer add on?

Thank you!
-Tracy

**Comment by russell0670** [comment]
The base plugin

**Comment by TheTracyL** [comment]
We don't have settings built in for styling forms. We do have plenty of CSS selectors added to form elements so you can style the forms yourself if you know CSS.

We also have a customizer add-on for sale that lets you style your forms if you don't know CSS.

Thank you!
-Tracy
