### ISSUE TITLE
Getting the location

### ISSUE THREAD

**Issue by arabtornado** [yikesinc/yikes-inc-easy-mailchimp-extender#625]
It seems that i'm unable to get the signup location tracking to work so i can't get the segment location filter to work since all the superscribes location set to unknown in Mailchimp. however i tried another plugin that use "Embed Form" instead of API and the location tracking was working nicely... so i'm wondering how to solve this issue.

Thank you

**Comment by kpu23** [comment]
Hi @arabtornado,

I am not sure exactly which field you are talking about. Do you mean MailChimp's "Signup Source" field? When you look at a specific subscriber, the field looks like 
![image](https://cloud.githubusercontent.com/assets/2415516/22022276/4ac3d3ec-dc8f-11e6-92c1-2033c11c0b23.png)?

**Comment by arabtornado** [comment]
Thanks Kpu23 for your reply,

As you can see on this link the subscriber detail page above that made using other wordpress plugin was able to get aditional useful details like country, language and time zone however those info were missing when i used "Easy Forms" plugin.. so i just was wondering if there is anyway to get those additional "Overview" info when the visitors sign up using the "Easy Forms" plugin.

https://www.dropbox.com/s/9l6c1qfmg2tdvad/compare.png?dl=0

**Comment by kpu23** [comment]
Hi @arabtornado,

Unfortunately our plugin does not include functionality to fill out these fields. However, we could write some custom code and leverage one of our plugin's filters to achieve the same result. Does that sound good?

Kevin.

**Comment by arabtornado** [comment]
Hi @kpu23 i really appreciate your nice support, but unfortunately i don't know how to write custom codes and how to add this functionality :(

**Comment by kpu23** [comment]
I can help you there! We're actually releasing a very large update to the plugin today and I am including filters that will allow us to add these fields when a user subscribes. It will probably be at least a few hours though; I will comment here when it is released and give you a couple of code snippets. You should also be aware that for the embedded forms MailChimp is supplying these fields based on the user's browser, and that the browser can be unreliable sometimes (for example, location can be turned off, and language can be changed/not reflect the user's language).

**Comment by arabtornado** [comment]
Thank you for your awesome support, really appreciate it

**Comment by kpu23** [comment]
Hi @arabtornado,

Sorry it's been a busy day. We just released the new version of the plugin; you'll need this version to add our custom code. I will get back to you tomorrow with some code snippets. Have you ever added a filter to your functions.php file?

**Comment by arabtornado** [comment]
Hi @kpu23 

Never mind, thanks so much for the update, also thanks in advance for sending the code snippets.
Unfortunately i never tried to alter or add filters to the functions.php

**Comment by kpu23** [comment]
Hi @arabtornado,

I'm writing the code now. Is there a default country you'd like to default to if we can't detect the user's country? If you don't feel comfortable editing the functions.php file you can use a plugin like this one - https://wordpress.org/plugins/my-custom-functions/.

**Comment by kpu23** [comment]
This function will supply the language field and if we couldn't detect the language it will leave it empty: 
```
function mailchimp_add_language_to_user_subscription( $body, $form_id ) {

	$language = isset( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) ? substr( $_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2 ) : '';

	// All of MailChimp's accepted country/language codes
	// Found here: http://kb.mailchimp.com/lists/managing-subscribers/view-and-edit-subscriber-languages
	switch( $language ) {
		case 'en':
		case 'ar':
		case 'af':
		case 'be':
		case 'bg':
		case 'ca':
		case 'zh':
		case 'cs':
		case 'da':
		case 'nl':
		case 'et':
		case 'fa':
		case 'fi':
		case 'fr':
		case 'de':
		case 'el':
		case 'he':
		case 'hi':
		case 'hu':
		case 'is':
		case 'id':
		case 'ga':
		case 'it':
		case 'ja':
		case 'km':
		case 'ko':
		case 'lv':
		case 'lt':
		case 'mt':
		case 'ms':
		case 'mk':
		case 'no':
		case 'pl':
		case 'pt':
		case 'ro':
		case 'ru':
		case 'sr':
		case 'sk':
		case 'sl':
		case 'es':
		case 'sw':
		case 'sv':
		case 'ta':
		case 'th':
		case 'tr':
		case 'uk':
		case 'vi':
			$body['language'] = $language;
			return $body;
			break;
		default:

			// If our country is not in the list, do not add the language item
			return $body;
	}
}

add_filter( 'yikes-mailchimp-filter-subscribe-request', 'mailchimp_add_language_to_user_subscription', 10, 2 );
```

**Comment by kpu23** [comment]
Also, I believe MailChimp _will_ supply the language / country fields if you use double opt-in. Just a thought.

**Comment by arabtornado** [comment]
Thank you @kpu23  for you help... i'm gonna try this.

**Comment by kpu23** [comment]
Sounds good - supplying the location takes a bit more work but I will get that over to you. Let me know if you can test the language parts - it worked perfect for me. Sorry if this is a bit more technical than you wanted!

**Comment by arabtornado** [comment]
I will... i'm just not familiar with such technical stuff but i will try with that function.
Thanks again :)

**Comment by kpu23** [comment]
Unfortunately getting the location is not as simple as I initially thought. I won't be able to supply that for you. So you can use the above function will get the user's language, or switch to a double opt-in and let MailChimp fill these in automatically. I will let you know if I find a way to get the location.

**Comment by arabtornado** [comment]
Thanks, btw i'm honestly amazed by the superior support... especially for a free plugin!! i really appreciate your effort

**Comment by kpu23** [comment]
Also, I read this article (http://kb.mailchimp.com/lists/managing-subscribers/about-geolocation) which explains how MailChimp does the geolocation. It says that when a user receives emails, they will update the geolocation accordingly. So over time, after interacting with your subscribers, the location data _should_ be supplied by MailChimp.

Sorry I'm posting so many messages - I'm investigating the topic for the first time and I'm interested in it also!
Cheers,
Kevin.

**Comment by arabtornado** [comment]
Never mind feel free to to post anything you like :)
