### ISSUE TITLE
Warning: stripslashes() expects parameter 1 to be string, array given in wp-content/plugins/yikes-inc-easy-mailchimp-extender/admin/class-yikes-inc-easy-mailchimp-extender-admin.php on line 2178

### ISSUE THREAD

**Issue by ipolikarpov** [yikesinc/yikes-inc-easy-mailchimp-extender#629]
Same thing in frontend when showing form with group select checkboxes. It looks like $name variable in proccess_from_shortcode.php is an array, and it should be printed like this:
`<?php echo $name['name']; ?>`

**Comment by kpu23** [comment]
Hi @ipolikarpov,

Sorry about that! I'm working on a fix right now. What is the error you are seeing on the front-end?

Kevin.

**Comment by kpu23** [comment]
Hello again @ipolikarpov, I am having trouble re-creating the issue. What type of interest group is the error appearing for (front-end and back-end)? Is it a 'checkbox' type interest group with multiple checkboxes?

**Comment by ipolikarpov** [comment]
Hi Kevin!
I can't see this error in front-end right now beacause I fixed it in /public/partials/shortcodes/process_from_shortcode.php on line 1104: 
`<?php echo $name; ?> -> <?php echo $name['name']; ?>`

Same fix may help in admin/class-yikes-inc-easy-mailchimp-extender-admin.php on line 2178:
`<?php echo stripslashes( str_replace( '\'' , '' , $group ) ); ?>&nbsp; -> <?php echo stripslashes( str_replace( '\'' , '' , $group['name'] ) ); ?>&nbsp;`

Yes, it's 'checkbox' type in interests group whith 4 checkboxes. Screenshot is attached, but it's in russian, sorry :)
![2017-01-19_17-24-07](https://cloud.githubusercontent.com/assets/6024441/22110290/39240ccc-de6c-11e6-8a2e-59a388c70456.png)

**Comment by kpu23** [comment]
Thanks for the detailed response. I am not sure why your interest groups are coming in as arrays though. If I added what you added to the code, I would get the reverse error ($group is not an array). Could you try creating a new form based on the same list, adding the interest group, saving, and check if the error persists? I am very interested!

Kevin.

**Comment by kpu23** [comment]
Are you on version 6.3.0+ of the plugin?

**Comment by ipolikarpov** [comment]
Yes, it's 6.3.1.
Just created same list and settings form, no errors in backend. Replaced code to original in front-end process_from_shortcode.php and everything works well.

**Comment by kpu23** [comment]
Thank you very much for doing that! It seems like there was a point where interest groups were arrays of arrays and for some reason your form still has that data structure. We've got some minor features we want to add to a 6.3.2, and as a part of that I will add a check to make sure we're dealing with the correct structure. 

I'm going to close the ticket but feel free to ask any more questions if you have them.

Thanks again for your help - I appreciate it.
Kevin.

**Comment by ipolikarpov** [comment]
Thank you, Kevin!
I hope adding lists select in front-end in your plans too!

**Comment by kpu23** [comment]
Can you explain what you mean by that?

**Comment by ipolikarpov** [comment]
I mean visitor can select which list to subscribe to.

**Comment by kpu23** [comment]
I understand now. It's a bigger task than it first appears, but it's on our list for potential features. Thanks for the suggestion.

**Comment by ipolikarpov** [comment]
Thank you!
