### ISSUE TITLE
UTM Referrer Tracking Help

### ISSUE THREAD

**Issue by azams5** [yikesinc/yikes-inc-easy-mailchimp-extender#634]
Hi, 

I was using the script here http://www.terminusapp.com/blog/add-utm-referrer-lead-forms/ with contact form 7 to pull referrer tracking into Mailchimp. I have been unable to get it to work with with YIKES Easy Forms for MailChimp: the data isn't set over to Mailchimp, though I can see it is being loaded into the form.

Any help would be much appreciated.

Thanks!

**Comment by kpu23** [comment]
Hi @azams5,

Hmm. We may need to add some custom code using our filters/hooks for this to work properly. Could you send a URL to your page with the form?

Thanks,
Kevin.

**Comment by azams5** [comment]
Sorry Kevin, I thought I was just missing something. I didn't realise this wasn't supported. Thanks for your offer of help, but I've had to revert to our previous solution as I also needed GTM support and to ability to send a copy of the submission to a mailbox.

Thanks for your time. Great plugin.
