### ISSUE TITLE
PCI compliance scan reporting XSS vulnerabilities

### ISSUE THREAD

**Issue by nathan-hermit** [yikesinc/yikes-inc-easy-mailchimp-extender#638]
Hello. I'm not sure if these might be false-positives or if it's a mis-configuration somewhere on my end, but I've been trying to get a PCI compliance scan to pass and it keeps reporting XSS vulnerabilities that reference the Yikes Easy Mailchimp Forms plugin.

The errors are reported as:

> **Summary:** 
Cross-site scripting vulnerability in EMAIL parameter to /page/location/
Risk: High (3)
Port: 443/tcp
Protocol: tcp
Threat ID: web_prog_cgi_xssgeneric
**Information From Target:**
Service: 443:TCP
SENT: POST /page/location/ HTTP/1.0
Host: www.domain.com
User-Agent: Mozilla/5.0
Content-length: 290
Content-Type: application/x-www-form-urlencoded
Connection: Keep-Alive
Cookie: wordpress_test_cookie=WP+Cookie+check; woocommerce_cart_hash=e720cc9f16f4b58312bd40a4b17dbc93; woocommerce_items_in_cart=1; wp_woocommerce_session_0b71d6e5497c2eaf1d3ce11f2d7fb84f=32717699e9f3f7daf316bb71327dfa27%7C%7C1485994330%7C%7C1485990730%7C%7Ce6c8f09b9baf491d76b98f741666dbec
EMAIL=%3Cscript%3Ealert%28%22SAINTL3Byb2R1Y3QvaGVtcC13cmFwLWJveC8gRU1BSUw=%22%29%3C%2Fscript%3E&yikes-mailchimp-honeypot=123&yikes-mailchimp-associated-list-id=xxxx&yikes-mailchimp-submitted-form=1&yikes_easy_mc_new_subscriber=xxxx&_wp_http_referer=%2Fpage%2Flocation%2F
RECEIVED: ??????????<input id="yikes-easy-mc-form-1-EMAIL" name="EMAIL" placeholder="you@example.com" class="yikes-easy-mc-email field-no-label" required="required" type="email" value="<script>alert(\"SAINTL3Byb2R1Y3QvaGVtcC13cmFwLWJveC8gRU1BSUw=\")</script>">

Ultimately I'm not sure if this is a matter of this plugin or not, since WooCommerce is also in the cookie mentioned, but the Yikes MC form is also present in many of the errors that are being returned and they all mention the 'EMAIL parameter'. I'm displaying this plugin's form globally in the site footer.

Maybe you folks can make more sense of it?

Thanks.

**Comment by kpu23** [comment]
Hi @nathan-hermit, 

Thanks for letting us know. We're actively developing a fix.

Kevin.

**Comment by kpu23** [comment]
Hi @nathan-hermit,

We recently released v6.3.3 that should fix this vulnerability. Would you mind re-running your PCI compliance scan and letting us know?

Thanks,
Kevin.

**Comment by nathan-hermit** [comment]
Yes, the PCI compliance scan that I ran today turned up free of all the previous XSS issues.

Thank you for the quick patch!

**Comment by TheTracyL** [comment]
Awesome! Thank you so much for re-checking.

We gave you credit in he changelog.

Have a good day!
-Tracy
