### ISSUE TITLE
province is hidden when defaulting to Canada

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#645]
defaulting to Canada is hiding the province/postal code in the address field – these should be available – how do I enable these fields for the Country Canada?

**Comment by kpu23** [comment]
Hi @Lir2303,

Looking into this now. Will get back to you in a couple of hours.

Kevin.

**Comment by kpu23** [comment]
Hi @Lir2303,

To confirm, you're using our filter 'yikes-mailchimp-default-country-value' and returning 'CA', correct?

**Comment by Lir2303** [comment]
Yes that's correct. I have the following code:
function yikes_mailchimp_set_default_country_in_dropdown( $country_abbrev ) {
	$country_abbrev = 'CA';
	return $country_abbrev;
}
add_filter( 'yikes-mailchimp-default-country-value', 'yikes_mailchimp_set_default_country_in_dropdown' );

**Comment by kpu23** [comment]
@Lir2303 - sounds good. I'm developing a solution to this now. Not everyone is going to want province, so I'm setting up a few more filters to control it. At the moment, they're all pretty simple filters and work similar to the default country code.

**Comment by Lir2303** [comment]
Sounds good. Thanks

**Comment by kpu23** [comment]
You're looking for something like this, correct?

![image](https://cloud.githubusercontent.com/assets/2415516/22833977/bafbd128-ef81-11e6-8d76-245414e7e361.png)

![image](https://cloud.githubusercontent.com/assets/2415516/22833931/93b611be-ef81-11e6-8711-492e4e28c678.png)

**Comment by Lir2303** [comment]
Yes

**Comment by Lir2303** [comment]
Should I make a new form to see the implemented feature

**Comment by kpu23** [comment]
It's not ready yet - there are some technical details I'm still working through; that is just a screenshot from my local development install to confirm we're on the same page. I'll let you know when a new version of the plugin is ready; it could be a couple of hours still.

Kevin.

**Comment by Lir2303** [comment]
Sounds good. Thanks

**Comment by kpu23** [comment]
Hi @Lir2303,

I've got your issue fixed, but I can't release it until Monday (need to fix a separate item before release).

Sorry it took me so long; it's more complicated than you would think!

Have a good weekend - I'll comment here on Monday,
Kevin.

**Comment by Lir2303** [comment]
No worries. Thank you very much for your support. 
This will greatly help me.

**Comment by Lir2303** [comment]
Hi @kpu23 ,
Just wanted to know if I should re download the plugin to see the updated changes.

**Comment by kpu23** [comment]
Hi @Lir2303,

I'll let you know - hopefully around a half hour. I'm finishing up some final changes and testing right now.

**Comment by kpu23** [comment]
Hi @Lir2303,

I just released version 6.3.5 of the plugin. You should see the update prompt in your dashboard soon (or you can remove and re-add the plugin if you want the update immediately). 

Please let me know if this works for you.

Cheers,
Kevin.

**Comment by kpu23** [comment]
I forgot to mention that if you want the default title for "State" to be "Province" you can use the filter `yikes-mailchimp-address-state-label`. 

Here is an example:

```
function yikes_mailchimp_change_state_label( $state_label, $form_id ) {
	return 'Province';
}

add_filter( 'yikes-mailchimp-address-state-label', 'yikes_mailchimp_change_state_label', 10, 2 );
```

Additionally, you should use the filter `yikes-mailchimp-default-zip-code` to default your zip code. I am currently writing an article as to why defaulting the zip code is a good idea. I'll comment here when that's ready.

**Comment by Lir2303** [comment]
Yes, it work now. Thank you very much. 
Just a quick question, is there a way to display the title 'Province' when 'CAN' is selected and the title
'State' when 'US' is selected. Right now if you select either country 'Province' is shown.

**Comment by kpu23** [comment]
Unfortunately there is no way to do this right now. However, it's on my to-do list. It's difficult to make it work and be customizable for all countries and all users and I didn't want to rush a feature that was not fully thought out. For now, you could call it "Province / State" if you'd like, but I know it's not ideal.

P.S. Here is an article on why you might want to default the zip code to a value: https://yikesplugins.com/support/knowledge-base/received-following-error-error-address-field-please-enter-complete-address-may-want-consider-defaulting-zip-code/

**Comment by Lir2303** [comment]
Yeah that's fine. It was not a priority. Thank you very much for 
the help.

**Comment by kpu23** [comment]
No problem! I'm going to close this ticket. I'll let you know when changing state/province dynamically is ready (or when it's scheduled to be ready). Feel free to open a new one if you have more problems.

Cheers!
