### ISSUE TITLE
You're already subscribed message even after deleting

### ISSUE THREAD

**Issue by arabtornado** [yikesinc/yikes-inc-easy-mailchimp-extender#646]
Hi,
I subscribed to a list for testing and then deleted the subscription from my mailchimp list and tried to signup again but i always get this message..

"You're already subscribed. To update your MailChimp profile, please click to send yourself an update link"

why i always get it even after deleting myself from the mailchimp list and how can i avoid/solve this issue?

Thanks

**Comment by kpu23** [comment]
Hello again @arabtornado,

Hmm. I've subscribed and re-subscribed many times and never seen this issue. It could be a slight delay in MailChimp where it hasn't recognized the deletion yet; if this were the case, it would allow re-subscribing a few minutes later. Is this issue still occurring for you?

Thanks,
Kevin.

**Comment by arabtornado** [comment]
Hi, Hope you are fine :)

I tried again and it worked so i guess you are right, it's a mailchimp delay!!
Thanks again for your awesome support.

btw i solved that issue we were talking about by using a Geo targeting plugin that enable showing a specific newsletter form per country and added a hidden field with the country name as a default value.  So the shortcode used ended up looking like this. and signing up from for 7 will show the word "Other" in the country field since my client not interested anyway with the other countries.

[geot country="United States"] [yikes-mailchimp form="1"] [/geot]
[geot country="Germany"] [yikes-mailchimp form="2"] [/geot]
[geot country="United Kingdom"] [yikes-mailchimp form="3"] [/geot]
[geot country="France"] [yikes-mailchimp form="4"] [/geot]
[geot country="Italy"] [yikes-mailchimp form="5"] [/geot]
[geot country="Spain"] [yikes-mailchimp form="6"] [/geot]
[geot exclude_country="United States,Germany,United Kingdom,France,Italy,Spain"] [yikes-mailchimp form="7"] [/geot]

I know it was a very stupid solution that i did but at least it works fine for my need :)

Thanks again for your awesome support my friend :)

**Comment by kpu23** [comment]
Hi @arabtornado,

I'm good! And even better now that it's working for you. :-). How are you?

For the geo-location stuff, that's not a stupid solution at all! That sounds simpler than going through the process of adding custom code. Would you mind posting a URL to the Geo targeting plugin you're using? I would like to recommend it as a solution for people who are trying to do what you did.

Cheers,
Kevin.

**Comment by arabtornado** [comment]
I'm fine, Thanks
Sure, here you are, the free version of that geo targeting plugin worked very nicely for my need actually
https://ar.wordpress.org/plugins/geotargeting/

btw unlike what i said previously,,, it seems that all the other mailchimp plugins suffer from the same issue when you set it as single opt-in

**Comment by kpu23** [comment]
Got it - thanks. Enjoy your day / night!

(I'm going to close this ticket, but feel free to post whenever.)
