### ISSUE TITLE
Only form field option I have is email address

### ISSUE THREAD

**Issue by taylordavisdoula** [yikesinc/yikes-inc-easy-mailchimp-extender#648]
I don't have the option to add any form fields except for email address...how can i get options for name, etc?

**Comment by TheTracyL** [comment]
Hello Taylor,

Our plugin pulls in the fields you create in your MailChimp account. You see to add the fields there to be able to use them with our plugin.

Here are some instructions on how to do that: https://yikesplugins.com/support/knowledge-base/how-do-i-add-new-fields-to-my-form/

Thank you!
-Tracy
