### ISSUE TITLE
Subscriber profile update on sign-up deletes/replaces groups they belong to

### ISSUE THREAD

**Issue by alexmo0** [yikesinc/yikes-inc-easy-mailchimp-extender#651]
Hi I think this is in may ways intended hence the term 'update' but when my already-subscribers register for my webinar here https://www.loveyourhappylife.com/besplatnye-vebinary-new/ their profile is updated to put them in a group that indicates they want updates about the upcoming webinar. The problem is that I have a lot of them in half a dozen other groups (current/former clients, demographics etc etc) and I don't want those group memberships to be annuled. 

Can this be achieved (append not replace) profile? Who is responsible for it my mailchimp config or plugin api? I would even pay for this feature if available thank you.

**Comment by kpu23** [comment]
Hi @alexmo0,

We have an option that you can toggle: 
![image](https://cloud.githubusercontent.com/assets/2415516/23317523/c59a744c-fa9c-11e6-9cb3-5666026a5fe7.png)

**Comment by kpu23** [comment]
Set it to update and you should be good to go!

Cheers,
Kevin.

**Comment by alexmo0** [comment]
Holy cow this must be the greatest moment of free support I ever received. Instant and with clear no bullshit working response. 

/bow thanks Kevin!

**Comment by TheTracyL** [comment]
That's awesome.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy
