### ISSUE TITLE
Error messages not working in Safari on Mac

### ISSUE THREAD

**Issue by spotUP** [yikesinc/yikes-inc-easy-mailchimp-extender#653]
Hi, the form validation doesn't show up at all on Safari/Mac.
Could this be adressed?
The issue can be seen here:
http://anicuracareer.com/birmingham/

**Comment by kpu23** [comment]
Hi @spotUP,

We're currently doing "HTML5" validation which all major browsers except Safari support. To counteract this, we do a "server side" validation. After the form is submitted, if a required field is missing, the form will submit, but return with a message at the top saying "A required field is missing." (this is happening on your site). I know this is not ideal, but it's the best we can do right now. Also, _Safari is working on implementing HTML5 validation_. I'm not sure when it will be included, but it should be soon (other browsers have had it for years).

So, I'm sorry we don't have "front-end" validation for Safari, but (1) it's coming and (2) we still prevent the submission from going to MailChimp if a required form field is missing.

Hope that helps,
Kevin.

**Comment by spotUP** [comment]
OK thanks.

**Comment by kpu23** [comment]
Hello again @spotUP,

I spoke to my Mac using colleague and they told me that the latest version of Safari _does_ include HTML5 validation. Are you using the latest version?

Kevin.

**Comment by spotUP** [comment]
Yes, I am using the latest version.
