### ISSUE TITLE
Refresh list when changes are made in Mailchimp

### ISSUE THREAD

**Issue by DigitalNomadStu** [yikesinc/yikes-inc-easy-mailchimp-extender#654]
Hi there,

Is there a way to refresh the contents / setting of a Mailchimp list within the Easy MC Forms plugin?

I've changed some of the options on a Checkbox field in Mailchimp, but the plugin is still showing the old options. I've tried refreshing the API key. I'm not sure if I just need to wait or what needs to happen.

Thanks,
-Stu

**Comment by kpu23** [comment]
Hi Stu,

Yes there is! Here is very brief article explaining it: https://yikesplugins.com/support/knowledge-base/api-cache-settings/.

Cheers,
Kevin.

**Comment by DigitalNomadStu** [comment]
Well, I feel silly! Thanks so much for the quick response.

**Comment by kpu23** [comment]
No problem :-)
