### ISSUE TITLE
Subscriptions are not adding to mailing list

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#663]
Hi,
For some reason when I subscribe in the form and enter my email address and other fields 
it does not get added to mailing list. I verified that the form uses the correct associated list and verified that I am using the correct API key for mailchimp. Do you know what causes this issue because it used to work before?

**Comment by kpu23** [comment]
Hi @Lir2303,

Are you getting an error message when subscribing or does the message indicate a successful subscription? Would you mind posting a URL to your form so I can test out the subscription process?

Thanks,
Kevin.

**Comment by Lir2303** [comment]
Yes, here it is:
http://newsite.myclientschedule.com/wp/
I think it indicates success

**Comment by Lir2303** [comment]
oh sorry. its fixed now

**Comment by kpu23** [comment]
Hi @Lir2303,

I was able to subscribe successfully:
![image](https://cloud.githubusercontent.com/assets/2415516/24009026/0271b7c4-0a4a-11e7-9636-ab971cb9ac7e.png)

The issue may be that you're testing with an email address that has already received the double opt-in email. MailChimp currently has an issue where the double opt-in email is not re-sent.

Could that explain it?

Kevin.

**Comment by Lir2303** [comment]
Hi,
Yeah for some reason I didn't get emails but I do now and it allows me to subscribe.
I think its resolved. The issue was on my part.

Thanks again

**Comment by kpu23** [comment]
No problem :-)

**Comment by Lir2303** [comment]
Another quick question, when I select Canada as a country the field with postal code disappears. Can I enable it?

**Comment by kpu23** [comment]
At the moment, you cannot enable it. I could definitely add that to the plugin though.

I'm actually quite ignorant about Canadian addresses/contact forms. Do you know if zip/postal code is a standard Canadian address form field, like it is in the U.S.? In your opinion, would everyone prefer a zip code field for Canadian addresses?
