### ISSUE TITLE
Postal code dissapears on select Canada as country 

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#664]
Hi,
Sorry I had another question to ask quickly. When I select Canada as a country in the field the postal code field disappears. Is there a way to enable that?

**Comment by kpu23** [comment]
Hi @Lir2303,

Sorry I closed the other ticket so quickly. I'm not sure if you saw my response: there is no way to enable this. However, I'm going to add this to the plugin. If not today, early next week.

**Comment by kpu23** [comment]
This was just released! v6.3.10. This should work without any filters/functions added on your part.

**Comment by Lir2303** [comment]
Yep this works. Thanks :)

**Comment by Lir2303** [comment]
For the zip code I can wait in the meantime

**Comment by Lir2303** [comment]
Hi,
I just wanted to confirm that everything is good if you need to close this forum. 
Thanks,

**Comment by kpu23** [comment]
Hey @Lir2303 - thanks. Closing both tickets :-)
