### ISSUE TITLE
Possible Bug: Easy Forms Mailchimp

### ISSUE THREAD

**Issue by zikuke** [yikesinc/yikes-inc-easy-mailchimp-extender#665]
Hello

I`m complete newbie. 
I activated the Easy Forms plugin yesterday, connected with Mailchimp account through API key and tested a couple of times. It connected and worked. Today I tried again to insert different emails, but this time it didn`t connect to Mailchimp at all. Doesn´t give any error messages either. Just not doing anything after I push the submit button. I then uninstalled the plugin, created a completely new list in Mailchimp and installed the plugin again. Still nothing. I cleaned the plugin cache and checked my if my IP is being blacklisted as I tried to submit many different emails to test the plugin. It wasn´t. 
Perhaps there`s something wrong with the plugin? It´s looking so nice, it would be such a pity to uninstall the plugin and use Mailchimp defaults instead. 

What could cause the disconnection between the plugin and Mailchimp? API is connected.  

Please help! 
Here is the page: 
http://foodiesjournal.com/food-blog-starting-guide/

Thank you in advance,
Sigrid

**Comment by kpu23** [comment]
Hello Sigrid,

I'm looking into this now. Not exactly sure what's going on. Can you let me know how you confirmed that your IP wasn't blacklisted?

Thanks,
Kevin.

**Comment by TheTracyL** [comment]
Hello Sigrid,

You can also try the suggestions on our Knowledge Base article:
https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

Thank you!
-Tracy

**Comment by zikuke** [comment]
Thank you!

I read from Mailchimp HELP that:
Find out if your IP address is on a blacklist at  http://multirbl.valli.org/lookup/.

I put it there, it seemed OK for me. 

The main problem is, that when I insert a name and email address into the fields and push the pink button, nothing happens. But it should show the message: Please confirm your email to subscribe etc. 
And I should get an email where I can confirm and subscribe.

Siku

**Comment by TheTracyL** [comment]
Hi Siku,

Please try the steps outlined here: https://yikesplugins.com/support/knowledge-base/i-hit-submit-on-my-form-but-nothing-happens/

Thank you!
-Tracy

**Comment by kpu23** [comment]
Siku,

Can you try toggling on AJAX submissions? I'd like to test a subscription going through AJAX. 

I also noticed there's a JavaScript error on the page coming from your theme. This _may_ be the cause of the issue, and there are steps to diagnosing them in the article Tracy posted.

**Comment by zikuke** [comment]
Hey!

Yes, I disabled AJAX and now it seems to work again. Yay!

Thank you so much for such a quick and wonderful support. 

Sigrid
