### ISSUE TITLE
How to get value of field for php

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#666]
I need to get value of a field and compare it against a string. Do you know as to how I can do that?
Is there documentation I can read about?

Thanks,

**Comment by kpu23** [comment]
Hello Again @Lir2303,

We do offer a filter for this: `yikes-mailchimp-filter-before-submission`

You can search for the filter in this article: https://yikesplugins.com/support/knowledge-base/filters/. (There's an example of how to use the filter below the list of all the filters).

Let me know if you need any more help!

Kevin.

**Comment by Lir2303** [comment]
Hi,
I essentially want to hide the 'province' field if 'country' field is set to US. So something like if(provincefield.getvalue == 'US'){
hide province field
} else{

}
The yikes-mailchimp-filter-before-submission looks like its executing after the form is submitted. 

Thanks,

**Comment by Lir2303** [comment]
sorry it should be 
if(countryfield.getvalue=='US'){
hide province field
}

**Comment by kpu23** [comment]
I see - I thought you were referring to the form data that is submitted. 

To accomplish what you're trying to do is difficult because we already have javascript that is looking for countries that have states in the dropdown, and showing/hiding the states dropdown if values exist. 

What I think I can do is put a filter on the list of states, and then you can add a function to remove the U.S. states from the list.

Does that sound right?

**Comment by Lir2303** [comment]
Oh yeah that should work.

**Comment by kpu23** [comment]
Okay sounds good - we have a couple of other things we'd like to bundle up with a new release so I can't promise it will be released today but it should be by the end of the week.

**Comment by kpu23** [comment]
P.S. one of the things we're going to bundle up with the release is the postal code issue for Canada that you're still waiting on

**Comment by Lir2303** [comment]
Sounds good. Thanks a lot. Really appreciate the support.

**Comment by kpu23** [comment]
As I said in the other thread, this was also just released! v6.3.10. You will need to add a filter function that looks just like this:

`// Add/Remove items from the states dropdown list
add_filter( 'yikes-mailchimp-state-province-list', 'remove_us_states_from_states_dropdown', 10, 2 );

function remove_us_states_from_states_dropdown( $states_dropdown_html, $form_id ) {
	return '<option data-country="CA" value="">---</option>
			<option data-country="CA" value="AB">Alberta</option>
			<option data-country="CA" value="BC">British Columbia</option>
			<option data-country="CA" value="MB">Manitoba</option>
			<option data-country="CA" value="NB">New Brunswick</option>
			<option data-country="CA" value="NL">Newfoundland and Labrador</option>
			<option data-country="CA" value="NS">Nova Scotia</option>
			<option data-country="CA" value="ON">Ontario</option>
			<option data-country="CA" value="PE">Prince Edward Island</option>
			<option data-country="CA" value="QC">Quebec</option>
			<option data-country="CA" value="SK">Saskatchewan</option>
			<option data-country="CA" value="NT">Northwest Territories</option>
			<option data-country="CA" value="NU">Nunavut</option>
			<option data-country="CA" value="YT">Yukon</option>';
}`

You should probably just copy and paste this :-)

Let me know how you get along on both open tickets!

Cheers,
Kevin.

**Comment by Lir2303** [comment]
Yep this works. Thanks :)

**Comment by Lir2303** [comment]
For the zip code I can wait in the meantime

**Comment by Lir2303** [comment]
Hi,
I just wanted to confirm that everything is good if you need to close this forum. 
Thanks,
