### ISSUE TITLE
Forward tag

### ISSUE THREAD

**Issue by Teresa-Fernandes** [yikesinc/yikes-inc-easy-mailchimp-extender#670]
Hi,

In my form, it is possible use `*|FORWARD|*` code to forward to a friend? 
Where must put this code?
Regards
          Teresa

**Comment by kpu23** [comment]
Hi Teresa,

Unfortunately we do not have any logic to handle this tag. To be honest, this is the first time I've heard of MailChimp's `|FORWARD|` tag. I'll make a ticket for this and we can, at the least, investigate the feasibility and how long it would take to add it. 

Sorry about that,
Kevin.

**Comment by Teresa-Fernandes** [comment]
Hi Kevin,


So, when you have news, let me know...

Regards

        Teresa


________________________________

**Comment by kpu23** [comment]
Hi Teresa,

Unfortunately the `|FORWARD|` tag is not something we can add to our plugin; this is a variable that is used in MailChimp emails, and we do not control those in any way.

Sorry about that!

Kevin.
