### ISSUE TITLE
MailChimp Forward Tag

### ISSUE THREAD

**Issue by kpu23** [yikesinc/yikes-inc-easy-mailchimp-extender#671]
Investigate the `*|FORWARD|*` tag and see if we can add it as a variable for our success messages. Does the MailChimp API expose this data? Let's find out.

See Issue #670 

MailChimp link: http://kb.mailchimp.com/campaigns/design/add-the-forward-to-a-friend-link

**Comment by JPry** [comment]
Kevin,

Based on reading the description in the MailChimp KB, it seems that the `*|FORWARD|*` tag is intended to be embedded in the campaign message content (e.g., the actual email that is sent out to subscribers). It doesn't seem to be used as a merge tag that's relevant at the time someone subscribes to the list.

I don't think there's anything to do with that tag in the plugin.

**Comment by kpu23** [comment]
Thanks for investigating that. I'm just going to close this ticket out. It has served its purpose!
