### ISSUE TITLE
Single opt-in is not receiving new subscriber notifications

### ISSUE THREAD

**Issue by fabiolobo17** [yikesinc/yikes-inc-easy-mailchimp-extender#672]
Hello how are everyone? I have a problem with the yikes-inc-easy-mailchimp-extender plugin. I tried to include the form of the plugin yikes with single opt-in but not getting new subscriber notifications in my email when I choose single opt-in. I also tried to integrate using contact form 7, putting the checkbox. In this case, I get the contact's data but the user is not inserted in the mailchimp list. All tags are filled in accordingly. I also include the block of code in the function.php file suggested by EvanHerman. Can you give me any tips? I do not know what else to do.

**Comment by kpu23** [comment]
Hi @fabiolobo17,

I'm doing well, thanks for asking :-).

Could you send us a URL to your form (specifically the standard Easy Forms form - not the contact form 7 form). That should give me some visibility into the problem.

Thanks,
Kevin.

**Comment by TheTracyL** [comment]
Hi.

For the first issue, MailChimp doesn't allow notifications with single opt-in. Kevin can help with the 2nd issue.

Thank you
-Tracy

**Comment by fabiolobo17** [comment]
Thank you so much guys.
