### ISSUE TITLE
Formatting the Sign Up Form

### ISSUE THREAD

**Issue by phyohtetminn** [yikesinc/yikes-inc-easy-mailchimp-extender#673]
Hi there,
I need support formatting the sign up form.
Currently they are not aligned at all.
Please see here:
https://snag.gy/QlbHNV.jpg
Kindly advise.

Thanks & regards,
Phyo Htet Minn

**Comment by kpu23** [comment]
Hello Phyo Htet Minn,

I believe you need to remove the labels "First Name" and "Last Name" and the form will align itself into place. To do this, click on the First & Last Name fields (so it slides down and shows the field options), then check the checkbox "Hide Label."

Let me know if that solves it,
Kevin.

**Comment by phyohtetminn** [comment]
Hi Kevin,
That helped. Thanks a lot.
Best,
Phyo Htet Minn

**Comment by kpu23** [comment]
Hey no problem!
