### ISSUE TITLE
Canada Postal Code Issue

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#674]
Hi,
The postal code field requires to enter 5 digits. However the Canadian postal code is different. The format is 
A2V 6G1. So letter,number,letter    number,letter,number. So when I select Canada as a country I want to be able to enter the zip code in this format.

**Comment by kpu23** [comment]
Hello again @Lir2303,

Yes this is known. Here is an article from our knowledge base - you may want to skip to the end where it shows you how to remove the regex validation, which is probably what you'd like to do. Alternatively, you can add your own regex, but this is a bit more complicated. 

https://yikesplugins.com/support/knowledge-base/received-following-error-error-address-field-please-enter-complete-address-may-want-consider-defaulting-zip-code/

Let me know if you need more info,
Kevin.

**Comment by Lir2303** [comment]
I see, yeah it works now. I will be reading the API so that I won't ask so many questions in the future. 

Thanks

**Comment by kpu23** [comment]
Hey no problem - almost all of the questions/requests you've been asking about were added for you (and a couple other users) within the past month. The article I linked to is less than a month old. Feel free to ask questions :-).
