### ISSUE TITLE
Form field text color is same color as form field (invisible)

### ISSUE THREAD

**Issue by rachelreally** [yikesinc/yikes-inc-easy-mailchimp-extender#675]
I'm using a new theme, Analytical, and now my Easy Forms fields text are all colored white, blending so well in the fields that you can't see what you're typing. I've tried searching for where I can make form field text a dark instead of light color but am hitting a wall. Any recommendations?

**Comment by TheTracyL** [comment]
Hi Rachel,

Please post a link to your form and we'll be happy to help.

Thank you!
-Tracy

**Comment by rachelreally** [comment]
Sure!
Here's my newsletter landing page with an Easy Form for the sign-up:
http://really.social/newsletter.

I have a feeling I just need to add form class to my forms to make the
input font not white, but I can't find a definitive code to use for that.

**Comment by TheTracyL** [comment]
Hi Rachel.

The theme has CSS that makes every form input white.

You can use the CSS code below to fix that.

```CSS
#content .yikes-easy-mc-form input[type="text"], 
#content .yikes-easy-mc-form input[type="email"] {
	color: #000;
}
```


You have a few options to add CSS code:

- If you created this theme yourself, you can just add it to your style.css file
- If you're using WordPress 4.7 or higher, you can go to Appearance > Customize > Additional CSS and place the code there.
- If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
- Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
- You can use a plugin like <a href="https://wordpress.org/plugins/simple-custom-css/">Simple Custom CSS</a> or Jetpack and enter the code in their Custom CSS area

Thank you!
-Tracy

**Comment by rachelreally** [comment]
THANK YOU! That worked - I so appreciate it! Saved me tons of headache. :)

**Comment by TheTracyL** [comment]
Yay! I'm so glad I could help.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy
