### ISSUE TITLE
Change Particular Form the Field Labels to French

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#679]
Hi again,
Thank you for all the help thus far. I am almost complete integrating the forms to my site, I just have a few questions.
I attached two images that show two different forms. One in French and one is in English. They both use the same mailing list. **I wanted to change the fields for Address, City, State/Province and etc.. to French in the French form.** **Wondering as to how to do so since I cannot edit the City, State/Province fields individually.** **The other fields I was able to. Also I wanted to edit the captcha to French in the French form only.** 

Thanks,
![english form](https://cloud.githubusercontent.com/assets/16902054/24963674/3f72fb82-1f6d-11e7-8086-730e5158fb8b.PNG)
![french form](https://cloud.githubusercontent.com/assets/16902054/24963675/3fd0f624-1f6d-11e7-9b61-6aacf7b312e9.PNG)

**Comment by kpu23** [comment]
Hi @Lir2303,

Hope you're well.

Because address fields work differently (one "field" for 6 input fields), the associated filters work differently also. To change the address field labels, use these filters:
- `yikes-mailchimp-address-addr1-label`
- `yikes-mailchimp-address-addr2-label`
- `yikes-mailchimp-address-city-label`
- `yikes-mailchimp-address-state-label`
- `yikes-mailchimp-address-zip-label`
- `yikes-mailchimp-address-country-label`

I'm looking into the ReCaptcha now.

**Comment by kpu23** [comment]
For the ReCaptcha, check out this article: https://yikesplugins.com/support/knowledge-base/how-do-i-customize-the-recaptcha-field/.

I don't have much experience with customizing the ReCaptcha field, so please let me know how you get along.

As always,
Kevin.

**Comment by Lir2303** [comment]
Yeah that's perfect the ReCaptcha works. For the fields, how do I change it only to a specific form shortcode. I have something like this:
function yikes_mailchimp_change_addr1_label( $field_label, $form_id ){
	$field_label = 'TestTest';
	return $field_label;
}
add_filter( 'yikes-mailchimp-address-addr1-label', 'yikes_mailchimp_change_addr1_label', 10, 3 );

I am passing in arguments the form id 3 so that it changes that label only on my form with the shortcode  3 but it seems like it changes  the label on all forms.

**Comment by kpu23** [comment]
Here is an example targeting only form ID 3:
```
function yikes_mailchimp_change_addr1_label( $field_label, $form_id ){
    if ( $form_id === 3 ) {
        $field_label = 'Form ID 3's Addr1 Label';
        return $field_label;
    }
}
add_filter( 'yikes-mailchimp-address-addr1-label', 'yikes_mailchimp_change_addr1_label', 10, 2 );
```

**Comment by Lir2303** [comment]
Oh I see. Thank you.

**Comment by kpu23** [comment]
No problem :D
