### ISSUE TITLE
How to add multiple classes to submit button

### ISSUE THREAD

**Issue by awilson69** [yikesinc/yikes-inc-easy-mailchimp-extender#681]
I am trying to style the submit button.  I have been able to add a single class to change the background color, but I am also trying to change the color whenever a user hovers over / clicks the button.

I thought adding a second class would do this, but that doesn't appear to work or I am not separating the classes correctly.

Could you provide direction on how to do this?  

Below are two examples I've tried which have not worked for me:

yikes-subscribe-button,yikes-subscribe-button-hover
yikes-subscribe-button|yikes-subscribe-button-hover

**Comment by TheTracyL** [comment]
Hi there,

Here is how you style various element states:

:link - a normal, unvisited link
:visited - a link the user has visited
:hover - a link when the user mouses over it
:active - a link the moment it is clicked

So in your example, to style the hover state of the button would be styled liked this:

```CSS
.yikes-subscribe-button:hover {
     your styles here...
}

Let me know if that makes sense :-)

Thank you!
-Tracy
```

**Comment by awilson69** [comment]
Thank you, Tracy.  That makes a lot of sense.

Following that, I added the following two CSS statements, which appear to work, except ":active".  By that, I mean when I tab to the button is still reverts back to the default color and ignores the color I specified, even with !important.  

Is there another state that I'm missing?  

.yikes-subscribe-button, .yikes-subscribe-button:visited {background-color: #ffc000;}
.yikes-subscribe-button:hover, .yikes-subscribe-button:active {background-color: #d9a915 !important;}

**Comment by TheTracyL** [comment]
Active should work on non-link elements: https://css-tricks.com/almanac/selectors/a/active/

Tabbing to the button wont trigger :active, it will happen when you click on it.

:focus may work for tabbing: https://css-tricks.com/almanac/selectors/f/focus/

**Comment by awilson69** [comment]
Thank you, Tracy.  That totally worked!

**Comment by TheTracyL** [comment]
Woot! Glad I could help.

Have a good weekend!
-Tracy

**Comment by awilson69** [comment]
Me too!  Thank you, and you too!
