### ISSUE TITLE
How can people who previously unsubscribed be added to our list?

### ISSUE THREAD

**Issue by PASAprimates** [yikesinc/yikes-inc-easy-mailchimp-extender#684]
We used a Yikes plugin to make a petition, which sends email addresses to our MailChimp account. Every day, dozens of people who unsubscribed from our mailing list sometime in the past are trying to sign the petition and are getting error messages that say “[email address] has been removed, and cannot be resubscribed by you…”. 

How can they sign the petition, be added to the petition list in MailChimp, and receive our mailings? 

I imagine one possibility is to have a separate list in MailChimp for petition signers, but it would be awkward to manage 2 lists and many people would be on both lists.

**Comment by kpu23** [comment]
Hi @PASAprimates,

Unfortunately this behavior is really difficult to get around without using separate lists. MailChimp prevents emails from being re-added to lists that they've unsubscribed from (for privacy reasons). They do allow the user to resubscribe themselves, but the problem is that the MailChimp API the plugin is using has no way of knowing if this was the user. 

My suggestion would be to use a list for your normal MailChimp emails, and a separate list for each petition. I know it may be annoying and I'm sorry about that.

However, after reading this article, http://kb.mailchimp.com/lists/manage-contacts/resubscribe-a-contact, it seems like using the double opt-in method should allow users to re-subscribe. Is your form set to single or double opt-in? (I'm not positive this will work because most of the information in the article relates to a MailChimp "Hosted Form," and we're not using that - we're using a custom form with the MailChimp API).

Sorry I couldn't be more helpful - this is one of the confusing parts of MailChimp where laws restrict some otherwise basic functionality.

Kevin.

**Comment by PASAprimates** [comment]
Hi Kevin,



Thanks for your reply. Is it possible for me to change the text of the
error message people see when they try to sign the petition but have
already been unsubscribed from our MailChimp list? Currently, it says, “…*Has
Been Removed, And Cannot Be Resubscribed By You. To Prevent False Spam
Complaints, They'll Need To Resubscribe Of Their Own Free Will.*” It would
be great if I can change it to a link to a different form that is connected
to a different List in MailChimp.



Thanks,

Gregg




*Gregg Tully*
*Executive DirectorPan African Sanctuary Alliance*
pasaprimates.org <http://www.pasaprimates.org/>
facebook.com/pasaprimates



*From:* Kevin Utz [mailto:notifications@github.com]
*Sent:* Tuesday, April 18, 2017 9:28 AM
*To:* yikesinc/yikes-inc-easy-mailchimp-extender <
yikes-inc-easy-mailchimp-extender@noreply.github.com>
*Cc:* PASAprimates <gregg@pasaprimates.org>; Mention <
mention@noreply.github.com>
*Subject:* Re: [yikesinc/yikes-inc-easy-mailchimp-extender] How can people
who previously unsubscribed be added to our list? (#684)



Hi @PASAprimates <https://github.com/PASAprimates>,

Unfortunately this behavior is really difficult to get around without using
separate lists. MailChimp prevents emails from being re-added to lists that
they've unsubscribed from (for privacy reasons). They do allow the user to
resubscribe themselves, but the problem is that the MailChimp API the
plugin is using has no way of knowing if this was the user.

My suggestion would be to use a list for your normal MailChimp emails, and
a separate list for each petition. I know it may be annoying and I'm sorry
about that.

However, after reading this article,
http://kb.mailchimp.com/lists/manage-contacts/resubscribe-a-contact, it
seems like using the double opt-in method should allow users to
re-subscribe. Is your form set to single or double opt-in? (I'm not
positive this will work because most of the information in the article
relates to a MailChimp "Hosted Form," and we're not using that - we're
using a custom form with the MailChimp API).

Sorry I couldn't be more helpful - this is one of the confusing parts of
MailChimp where laws restrict some otherwise basic functionality.

Kevin.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/684#issuecomment-294843807>,
or mute the thread

**Comment by kpu23** [comment]
Hi Gregg,

Unfortunately this message is coming directly from MailChimp.

We do offer custom messages (see the custom messages section of the form builder), but we have only one error message ("General Error"). In this case, MailChimp views this subscription as an error, so you could use the General Error message and include a link to the other form. The problem is that different errors may occur, and you would be sending everyone to the other form. Does that make sense?

Cheers,
Kevin.

**Comment by PASAprimates** [comment]
Hi Kevin,



Thanks, I think I can make a decent workaround based on this. Is there a
way to include links in the General Error message? I tried using [link] …
[/link], which is an option in a different kind of message, but it didn’t
seem to work.



Thanks very much,

Gregg




*Gregg Tully*
*Executive DirectorPan African Sanctuary Alliance*
pasaprimates.org <http://www.pasaprimates.org/>
facebook.com/pasaprimates



*From:* Kevin Utz [mailto:notifications@github.com]
*Sent:* Monday, April 24, 2017 4:11 PM
*To:* yikesinc/yikes-inc-easy-mailchimp-extender <
yikes-inc-easy-mailchimp-extender@noreply.github.com>
*Cc:* PASAprimates <gregg@pasaprimates.org>; Mention <
mention@noreply.github.com>
*Subject:* Re: [yikesinc/yikes-inc-easy-mailchimp-extender] How can people
who previously unsubscribed be added to our list? (#684)



Hi Gregg,

Unfortunately this message is coming directly from MailChimp.

We do offer custom messages (see the custom messages section of the form
builder), but we have only one error message ("General Error"). In this
case, MailChimp views this subscription as an error, so you could use the
General Error message and include a link to the other form. The problem is
that different errors may occur, and you would be sending everyone to the
other form. Does that make sense?

Cheers,
Kevin.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/684#issuecomment-296808326>,
or mute the thread

**Comment by kpu23** [comment]
Hi Gregg, 

You'll need to use HTML for the link in the error message. The HTML link tag should look like this:
`<a href="www.example.com">Your Link Text</a>`

If you need any help with the error message just let me know the text and I can add any necessary HTML to it.

Kevin.

P.S. I support and respect your organization. Best wishes to you and your colleagues, and send my love to the primates :)

**Comment by PASAprimates** [comment]
Hi Kevin,



On behalf of the monkeys and apes in our care, thanks so much for your kind
help. We really appreciate it.



All best,

Gregg




*Gregg Tully*
*Executive DirectorPan African Sanctuary Alliance*
pasaprimates.org <http://www.pasaprimates.org/>
facebook.com/pasaprimates



*From:* Kevin Utz [mailto:notifications@github.com]
*Sent:* Tuesday, April 25, 2017 8:52 AM
*To:* yikesinc/yikes-inc-easy-mailchimp-extender <
yikes-inc-easy-mailchimp-extender@noreply.github.com>
*Cc:* PASAprimates <gregg@pasaprimates.org>; Mention <
mention@noreply.github.com>
*Subject:* Re: [yikesinc/yikes-inc-easy-mailchimp-extender] How can people
who previously unsubscribed be added to our list? (#684)



Hi Gregg,

You'll need to use HTML for the link in the error message. The HTML link
tag should look like this:
<a href="www.example.com">Your Link Text</a>

If you need any help with the error message just let me know the text and I
can add any necessary HTML to it.

Kevin.

P.S. I support and respect your organization. Best wishes to you and your
colleagues, and send my love to the primates :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/684#issuecomment-297019849>,
or mute the thread
