### ISSUE TITLE
Can I make the 'state' field optional to fill?

### ISSUE THREAD

**Issue by Lir2303** [yikesinc/yikes-inc-easy-mailchimp-extender#685]

**Comment by kpu23** [comment]
Hi Liran,

At the moment, no, but I will add a filter to this for the next release. It's an easy change and there should be a filter there anyway.

Cheers,
Kevin.

**Comment by Lir2303** [comment]
Oh is see. The reason I am asking is because when I select a country other then US or Canada, it hides the state and zip fields. Since the state field is required it gives me an error that not all fields are filled but because 'state' is hidden you are unable to submit the form.

**Comment by kpu23** [comment]
Yeah I see that. It'll be fixed soon.

**Comment by Lir2303** [comment]
Thank you

**Comment by Lir2303** [comment]
Sorry just a quick question, i changed my site domain and the captcha in mailchimp form gets the following error:
ERROR for site owner:
Invalid domain for site key

Is there a way I can fix it?

**Comment by Lir2303** [comment]
Actually I just found out the reason. Its all good

**Comment by kpu23** [comment]
Okay good. I ran into a snag yesterday with the state field being required. We do a check on the back end (when the form is submitted) to see if required fields are empty. This check is not as flexible as the front-end one, and I need to extend it to allow me to ignore certain fields. The fix will come in good time.

**Comment by Lir2303** [comment]
Sounds good.

**Comment by kpu23** [comment]
Ahh, I ran into a much bigger issue: MailChimp rejects addresses that do not contain addr1, city, state, zip, and country. This means you can't submit a successful subscription without having a value for state. 

The best way to go about this is to supply the "---" option (the first, default option for the state dropdown) with a value like "--". Are you using the `'yikes-mailchimp-state-province-list'` to create your own dropdown?

**Comment by Lir2303** [comment]
Yes, I am using 'yikes-mailchimp-state-province-list'. I think I have the province defaulted to "---"

**Comment by kpu23** [comment]
Hi Liran,

Make sure that the HTML `value` field also equals "---". The default for the plugin is something like `<option data-country="CA" value="">---</option>`. For it to pass through successfully, it would need to be like `<option data-country="CA" value="---">---</option>`.

Sorry this is a bit inconvenient - MailChimp was not built for international addresses and their support for them is building slowly.

**Comment by Lir2303** [comment]
Hi,
Sorry I was making some changes and it took a while.  I think I was using the mailchimp dropdown list from mailchimp.com but its working on the yikes mailchimp form. Because its mailchimp.com i'm unsure how to set default value in province list. 

Also do you have an example of how to use 'yikes-mailchimp-address-2-required'. I want to set the field to some string. 

Thank you.

**Comment by kpu23** [comment]
Can you send over the code you're using for the MailChimp.com state/province list?

And the addr2 field works differently than the other address fields. By default, it shouldn't be required (by MailChimp or by the plugin). There's a little bug right now that is forcing it to be required. Pretty sure I just fixed it though. Will push soon.

**Comment by kpu23** [comment]
If you update to v6.3.18 you'll see that the address 2 field is no longer required.
