### ISSUE TITLE
Woocommerce integration breaks checkout

### ISSUE THREAD

**Issue by rvstoreplus** [yikesinc/yikes-inc-easy-mailchimp-extender#686]
Hi,

We have woocommerce (3.03) installed on accesspress store (2.17) and have been using Easy Forms for MailChimp successfully for quite a while. During a recent round of updates a problem popped up where on the checkout page the phone and email text boxes could not be selected with the mouse only moved to with the tab key. The text for the opt in check box is also out of place. I narrowed it down to this plugin causing the issue. I now have the plugin active but not integrated with woocommerce which has fixed the selection problem but we would obviously like to be capturing signups at checkout again. Site is rvstoreplus.com if this helps, I can provide more info as required. Thanks for your help.

**Comment by kpu23** [comment]
Hi @rvstoreplus,

WooCommerce's 3.0 launch was a major update and they changed a lot of the HTML structure/classes. Let me test this out; I will most likely need to fix something and push a new version of the plugin to support the WooCo update.

Thanks for letting me know and thanks for your patience :)

All the best,
Kevin.

**Comment by rvstoreplus** [comment]
Ok, Thanks.

I’ll keep an eye out for updates.

Cheers, Ben


RVStore Plus - Accessories Parts Supplies
A1 Caravans - Installation Service Repair

SA's Home of Blue Sky Caravans

Helping great holidays happen!

www.rvstoreplus.com <>

**Comment by kpu23** [comment]
Hi Ben,

I have a fix for this issue. I just need to fix one other issue and then I will release a new plugin version.

Cheers,
Kevin.

**Comment by kpu23** [comment]
Ben,

Please download v6.3.14 and re-enable the WooCommerce checkbox integration. 

Let me know if it's working,
Kevin.

**Comment by rvstoreplus** [comment]
Thanks Kevin,

I’ll do that today and let you know,

Ben


RVStore Plus - Accessories Parts Supplies
A1 Caravans - Installation Service Repair

SA's Home of Blue Sky Caravans

Helping great holidays happen!

www.rvstoreplus.com <>

**Comment by rvstoreplus** [comment]
All looks good and is working fine, Thanks for your work on it.

Ben


RVStore Plus - Accessories Parts Supplies
A1 Caravans - Installation Service Repair

SA's Home of Blue Sky Caravans

Helping great holidays happen!

www.rvstoreplus.com <>

**Comment by kpu23** [comment]
Great! No problem. Cheers Ben.
