### ISSUE TITLE
400+ popup support??

### ISSUE THREAD

**Issue by joshkeely** [yikesinc/yikes-inc-easy-mailchimp-extender#687]
Hello,
Currently we use Popup by Supsystic pro (https://supsystic.com/plugins/popup-plugin/) for our website. We have over 400 different unique popup URLs to track WHERE a subscriber came from. For example, http://ourdomain.com/#showpopup_434 would be from advertisement A, while http://ourdomain.com/#showpopup_435 would be from advertisement B. We are able to get a csv report on how many subscribers by using mysql . It tells us how and when each subscriber came to us.

The problem is that with 400+ unique popups, it renders each in HTML with every page load, so that when the #showpopup_x is called, it displays the hidden DIV for the subscribe box. So the page now loads very slowly with 400+ popups (13-15 seconds). 

Can you tell me how your system would handle 400+ popups before I buy the license? I cannot test this out and want to make sure it works before purchasing.

Thank you.

Josh

**Comment by kpu23** [comment]
Hi Josh,

First, you would need to write some code to extend our popup plugin if you'd like the tracking features that you're currently getting.

Second, the way the plugin works is that we have rules for whether or not the popup should show on that page. The first thing we do on page load is check the rules for the popups. If any of the rules return true (e.g. "Show popup on Home page"), then we load the JS and HTML for that specific popup.

So if you had 400 popups, there would be at least the initial rule check on every page. This is much quicker than loading HTML/JS on every page, but I would still think it would take around half a second. Also, the best way to optimize our plugin would be to make your rules unique (e.g. on popup assigned to one single page). This way you ensure the only processing time is to (1) check the logic for all 400 popups and (2) loading the HTML/JS for that single popup.

I personally haven't tested the affect of having 400 popups on one site.

Let me know if you have any questions,
Kevin.
