### ISSUE TITLE
Center Submit Button Text

### ISSUE THREAD

**Issue by smmerlovin64** [yikesinc/yikes-inc-easy-mailchimp-extender#689]
The "submit" text is at the bottom of my button, rather than vertically centered. How do I fix this?

**Comment by TheTracyL** [comment]
Hello,

Can you please post a link to your form so we can take a look?

Thank you,
-Tracy

**Comment by TheTracyL** [comment]
Hi @ smmerlovin64 

There is this tag inserted in the button tag with the class of `btn-raised` which is causing the text to have too much line height. 

`<a class=\&quot;btn btn-raised btn-rounded btn-color-1\&quot;">`

Can that tag be removed? It doesn't seem to be doing anything.

Thank you,
-Tracy

**Comment by smmerlovin64** [comment]
The problem existed before I made any changes to the form. I just deleted the form and created a new one, and the issue is still there. Thank you for the help!

**Comment by TheTracyL** [comment]
We're getting closer :-)

Your theme also has styles applied to all .btn classes that makes the line-height: 40px;

This CSS should fix it.

```CSS
.yikes-easy-mc-form .yikes-easy-mc-submit-button {
    cursor: pointer;
    line-height: 1;
}
```

You have a few options to add CSS code:

- If you created this theme yourself, you can just add it to your style.css file
- If you're using WordPress 4.7 or higher, you can go to Appearance > Customize > Additional CSS and place the code there.
- If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
- Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
- You can use a plugin like <a href="https://wordpress.org/plugins/simple-custom-css/">Simple Custom CSS</a> or Jetpack and enter the code in their Custom CSS area

Thank you!
-Tracy

**Comment by smmerlovin64** [comment]
That worked! Thank you so much.

**Comment by TheTracyL** [comment]
Yay! Awesome, glad I could help.
-Tracy
