### ISSUE TITLE
Unable to Purchase "Popups for Easy Forms for MailChimp" 

### ISSUE THREAD

**Issue by fibercloset** [yikesinc/yikes-inc-easy-mailchimp-extender#691]
I want to purchase the above plugin.  I was paying with PayPal.  PayPal shows they sent the payment and it is unclaimed.  But, the checkout shows Failed.
The checkout showed:  Unable to process order for #6344 	April 25, 2017 	$19.99 	Failed 
PayPal shows:  Payment to YIKES, Inc., Status: Unclaimed, Shopping Cart Payment Sent (Unique Transaction ID #7HV23733UH762822N)
When I tried to re-order, PayPal says the order has already processed.

**Comment by TheTracyL** [comment]
Hi there,

I accepted the payment and you should now have gotten the purchase receipt.

Sorry for the inconvenience!
-Tracy

**Comment by fibercloset** [comment]
Thanks for the prompt reply.  I have downloaded the plugin.

Cheryl Ann Moreo
The Fiber Closet
120 S Market Street
Rockville, IN  47872
765-569-2953
The Fiber Closet Online <http://www.thefibercloset.com>
