### ISSUE TITLE
Error collecting the API response

### ISSUE THREAD

**Issue by dgparham** [yikesinc/yikes-inc-easy-mailchimp-extender#695]
Hello - I believe everything is correct but I'm getting Error Collecting API Response.
![screenshot-aphw com-2017-04-27-13-52-31](https://cloud.githubusercontent.com/assets/5923615/25496937/e72539d2-2b50-11e7-9305-af7df09b183a.png)

MailChimp API is connected, but what does the "enable nonce validation on this site" do?

I set it to "no" and get this error, set it back and continue to get it?
Warning: Cannot modify header information - headers already sent by (output started at /home/content/p3pnexwpnas09_data02/22/2653722/html/wp-content/themes/reverie-child-master-aphw/functions.php:3) in /home/content/p3pnexwpnas09_data02/22/2653722/html/wp-includes/pluggable.php on line 1195

Any help appreciated!

**Comment by kpu23** [comment]
Hi @dgparham,

An "Error collecting the API response" usually means there's a fatal error going on somewhere, which usually means a plugin or theme conflict. Can you send a URL to your form so I can check it out? 

Thanks,
Kevin.

**Comment by dgparham** [comment]
https://aphw.com/rfq-test-mailchimp/

Thanks for looking at this Kevin, can share the WP info if needed

**Comment by kpu23** [comment]
The form is sending and receiving the data properly, but there's something in your system that is outputting whitespace and this makes the response unreadable. 

Have you had issues with AJAX on your site?

As a short term fix, you could set your form to non-AJAX (via the submission settings on the form builder). To get AJAX working we'll need to diagnose what's going on with the whitespace being outputted. Any ideas?

Kevin.

**Comment by dgparham** [comment]
We've got a nice Contact Form 7 that's been doing fine, we just want to
integrate w/MC now and plugin seemed like the best way..

Ideally would like to integrate with Contact Form 7 using some mod to the
php, what do you think would be best?

Goal is to populate MC with our form data.

**Comment by kpu23** [comment]
I would recommend using our CF7 integration. If you go to our plugin's settings page you'll see an integrations link. If you enable the Contact Form 7 integration, your contact form will include a checkbox. Clicking this checkbox will subscribe the user to your specified mailing list. 

That's what you're looking for, right?

**Comment by dgparham** [comment]
Yeah, but these are RFQ forms, not customers who need an opt-in/out option
may not need checkbox?

I'd like to map the CF7 fields to MC and actually attempted, need help.

So, in integration settings I select CF7 and the list and Checkbox Label ,
named "Get a Quote" and Precheck Checkbox, attached.

But in the Function.php I wasn't sure where to place the code, can it be
altered to have all the field at once?

Need to have the First Last Phone Email Street City State Zip

if ( isset( $cf7_variables['your-name'] ) ) {

        // Filter name and add it to our MailChimp merge variables array
        $merge_variables['NAME'] = filter_var( $cf7_variables['your-name'],
FILTER_SANITIZE_STRING );

**Comment by dgparham** [comment]
Here are the actual MC fields to pull

**Comment by kpu23** [comment]
Hi David,

I'm sorry I'm a bit confused as to what you're trying to achieve. Can you explain what you're trying to achieve with the function in functions.php?

**Comment by dgparham** [comment]
Sorry, Kevin,

I'd like to have this form: https://aphw.com/home-warranty-quotes/ send
data to MC.

**Comment by kpu23** [comment]
Okay I understand now. So we're going to need to add the checkbox regardless. You can have it pre-checked and customize the text so it doesn't feel out of place. This will prepare the subscription request to MailChimp.

Next, we need to decide which fields we want to send. We can add these fields to our MailChimp request using a filter. Are we sending all of the fields? 

Based on the code from our KB article (https://yikesplugins.com/support/knowledge-base/contact-form-7-populate-the-merge-variable-data-with-additional-information-about-the-user/), this is what the function should look like:

`// Defining the filter
add_filter( 'yikes-mailchimp-contact-form-7', 'additional_contact_form_7_data', 10, 2 );

// And defining our function to grab CF7 form data and send it off to MC
function additional_contact_form_7_data( $merge_variables, $cf7_variables ) {
 
	$merge_variables['NAME'] = isset( $cf7_variables['your-name'] ) ? $cf7_variables['your-name'] : '';
	$merge_variables['phone'] = isset( $cf7_variables['tel-506'] ) ? $cf7_variables['tel-506'] : '';
	$merge_variables['address']['addr1'] = isset( $cf7_variables['property-street-address'] ) ? $cf7_variables['property-street-address'] : '';
	$merge_variables['address']['city'] = isset( $cf7_variables['city'] ) ? $cf7_variables['city'] : '';
	$merge_variables['address']['state'] = isset( $cf7_variables['menu-346'] ) ? $cf7_variables['menu-346'] : '';
	$merge_variables['address']['zip'] = isset( $cf7_variables['zip-code'] ) ? $cf7_variables['zip-code'] : '';
	$merge_variables['address']['country'] = 'US';

	return $merge_variables;
}`

The keys 'NAME', 'phone', and 'address' need to be replaced with the field's MERGE tag. The article I linked to has some details on how to find the MERGE tags.

The keys 'your-name', 'tel-506', and the address ones are the names of the CF7 input fields. Based on your form, I'm pretty sure I grabbed the correct names so you shouldn't need to change those unless you're making changes to the CF7 form.

**Comment by dgparham** [comment]
Kevin, I'm not skilled in this but will give it a try.

Yesterday I attempted to change the function.php and thought I changed it
back but now getting these errors when trying to sign in to WP, what should
I do? (Site still works to the public).


*Warning*: Cannot modify header information - headers already sent by
(output started at
/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-content/themes/reverie-child-master-aphw/functions.php:3)
in */home/content/p3pnexwpnas09_data02/22/2653722/html/wp-login.php* on
line *394*

*Warning*: Cannot modify header information - headers already sent by
(output started at
/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-content/themes/reverie-child-master-aphw/functions.php:3)
in */home/content/p3pnexwpnas09_data02/22/2653722/html/wp-login.php* on
line *407*

*Warning*: Cannot modify header information - headers already sent by
(output started at
/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-content/themes/reverie-child-master-aphw/functions.php:3)
in
*/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-includes/pluggable.php*
on
line *904*

*Warning*: Cannot modify header information - headers already sent by
(output started at
/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-content/themes/reverie-child-master-aphw/functions.php:3)
in
*/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-includes/pluggable.php*
on
line *905*

*Warning*: Cannot modify header information - headers already sent by
(output started at
/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-content/themes/reverie-child-master-aphw/functions.php:3)
in
*/home/content/p3pnexwpnas09_data02/22/2653722/html/wp-includes/pluggable.php*
on
line *906*
America's Preferred Home Warranty <https://wordpress.org/>

**Comment by kpu23** [comment]
Hmm. I'm not sure how that would happen. All of the errors seem to originate with the functions.php file at line 3. Can you check out that part of the file and see if you may have left something from yesterday? You could paste the top 10 lines or so from the file here and I can try to see if there's any obvious errors. It may be whitespace (spacebars/enters/tabs) at the top of the file that's being interpreted as output.

**Comment by dgparham** [comment]
Just talked to GoDaddy, have shared hosting, they reinstalled the core
files and said it should take about an hour.

Once/if it restarts and I can get access I'll try to paste the top 10 lines
into the top of the functions.php file, thanks

**Comment by kpu23** [comment]
Don't paste the top 10 lines into the top of the functions.php file! Sorry I was unclear - I was asking you to paste the top lines FROM the functions.php file HERE (so I could look at it and see if there were any obvious issues).

**Comment by kpu23** [comment]
Also I should leave you with a note of caution - please backup your functions.php file (just create another one called functions-backup.php or something and place it on your desktop). This way if anything goes wrong we can replace the file.

**Comment by dgparham** [comment]
Will do - once it comes back, hasn't yet..

**Comment by dgparham** [comment]
Sorry for the delay, back up, had to restore from Wed.

Which plugin do you think would work best for this task, Easy Forms for
MailChimp or Contact Form 7 MailChimp Extension?

**Comment by dgparham** [comment]
Hi Kevin,

What should I select for these?

**Comment by kpu23** [comment]
Hi David,

Since I develop and maintain Easy Forms for Mailchimp and have no experience with Contact Form 7 for Mailchimp, I naturally would recommend Easy Forms.

What step are you on?

**Comment by dgparham** [comment]
Hey Kevin,

I'm on the Integration Settings and just selected Contact Form 7, and
choose the Associated List from the pull down,

But what about Checkbox Label? Do I just put something like "I agree to
have APHW supply a quote."

**Comment by kpu23** [comment]
Yeah I would recommend language like that. If you want to get a bit fancy we can try to add code to hide the checkbox completely, but let's start with it like this and get it working first.

**Comment by dgparham** [comment]
Okay that parts done, here's what the mailchimp person said however.

Thanks, can you make sure that the fields line up (RFQ list). It’s
important that the phone number is added to both the phone number and
company fields in MC. The purl is derived from the company field.

*Web Site Field*

*Mail Chimp Field*

First Name

First Name

Last Name

Last Name

Phone Number

Phone Number

Phone Number

Company

Email Address

Email Address

Property Address

Property Address

Unit

Unit

Property State

Property State

Property Zip

Property Zip

Kevin, I think I need your help formatting the php, do you need the
screenshot from the MailChimp for List fields and *|MERGE|* tags?

**Comment by kpu23** [comment]
Yeah send over the List Fields / MERGE tags.

**Comment by dgparham** [comment]
Hi Kevin,

Please let me know if you think you can help me with getting this to work,
per previous emails.

Thanks!

Dave

**Comment by kpu23** [comment]
Hi David,

Did you miss my last message? Send over the List Fields / MERGE tags :)

**Comment by dgparham** [comment]
Yes, I had sent these right after you requested them on Friday.

**Comment by kpu23** [comment]
Can you re-send them? I don't see them.

**Comment by dgparham** [comment]
It is a PNG attachment, please let me know if you don't see it.

**Comment by kpu23** [comment]
Paste the image to the public message thread: https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/issues/695#issuecomment-298368440

**Comment by dgparham** [comment]
![screenshot-us13 admin mailchimp com-2017-04-28-16-14-00](https://cloud.githubusercontent.com/assets/5923615/25586011/5c2f8102-2e6b-11e7-8069-79e9f2dbc0a5.png)

**Comment by dgparham** [comment]
All set Kevin, sorry didn't realize you couldn't get it via email

**Comment by kpu23** [comment]
Yup no problem. I'm writing up the function now.

**Comment by kpu23** [comment]
I pasted the function below, but there are some outstanding items we should probably clear up first:
- Your current CF7 form only has a "Name" field even though your MailChimp list uses FNAME and LNAME. 

- I'm not seeing the CF7 equivalent for the MailChimp fields - Unit Company, PURL, and Account Rep (and last name)

```
// Defining the filter
add_filter( 'yikes-mailchimp-contact-form-7', 'additional_contact_form_7_data', 10, 2 );

// And defining our function to grab CF7 form data and send it off to MC
function additional_contact_form_7_data( $merge_variables, $cf7_variables ) {

	// Name 
	$merge_variables['FNAME'] = isset( $cf7_variables['your-name'] ) ? $cf7_variables['your-name'] : '';

	// Phone number
	$merge_variables['MMERGE10'] = isset( $cf7_variables['tel-506'] ) ? $cf7_variables['tel-506'] : '';

	// Address fields

	// Property Address
	$merge_variables['MMERGE5'] = isset( $cf7_variables['property-street-address'] ) ? $cf7_variables['property-street-address'] : '';

	// City
	$merge_variables['MMERGE6'] = isset( $cf7_variables['city'] ) ? $cf7_variables['city'] : '';

	// State
	$merge_variables['MMERGE7'] = isset( $cf7_variables['menu-346'] ) ? $cf7_variables['menu-346'] : '';

	// Zip
	$merge_variables['MMERGE9'] = isset( $cf7_variables['zip-code'] ) ? $cf7_variables['zip-code'] : '';

	// Submission Date. Hardcode the date to today. Date format must be MM/DD/YYYY
	$merge_variables['MMERGE3'] = date( 'm/d/y' );

	return $merge_variables;
}
```

**Comment by dgparham** [comment]
I never noticed it was just NAME before, we'll need to separate it to First and Last, can you help me? 
https://aphw.com/wp-login.php
dparham / Chipster1972*

As for the extra fields, can they just be left blank, somehow?

**Comment by TheTracyL** [comment]
Hi @dgparham 

Please don't post your login credentials on Github, I just removed them.

Thank you!
-Tracy

**Comment by dgparham** [comment]
Whoops, thanks

**Comment by kpu23** [comment]
Add this function to functions.php and we can test

```
// Defining the filter
add_filter( 'yikes-mailchimp-contact-form-7', 'additional_contact_form_7_data', 10, 2 );

// And defining our function to grab CF7 form data and send it off to MC
function additional_contact_form_7_data( $merge_variables, $cf7_variables ) {

	// First Name 
	$merge_variables['FNAME'] = isset( $cf7_variables['FName'] ) ? $cf7_variables['FName'] : '';

	// Last Name 
	$merge_variables['LNAME'] = isset( $cf7_variables['LName'] ) ? $cf7_variables['LName'] : '';

	// Phone number
	$merge_variables['MMERGE10'] = isset( $cf7_variables['tel-506'] ) ? $cf7_variables['tel-506'] : '';

	// Address fields

	// Property Address
	$merge_variables['MMERGE5'] = isset( $cf7_variables['property-street-address'] ) ? $cf7_variables['property-street-address'] : '';

	// City
	$merge_variables['MMERGE6'] = isset( $cf7_variables['city'] ) ? $cf7_variables['city'] : '';

	// State
	$merge_variables['MMERGE7'] = isset( $cf7_variables['menu-346'] ) ? $cf7_variables['menu-346'] : '';

	// Zip
	$merge_variables['MMERGE9'] = isset( $cf7_variables['zip-code'] ) ? $cf7_variables['zip-code'] : '';

	// Submission Date. Hardcode the date to today. Date format must be MM/DD/YYYY
	$merge_variables['MMERGE3'] = date( 'm/d/y' );

	return $merge_variables;
}
```

**Comment by dgparham** [comment]
Disregard previous. Have added the FName, LName fields, please let me know if the function code can be revised accordingly. Also, for the missing fields in MC, can they just be blank?

**Comment by kpu23** [comment]
I saw you added the last name - I updated the function to recognize LNAME/FNAME. In terms of leaving the fields blank - yes - we'll be leaving Unit, Company, PURL, and Account Rep blank.

**Comment by dgparham** [comment]
Question, so this Home Warranty Quote form is for Home Owners, but we also have one for Realtors https://aphw.com/new-quote/ Will this code pull from both or can it be applied to only this one? [contact-form-7 id="152" title="Get A Quote - Homeowner"] Appreciate your help!

**Comment by kpu23** [comment]
I believe if you're using the MailChimp integration checkbox on both forms, then the function will run for both forms.

**Comment by dgparham** [comment]
We don't want to pull from the other form, maybe this won't work then?

**Comment by dgparham** [comment]
Going to lunch, maybe the other form will need to be recreated using another format?

**Comment by kpu23** [comment]
Are you using the "subscribe" integration checkbox on both forms?

**Comment by dgparham** [comment]
Wait - so if I put this [yikes_mailchimp_checkbox] in the homeowners one, that we're working on, then the other one without it won't go to MC, correct?

**Comment by kpu23** [comment]
Yes precisely.

**Comment by dgparham** [comment]
Great - now for the function code.... where exactly in here should it go?

<?php

// create NEW widget areas:
$sidebars = array('Slider');
foreach ($sidebars as $sidebar) {
    register_sidebar(array('name'=> $sidebar,
    	'id' => 'Slider',
        'before_widget' => '<article id="%1$s" class="panel widget %2$s">',
        'after_widget' => '</article>',
        'before_title' => '<h4>',
        'after_title' => '</h4>'
    ));
}

if ( function_exists('register_sidebar') )
  register_sidebar(array(
    'name' => 'Home Warranty Area',
    'before_widget' => '<div class="large-6 columns"><article id="%1$s" class="panel widget %2$s">',
    'after_widget' => '</article></div>',
    'before_title' => '<h2>',
    'after_title' => '</h2>',
  )
);

if ( function_exists('register_sidebar') )
  register_sidebar(array(
    'name' => 'Left Sidebar Menu',
    'before_widget' => '<div class="large-6 columns"><article id="%1$s" class="panel widget %2$s">',
    'after_widget' => '</article></div>',
    'before_title' => '<h2>',
    'after_title' => '</h2>',
  )
);

?>

**Comment by kpu23** [comment]
If done incorrectly this part can create some errors on the website, so I'd recommend you to email the file (don't copy and paste the contents, attach the actual file) to this email: plugins@yikesinc.com.

I'll send it back to you with the function at the bottom of the file.

**Comment by dgparham** [comment]
Okay, emailed

**Comment by kpu23** [comment]
Yup, let me know how it's going and if you'd like me to fill out the form to test.

**Comment by dgparham** [comment]
I just did, works! One last thing Kevin, so that's going, we also got a duplicate of the same form on this page https://aphw.com/home-warranties/, I think I can make this work doing the same steps, adding FName, LName, the [yikes_mailchimp_checkbox], correct?

**Comment by kpu23** [comment]
Woohoo!! That's great news!!

For the other form - yes, just split up FName and LName (I'm assuming the other field names are the same between the forms).

**Comment by dgparham** [comment]
Okay - they wanted to have the PHONE go into two MC fields, can that somehow be done? Sorry, here's what they said. "important that the phone number is added to both the phone number and company fields in MC"

**Comment by kpu23** [comment]
We can add the phone number to the company field, but it will overwrite anything in there. So it would strictly act as a second phone field (unless someone manually updates the field and adds company info).

**Comment by dgparham** [comment]
Got it, testing now

**Comment by dgparham** [comment]
Wait - this last one asked for a MC confirmation, guess I'll need to see why I didn't get one before.

![screenshot-mail google com-2017-05-01-15-52-41](https://cloud.githubusercontent.com/assets/5923615/25592482/f601464c-2e86-11e7-893b-c89739318220.png)

**Comment by kpu23** [comment]
Subscriptions will go through double opt-in when using the integration checkbox so the confirmation email will always be sent.

**Comment by dgparham** [comment]
Right, but I didn't get one from the first test and this one says Renewals, should be APHW - Quote, or something else (need to get with our person for this, not your problem.) But, I did two more tests using different emails and they aren't in the MC RFQ list, what do you think happened to them?

**Comment by kpu23** [comment]
I'm thinking what happened is that the first time you tested your email was actually already subscribed. For the two different emails you tried later, did you receive the confirmation email?

**Comment by dgparham** [comment]
That was exactly right, good call. Unfortunately this will be way too many hoops for people to jump thru to just get a quote with having to Confirm Subscription and also Confirm Humanity but we got it!

**Comment by dgparham** [comment]
Is there any way to not have to have the Subscription Confirmation included with the CF7 form?

**Comment by kpu23** [comment]
At the moment there's no way to make the subscription a single optin (meaning no confirmation email) but I already added a filter in my environment. When we do the next release, there will be a filter we can use to change this to a single opt-in. I still need to test it, but I'm pretty sure this is easily done.

**Comment by kpu23** [comment]
I'll let you know when we release it. It should be within the next couple of days. I understand that the double opt-in process undermines what you're trying to achieve here.

**Comment by dgparham** [comment]
So are you saying that there might be a way in the future to not have a have them click the Sub Confirmation and Confirm Humanity?

**Comment by kpu23** [comment]
Precisely.

**Comment by kpu23** [comment]
And the future should be within the next few days :)

**Comment by dgparham** [comment]
Here's what I was going to say, please review and revise as needed.

"This is set up, you can see my name in the RFQ list now, twice, even got the phone number to populate the company field....

But in order for it to integrate and comply with MC's opt-in requirements it has to have a Subscription Confirmation and then they would also have to Confirm Humanity, too many hoops for getting a RFQ from total strangers, so I removed it for the time being. 

They are working on a way to make the subscription single option (no confirmation) with the next release, should be within a few days. Will keep you posted."

**Comment by kpu23** [comment]
Yes that sounds perfect

**Comment by dgparham** [comment]
thx - can you please let me know once the new version come out?

**Comment by kpu23** [comment]
Hello friend,

New version has been released. Download v6.3.18 and email the functions.php to the same email you did before!

**Comment by dgparham** [comment]
Thanks much - I'll check it out Kevin

**Comment by dgparham** [comment]
Kevin - I really appreciate your help with this, after all we did they
decided to not import the leads to MC.

**Comment by kpu23** [comment]
You win some you lose some! :smile:
