### ISSUE TITLE
Integration Shortcodes Should Allow for a List ID

### ISSUE THREAD

**Issue by kpu23** [yikesinc/yikes-inc-easy-mailchimp-extender#696]
At the moment you can only integrate with a single MailChimp list at a time. Let's expand this. Probably the best idea is to add the list id as part of the shortcode.

**Comment by xxvii** [comment]
Any update on this?

**Comment by kpu23** [comment]
Hi @xxvii,

Nothing yet - sorry.

**Comment by kpu23** [comment]
@TheTracyL - I'd like you to check out this page. There's a lot going on now and I think the UI/UX could be improved with some styles.

Kevin - you need to test:
- [ ] bbPress
- [ ] BuddyPress
- [ ] EDD Checkout
- [ ] Registration Form

You should also see if it's possible to give a better error message in the debug log. Something specific to the error that occurred instead of `Page: Checkbox Integrations || Type: Checkbox Integration Subscribe User`

**Comment by kpu23** [comment]
We should update this page too: https://yikesplugins.com/support/knowledge-base/integration-settings/
