### ISSUE TITLE
Additional Settings-Addons doesn't appear

### ISSUE THREAD

**Issue by kitesurfer21** [yikesinc/yikes-inc-easy-mailchimp-extender#700]
I'm using Easy Forms plugin for wordpress. I purchased an add on and there is no place to input the license key. Instructions say go to "settings" then under "additional settings" it should say "addons" but it isn't there.

**Comment by kpu23** [comment]
Hi @kitesurfer21,

Not good! 

Did you install the plugin on your site first? You'll need to install it first, and then go to the Settings -> Addons page.

There were some recent changes to this area of the codebase, but I just tested them again and nothing seems broken. 

Let me know,
Kevin.
