### ISSUE TITLE
Mail Chimp Easy forms not working on website since 5/3/17 upated

### ISSUE THREAD

**Issue by FDACS** [yikesinc/yikes-inc-easy-mailchimp-extender#701]
The easy forms subscribe widget for mailchimp is not working.  The form looks like this:
Email Address Newsletters 
(click all that you'd like) 
Array 
Array 
Array 
Array 
Array 
Array 
Array 
Array 
Array

**Comment by kpu23** [comment]
Hi @FDACS,

This happens from time to time with forms that have interest groups. Please go to the form that your widget is using, remove the interest groups, save the form, and then re-add the interest groups and save the form again. This usually fixes the issue.

The underlying cause of the issue hasn't been determined yet but we're aware of it and looking out for it.

Please let me know if that works,
Kevin.

**Comment by FDACS** [comment]
Kevin,
Is there a source I can use for the code?  I am not a developer--just a desperate business owner trying to get this to work.

**Comment by kpu23** [comment]
Hello,

You won't need to edit any code. Are you familiar with the MailChimp form and how to edit it? All of the editing is done via a user interface - there's no code involved. This user interface can be found by going to the Easy Forms menu (located in your WordPress admin). Find the form that your widget is using, and click the edit button.

To remove an interest group, click it and click the "Remove Field" option. Once you've removed all of the interest groups, save your form, and then re-add them.

Instructions, including pictures, on how to add interest groups can be found in one of our knowledge base articles here: https://yikesplugins.com/support/knowledge-base/interest-groups/

**Comment by FDACS** [comment]
Thanks!  It seems to be fixed for now.

**Comment by kpu23** [comment]
Great! Glad that worked. Cheers.
