### ISSUE TITLE
Need form to be responsive

### ISSUE THREAD

**Issue by jordanscott7** [yikesinc/yikes-inc-easy-mailchimp-extender#702]
I currently have the signup form in the footer and it is inline. How can I make it responsive?

http://edutransitions.staging.wpengine.com/

**Comment by kpu23** [comment]
Hi @jordanscott7,

Unfortunately the inline styles do not come with responsive styles. We'll need to add some custom CSS for the form to be responsive. Are you familiar with adding custom CSS? I'm testing some styles on your site now and will let you know when I have working CSS.

Cheers,
Kevin.

**Comment by kpu23** [comment]
It's not the cleanest CSS, but these styles will fire off at the same width as the Achievements counter. Once those achievement counters stack on top of each other, so will the MailChimp form fields. 

Here is the CSS:
```
@media (max-width: 800px) {
  .yikes-easy-mc-form label {
    display: block;
    float: none !important;
    width: 100% !important;
    padding: 0px !important;
  }
}
```

And as I said before, reach out if you need help adding this CSS to your page.

Kevin.

**Comment by jordanscott7** [comment]
Thank you for the code. I tried adding it to the public.min.css file.
Should it be added to another css file?


[image: logo]
*Jordan Burleson* *Digital Strategist**, Beacon*
828-385-2444 | jordan.burleson@gmail.com | www.beacontec.com
<http://www.facebook.com/jordan.s.burleson>
<http://twitter.com/#!/jordanscottb>
<http://plus.google.com/u/0/+JordanBurleson/>
<http://instagram.com/jordansburleson>
<http://www.linkedin.com/in/jordanburleson> <http://about.me/jordanburleson>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=303693755360683>

**Comment by TheTracyL** [comment]
**You have a few options to add CSS code:**

- If you created this theme yourself, you can just add it to your style.css file
- If you're using a theme you downloaded or bought you can [make a child theme](https://codex.wordpress.org/Child_Themes#How_to_Create_a_Child_Theme) and add the code to your child theme's style.css file
- Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.</li>
- You can use a plugin like [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/) or Jetpack and enter the code in their Custom CSS area
