### ISSUE TITLE
mailchimp lists are not coming up in WP

### ISSUE THREAD

**Issue by lmkosten** [yikesinc/yikes-inc-easy-mailchimp-extender#703]
I am using WP and mailchimp. I am trying to create a funnel and when someone types in their name their name and email do not go onto any lists. 
When I try to see a list it only lets me see mailchimp as my provider but doesn't allow me to select a list even though there are lists created

**Comment by kpu23** [comment]
Hi @lmkosten,

I'm not quite sure what you mean. Are you unable to create a form using the Easy Forms plugin? Or is it that users who try to subscribe aren't making it to your MailChimp list?

Any additional information would help!

Cheers,
Kevin.

**Comment by lmkosten** [comment]
It is that users who try to subscribe are not making it onto my list.



Sent from my iPhone

On May 5, 2017, at 7:36 AM, Kevin Utz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @lmkosten<https://github.com/lmkosten>,

I'm not quite sure what you mean. Are you unable to create a form using the Easy Forms plugin? Or is it that users who try to subscribe aren't making it to your MailChimp list?

Any additional information would help!

Cheers,
Kevin.

**Comment by kpu23** [comment]
Hi @lmkosten,

Would you mind sending us a URL to your form so we can check it out?

Thanks,
Kevin.

**Comment by lmkosten** [comment]
http://miracleoffood.com/listen-to-your-bodys-whispers-2/


I hope this helps

1_Listen To Your Body’s Whispers — Miracle of Food<http://miracleoffood.com/listen-to-your-bodys-whispers-2/>
miracleoffood.com
As a special bonus, you will also receive access to The Whole Food Summit! Completely free for 7 Days:)




________________________________

**Comment by kpu23** [comment]
Hi @lmkosten,

Are you using our Easy Forms plugin? The form you linked to is a Contact Form 7 form, and I don't see any email integration going on. Are you looking to integrate this form with MailChimp using our plugin?

Let me know,
Kevin.

**Comment by lmkosten** [comment]
http://miracleoffood.com/listen-to-your-bodys-whispers-2/


Can you try this link?

1_Listen To Your Body’s Whispers — Miracle of Food<http://miracleoffood.com/listen-to-your-bodys-whispers-2/>
miracleoffood.com
As a special bonus, you will also receive access to The Whole Food Summit! Completely free for 7 Days:)




________________________________

**Comment by lmkosten** [comment]
Yes I need this integrated.

I'm not sure I sent you the right link.

Can you check this one out?

http://miracleoffood.com/listen-to-your-bodys-whispers-2/

Anyone who puts their name in here does not go onto my list.

Please help me. I need this working.

Sent from my iPhone

On May 10, 2017, at 7:57 AM, Kevin Utz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @lmkosten<https://github.com/lmkosten>,

Are you using our Easy Forms plugin? The form you linked to is a Contact Form 7 form, and I don't see any email integration going on. Are you looking to integrate this form with MailChimp using our plugin?

Let me know,
Kevin.

**Comment by kpu23** [comment]
Hi @lmkosten,

You're not using our plugin, [Easy Forms for MailChimp](https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/), so I can't debug and resolve your issue. 

Do you know which MailChimp plugin you're using?

You have two options:
1. Download our plugin and set up the Contact Form 7 integration (and remove the current MailChimp plugin)
2. Find out which plugin you're using and find their support board

**Comment by lmkosten** [comment]
Thanks Kevin,

I am at a loss. It doesn't make any sense. It says I am using your plug in.

http://miracleoffood.com/listen-to-your-bodys-whispers-2/

Did I give you the correct URL?
1_Listen To Your Body’s Whispers — Miracle of Food<http://miracleoffood.com/listen-to-your-bodys-whispers-2/>
miracleoffood.com
As a special bonus, you will also receive access to The Whole Food Summit! Completely free for 7 Days:)



________________________________

**Comment by TheTracyL** [comment]
Hi @lmkosten,

Do you see this menu item on your Dashboard?
![image](https://cloud.githubusercontent.com/assets/1252286/26153102/f6159bd0-3ad7-11e7-8ce4-a40b07df6abb.png)

If so, please follow these instructions to integrate it with CF7:
https://yikesplugins.com/support/knowledge-base/contact-form-7-integration/

When I look at the source code of your site I don't see any of our plugin's code, so maybe you have it installed, but not activated?

Thank you,
-Tracy

**Comment by TheTracyL** [comment]
Hi @lmkosten,,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
