### ISSUE TITLE
Problem with cf7 integration

### ISSUE THREAD

**Issue by frengo1970** [yikesinc/yikes-inc-easy-mailchimp-extender#704]
Hello
is my first time with easy form.
i have followed instraction for add cf7 integration here: https://conectandocontuser.com/reserva-tu-consulta/ but don't work and in debug show me this error:

Invalid Resource	Page: Checkbox Integrations || 
Type: Checkbox Integration Subscribe User || Time: May 5, 2017 6:41 pm

but I can't understand wich is the problem.

can you help me?

regards,
Francesco

**Comment by kpu23** [comment]
Hi Francesco,

Unfortunately it's difficult to test CF7 integration errors. We have a couple of options:

1. Set up a standard MailChimp form via our plugin using the same list that the CF7 list is going through and test subscribing through there. This will tell us that the error is not with the list, but with the CF7 integration.

2. Use the `yikes-mailchimp-checkbox-integration-body` filter to see the data that's being sent to MailChimp. This option takes some technical skill. If you're unfamiliar with PHP then I would recommend emailing us at plugins@yikesinc.com and we can try to set this up for you.

Sorry for the issues!

Kevin.

**Comment by TheTracyL** [comment]
Hi Francesco,

Did you try the steps Kevin listed above?

Please let us know if you need more help.

Thank you!
-Tracy

**Comment by TheTracyL** [comment]
Hi Francesco,

We haven't heard back from you in awhile so I am going to close out this ticket.

If you need more help, please reopen it and we will be happy to help you.

Thank you!
-Tracy
