### ISSUE TITLE
JS Error on form

### ISSUE THREAD

**Issue by prokopsdk** [yikesinc/yikes-inc-easy-mailchimp-extender#705]
Hi!

I get this:

SyntaxError: Unexpected token < in JSON at position 0
 /wp-content/plugins/yikes-inc-easy-mailchimp-extender/public/js/yikes-mc-ajax-forms.min.js?ver=6.3.18:1

when trying to press "submit" button on a form inside a widget.

What gives?

![image](https://cloud.githubusercontent.com/assets/11707342/25971861/14f04480-369e-11e7-84ee-13dbf80291e2.png)

**Comment by kpu23** [comment]
Hi @prokopsdk,

This usually means there's another plugin or theme that's throwing in content and breaking the AJAX call. Do you know if you've had issues with AJAX in the past? Also, would you mind sending us the URL to your site so we can check out the form?

If you'd like a quick fix, you can turn off AJAX (via the submission settings) and that should resolve the issue for now. 

I think we'll need to investigate the form and the other plugins on the site to fix the AJAX issue.

Let me know,
Kevin.

**Comment by kpu23** [comment]
Hi @prokopsdk,

Any update on this?

Let me know,
Kevin.

**Comment by prokopsdk** [comment]
Hi Kevin

Unfortunately I was in a bit of a hurry and there were multiple plugins 
to review. We went with "MailChimp for WordPress" as it worked out of 
the box.

I wish you the best in the future.



Prokop Suchánek
/VOXOP: Succes med dit website/

skype: prokop.suchanek
+45 77 34 2007 (office)
www.voxop.dk <http://www.voxop.dk/>

**Comment by TheTracyL** [comment]
Hi @prokopsdk,

Thank you for the update.

Best wishes,
-Tracy
