### ISSUE TITLE
css to change the height of field boxes

### ISSUE THREAD

**Issue by nylarosie** [yikesinc/yikes-inc-easy-mailchimp-extender#706]
I'm using the Yikes Easy Mailchimp form - mainly as a widget. I'd like to change the height of the field boxes so that they are the same as the submit button. Also, how can I increase the gap between the title and the field box? www.workplayfit.com

Thank you

**Comment by kpu23** [comment]
Hi @nylarosie,

Are you familiar with adding custom CSS to your site? 

Here is the CSS you need to add to style the form as you'd like:

```
.yikes-easy-mc-form-1 {
    margin-top: 12px;
}

.yikes-easy-mc-form-1 label input {
    height: 40px;
}

.yikes-easy-mc-submit-button-1 {
    margin-top: 0px !important;
}
```

In terms of adding custom CSS, you have a few options:
• If you created this theme yourself, you can just add it to your style.css file
• If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file
• Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.
• You can use a plugin like Simple Custom CSS or Jetpack and enter the code in their

Cheers,
Kevin.

**Comment by kpu23** [comment]
Hi @nylarosie.

Were you able to apply these styles?

Let me know,
Kevin.

**Comment by nylarosie** [comment]
Hi Kevin,

Sorry for the slight delay in getting back to you! This works perfectly.

I am very pleased...you can see the result on the site. 

Thank you so much for your kind interest and assistance.

Nyla

**Comment by kpu23** [comment]
Great :)
