### ISSUE TITLE
Submit button not updating

### ISSUE THREAD

**Issue by RichardHolly** [yikesinc/yikes-inc-easy-mailchimp-extender#707]
HI,

We are using the wordpress plugin and it works really well.

I used the option to change the Submit button to Subscribe and that worked.  Now I want to change it back to Submit.  Its changed in settings and committed.    But the site still stays as Subscribe no matter what I do.

Any help appreciated.

Thanks
Richard

**Comment by kpu23** [comment]
Hello Richard,

Am I correct that you're talking about this setting:
![image](https://cloud.githubusercontent.com/assets/2415516/26058619/9b333010-394c-11e7-85bd-0d84cda36579.png)

I haven't seen any issues with this updating. Can you (1) make sure you've saved your form, (2) clear your browser cache, and (3) check if you have any caching plugins (e.g. W3 Total Cache) and flush their cache as well. 

Let me know if the issue continues,
Kevin.

**Comment by RichardHolly** [comment]
Hi Kevin,

Thanks for the prompt support.

Yes its that setting we have changed and would like to change back.

1) Yes we are sure the form is saved.

2) Yes we had already flushed the browser cache.

3) we don't believe we have a cache like this running and if we change other things like fields these do change....

So the issue continues....

Just for info the Url of the form is:
Http://www.datapacific.com/ransomware

If I can provide any more info or screenshots just let me know.

Many thanks

Richard



On 15 May 2017, at 14:01, Kevin Utz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Richard,

Am I correct that you're talking about this setting:
[image]<https://cloud.githubusercontent.com/assets/2415516/26058619/9b333010-394c-11e7-85bd-0d84cda36579.png>

I haven't seen any issues with this updating. Can you (1) make sure you've saved your form, (2) clear your browser cache, and (3) check if you have any caching plugins (e.g. W3 Total Cache) and flush their cache as well.

Let me know if the issue continues,
Kevin.

**Comment by kpu23** [comment]
Hi Richard,

Hmm. I'm not sure why that's not working. Try changing the submit button via the shortcode by using `submit="{your text}"` so the shortcode will look like: `[yikes-mailchimp form="{ID}" submit="submit"]`

**Comment by kpu23** [comment]
Hi Richard,

Did changing the submit button's text through the shortcode work?

**Comment by RichardHolly** [comment]
Hi Kevin,

Yes that worked great.

Many thanks for the prompt support.

Regards

Richard

**Comment by TheTracyL** [comment]
Super! We're glad that worked.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy
