### ISSUE TITLE
No error message is generated if user fails to click ReCaptcha button

### ISSUE THREAD

**Issue by jamesphw** [yikesinc/yikes-inc-easy-mailchimp-extender#708]
I have created a new form, but if the user fills out the form correctly, does not click the ReCaptcha button, and then hits submit, the form fails to submit but no error is generated. Instead, the user is redirected back to the page -- the following code is generated at the top of the form, but this does not display an error for the user:

`<p class="yikes-easy-mc-error-message yikes-easy-mc-error-message-1 yikes-easy-mc-hidden"></p>`

**Comment by kpu23** [comment]
Hi @jamesphw 

Would you mind sending me a URL to your form so I can check it out? I haven't seen this behavior before.

Let me know,
Kevin.

**Comment by jamesphw** [comment]
Yes, I've set up a publicly available test form here: https://ocst.ca/mailing-list-test/

**Comment by kpu23** [comment]
I've got some good news and bad news.

The bad news is it's a bug. The good news is that it's easy to fix and I am working on a fix right now. I had some other minor items to release today so I should be able to get a new, fixed version out today. 

I'll let you know when it's ready to go. 

Thanks for letting us know about this.

Kevin.

**Comment by jamesphw** [comment]
Got it, thanks for the update. Glad you narrowed it down so quickly!

**Comment by kpu23** [comment]
Hello,

I have a fix ready but unfortunately I can't release it until tomorrow because there are some other items I need to complete first.

**Comment by kpu23** [comment]
Hi @jamesphw 

Please download v6.3.19 and test your form again!

Let me know.

Cheers,
Kevin.

**Comment by jamesphw** [comment]
Hey Kevin, I tested with 6.3.19 and it looks good to me!

Cheers,
James
