### ISSUE TITLE
Adding Parameter to Redirect URL

### ISSUE THREAD

**Issue by korynorthrop** [yikesinc/yikes-inc-easy-mailchimp-extender#710]
This isn't a bug or feature request, I'm just curious if there's a way that I can dynamically add a URL parameter to the redirect URL after the form is submitted. Without going into too many specifics, it would be ideal if I could grab the `yikes-mailchimp-associated-list-id` hidden input field value. Is this possible? I envision using the filter below.

```
function add_mailchimp_redirect_param( $url, $form_id, $page_data ) {
    $url = add_query_arg( 'formID', 'the-list-id-grabbed-from-submission' , $url );
    return $url;
}
add_filter( 'yikes-mailchimp-redirect-url', 'add_mailchimp_redirect_param', 10 );
```

**Comment by kpu23** [comment]
Hi @korynorthrop,

I just tested this and it works:
```

add_filter( 'yikes-mailchimp-redirect-url', 'yikes_mailchimp_customize_redirect_url', 10, 3 );

function yikes_mailchimp_customize_redirect_url( $redirect_url, $form_id, $page_data ) {
	parse_str( $_POST['form_data'], $form_data_array );

	$list_id = isset( $form_data_array['yikes-mailchimp-associated-list-id'] ) ? $form_data_array['yikes-mailchimp-associated-list-id'] : '';

	$redirect_url = add_query_arg( 'formID', $list_id, $redirect_url );

	return $redirect_url;
}
```

Cheers,
Kevin.

**Comment by korynorthrop** [comment]
Works great, thank you for your quick reply, @kpu23 !

**Comment by TheTracyL** [comment]
Awesome! We're so glad that worked for you.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make our day :-)

Thank you!
-Tracy
