### ISSUE TITLE
HELP! Error message with irrelevant merge fields

### ISSUE THREAD

**Issue by ZoharTobi** [yikesinc/yikes-inc-easy-mailchimp-extender#713]
Hi!

I created a form with First Name, Last Name, Email, and one hidden Group field:
https://www.dropbox.com/s/4gscy37x6c3ooqj/Screenshot%202017-05-27%2015.39.15.png?dl=0

You can see the live form at:
www.zotobi.com/love-intro/

And for some reason, when a friend tried to subscribe, they got this bizarre error message, seemingly pertaining to "Country" and "State" fields being invalid:
https://api.asm.skype.com/v1/objects/0-cus-d2-d932b3a2813c46a345160f228ad8655f/views/imgpsh_fullsize

Did I do something wrong? Is it a bug? In any case, how can we fix it?

Thanks!!!
~Zo

**Comment by ZoharTobi** [comment]
I figured out what was happening but y'all definitely still need to fix this -- the particular MailChimp subscriber profile listed "CT" as state instead of "Connecticut", causing the error.

What needs to happen so that this error doesn't happen again for me or others?

**Comment by kpu23** [comment]
Hi @ZoharTobi,

I'm a bit confused. Your form doesn't include an address field so how could the CT/Connecticut error arise? Also, I can't see the image you posted; you should be able to paste images directly into GitHub's editor. 

Can you explain the issue further and repost the image?

Thanks for helping - sorry for the issue,
Kevin.

**Comment by ZoharTobi** [comment]
Hi Kevin! Thanks for asking :) I love the Yikes MailChimp plugin so I hope
this helps fix a bug.

I removed the state and country fields from my MailChimp list altogether
(after exporting my data), because I just didn't want to deal with the data
cleanup in the short-term, and this was the easiest/quickest fix.

You can replicate the problem, though, I'm sure, by creating a test
MailChimp list, adding "bad" data to the state and/or country field (like
"CT" instead of "Connecticut"), and watch what happens.

A fuller explanation of what happened:

   1. I had probably at some point imported data into my MailChimp list,
   with some subscribers having abbreviations instead of the full state name.

   2. Then, I set up this opt-in form for a webinar, linked to a particular
   MailChimp Group, so that existing subscribers could easily opt in, and then
   enter the automation sequence I had set up solely for the group.

   3. Then, when one of my existing list subscribers tried to sign up on
   that opt-in form, they got this error:

   https://api.asm.skype.com/v1/objects/0-cus-d2-d932b3a2813c46a345160f228ad8655f/views/imgpsh_fullsize

Does that clarify?
ᐧ

--
​Zo Tobi
+1 (603) 435-3825 • Skype: zo.tobi

*"I am of the opinion that my life belongs to the whole community, and as
long as I live it is my privilege to do for it whatever I can."* - George
Bernard Shaw

**Comment by TraciC** [comment]
Hi,
I did not send this to you. I have no idea how my email address would be connected to their question.

Sorry,
Traci

**Comment by kpu23** [comment]
Hi @ZoharTobi,

I'm glad you love the plugin! I'm still dubious about the cause of the error so I will go through your scenario at some point tomorrow and see if I can replicate it. Do you have any feature requests for the plugin?

@TraciC - not sure how you got roped into this thread. Sorry about that. You can click the "Unsubscribe" button on the right-hand side to exclude yourself.
