### ISSUE TITLE
Button not centered

### ISSUE THREAD

**Issue by TraciC** [yikesinc/yikes-inc-easy-mailchimp-extender#714]
Hi,
I cannot figure out why the input lines and the submit button are not aligned. It isn't all centered. Also, I would like to change the color of the submit button. Could you tell me what .css would I use to do that?

http://traciclausen.com/

Thanks for your help.

**Comment by kpu23** [comment]
Hi Traci,

This CSS will move the submit underneath the input fields (and should center it exactly). Just add whatever color/color code you'd like the submit button to be (and replace "blue").

.yikes-easy-mc-form .yikes-easy-mc-submit-button {
    margin-left: 15px;
    background-color: blue;
}

Cheers,
Kevin.

**Comment by TraciC** [comment]
Hi Kevin,
That’s perfect! Thank you!!!

~Traci

**Comment by kpu23** [comment]
Hey no problem - not sure how you ended up on the other thread - sorry about that!
