### ISSUE TITLE
Stop showing the popup for <interval> if user closes the popup with subscribing

### ISSUE THREAD

**Issue by bogtan** [yikesinc/yikes-inc-easy-mailchimp-extender#715]
Hi, 

Is there a way so I can stop showing MailChimp subscribing form for a specified amount of time, if user just closes the form, without submitting?

**Comment by kpu23** [comment]
Hi @bogtan,

Can you explain this further? Are you using the form within a popup? Are you trying to have the form not appear for X amount of time for each specific user? 

If you provide a URL to your site that could also help!

Let me know,
Kevin.

**Comment by bogtan** [comment]
Hi @kpu23,

Unfortunately the client doesn't want to deactivate the coming soon page so the whole functionality is hidden.

I'm using the form within a popup, indeed, and the popup shows on every page even if the user closes the popup. What I'm trying to do is to:
1. Don't show the popup for already subscribed users (this is already done from the settings, no problem here)
2. If a user chooses to close the popup without submitting the form, I want to hook into the close action and set a cookie for X minutes to mark that the user opted to close the popup. Then, I want to hook into the popup preopen, and check if the cookie exists. If the cookie exists and is not expired, the popup should not be shown again. If the cookie doesn't exist, then show it.


Thanks,
Bogdan

**Comment by kpu23** [comment]
Hi Bogdan,

We actually offer a [premium plugin](https://yikesplugins.com/plugin/pop-ups-easy-forms-mailchimp/) that does this, but I understand if you'd rather not purchase this. I will give you a rough explanation of how we do it. It's a bit technical so if you don't have much experience with this stuff I wouldn't recommend trying it.

What you need to do is find out if the popup has actions that get fired off before it's displayed and after it's closed. Most of the javascript popup libraries that power popups have events you can hook into.

If you have a "pre-open" and a "close" event, then the JavaScript will look like:

```
// Before the popup opens, check if we have the cookie
jQuery( document ).on( 'mypopup:beforeopen', function() {
    // check the cookie
    cookies = document.cookies;

    // loop through each cookie and check if the one with your name is in the list

   // If we find the cookie, return false
});

// Set the cookie when the popup is closed
jQuery( document ).on( 'mypopup:closed, function() {
    // set our cookie
    var cookie = 'my_popup_cookie=true;expires=date_of_expiry;domain=domain;';
    document.cookie = cookie;
});
```

If you find your popup's actions I can help you with the specific JavaScript.

Hope that helps, let me know how you'd like to proceed,
Kevin.

**Comment by bogtan** [comment]
Hi Kevin,

Thank you for the details. Can you provide a screenshot with the configuration from the premium plugin?
> Set the aggressiveness of popups and how often a popup will display for a single user.
I would go for buying the plugin instead of add some custom code.

>

**Comment by kpu23** [comment]
Hello @bogtan,

What do you mean by the configuration of the premium plugin? Unfortunately I cannot provide  a screenshot of the actual code if that's what you're looking for.

Let me know,
Kevin.

**Comment by bogtan** [comment]
Hi Kevin,

😄  No, not a screenshot of the actual code, but a screenshot of the admin section. Mostly I'm interested in the options of the `aggressiveness` of popups. Is there an option for how many ours to hide the popup before an user closed it without submitting?

**Comment by kpu23** [comment]
Ah, yes, I understand now! The option is currently for days only, but expanding this to accept hours (or, at the least, decimal values) is something I've been meaning to add. Here is the screenshot:


<img width="618" alt="popup-cookie" src="https://user-images.githubusercontent.com/2415516/27174878-8e77ca28-518b-11e7-9922-106a122b5feb.PNG">
