### ISSUE TITLE
Plugin Has Disappeared and I Cannot Re-Install

### ISSUE THREAD

**Issue by chelseelately** [yikesinc/yikes-inc-easy-mailchimp-extender#725]
Logged into my account today for the first time in awhile and got an error message about the Mailchimp Extender plugin (the error message has now disappeared). The plugin is no longer showering up and just the short codes are being displayed on my site. 

When I attempt to re-install the plugin, I get the following message: "Destination folder already exists. /homepages/37/d668895577/htdocs/app668895597/wp-content/plugins/yikes-inc-easy-mailchimp-extender/" 

Hoping someone can explain what is going on here and either how to get the plugin working again or how to clear the 'destination folder' so I can re-install.

**Comment by kpu23** [comment]
Hi @chelseelately,

I've never seen this happen before. It sounds like something got corrupted in your `plugins` folder. Do you know how old the plugin was (which version, or when the last time you updated it was?)

Do you have SFTP access to your WordPress install? The best thing to do would be to connect to your server via SFTP and remove the current `yikes-inc-easy-mailchimp-extender` folder and replace it with a fresh copy downloaded from https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/. Make sure to unzip the folder when you're replacing it.

Does that sound possible? I can give more detailed instructions if you need them.

Let me know.

Sorry for the issue,
Kevin.

**Comment by chelseelately** [comment]
More detailed instructions would be great. 

I'm not sure which version of the plugin it was. I installed it toward the beginning of this year- would have done any updates that came along unless it was in the last maybe 2 months.

**Comment by kpu23** [comment]
1. SFTP into your server
2. Go to `wp-content/plugins` - you should see the folder `yikes-inc-easy-mailchimp-extender`
3. Delete this folder
4. Go to https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/
5. Click the download button - you will download a .zip file called `yikes-inc-easy-mailchimp-extender.6.3.26`
6. Unzip this file - you will now have a folder called `yikes-inc-easy-mailchimp-extender.6.3.26`
7. Open up this folder and copy the `yikes-inc-easy-mailchimp-extender` folder to your plugins directory

Does that make sense?
