### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by szepeviktor** [yikesinc/yikes-inc-easy-mailchimp-extender#726]
Hello!

Have you met with this warning?

`Invalid argument supplied for foreach() in .../plugins/yikes-inc-easy-mailchimp-extender/public/classes/process/class.process_form_submission_handler.php on line 1398`

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/classes/process/class.process_form_submission_handler.php#L1401

**Comment by szepeviktor** [comment]
There are couple of places where the fourth parameter passed is `false` thus not an array
https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/classes/process/class.process_form_submission_handler.php#L988

Please advise.

**Comment by kpu23** [comment]
Hi @szepeviktor,

As this is only a warning it should not affect the functionality of the plugin. I am going to fix the code up now so it'll be fixed for our next release.

Thanks for letting us know.

Cheers,
Kevin.

**Comment by kpu23** [comment]
Hi @szepeviktor,

These are getting fixed with today's release of 6.3.27. Thanks for reporting them!

**Comment by szepeviktor** [comment]
Nice from you.
Please close this one on public release.
