### ISSUE TITLE
Add a new custom message for successful email updates

### ISSUE THREAD

**Issue by kpu23** [yikesinc/yikes-inc-easy-mailchimp-extender#738]
There is no way to change the message `Update email successfully sent. Please check your inbox for the message.`.

Add this to the custom messages section.

https://wordpress.org/support/topic/missing-translation-option-for-update-profile

**Comment by kpu23** [comment]
Hey @TheTracyL,

I'm finishing this up now. This is the copy I am using. Let me know if you want to change it.

>Success: Update email successfully sent
>The message displayed after an update profile email is successfully sent.

>Error: Update email failed to send
>The message displayed after an update profile email failed to send.


![image](https://user-images.githubusercontent.com/2415516/36903120-b792601c-1dfa-11e8-8ea2-3881ef85f906.png)


Also, we need to update this article - https://yikesplugins.com/support/knowledge-base/custom-form-messages/. Let me know if you want me to do that.

**Comment by TheTracyL** [comment]
This all looks great! And yes, please update the KB.

Thank you!
