### ISSUE TITLE
Add Acceptance checkbox

### ISSUE THREAD

**Issue by Filoz** [yikesinc/yikes-inc-easy-mailchimp-extender#740]
Hi!
thank you for your plugin!
Is there a way to add  an "acceptance checkbox"?
Because of European Privacy Law, user must accept the privacy policy before send his data.

Thank You!

**Comment by Filoz** [comment]
Hi,
thank you for your reply!

Can I ask you another thing?
Every time I send the form I always get "Please enter a complete address"
I put this field as not required.
I filled every part... but it doesn't work if I set a country different to USA.

I probably found the cause:
It always tries to check the "state" field, but it is only active when USA is selected.
Is there a way to solve that behavior?

Thank you for all!

**Comment by Filoz** [comment]
I made a really ugly tmp fix that works:
	`jQuery("[data-attr-name='state-dropdown'] select  option:first").before('<option value="-" selected="selected">None</option>');	`

**Comment by kpu23** [comment]
Hi @Filoz,

MailChimp has a lot of issues with international addresses but I believe if you set the address field to not required both in MailChimp.com and in the plugin it should work. 

Your work around is also acceptable but this functionality should be available without any additional code.

Let me know if you want to try that.

Cheers,
Kevin.

**Comment by Filoz** [comment]
Hi,
my address filed is not require both in mailchimp and and in the plugin... but it doesn't work 

A solution could be replacing 
`<option data-country="US" value="">---</option>
`
with
`<option data-country="US" value="-">---</option>
`
in https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/partials/shortcodes/templates/state-and-province-dropdown.php

Would you accept a PR?

**Comment by kpu23** [comment]
The problem is that we need an empty value for folks who want to force users to select a state. 

We do filter that list of states though so you could use a filter function to change the list. I'm afraid this wouldn't be any different from your current work-around though.

I was almost certain we had a solution for this so let me do some research.

**Comment by kpu23** [comment]
There is no other solution than to use the filter. 

If you won't ever have U.S./Canadian addresses, then the filter is very simple and you can simply return a HTML like `<option value="-">---</option>`.

If you need to handle U.S./Canadian addresses also, then I would suggest copying the `state-and-province-dropdown.php` file, adding the change you suggested, and running a filter function like:

```
add_filter( 'yikes-mailchimp-state-province-list', 'my_own_state_province_list', 10, 2 );`

function my_own_state_province_list( $html_list, $form_id ) {
    return PATH/TO/MY/VERSION/OF/STATE/AND/PROVINCE/LIST
}
```

Does that make sense? 

Cheers,
Kevin.

**Comment by Filoz** [comment]
Yes it makes absolutely sense :)

Thank you for your help!

**Comment by kpu23** [comment]
No problem; it was nice working with you :)
