### ISSUE TITLE
adding a custom pre-defined tag

### ISSUE THREAD

**Issue by arabtornado** [yikesinc/yikes-inc-easy-mailchimp-extender#741]
Hi @kpu23 
 I see that the plugin has a pre-defined tags, but i was wondering how can i use a certain php snippet as a tag and use that tag as a default value on the form.

What i'm trying to do is to use the following php snippet to return the visitor location based on his IP using Cloudflare GeoIP headers with the below php code
`$country_code = $_SERVER["HTTP_CF_IPCOUNTRY"];`

btw i think it could be nice and easy to implement if you implemented that tag for cloudflare users (Cloudflare CDN is free) to get the visitor location to mailchimp if they are not using double opt-in, the above code will return the country code based on the visitor IP in ISO 3166-1 Alpha 2 format and maybe with a short code that ISO 3166-1 Alpha 2 format could be converted to Country Name, If you need a test website connected with cloudflare  then i can give you an access to my development website if you are interested.

for more info go here
https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-Cloudflare-IP-Geolocation-do-

Thanks

**Comment by kpu23** [comment]
Hi @arabtornado,

For these kinds of situations we recommend using a hidden field and then using our filters to populate that hidden field with data when the form is submitted. I wrote a filter for a guy trying to use his URL's `utm_source` variable. It worked for him - here is the code. 

```add_filter( 'yikes-mailchimp-filter-before-submission', 'mc_before_submit_utm_src', 10, 1 );

function mc_before_submit_utm_src( $mc_form_variables ) {

	// Set default
	$utm_source = '';

	// Check URL $_GET vars for utm_source
	if ( isset( $_GET['utm_source'] ) && ! empty( $_GET['utm_source'] ) ) {
		$utm_source = $_GET['utm_source'];
	}

	if ( isset( $mc_form_variables ) && ! empty( $mc_form_variables ) ) {
		$mc_form_variables['UTM_SOURCE'] = $utm_source;
	}

	return $mc_form_variables;
}```

For you, I think we need to 
(1) change where we're getting the variable value `$_SERVER['HTTP_CF_IPCOUNTRY']`
(2) change the MailChimp field we're supplying - I will use `['LOCATION']` as the example but make sure you use whatever your field's MERGE tag is.

So you should be good using something like this:
```add_filter( 'yikes-mailchimp-filter-before-submission', 'mc_before_submit_add_location', 10, 1 );

function mc_before_submit_add_location( $mc_form_variables ) {

	// Set default
	$location = isset( $_SERVER['HTTP_CF_IPCOUNTRY'] ) ? $_SERVER['HTTP_CF_IPCOUNTRY'] : '';

	if ( isset( $mc_form_variables ) && ! empty( $mc_form_variables ) ) {
		$mc_form_variables['LOCATION'] = $location;
	}

	return $mc_form_variables;
}```

Let me know whether that makes sense.

Cheers,
Kevin.

**Comment by kpu23** [comment]
Were you able to achieve what you wanted?

**Comment by arabtornado** [comment]
Thanks Allot Kevin, It worked nicely.
btw Cloudflare return the country code in ISO 3166-1 Alpha 2 format... how can i edit your snippet to implement that array to show the full country name
https://gist.github.com/vxnick/380904

Thanks

**Comment by kpu23** [comment]
So the value of `$_SERVER['HTTP_CF_IPCOUNTRY']` will be `array( 'AF' => 'Afghanistan' )`? And do you want the abbreviation or the full name?

Either way, replace this line, `$location = isset( $_SERVER['HTTP_CF_IPCOUNTRY'] ) ? $_SERVER['HTTP_CF_IPCOUNTRY'] : '';`, with the following.

Abbreviation: `$location = `isset( $_SERVER['HTTP_CF_IPCOUNTRY'] ) && is_array( $_SERVER['HTTP_CF_IPCOUNTRY'] ) ? array_keys( $_SERVER['HTTP_CF_IPCOUNTRY'] )[0] : '';`

Full Name: `$location = `isset( $_SERVER['HTTP_CF_IPCOUNTRY'] ) && is_array( $_SERVER['HTTP_CF_IPCOUNTRY'] ) ? current( $_SERVER['HTTP_CF_IPCOUNTRY'] ) : '';`

Cheers,
Kevin.

**Comment by arabtornado** [comment]
Thanks Kevin, Unfortunately i'm not familiar to PHP coding, Currently the cloudflare return the abbreviation and i wanna convert that abbreviation to full name and send that full name to mailchimp, Could you please give me an example showing how should i add an array of 2 countries below for example on the above snippet, I would really appreciate that.

`'AF' => 'Afghanistan',
'AX' => 'Aland Islands',`

**Comment by kpu23** [comment]
Ohhhh I understand. Ignore the last snippet. 

```
        // Define our list of countries
        $countries = array( 'AF' => 'Afghanistan', 'AX' => 'Aland Islands', );

        // Get the location, default to ''
	$location = isset( $_SERVER['HTTP_CF_IPCOUNTRY'] ) ? $_SERVER['HTTP_CF_IPCOUNTRY'] : '';

        $location = ! empty( $location ) && isset( $countries[ $location ] ) ? $countries[ $location ] : '';
```

Does that make sense?

**Comment by arabtornado** [comment]
Thanks so much Kevin, this worked perfectly, I really appreciate your help :)

**Comment by kpu23** [comment]
No problem 😃
