### ISSUE TITLE
Make a plan for the remaining v2 endpoints

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#742]
A user in the support forums mentioned:

> I was speaking with mailchimp support they pointed out that this plugin is passing over data using an older version of their API which has been deprecated. She strongly recommended working with an integration that is on version 3.0), or using a MailChimp form.

It's a bummer that MailChimp would be telling folks not to use our plugin because it's using v2.

Here is a list of features that are still on v2.

**Affected features not supported by v3:**

- Dashboard widget. 
  - ChimpChatter: How many new subscribers, etc.

- Account details
  - Avatar
  - Company Name
  - Etc Meta Data

**Let's make a plan to:**

1. See if any of these got mirgated to v3 and then update them
2. Figure out another way to accomplish these with v3
3. Get rid of them gracefully

**Comment by TheTracyL** [comment]
Josiah says the dashboard widget's a waste anyway :-)

**Comment by TheTracyL** [comment]
From MailChimp:

> In a previous ticket, the v2.0 endpoints /helper/chimp-chatter.format, /users/profile.json, and helper/account-details were discussed. Currently there is no parity endpoints for the chimp-chatter endpoint. However, it does appear that some of the parameters from the users/profile.json and helper/account-details.format endpoints have been added to the response of the [API root](http://developer.mailchimp.com/documentation/mailchimp/reference/root/). 
> 
> I would not be able to speak as to if or when additional parameters or endpoints will be added to the API v3.0. I would be happy to relay your interests in full parity for these endpoints to our development team. That said, once future endpoints are enabled, the new information will be available in the schema and in the [changelog](http://developer.mailchimp.com/documentation/mailchimp/guides/changelog/). 
>

**Comment by kpu23** [comment]
I am going to document the data/functionality that we can no longer do w/ v3.

### Emails Left

- Page: wp-admin/admin.php?page=yikes-inc-easy-mailchimp-account-overview
- Issue: We can no longer display the amount of emails left for "pay as you go" and "forever free" plans.
