### ISSUE TITLE
ISSUE: The requested resource could not be found.

### ISSUE THREAD

**Issue by Cre8tvnrg** [yikesinc/yikes-inc-easy-mailchimp-extender#743]
ISSUE WITH OPT IN FORM: I am having the issue after someone inputs their info on my optin form:

"The requested resource could not be found."

![mailchimp form error](https://user-images.githubusercontent.com/35905422/36230225-936842c4-118e-11e8-96fd-27a98b754254.png)

The error log says there are no errors? - but that is not true.

![screen shot 2018-02-14 at 1 37 15 pm](https://user-images.githubusercontent.com/35905422/36230247-a9699640-118e-11e8-90b4-7d4f9fb39b29.png)

API is connected as you can see here:

![screen shot 2018-02-14 at 1 57 05 pm](https://user-images.githubusercontent.com/35905422/36230369-136d4bf4-118f-11e8-9151-531380027a66.png)

PLEASE ADVISE, we are missing out on adding to our mail list!

Thank you !

URL:
https://www.shopdibsonresale.com/

**Comment by kpu23** [comment]
Hi @Cre8tvnrg,

1. Can you try creating a new form and subscribing via that form? 

2. Have you changed anything in your MailChimp.com settings recently? 

3. Do you have any type of security plugin running that would block external API requests?

Let me know. 

Apologies for the issue.

Cheers,
Kevin.

**Comment by kpu23** [comment]
Hi @Cre8tvnrg,

Is this still an issue?

Let us know!

**Comment by Cre8tvnrg** [comment]
yes

Thanks!
Teri Massick
…………………..

949-235-3477
