### ISSUE TITLE
Move changelog to its own file.

### ISSUE THREAD

**Issue by TheTracyL** [yikesinc/yikes-inc-easy-mailchimp-extender#748]
We need to move a lot of the changelog to a separate file. The readme parser doesn't like files of 10k or bigger.

Keep the current version ones in the readme (6.3.x ones) and remove the rest from readme.txt and put it in changelog.txt

**Comment by kpu23** [comment]
My only issue is that users might look at the changelog.txt to see the most recent changes (not realizing they're in the readme). Should we call it changelog-archive.txt?  Or should we copy the 6.3.x changelogs from the readme into the changelog.txt file too?

**Comment by TheTracyL** [comment]
Mika says: 

> Sure. Or keep everything in the change log and only the most recent duped in the readme. The point is the longer the readme gets the less likely it is to properly load on .org

**Comment by kpu23** [comment]
Yup that's what I was thinking too. Awesome.

**Comment by kpu23** [comment]
Even after deleting the filters section and the whole changelog (minus the most recent update), we're at 14kb.

**Comment by TheTracyL** [comment]
Making a comment to see if the upgraded Github Slack integration works :-)

**Comment by mialevesque** [comment]
Add to the comment.

**Comment by TheTracyL** [comment]
Test again
