### ISSUE TITLE
Label Heading Color

### ISSUE THREAD

**Issue by Vupinder11** [yikesinc/yikes-inc-easy-mailchimp-extender#751]
Morning!

I cannot seem to change the label heading colors on my mailchimp easy forms wordpress form.  Simply trying to change font color to #ffffff via the additional classes section in the plugin itself.

Below is the css i'm trying and the form itself.  I'm sure i am missing something obvious right?

http://sellmyhomeweston.com/rick-mullen-home-evaluation/

#top .yikes-mailchimp-container-2 label.BEDROOMS-label span.BEDROOMS-label {
    color: #FFFFFF !important;
}

Thank you!

**Comment by Vupinder11** [comment]
Thank you Kevin!  I will give that a shot tonight.  Appreciate it

**Comment by Vupinder11** [comment]
Morning Kevin,

I was able to get this to work!  Thank you.  1 last selfish ask.  I will have several labels (10) that need to be styledand I cannot seem to apply a global css style to all labels.  Any thoughts?  I can manually do each label, just curious if there is a faster way as I will be building multiple pages. 

Thank you again!

**Comment by kpu23** [comment]
Hi @Vupinder11,

You should be able to apply the same class to all of your labels or you could set it up like 

```
.yikes-mailchimp-container label {
    color: #FFFFFF;
}
```

That should work for all labels w/o adding classes to them.

Cheers,
Kevin.
