### ISSUE TITLE
stripslashes() expects parameter 1  to be string, array given

### ISSUE THREAD

**Issue by jasperf** [yikesinc/yikes-inc-easy-mailchimp-extender#752]
Getting a 
````
2579#2579: *8194 FastCGI sent in stderr: "PHP message: PHP Warning:  stripslashes() expects parameter 1 
to be string, array given in plugins/yikes-inc-easy-mailchimp-extender/public/partials/shortcodes/process_form_shortcode.php on line 1228
````
causing a warning causing an error. Any ideas how I can remedy this real quickly?

**Comment by kpu23** [comment]
Hi @jasperf,

Which version of the plugin are you on? The current version's line 1228 doesn't have a `stripslashes()` call (https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/partials/shortcodes/process_form_shortcode.php#L1228).

I think I know what this error is coming from - a while back the data structure of interest groups changed in MailChimp. Try going to your form, removing the interest groups, adding them back, and then updating it. 

Let me know.

Cheers,
Kevin.

**Comment by jasperf** [comment]
Using 6.3.29 Will try what you suggested @kpu23
