### ISSUE TITLE
Need help to access the mailchimp account for our wordpress servers 

### ISSUE THREAD

**Issue by Vipali** [yikesinc/yikes-inc-easy-mailchimp-extender#754]
Hello, Our WordPress servers we don't currently allow outbound internet access (only inbound internet access to our blog running on WordPress)
so now we want to allow outbound internet access specifically to IP ranges for using the MailChimp service... 
please provide us all possible IP network ranges and port numbers we must be able to reach to use MailChimp email services.

**Comment by kpu23** [comment]
Hi @Vipali, 

You're looking for the IP addresses for MailChimp's servers so your server can communicate with their API, correct? IP addresses are subject to change and so are the server's MailChimp hosts their API on. However, you should be able to find the IP address once we establish what data center your account is in. The data center is something like us1, us2, us5, etc. You can find out what data center you're in by looking at your API key. (It should be something like `xxxxxxxxxxxxxxxxxx-us1`)

If you're looking for MailChimp's email-sending server's IP addresses, MailChimp has an article about them here: https://mailchimp.com/about/ips/.

Cheers,
Kevin.

**Comment by Vipali** [comment]
Thanks much Kevin for your prompt response. 

Yes, we need to connect to the MailChimp's server API through our servers. Our API key ends with us15 (i.e. xxxxxxxxxxxxxxxxxx-us15). Please advise.

**Comment by kpu23** [comment]
Perfect. This means your communication with MailChimp will be with this URL: https://us15.api.mailchimp.com/3.0/. That is your API URL.

If I ping that URL, I can see this is the IP address: 104.121.102.56

As I said before, this IP is subject to change (I know nothing of MailChimp's server architecture). But try it out and see if you can connect!

Cheers,
Kevin.

**Comment by Vipali** [comment]
Thanks for your response. We'll try to whitelist the ip you provided and see if that resolves. It might take few days for us since it's handled by the different team and requires guidance from them. I'll let you know on our outcome. Thanks again!

**Comment by Vipali** [comment]
Hi Kevin! 

Above error I mentioned was occurring on our internal test environment, We've now moved our wordpress application on the UAT server and which is able to communicate port 443, we have that confirmed with network test. Whenever I try to update the API on the settings, it says 'No working transports found'. Please refer to the below capture 
![mailchimp error1](https://user-images.githubusercontent.com/38229929/38960414-08c270d6-432a-11e8-95c1-f3d26dfcf534.png)
I also obeserved the 'Http Request Failure' error in the log 
![image](https://user-images.githubusercontent.com/38229929/38960513-6e9a0874-432a-11e8-92a7-db1992903447.png)
Do you think we need to enable any extension for the plugin to support the HTTP calls? 

Please advise

**Comment by kpu23** [comment]
Hi @Vipali,

Some googling shows that this could possibly be fixed by editing your php.ini file and enabling this extension: `extension=php_openssl.dll` (it should be as simple as uncommenting that line). This is the article I'm referring to: http://www.howtosolutions.net/2017/01/easyphp-wordpress-no-working-transports-found-error/

However, I'm really not sure that this is the issue. I think it'd be more likely that MailChimp uses a variety of different servers (and IP addresses) for their API calls and whitelisting one doesn't allow full connectivity.
