### ISSUE TITLE
Code for changing css of submit button and form field

### ISSUE THREAD

**Issue by MarinaWinkler** [yikesinc/yikes-inc-easy-mailchimp-extender#763]
Hi, sorry in advance for this absolute beginner question. But I just switched from getresponse to mailchimp and would like to adjust the css of my Yikes Mailchimp form to look a bit more like the getresponse form. But I have no clue how to achieve this in the css field of the button. 

I would like the button to be horizontally less wide, a bit rounded on corners, different background color and perhaps with shadow (if its possible)? And the email form field to have "Email" written in it instead of above it and have rounded corners. 

On this blog post I have both, my [old getresponse form (goal) and a bit further down the new form (how it looks right now)](https://marinawinkler.com/blog/8-common-signs-of-deception/). Could you maybe give me some input on what code to use? This would be very helpful.
Other than that I am very happy to have found your plugin! I love especially the GDPR addon possibility to comply with new EU laws. This rocks!
Thank you,
Marina

**Comment by kpu23** [comment]
Try these - I've tried to add comments on them so you can see what they do. 

```
/* Submit Button */
button.yikes-easy-mc-submit-button {

    /* Width @ 50%, button centered */
    width: 50% !important;
    margin-left: auto;
    margin-right: auto;

    /* Rounded Corners */
    border-radius: 10px;

    /* Drop Shadow - #917676 is a shade of grey */
    box-shadow: 0 10px 17px 1px #917676;

}

/* Email Field */
input.yikes-easy-mc-email {

    /* Rounded Corners */
    border-radius: 10px;
}
```

Are you familiar with CSS? Do you know how to add these styles to your website?

Let me know.

Cheers,
Kevin.

**Comment by MarinaWinkler** [comment]
Hi Kevin, 
This worked like magic! :-)
I adjusted the height of the email field as well. 

But small 2 things I still can't figure out: How do I make the text next to my checkbox have a smaller line height? When I put html codes in there, where I changed the text and the text size, it won't recognize them. 
 
And how do I change background colour of the button (without changing it for the whole theme) in such a way, that I can also define a distinct hover color, or at least change the background color in such a way that the hover as it is right now still works? 

Here is the current code (with the attempt to change background color (but then the hover won't work... Probably changing background color sets both button bg and the hover bg to the color?):

Thank you very much for your help :-)!!! 

/* Submit Button */
button.yikes-easy-mc-submit-button {

    /* Width @ 50%, button centered */
    width: 50% !important;
    margin-left: auto;
    margin-right: auto;

    /* Rounded Corners */
    border-radius: 10px;
	
	/* Background Colour */
    background-color: #6f5df7;

    /* Drop Shadow - #917676 is a shade of grey */
    box-shadow: 0 3px 3px 1px #917676;

}

/* Email Field */
input.yikes-easy-mc-email {
     
	font-size: 80%;
	height: 70% !important;
    /* Rounded Corners */
    border-radius: 10px;
}

**Comment by kpu23** [comment]
Hello Marina,

1. I don't know what's going on with your checkbox text's line height! I can't change it. It seems like the line height is not properly scaling with the font size but this is not an issue I've seen before and I'm not sure how to fix it. If you make the font slightly bigger, the line height doesn't look like as much of an issue but that's a lame solution. Sorry about that.

2. This is how you can change the hover color (notice the keyword `:hover` after the selector)

```
/* Submit Button on Hover */
button.yikes-easy-mc-submit-button:hover {
    /* A shade of blue */
    background-color: #fff;
}
```

Cheers,
Kevin.

**Comment by MarinaWinkler** [comment]
Thanks, this worked :-)

**Do you guys have somewhere here on Github a document, where I could look up all CSS selector names you've used for the sign-up form?**

I would need the name to address the checkbox with its' corresponding text from inside the custom css code. Maybe this could solve the line height issue. 

Otherwise, there might be an ugly "workaround" by changing the textsize and line height in my theme for let's say Heading 6 and assign the text next to the checkbox Heading 6 :-).  
Thank you
Marina

**Comment by kpu23** [comment]
Here is an article showing some of the plugin's main selectors: https://yikesplugins.com/support/knowledge-base/selectors-add-custom-css/

The selector you're referring to is not documented in that article though. All of the "checkbox text" is in a paragraph with the class `yikes-mailchimp-eu-compliance-text`. So you can try to style it like 

```
.yikes-mailchimp-eu-compliance-text {
    line-height: 1.0;
}
```

Good luck with styling it - I wasn't having any joy 😉

**Comment by MarinaWinkler** [comment]
Um, well ... I think I have to give up line height now ;-) For some mysterious reason, that does not work. But at least I could change the text size out of the stylesheet instead of filling my text input box with HTML code. I will close this issue now.

Again, thanks a lot for your fast and very helpful help!
Marina

**Comment by kpu23** [comment]
You're welcome Marina. Best of luck with your very interesting website; I support your content!
