### ISSUE TITLE
Easy Mailchimp opt in form not working

### ISSUE THREAD

**Issue by sscott213** [yikesinc/yikes-inc-easy-mailchimp-extender#767]
I've been thru the knowledge base but couldn't find a solution. I''ve synced with mail chimp API, not sue what else could be the problem. Can't see the form on the page.

**Comment by kpu23** [comment]
Hi @sscott213,

Can you send me the URL to the page you're trying to add the form to? Also, how are you adding the form? Using the shortcode?

Let me know.

Thank you,
Kevin.

**Comment by kpu23** [comment]
Hey @sscott213,

Are you still having issues with this?

Let us know.

Thank you,
Kevin.

**Comment by sscott213** [comment]
Thanks I’m all set now

Sabrina

**Comment by kpu23** [comment]
Sounds good. Cheers Sabrina 😄
