### ISSUE TITLE
email address and submit button in one line without checkbox for private privancy

### ISSUE THREAD

**Issue by n3blau** [yikesinc/yikes-inc-easy-mailchimp-extender#769]
Hi at all,
sorry for the beginner question: for my landingpage I have a field for the newsletter. However, this box should be as small as possible to display important contents on the front page. For this reason I would like to make the registration field single-line and do without the checkbox for the data privacy declaration.
Unfortunately, I failed and am looking for a solution.
It's about this page: https://scoobe3d.com/scoobe3d-product/?lang=en
Thanks in forward, Ben

**Comment by kpu23** [comment]
Hi Ben,

We don't have a way of removing the privacy checkbox via the dashboard although we'd love to have one soon!

For the moment, you'll need to use a PHP filter function.

Here is the code:

```
// Remove the GDPR checkbox from a specific page
add_filter( 'yikes-mailchimp-eu-compliance-checkbox-text-html', 'yikes_mailchimp_remove_GDPR_checkbox', 10, 1 );

function yikes_mailchimp_remove_GDPR_checkbox( $checkbox_text ) {
	global $post;

	// Remove checkbox from /scoobe3d-product/ page (ID = 3342)
	if ( $post->ID === 3342 ) {
		return '';
	}

	return $checkbox_text;
}
```

Are you familiar with adding filter functions to your website? 

Let us know.

Thank you,
Kevin.

**Comment by n3blau** [comment]
Hi Kevin,

It's will be the first time with filter functions. Do i need an extra plugin, or where can I insert the code?

Thanks

**Comment by kpu23** [comment]
Hi Ben,

I think the easiest way to do this for beginners is to use the plugin [My Custom Functions](https://wordpress.org/plugins/my-custom-functions/). 

This gives you an editor in your dashboard where you can copy and paste the code. It also provides some helpful fallbacks if for some reason the code is faulty.

**Comment by n3blau** [comment]
Yes! It works 👍 
Now about my second question, how I can do the submit button closed to the email address in the same line?

**Comment by kpu23** [comment]
I'm still seeing the Privacy Checkbox on the page https://scoobe3d.com/scoobe3d-product/?lang=en. Is it removed for you?

Once it's removed we can give you CSS to fix the alignment.

**Comment by n3blau** [comment]
Yes, its removed, but only on the english site.
At https://scoobe3d.com/scoobe3d-product/ I see the checkbox, too.
Is there any other code?

**Comment by n3blau** [comment]
I fount it. Page 2904 is also removed.

**Comment by kpu23** [comment]
I'm still seeing it on the German and English versions. You're not seeing it?

**Comment by n3blau** [comment]
Can you looking again? At my browser the checkboxes are away.

**Comment by kpu23** [comment]
We're good. I think the page is cached (English version is still showing the checkbox but the German is good).

Try adding this CSS:
```
button.yikes-easy-mc-submit-button {
    max-height: 0px;
    height: 20px;
    padding: 0px !important;
}
```

It should make it look like this:
![image](https://user-images.githubusercontent.com/2415516/42586052-29bf9972-8505-11e8-88b3-43f376fae192.png)

C'est bien?

Are you familiar with adding custom CSS? You should be able to do this from your dashboard either through Appearance -> Customize -> Custom CSS or from a field from your theme.

**Comment by n3blau** [comment]
In one of my incognito windows shows it well. 
I'll continue tomorrow. Thank you so much for your help.
Chears, Ben

**Comment by n3blau** [comment]
Hi, it's me again.
the last one is without checkbox, now I want to have the two fields next to each other and in the same line. Unfortunately the code didn't work.
Can you help again?

**Comment by kpu23** [comment]
Hi. What's the last one? The two pages we were working on yesterday are all good. Can you send me a URL?

**Comment by n3blau** [comment]
yes:
https://scoobe3d.com/scoobe3d-product/ (german)
https://scoobe3d.com/en/scoobe3d-product/ (english)

now I want the OK-Button next to the email-address. In the same line.

**Comment by kpu23** [comment]
This is what the forms look like to me:
![image](https://user-images.githubusercontent.com/2415516/42632872-a82607ea-85ac-11e8-821f-9d014292e945.png)

![image](https://user-images.githubusercontent.com/2415516/42632878-ade2e874-85ac-11e8-807e-13480fa639bd.png)

What am I missing? Do they look different to you?

**Comment by kpu23** [comment]
I see. I don't know why that's happening. Try this...

```
.page-id-2627 section.avia_codeblock_section.avia_code_block_0 {
    height: 20px;
}

.page-id-2904 section.avia_codeblock_section.avia_code_block_0 {
    height: 70px;
}
```

**Comment by n3blau** [comment]
perfect! Thanks a lot! I'm very happy about this site, now 😄 
--> we can closed this 👍

**Comment by kpu23** [comment]
You're very welcome :)

Cheers,
Kevin.
