### ISSUE TITLE
Custom/multiple checkboxes for Contact form integration

### ISSUE THREAD

**Issue by tideandtree** [yikesinc/yikes-inc-easy-mailchimp-extender#774]
Hi!
Is there a way of adding another checkbox option to contact forms? Currently the one available is for new sign ups going into a specific group. But I want to add one that users could select additionally to opt them into another group.

Is this possible?
Thanks
Charlie

**Comment by kpu23** [comment]
Hi Charlie,

You could do this if you're familiar with PHP.

What you would need to do is create a custom CF7 field (using filters/actions) and pull all the interest groups from your list into a dropdown. (A weaker alternative option is to hardcode your interest groups into a Gravity Forms field.)

Once the form is submitted, you can hook into our action (`yikes-mailchimp-checkbox-integration-body`) to add any additional `$_POST` data to the interest groups.

If you're interested in that, I can help you write the PHP functions to get it accomplished. It is quite involved though and if you're not familiar with PHP/WordPress it might not be worth pursuing. 

Let me know.

Cheers,
Kevin.

**Comment by tideandtree** [comment]
Thanks for your reply :) tbh I'm a bit of a novice so I'm not sure I would be able to accomplish that. I will look for a workaround :)

I am noticing however that the checkbox doesn't appear to be adding myself (as a test) to the required group. I'm testing the checkbox as an unsubscribed email to opt in to a group within my mailchimp list. For some reason, nothing is being added to the mailchimp list, and the automation email therefore is not going out.

Could you help with that at all?

Thanks :)

**Comment by kpu23** [comment]
Hello,

The most likely reason is that all of our integrations are double opt-in by default. Are you using an email address you have access to? Are you seeing the double opt-in confirmation email?

Would you like to change the integration from double opt-in to single opt-in? 

Let me know.

Cheers,
Kevin.

**Comment by tideandtree** [comment]
Sorry - no I'm not seeing a double opt-in email come through either

**Comment by kpu23** [comment]
Can you send me a URL to your CF7 form?

**Comment by tideandtree** [comment]
Sure :) https://www.tideandtree.com/membership-survey/

**Comment by tideandtree** [comment]
It's this checkbox where the Easy Forms is integrating:
**Yes I want to be in for the early bird pricing!**

**Comment by kpu23** [comment]
I just submitted the form but I _don't_ think I was subscribed to your MailChimp list. I only received the "Thank you! Your FREEBIE coupon is here..." email. Hmm... Thinking...

**Comment by tideandtree** [comment]
Yeah I've just checked and you've not been added to the list although I can see you've filled the form in. That's the exact scenario I'm getting. It must be a setting I've enabled or disabled perhaps?

**Comment by tideandtree** [comment]
Haha, thanks for helping! I am a bit perplexed myself!

**Comment by kpu23** [comment]
I don't think it's anything you're doing. I've seen this happen before and I don't know what causes it. Can you turn on debugging in Easy Forms -> Settings -> Debug settings? And do you mind if I test this form again after you've turned debugging on?

**Comment by tideandtree** [comment]
No problem - just done that, and yeah of course thank you :)

**Comment by kpu23** [comment]
Cool. I'll test again.

The last reply on this post might help as well: https://wordpress.org/support/topic/invalid-resource-in-contact-7-integration/page/2/.

**Comment by kpu23** [comment]
Can you check the settings' debug section and copy & paste or screenshot any errors? (You can paste any screenshots directly into the textarea).

**Comment by tideandtree** [comment]
Page: Checkbox Integrations \|\| Type: Checkbox Integration Subscribe User \|\| Time: 4th September 2018 2:59 pm
--

**Comment by tideandtree** [comment]
Error message: Invalid Resource

**Comment by tideandtree** [comment]
Had a look at that article, if it is that, I may struggle. Not really PHP-literate...

**Comment by kpu23** [comment]
Agghhhh, this is the typical error. Okay. I forgot one important part of debugging these integrations: do you have any required fields in your MailChimp list?

During an integration, we're only sending the email address (although this can be changed) so any other required fields (i.e. first name or last name) are not present and will cause this Invalid Resource error.

Could that be the problem?

**Comment by tideandtree** [comment]
Ahhhhhh - yes I have a first name field I think... I'll just check

**Comment by tideandtree** [comment]
yeah, just the one extra - first name

**Comment by kpu23** [comment]
Sorry - missed your last comment. Can you un-require that field to ensure it was the field causing the issue? After we've tested, we can re-require it and add a filter to send the first name with the subscription if you'd like.

**Comment by kpu23** [comment]
Okay, so you currently have one name in Contact Form 7. If you want to capture first/last name for MailChimp, you'll need to make this two separate fields. 

- Create a field in Contact Form 7 with the name `your-firstname`
- Verify that your field in MailChimp is called `FNAME` (this is the default but it could've been changed)
- Add the following function to your child theme's functions.php file, to your theme's functions.php file, or add it via a plugin like [My Custom Functions](https://wordpress.org/plugins/my-custom-functions/)
```
/*
* Add data from CF7 form to MailChimp subscription
*
* @param array | $merge_variables | An array of variables we're sending to MailChimp
* @param array | $cf7_variables   | An array of variables we received from the CF7 form submission
* @return array| $merge_variables | An array of variables we're sending to MailChimp, hopefully with CF7 variables added
*/
function additional_contact_form_7_data( $merge_variables, $cf7_variables ) {

	// Check our $cf7_variables array for 'country'
	if ( isset( $cf7_variables['your-firstname'] ) ) {

		// Filter first name and add it to our MailChimp merge variables array
		$merge_variables['FNAME'] = filter_var( $cf7_variables['your-firstname'], FILTER_SANITIZE_STRING );
	}

	return $merge_variables;
}
add_filter( 'yikes-mailchimp-contact-form-7', 'additional_contact_form_7_data', 10, 2 );
```

**Comment by tideandtree** [comment]
Hi! So sorry for the silence - thanks for that code. I've tried using the code with the plugin you said. But it looks like I've gone back to the email not been added to the list again. I've tried removing the custom PHP code and going back to how it was (my first name field in mailchimp is not required) but again when I'm testing it I'm not being added to the list. Any ideas?

**Comment by tideandtree** [comment]
oh i've turned on debug settings and im getting this: 

Forgotten Email Not Subscribed | Page: Checkbox Integrations \|\| Type: Checkbox Integration Subscribe User \|\| Time: 10th September 2018 12:09 pm
-- | --

I think this might be because I unsubscribed so I can test the email again. Anyway to stop this from blocking it going through the Mailchimp? Would be nice to give past unsubscribers the chance to re-opt back in if they wish.

**Comment by tideandtree** [comment]
Ah ok I think I deleted myself from Mailchimp directly. If I resubscribe through Mailchimp, it should just work as normal right?

**Comment by kpu23** [comment]
I believe you can re-subscribe to a MailChimp hosted form but I can't guarantee it. MailChimp has some strict rules about re-subscribing especially with deleted addresses. 

As someone who does a lot of subscription testing w/ MailChimp, I'd recommend you always unsubscribe your email addresses rather than deleting them. 

I'm going to test your CF7 form now. I will run a few tests if that's alright.

**Comment by tideandtree** [comment]
That's fine thank you! Looks like you've just been added so hopefully you received an email about a coupon, and then when double optin completed another email about the membership??
(feel free to unsubscribe again once you're finished I won't take offence haha!)

**Comment by kpu23** [comment]
Yes, I received the three emails! 

Then I unsubscribed and re-subscribed. Unfortunately I only received the non-MailChimp email when I resubscribed (the coupon). We'll look into this.

**Comment by tideandtree** [comment]
Ok, really grateful for your help! I'll stay tuned...

**Comment by tideandtree** [comment]
If it helps, I've just checked my Mailchimp account and you're still showing as unsubscribed.

**Comment by tideandtree** [comment]
Thank you so much! Just updated it. You've been so helpful. I'll let you know if I have any more queries but otherwise cheers for all your assistance :)

**Comment by kpu23** [comment]
You're very welcome :)
