### ISSUE TITLE
Existing member issue when updating group preferences

### ISSUE THREAD

**Issue by tideandtree** [yikesinc/yikes-inc-easy-mailchimp-extender#779]
Hi! I've come across a small problem not sure how best to solve it?

Basically my list has two groups. If someone uses the Easy Form on my site, they opt in to group 1 automatically. If they then fill in a form with an Easy Forms checkbox at the bottom, it 'updates' their preferences to add them into group 2 - or so I'd like it too.

What I'm noticing is if someone is in group 1, and fills in the form to add them to group 2, it's not actually adding them. I'm getting the following error message:

Member Exists | Page: Checkbox Integrations \|\| Type: Checkbox Integration Subscribe User \|\| Time: 18th September 2018 12:10 pm
-- | --

Anything I can do about that?
Thanks :)

**Comment by TheTracyL** [comment]
Hello @tideandtree 

Do you have the settings set to "Update?"
https://yikesplugins.com/support/knowledge-base/opt-in-settings/

Let me know.

Thank you,
-Tracy

**Comment by tideandtree** [comment]
Yes I've set it to update but to not send an email.

It seems to be the checkbox integration thats not sending the information over to mailchimp though. The opt-in form is working fine.

**Comment by tideandtree** [comment]
apologies that issue has fixed itself but another has occurred. I'm already subscribed to my mailing list via a double opt-in. But the checkbox seems to be starting off another double opt-in process to simply add me to a new group within the existing list. I have to confirm the email before I'm added. 

I'm not sure whether that's yourself or Mailchimp?

**Comment by tideandtree** [comment]
hi there, just wondering if you're able to assist me with the issue? I've spoken to Mailchimp and they've advised the following: 

If your contacts are being added to the list form a third party source, like a signup form integration that connects to your list via the API, those contacts will only trigger the opt-in confirmation email if the integration passes them over to your list with a 'pending' status. Whether or not an integration can do this depends on the integration itself.  

It sounds like the form integration you mentioned, Easy Forms, is both passing over new subscribers and existing subscribers with that 'pending' status, which will trigger the double opt-in confirmation email. In order for the second scenario you described to happen, that integration would need to pass existing subscribers as subscribed and new subscribers as pending; this is possible using the API, but I'm not certain if it's possible with the way that integration is set up. 

We're very limited in the support we can provide for third party integrations, unfortunately; I would recommend reaching out the the developers of Easy Forms to see if what you described is possible with their set up.

**Comment by TheTracyL** [comment]
Hi @tideandtree,

Kevin is on vacation this week, but he will definitely be able to look into this when he is back next week.

Thank you,
-Tracy

**Comment by tideandtree** [comment]
That's fine thank you! It's not urgent so it can wait till then :)

**Comment by tideandtree** [comment]
Hi there, its the CF7 Form integration!

**Comment by kpu23** [comment]
Hello,

To accomplish what you want, you need to check if the email address is subscribed to the list. We don't do that by default. If you'd like, I can send you a snippet that will perform this check and change existing subscribers to `subscribed` (as described in the response from MailChimp, this will _not_ trigger the email) while everyone else gets double opt-in. 

Or, you could use a filter and change the default to single opt-in so everyone who subscribes via the CF7 form will automatically be subscribed. Let me know if you want that snippet.

Lastly, you may want to consider how many people who are already subscribed will be re-subscribing via your CF7 form. I know that _your_ email address is already subscribed, but will your potential subscribers be? Are there already a load of subscribers in your list? Are there multiple "entry points" to subscribing to this list?

So there are three options: (1) check if a subscriber is subscribed already and then set them to single opt-in, (2) set everyone to single opt-in, or (3) leave the form as it is.

Let me know which option you'd like!

Cheers,
Kevin.

**Comment by tideandtree** [comment]
Hi Kevin!

Ok I've had a read through and I think option 1 is what I'll need, only because it's different mailing list emails they'll be getting and I think it's important to still have a double opt-in, if they've never opted in to anything before. But if they've already double-opted in, there's no need to do so again.

Could you give me a very brief overview of how to add a 'snippet', and if there's a plugin that'll make it easier? Tech novice over here :)

Charlie

**Comment by kpu23** [comment]
Charlie, 

Try this snippet - I think you added custom PHP code to your site during our previous ticket...right? This would be added in the same way.

```
add_filter( 'yikes-mailchimp-checkbox-integration-body', 'set_integrations_to_single_optin_for_resubscribers', 10, 2 );
function set_integrations_to_single_optin( $request_body, $integration_type ) {

	// Get the email.
	$email_hash = md5( $request_body['email_address'] );

	// Check the API to see the status
	$response = yikes_get_mc_api_manager()->get_list_handler()->get_member( $list_id, $email_hash, false );

	if ( is_wp_error( $response ) ) {
		return $request_body;
	}

	// Look at the status from the API
	if ( 'subscribed' === $response['status'] ) {
		$request_body['status_if_new'] = 'subscribed';
		$request_body['status']        = 'subscribed';	
	}

	return $request_body;
}
```

Let me know.

**Comment by tideandtree** [comment]
Hi Kevin :)

Ok I added the snippet above and made sure everything was on. When I'm testing it, it doesn't appear to be adding the email to the selected group - so Mailchimp isn't receiving anything to activate the right email.

If that makes sense?

**Comment by kpu23** [comment]
I missed a variable. Try this.

```
add_filter( 'yikes-mailchimp-checkbox-integration-body', 'set_integrations_to_single_optin_for_resubscribers', 10, 3 );
function set_integrations_to_single_optin_for_resubscribers( $request_body, $integration_type, $list_id ) {

	// Get the email.
	$email_hash = md5( $request_body['email_address'] );

	// Check the API to see the status
	$response = yikes_get_mc_api_manager()->get_list_handler()->get_member( $list_id, $email_hash, false );

	if ( is_wp_error( $response ) ) {
		return $request_body;
	}

	// Look at the status from the API
	if ( 'subscribed' === $response['status'] ) {
		$request_body['status_if_new'] = 'subscribed';
		$request_body['status']        = 'subscribed';	
	}

	return $request_body;
}
```

**Comment by kpu23** [comment]
Woohoo! I'm glad it's working, Charlie.

I don't usually do this but if you're feeling generous you could give us a nice rating and review on the WordPress.org forums: https://wordpress.org/support/plugin/yikes-inc-easy-mailchimp-extender/reviews/#new-topic-0. 😄 

Cheers,
Kevin.

**Comment by tideandtree** [comment]
I already have left a glowing review and 5 stars :)

**Comment by kpu23** [comment]
Oh whoops! Ha. Thank you very much! Let us know if you have any issues in the future.
