### ISSUE TITLE
Requesting additional tags like [url] and [link][/link]

### ISSUE THREAD

**Issue by jhboerhof** [yikesinc/yikes-inc-easy-mailchimp-extender#786]
To expand the possibilities of custom messages we'd like to request the following tags:
- [EMAIL_UID]
- [EMAIL]

Possible implementation In _sendUpdateProfileEmail()_ at _public/partials/class.public_ajax.php_:
```
$email_body = str_replace( '[EMAIL_UID]', $subscriber_id, $email_body );
$email_body = str_replace( '[EMAIL]', $user_email, $email_body );

```
We've found this to be valueable additions to the plugin.

**Comment by kpu23** [comment]
Yeah, sure, I don't see any problem with this. I think we can add it to our release which should be coming this week

**Comment by kpu23** [comment]
@jhboerhof, why do you need the user's subscriber ID? This is just an md5 hash of the user's email. Are you looking to use it in URLs?

**Comment by jhboerhof** [comment]
Thank you. We are using the [EMAIL_UID] to create custom download URLs. On our server-side, we can use this to check if the user is still subscribed before handing over the downloadable file.

**Comment by kpu23** [comment]
The tags are in there (v6.4.8). It uses `[subscriber_id]` instead of `[EMAIL_UID]`. The available tags are listed in the sidebar.
