### ISSUE TITLE
Warning in get_submitted_interest_groups()

### ISSUE THREAD

**Issue by szepeviktor** [yikesinc/yikes-inc-easy-mailchimp-extender#804]
> Invalid argument supplied for foreach() in yikes-inc-easy-mailchimp-extender/public/classes/process/class.process_form_submission_handler.php on line 520

Could you check the value or fix the root cause?

https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/master/public/classes/process/class.process_form_submission_handler.php#L520

Thank you!

**Comment by kpu23** [comment]
Will do

**Comment by szepeviktor** [comment]
Thanks.

**Comment by kpu23** [comment]
You're welcome! Thanks again for your help. (Sorry that there are no jobs available here.)
