### ISSUE TITLE
reCAPTCHA error message

### ISSUE THREAD

**Issue by LaCatrina** [yikesinc/yikes-inc-easy-mailchimp-extender#814]
My visitors cannot subscribe to my newsletter,
everything looks good in the settings but on-site this is what they see (see attachment)
I'm available for TeamViewer call.
TIA
Cat
<img width="756" alt="Schermata 2019-03-15 alle 23 24 38" src="https://user-images.githubusercontent.com/48606388/54465065-92bd3880-4779-11e9-8708-4e7863b6f9fa.png">

**Comment by kpu23** [comment]
Hi Cat,

It appears as if the reCAPTCHA key is either not entered or is incorrect. Can you check your reCAPTCHA keys in the plugin's settings? (https://yikesplugins.com/support/knowledge-base/recaptcha-settings/)

Let me know if that fixes the error.

Cheers,
Kevin.

**Comment by LaCatrina** [comment]
Hi Kevin,
I followed the instructions and re-copy/paste the keys but I ended up with the same message. it says "ERROR for site owner: the type of key is invalid"
Looking forward for more hints on how to fix it, TIA!
Cat

**Comment by kpu23** [comment]
Can you send me the URL of your website so I can check it out? I've never seen this issue occur for anything other than an invalid site key.

**Comment by LaCatrina** [comment]
sure!
www.lagringatattoo.it

**Comment by kpu23** [comment]
There are no additional errors being logged in the console or from the reCAPTCHA request. It seems like it doesn't like your site key... Did you try clearing your site's cache? Maybe it's still pulling the old key.

As I said before, I've never seen this issue before except for invalid keys. You're sure you set both the site key and the secret key?

For reference, this is the _site_ key being used on the front end: `6LcX_JcUAAAAAGSsvc6i83GBmeQiaaS1vNphZovy`

**Comment by LaCatrina** [comment]
the key/secret key are correct
I've cleaned the cache and everything... I don't know what else I can do...

**Comment by kpu23** [comment]
This doesn't make sense to me either. Are you using any other plugins that have a reCAPTCHA option? Most contact form plugins like CF7 offer this. Are you using that (or similar) plugins on your website? I'd like to see if the reCAPTCHA issue is a result of our plugin or some other factor.

**Comment by LaCatrina** [comment]
I fixed it by deleting everything, cleaning the cache, rebooting the system and reinstalling everything, included the captcha registration website on google. Now it looks like it's working :-)

**Comment by kpu23** [comment]
So weird! I hope that wasn't too much of a hassle! Do you have an idea of which step in that process was key to making it work? Did it feel like something was being cached (either in our plugin or in the website)?

Regardless - glad you got it working. Sorry it was a pain :)
