### ISSUE TITLE
Add a block category for Easy Forms

### ISSUE THREAD

**Issue by kpu23** [yikesinc/yikes-inc-easy-mailchimp-extender#829]
And add the easy forms block to that category.

**Comment by Ajwerth** [comment]
I could look into this.

**Comment by freddiemixell** [comment]
@Ajwerth that would be awesome because I'm actually working on a PR that will set up some more Gutenberg enhancements so if you could create us a category and put up a PR I'll review!

**Comment by freddiemixell** [comment]
Here's some guidance:
[Creating a block category tutorial](https://loomo.ca/gutenberg-creating-custom-block-categories/)

If you look at the current implementation in `blocks/` you should have a pretty good idea what to do after looking over that tutorial.
