### ISSUE TITLE
Resubscriber email (profile update) not being trigerred 

### ISSUE THREAD

**Issue by techtello** [yikesinc/yikes-inc-easy-mailchimp-extender#843]
I am using easy forms plugin and everything else is working fine except resubscriber email (profile verification email sent to resubscribers) is not working. I have selected "Yes" for "Send Update Email" and "Update Existing Subscriber". I do not get any error message while submitting the form, but no email is being sent. I have checked spam and other possible locations. 

My WP email functionality is working fine since I use it with WP forms and it works there. I am also not get any error message when I enable debug functionality.

Can you please guide on how I can check what could be wrong?

Thanks

**Comment by techtello** [comment]
can you please update on this issue. I am blocked on using easy forms due to this issue as I need the update profile email functionality to work fine

**Comment by freddiemixell** [comment]
@techtello please send a link to the form so we could test this for you. If you have to you could create a private page with a test form that we could check out for you.

In the meantime if you turn off "Send Update Email" the form should work for your purposes.

Also, if you haven't seen our help base articles they might be a good resource for you.
 https://yikesplugins.com/support/knowledge-base/product/easy-forms-for-mailchimp/

**Comment by techtello** [comment]
Hi,

You can access the form here
https://www.techtello.com/test-easy-forms/

It's password protected. Please use E@syf0rMs!!

We need send update email functionality since it's a security risk to turn
it off and we don't want to expose that on our site. We cannot use easy
forms without getting emails to work. If you need any further information
please let me know.

Thanks,
Vinita

**Comment by techtello** [comment]
Sorry, we had to remove this form because it shows up on our site and we
cannot keep it. I have made it a private page now, but not sure how you can
access a private page. Can you please let us know if there's another way to
test.

Thanks,
Vinita

**Comment by techtello** [comment]
Kindly confirm how this can be tested. I am looking to use this form and
need your help in ensuring the profile email update functionality is
working properly

Thanks,
Vinita
