### ISSUE TITLE
Add additional information: Groups

### ISSUE THREAD

**Issue by Sirkiu** [yikesinc/yikes-inc-easy-mailchimp-extender#847]
Add additional information: Groups

I added more fields following your tutorial:
https://yikesplugins.com/support/knowledge-base/contact-form-7-populate-the-merge-variable-data-with-additional-information-about-the-user/

Muy doubt is how to add in a group? Is it possible from functions.php?

Thank you

**Comment by freddiemixell** [comment]
Hey @Sirkiu,

Please add questions to the WordPress.org forum in the future so we see it more quickly:
https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/

Cheers,
Freddie
