### ISSUE TITLE
Update not compatible with WP, and it's crashed my web page 

### ISSUE THREAD

**Issue by KKimber123** [yikesinc/yikes-inc-easy-mailchimp-extender#857]
I clicked update on the yikes-inc-easy-mailchimp-extender plugin, and it crashed my website. I am not therefore not enabling the plugin until the issue is resolved.

**Comment by freddiemixell** [comment]
Hey @KKimber123,

That's very strange because our latest update was adding the Recaptcha version 3 capability. That code followed the exact same pattern as the settings that were registered for Recaptcha version 2, which as been in the plugin for a long time.

Please include error messages from your error log, any information that could allow me to reproduce this issue because "my site crashed" doesn't give me much to work with 😄

**Comment by KKimber123** [comment]
Hi,

Following updates (WP and other plugins) error messages showed on the front end, and I was unable to log in to the back end.

When attempting to visit the back end I saw a white screen with the following errors:

Warning: array_keys() expects parameter 1 to be array, bool given in /home/atnudenu/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/class-yikes-inc-easy-mailchimp-extender-option-forms.php on line 37

Warning: Invalid argument supplied for foreach() in /home/atnudenu/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-form-customizer-extension/includes/classes/class-yikes-inc-easy-mailchimp-customizer-extension.php on line 136

Warning: Cannot modify header information - headers already sent by (output started at /home/atnudenu/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/includes/class-yikes-inc-easy-mailchimp-extender-option-forms.php:37) in /home/atnudenu/public_html/wp-includes/pluggable.php on line 1296

My host disabled the plugin, which allowed me to gain access back in to the site.

On attempting to reactivate the plugin within the WP dashboard the following error occurred:

Fatal error: Cannot redeclare yikes_mailchimp_plugin_textdomain() (previously declared in /home/atnudenu/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender1/yikes-inc-easy-mailchimp-extender.php:225) in /home/atnudenu/public_html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/yikes-inc-easy-mailchimp-extender.php on line 225

I deleted and reinstalled the plugin, and at this point all my forms were lost from the plugin. I’ve had my host restore backups before this issue, but all forms are now lost.

If you are able to help me recover the forms that would be very much appreciated, I’d spent many hours setting them all up and now they are all lost.

Thanks,
Katherine Kimber
07771868535

On 2 Sep 2020, at 15:01, Freddie Mixell <notifications@github.com> wrote:

﻿

Hey @KKimber123<https://github.com/KKimber123>,

That's very strange because our latest update was adding the Recaptcha version 3 capability. That code followed the exact same pattern as the settings that were registered for Recaptcha version 2, which as been in the plugin for a long time.

Please include error messages from your error log, any information that could allow me to reproduce this issue because "my site crashed" doesn't give me much to work with 😄

**Comment by freddiemixell** [comment]
Hey @KKimber123,

You have two versions of Easy Forms on your site:
`yikes-inc-easy-mailchimp-extender1`
`yikes-inc-easy-mailchimp-extender`

Please remove the extra install or ask your hosting provider to make sure there is only one version.

Cheers,
Freddie
