### ISSUE TITLE
Need some help with CSS

### ISSUE THREAD

**Issue by charelel** [yikesinc/yikes-inc-easy-mailchimp-extender#872]
Thank you for this plugin. I can finally make sure that my website visitors can fill in multiple forms on my website.

I made some changes to the CSS to make sure my form is on-brand but there are a couple of details I can't seem to figure out. This is what it looks like now:

<img width="372" alt="Screen Shot 2021-02-10 at 1 34 36 pm" src="https://user-images.githubusercontent.com/78874104/107555169-d78bbd00-6ba4-11eb-9250-3241b98751c9.png">

This is what I've added:

.yikes-easy-mc-submit-button.btn {
   background-color: #BEBBA7;
}

.yikes-easy-mc-submit-button.btn {
  font-color: #FFFFFF;
}

.yikes-easy-mc-submit-button.btn {
  border: 0px;
}

.yikes-easy-mc-submit-button.btn {
  width: 350px;
}

.yikes-easy-mc-submit-button.btn {
  height: 70px;
}

.yikes-easy-mc-form input {
    font-color: #000000;
}

.yikes-easy-mc-form input {
    background-color: #FFFFFF;
}

.yikes-easy-mc-form input {
    width: 350px;
}

.yikes-easy-mc-form input {
    height: 40px;
}

But I would like to have whitespace between the email form and the button. And I would like the button to have the same width and height as the form width: 350px;  height: 40px; and the text on the button to be centered. 

Thanks a lot for your help!

**Comment by jpowersdev** [comment]
Hi @charelel,

While we are happy to help you with this issue, we'd appreciate it if you'd open up a support ticket on the free support forums located here - https://wordpress.org/support/plugin/yikes-inc-easy-mailchimp-extender/. The GitHub issues are more for pull requests and problems with the plugin code.

Please also make sure to add a link to the page you're having trouble with!

Jon
