### ISSUE TITLE
Conflict with CMB2 Plugin

### ISSUE THREAD

**Issue by landreww** [yikesinc/yikes-inc-easy-mailchimp-extender#890]
Hello,

There is a conflict with CMB2 (developer’s toolkit for building metaboxes, custom fields, and forms).

On a YIKES Easy Forms for Mailchimp form, if Update Existing Subscriber = Yes and Send Update Email = Yes, the email body of the sent message will be a footer of the website.  If there are multiple footers it appears to choose the footer with the slug "footer".  If there is only one footer it will send that one, regardless of the slug name.

To test, I disabled the CMB2 Plugin and the form sent the message body specified in Custom Messages.

As you can see from the screen captures, the conflict email body is not the active footer ("footer-updona") but a published but unused footer ("footer").

Thank you in advance.

![3-conflict email](https://user-images.githubusercontent.com/6261643/149007839-f56ecd17-6af4-40d5-8529-e02c9ff9f479.JPG)
![4-no conflict message](https://user-images.githubusercontent.com/6261643/149007845-5fdb20b9-56f3-4fa1-89aa-2eddd902fdfa.png)
![1-site-footer](https://user-images.githubusercontent.com/6261643/149007846-8ad8e1cd-6fa2-4f58-8f88-6e3c21f87d89.JPG)
![2-footer with link](https://user-images.githubusercontent.com/6261643/149007848-1edff7bc-970a-44f7-9f25-fba267a1e928.png)

**Comment by jpowersdev** [comment]
Hi @landreww,

I'm struggling to understand your problem coupled with the screenshots. It seems as though when you have CMB2 active, the email body isn't lining up with what you expect?

If you take a look [at this line](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/d0425eb4ba7def8921e019d2eea7bb7130ef17be/public/partials/ajax/class.public_ajax.php#L102), you'll see that a custom email body is run through `the_content` filter. Is it possible that CMB2 is also interacting with that filter?

If you don't set a custom email body, the email [is defined here](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/d0425eb4ba7def8921e019d2eea7bb7130ef17be/admin/class-yikes-inc-easy-mailchimp-extender-admin.php#L2685). It lines up with one of your screenshots, though I cannot tell from the order under which circumstances it is being displayed.

By default, the email doesn't have any footer. You will only see a footer if it is either added in a custom email body, added through `the_content` filter, or added at the very end before the email is sent using the `yikes-mailchimp-update-email-content` filter [as shown here](https://github.com/yikesinc/yikes-inc-easy-mailchimp-extender/blob/d0425eb4ba7def8921e019d2eea7bb7130ef17be/public/partials/ajax/class.public_ajax.php#L188).

**Comment by landreww** [comment]
Thanks for your quick response.

With all plugins active the entire email message sent is the footer (photo #1 above) with NO CONTENT from Easy Forms.  With CMB2 or Elementor deactivated the entire email message is from Easy Forms (no footer) (photo #2 above).

You cannot see it but there are four photos.  After photo #2, the photo is of our standard footer with your form (photo #3 above).  Photo #4 is a closeup the form with the link displayed.

The line variable `$form_data['error_messages']['email-body']`  shows the correct correct text body from the forms Custom Settings.

In class.public_ajax.php (class YIKES_Inc_Easy_Mailchimp_Public_Ajax) line 102:
$email_body = apply_filters( 'the_content', $form_data['error_messages']['email-body'] );` 

$form_data['error_messages']['email-body'] contains the correct content from the Custom Settings of the form.
After the call to apply_filters, $email_body contains the site footer.

There is clearly a conflict with the apply_filters command.  I searched the CMB2 folder and did not find any calls to 'the_content'.  So I did some Internet searches and found someone else was having issues like this with Elementor.  I enabled CMB2 and disabled Elementor and duplicated the problem.  Looks as if Elementor is the issue.

I replaced line 102 with the following, which worked as the correct body was sent:
$email_body = wpautop($form_data['error_messages']['email-body']);

 I am an experienced PHP developer but new to WordPress.  Can it be that wpautop is getting unhooked somewhere?

Is there anything you can do on your end? Can you make a call to re-initialize 'the_content' filter?

**Comment by jpowersdev** [comment]
Hi @landreww,

I'm not surprised that Elementor is causing issues. Page builders account for the vast majority of support tickets across our handful of plugins.

Elementor specifically makes several modifications to `the_content`. You can see that in action here: https://github.com/elementor/elementor/blob/15f9a99db9b35d63358f26ebd46ed7c7b6f45d68/includes/frontend.php#L1210 and throughout this file.

**Comment by landreww** [comment]
I understand.

Calling `$email_body = wptexturize( wpautop( $form_data['error_messages']['email-body'] ));` produces the correct output.  However, I do not want to be in the position of updating a commercial Plugin for every update. So for now, I will set the 
"Send Update Email" option to "No".

Again, thank you for your help.  Great job on the Plugin!
